### ISSUE TITLE
Update version of PatternFly 3 included in scss-variables file

### ISSUE THREAD

**Issue by AdamJ** [patternfly/patternfly#1013]
Currently, PatternFly 4 pulls an older version of PatternFly 3 (3.37.10), when using the `$pf-global--load-pf-3: true !default;` variable.

With the current version of PatternFly 3 at 3.58.0, this CDN link is now over 20 minor version behind.

For reference, this is where the CDN link is defined: https://github.com/patternfly/patternfly-next/blob/f3bb000501b425fa689694aa98fab2ea877ad459/src/patternfly/sass-utilities/scss-variables.scss#L217

**Comment by mcoker** [comment]
@dgutride how do you think we should manage this? Should we update the version of PF3 with in a breaking change release? Or remove this and ask users to include their own version?

**Comment by rachael-phillips** [comment]
@dgutride did you see Michael's comment above? :)

**Comment by mcoker** [comment]
A breaking change release would be a great opportunity to have resolve this. We could always add a new var `$pf-global--load-pf-3-latest` (or something like that) that pulls in the latest version. However I have not heard of any requests around this method of loading PF3, so my inclination is to remove it as I imagine most users are pulling in PF3 themselves. @mindreeper2420 what do you think, would you still like to see this?
