### ISSUE TITLE
Feature Request: Secondary/Tertiary Danger Button

### ISSUE THREAD

**Issue by TimoSta** [patternfly/patternfly#1094]
**Current State**
[Patternfly 4 buttons](https://pf-next.com/components/Button/examples/) currently come in different designs, each with different semantics.

This includes the following:
- primary
- secondary
- tertiary
- danger

**Requested Feature**
The current set of options does not allow buttons with are both _secondary_ or _tertiary_, and _danger_.

We would like to correctly model a button which is not a primary action on the page and will rarely be used, but is destructive and should be marked as such.

**Example Use Case**
A project overview page in an app gives access to project header info, and allows the user to execute a bunch of actions, including deleting the project. This option will rarely be used:

![image](https://user-images.githubusercontent.com/5621996/49821457-7b207f00-fd48-11e8-9208-aa6399e961e3.png)

After some (highly unscientific) user testing, it seems that the big red button draws too much attention away from the rest of the page, considering that it should not be the focus.

**Potential Solution**
A combination of the _secondary_ and _danger_ style might be appropriate:

![image](https://user-images.githubusercontent.com/5621996/49821676-0c8ff100-fd49-11e8-92fe-a2b32ed87775.png)

---

**Please tell me why my interpretation of the PF4 design system is horribly wrong and how we should approach this use case instead** :slightly_smiling_face:

**Comment by dgutride** [comment]
@mcarrano @kybaker  - can you guys weigh in on this request or how you'd like to see these?

**Comment by kybaker** [comment]
@dgutride @rachael-phillips @mcarrano I think this is a valid usecase we should accommodate. Having a secondary destructive button allows us to have multiple levels severity in the same screen e.g. account delete and suspend. 

@rachael-phillips Could you create a story to add this post beta?

**Comment by ryelo** [comment]
@rachael-phillips Can we also include a danger "link"? So a button that doesn't have any borders. 

It was presented to us in mockups, so it would be awesome to be included.

**Comment by rachael-phillips** [comment]
@ryelo that sounds like a good idea to me. @kybaker @mcarrano what are your thoughts on the danger link suggestion?

**Comment by rachael-phillips** [comment]
Also, can you tell me more about your timeline for these requests and what priority this is for you?

**Comment by TimoSta** [comment]
@rachael-phillips We are planning to ship the first version of our product around April, so it would be nice to have it in place by then.

That said, it is a visual issue and does not negatively impact any functionality, so it probably can't be considered the highest of priorities.

**Comment by rachael-phillips** [comment]
That's good to know. Thank you!

**Comment by ryelo** [comment]
@rachael-phillips I think as soon as possible would be best for us, although we can always fake it before then. We're already past our first MVP, but these mock ups just came up.

**Comment by mcarrano** [comment]
I am OK with the idea of a Danger link. @kybaker do you have any concerns?

**Comment by kybaker** [comment]
@mcarrano I am fine with that.

**Comment by rachael-phillips** [comment]
@ryelo Thank you for the info. If you have any more insight on timeline please send that along!

**Comment by ryelo** [comment]
@rachael-phillips I got info that we're looking at March 1 for another MVP. It would be great to have by then. I've created a temporary shim in our application for it currently.

**Comment by rachael-phillips** [comment]
Thank you for letting me know. It looks like it would be more feasible for us to get it done by March 22. Could that work for you? Let me know how high priority this is because we have some other priority Insights components on the roadmap before this one.

**Comment by ryelo** [comment]
@rachael-phillips I think that should be fine. This isn't super high priority, we can serve a component up for now until the official PF one comes out.

**Comment by rachael-phillips** [comment]
Thanks for all of the info @ryelo !

**Comment by mceledonia** [comment]
Spot on there, let's use secondary button style with our destructive red color for the secondary, and our link text button in the same color for that as well.

Secondary danger button
![image](https://user-images.githubusercontent.com/30935938/53971586-313b0100-40cb-11e9-81b0-88f5a50ec153.png)


Secondary danger link button
![image](https://user-images.githubusercontent.com/30935938/53971596-35ffb500-40cb-11e9-9d89-8d36047209f2.png)

**Comment by TimoSta** [comment]
Commenting to keep it open.

This is still a valid use case for us, and it looks like for other projects as well.
