### ISSUE TITLE
PatternFly-Cli - component/layout generator should use standard tooling

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly#1120]
PatternFly-React is making us of Plop, we should review the use of this generator and possibly standardize core on it as well (removing the use of patternfly-cli).

**Comment by mcarrano** [comment]
@evwilkin @redallen Any reason to keep this open? Are we planning to do this? 

cc @mcoker

**Comment by evwilkin** [comment]
@mcarrano @mcoker confirmed with @dgutride that we can close this out.
