### ISSUE TITLE
AboutModal - review change request to allow productName prop. to accept JSX

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly#1131]
An additional ask from https://github.com/openshift/console/pull/936#discussion_r241446540

"..AboutModal's productTitle[Name] prop currently requires a string. As currently written, the OpenShift cases are JSX in order to include a superscript registration mark after "Red Hat". This works, but results in a warning the browser console. [1] Options are to remove the superscript registration mark, **change the upstream prop type to allow JSX**, or do nothing and ignore the error."

@dtaylor113 wrote "I 'think' allowing JSX in the `productName` would be ok, but I suppose app devs could add multiline JSX/cust. css classes, which could change the look of the AboutModal.  We just have to decide if we are ok with allowing this level of customization"  

Related PF4 Issue: https://github.com/patternfly/patternfly-next/issues/1110

**Comment by mcoker** [comment]
cc @tlabaj - is this still an issue?
