### ISSUE TITLE
Add overflow feature to Alert Group

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#1181]
Want to introduce the ability to manage an overflow condition when the number of toast notifications exceeds some threshold. The goal is to stop displaying alerts beyond a certain threshold (default 3) so the use does not get flooded with notifications that can potentially fill the screen.

Further requirements are summarized here: https://docs.google.com/document/d/1sW3b6wJNDCeZaxNQv895APoqZROz6BPRyBNj2D4Rmco/edit?usp=sharing

Related: https://github.com/patternfly/patternfly-next/issues/654

**Comment by lwrigh** [comment]
Just read over the requirements a bit more and my initial thoughts for an alert group involve having a single toast notification that appears once the toast threshold has been hit that features the aggregate number of toast notifications that are unread. The message within the aggregate toast message would provide the user with the number of new notifications and prompt the user to open the notification drawer to view them there. There could also be a link to the notification drawer that expands once it the user has clicked it. @mcarrano What are your thoughts? I can mock that concept up if you like.

**Comment by mcarrano** [comment]
@lwrigh This was our initial take on this and we actually have some designs that show this. The problem when we went to implement this was that it's not possible for a single toast to know about the existence of other toast notifications and therefore decide to behave differently. It seemed like the thing that contains the notification needs to keep track of the count and manage the overflow. That said, maybe the group can pop-up something that has this functionality?

**Comment by lwrigh** [comment]
@mcarrano Ah I see the issue with that sort of behavior. So when you say the thing that contains the notifications are you talking about a div contain that contains the toast notifications? Maybe if that container got to a certain size it could manage the overflow and respond by telling the user that more toast notifications are waiting for them.

**Comment by mcarrano** [comment]
Yes @lwrigh , that's exactly what we are thinking. The container (which is what we are calling an Alert Group) can be aware of the number of toasts it contains and manage the overflow. So the question is what is the mechanism for reporting back to the user. Right how the Alert Group is a component with no UI.

**Comment by lwrigh** [comment]
@mcarrano Within the alert group could a toast notification appear once the edge of the container has been reached?

**Comment by mcarrano** [comment]
Maybe. But we need to consider what happens when things are added and removed from the stack of toast notifications. It's hard to treat this as just another notification.

**Comment by lwrigh** [comment]
Would it make sense to treat the alert group as a separate component from the toast notifications then?

**Comment by mcarrano** [comment]
It already is a separate component. See https://www.patternfly.org/v4/documentation/core/components/alertgroup

**Comment by lwrigh** [comment]
Cool thanks for sharing this! What do you think of adding some sort of thin border around the alert group with a message along the lines of, 'More toast notifications have been added to the alert group. Please open the notification drawer to see all new toast notifications.'?

**Comment by mcarrano** [comment]
That's the direction I was thinking, also. Maybe with an action to open the drawer or temporarily silence notifications?

**Comment by lwrigh** [comment]
Those would be good actions to have accessible to the user. Great I can start to explore some options that are in that vein if that's cool with you. 

Another idea I had includes having a message like 'Click to view more toast notifications' that appears at the bottom of the alert group and the user can click it to expand more toast notifications if they like.

**Comment by lwrigh** [comment]
<img width="860" alt="Screen Shot 2019-06-10 at 11 09 14 AM" src="https://user-images.githubusercontent.com/20227374/59205159-4747da00-8b70-11e9-832c-4799c4e97bb8.png">

@mcarrano What do you think of this option? Do you know if the component could be smart enough to say something like "Click to view 4 more notifications"?

**Comment by mcarrano** [comment]
@lwrigh I like this approach. The text should be blue to indicate that it's an action, and I don't think you need the words, "Click to" therefore. Yes I think the component should be able to track the number of notifications. So including a count makes sense. When the list is expanded, do you think the user needs the ability to collapse it? What do you propose would happen if the number of alerts overflows the height of the screen? I do want to be careful to not duplicate the notification drawer with this. Maybe rather than expanding the list we just open the drawer?

**Comment by lwrigh** [comment]
@mcarrano This is good feedback thank you! I can update it to say 'View 4 more notifications" and change the text to blue so it looks actionable. I think having the user have the ability to collapse it would be a nice addition. I think in the case of the notifications overflowing the height of the screen we should direct the user to view the notifications in the notification drawer. I can explore both of these paths as options.

**Comment by lwrigh** [comment]
<img width="860" alt="Screen Shot 2019-06-10 at 11 45 11 AM" src="https://user-images.githubusercontent.com/20227374/59207575-49f8fe00-8b75-11e9-97b9-2461885100d7.png">

Here is the option that expands the notification. 

![Alert example](https://user-images.githubusercontent.com/20227374/59216121-f85a6e80-8b88-11e9-89bf-f77db0184c67.png)

![Alert example Copy](https://user-images.githubusercontent.com/20227374/59216120-f85a6e80-8b88-11e9-8443-f616bc523ab1.png)

@mcarrano What do you think of these options? One challenge with it is making sure that the text is legible, visual design mind have some good ideas for it but this is the general behavior I was thinking of.

**Comment by mcarrano** [comment]
I like this approach @lwrigh . Thanks for mocking this up. So is the expected behavior that the tab below the group will appear when there are more than 3 notifications and hide when the number falls below 3? I think that would make sense. Perhaps it can be configured to either expand the list or open the drawer.

Would be great to get some more eyes on this. @mceledonia @kybaker @matthewcarleton @jgiardino what do you this of this approach for handling the toast alert overflow?

**Comment by jgiardino** [comment]
Nothing jumps out as problematic. I thought it would be worth capturing how the user could potentially interact with these things, and considerations to think about.

- When the user clicks the action to show more, we should determine where that focus goes
  - If the action opens the notification drawer, this would behave like a modal, and usually we place focus on the first focusable element, which would be the kebab in this example.
    - If the notification drawer is visible, do we still display dynamic alerts, or do they only get populated in the drawer? It could be weird to be trying to manage the drawer of alerts, and then more alerts display on top of them. 
  - If the action displays more notifications (not in a drawer), then I think we would place focus on the first newly visible alert.
    - I'm assuming that old alerts are dynamically removed. But if the user hovers over this alert group or has focus in one of the alerts or the show more action, then would we pause the timeout of alerts? The alternative seems like a potentially weird interaction (e.g. as I'm trying to interact with the alerts, they start to disappear, etc...)
    - If we do pause timeout, then it's more possible that the alert group could be taller than the page. In this case, we should consider enabling that area so that it's scrollable. Currently if the toast alert group is taller than the page, they aren't scrollable.

**Comment by mcarrano** [comment]
These are great questions, @jgiardino .

> If the notification drawer is visible, do we still display dynamic alerts, or do they only get populated in the drawer? It could be weird to be trying to manage the drawer of alerts, and then more alerts display on top of them.

This is something I hadn't really thought through. I would be interested to hear thoughts on what should happen here.

**Comment by jgiardino** [comment]
Can the notification drawer have alerts grouped into an accordion structure?

In the design above, I'm assuming that alerts are populated in the drawer in the order they come in, with newest on top. And in that case, we can pause the display of toasts sense they're immediately visible in the drawer.

But if it's possible they are sorted into groups within an accordion, then they would not necessarily be visible in the drawer at the time that they are generated, correct? And is there a way to display some indication that alerts have been populated in collapsed sections of the drawer?

I don't have any strong opinions on this. Maybe the simplest option is to continue displaying toasts, since there is no guarantee that the would be visible in the drawer? Or maybe we make an assumption that if the user is interacting with the drawer, then the user willing to interact with it to find new alerts, in the case where we can clearly indicate when collapsed groups have new notifications. 

I'm really curious about what everyone else thinks.

**Comment by lwrigh** [comment]
@mcarrano Yes that was my thinking towards it too. It would be great if it had a similar behavior to the notification drawer opening. 

@jgiardino Thank you for the feedback Jenn!

I can update the mockup to include the first actionable elements in focus. 

Agreed, it could get weird and busy real quick if we had overlapping elements. I think in this case I would recommend just having the new alerts populate in the notification drawer if it is already open. 

When it comes to putting focus on the first element in the alert group that would be the first toast correct? 

That's a great point, I think making it scrollable in situations like that makes sense.

**Comment by lwrigh** [comment]
![Alert example Copy 2](https://user-images.githubusercontent.com/20227374/59286315-7d06c480-8c3d-11e9-8ecf-d3fedc7f1d0a.png)
![Alert example Copy 3](https://user-images.githubusercontent.com/20227374/59286320-8001b500-8c3d-11e9-8ef2-2ad6fd70f076.png)

@mcarrano @jgiardino what about something along these lines?

**Comment by matthewcarleton** [comment]
Hey @lwrigh this is looking great!
I prefer the idea of the notifications being added to the drawer when it is expanded for the same reasons mentioned above. Also, it's a strange interaction if a toast appears you close it and then it appears again un-read in the drawer. 
@mcarrano have we clarified  if it has a read or un-read state that when a toast is dismissed in the drawer?
It could be useful to have a temporary "new" state to indicate the notification is new, or in the group new ones have been added (along with the updated badge. I don't believe there has been any design for this on the PF.
From a design perspective the shadows in the box feel a little out of place to me. Maybe it's just the white box or the border.
This is quick and dirty but maybe breaking it out as it's own area could work.
<img width="475" alt="Screen Shot 2019-06-11 at 1 55 04 PM" src="https://user-images.githubusercontent.com/287880/59291140-8a797a00-8c50-11e9-9df0-5276f5410aec.png">

**Comment by jgiardino** [comment]
From @lwrigh's previous comment:

> When it comes to putting focus on the first element in the alert group that would be the first toast correct?

In your second example, the focus where you show it matches what I would expect. 

For the first example, the scenario I had in mind is after you click the "View more..." link. In that case, focus should go on the first alert that is displayed (i.e. the 4th alert in the list). I'm not sure you need to update your example to show this, but anytime we have a pattern where the user interacts with something that gets removed on click/enter, we should provide feedback to developers on how to handle focus. 

> Regarding your second comment @jgiardino having a new alerts group in the notification drawer could definitely be an option. The newest alerts would appear at the top and appear in the order that they happened. Having the notification drawer open to the grouped sections could be an option.

> Do you think having a number badges appear next to the new alerts section be enough of an indicator?

I don't have a strong opinion on this. I think something to consider is whether users will notice the badge update the same way they would notice a new toast. And is it important that the two are equally noticeable, or not?

**Comment by lwrigh** [comment]
![Alert example Copy 2](https://user-images.githubusercontent.com/20227374/59297472-4d17eb00-8c56-11e9-8b89-15af5725ab12.png)
![Alert example Copy](https://user-images.githubusercontent.com/20227374/59297474-4ee1ae80-8c56-11e9-8955-88f9bbb04f20.png)
I updated the alert group indicator to be more aligned with what you're suggesting @matthewcarleton. I updated the expanded notification drawer as well. In this case the user would click the view more link and it would open an expanded notification drawer with the new notifications at the top of the drawer. I tried to follow a similar pattern to what it looked like @mceledonia had proposed in one of the recent issues around unread notifications in the drawer.

**Comment by matthewcarleton** [comment]
@lwrigh thanks! This is looking great.  We could probably run this through Kyle/Michael, a few things stand out to me to consider with visuals : Spacing, for proper a11y we'll need a larger clickable size, I'm not sure if that box shadow aligns with PF4 shadows. I also wonder if we need that "x" or not. Does a user need to dismiss that? I think it might be better to be persistent.

**Comment by mcarrano** [comment]
Just catching up on this. A few thoughts...

* I agree that when the drawer is open, toast alerts should be suppressed and that new notifications will just end up in the drawer. I don't think we want a "New" category as it's hard to define what "new" means. Is new and unread the same thing? How long would something live in "new"? I'd rather just use the scheme we have now and let the unread count increment for a category as new notifications come in.

* Agree with @matthewcarleton that the View more... should not have a close.

* @lwrigh Will get someone from the visual team to establish the visual spec for this (spacing, etc)

**Comment by lwrigh** [comment]
@matthewcarleton That sounds like a good next step to me. Good point on the larger clickable area to improve the usability, totally agree with that. 

@mcarrano That works for me with sticking with the unread count since that has already been established. We can get rid of the close. Sounds good! If any other interaction work needs to be considered I'd be happy to help out with that.

**Comment by lwrigh** [comment]
Here's a link to the Marvel prototype: https://marvelapp.com/615e0ad

**Comment by mcarrano** [comment]
@lwrigh @mceledonia and I met today to discuss a request to aggregate repeat notifications as well. While this is good in theory, we determined that it would be difficult to implement in the front end (what criteria determines if a notification is a duplicate?). We will therefore keep this issue focused on managing the alert group overflow as currently designed.

Next steps - 

@lwrigh will write up more detailed notes on behavior/interaction to guide development.

@mceledonia Do you think we need any further visual refinement on this? Will CSS need a visual spec? Any issues re spacing, etc?

**Comment by mceledonia** [comment]
@mcarrano @lwrigh Re: Visuals

I think we can bring the "view more" button down in size a bit, let's try making it the same size as our buttons? Not sure if it would work better full width or just text-width, so try both. I think it makes sense being a different size than the alerts as it is less of an alert entry and more of an indication/action of multiple alerts.

To get that spacing: Draw a 24px box around the text and center the text in the box, then draw 6px tall boxes above/below against the edge of the 24px box. This creates the button dimensions, so resize the background to cover those shapes! Then you can try making the width either 16px from the left/right edges of the text, or just making it full width (same width as other alerts).

**Comment by lwrigh** [comment]
@mceledonia Those suggestions sound good to me. Do you want me to make those updates to it or would I hand it off to you at this point in the process? 

@mcarrano I added behavior notes to this doc and tried to cover some of the categories that are featured in the PF website documentation. Let me know what you think. https://docs.google.com/document/d/1sW3b6wJNDCeZaxNQv895APoqZROz6BPRyBNj2D4Rmco/edit#

**Comment by mcarrano** [comment]
This looks great @lwrigh . The only thing I can think to add is a mention that the alert group should be hidden whenever the notification drawer is open (we don't want them competing for the same space!).

**Comment by lwrigh** [comment]
@mcarrano Great thank you! Good catch and point, I added that to the behavior section in the doc.

**Comment by mceledonia** [comment]
@lwrigh @mcarrano Sorry for the delay here! Wanted to propose this approach for the view more button:

Using something a little closer to our button styling, as well as shortening the message a bit. The arrow icon implies you will be taken somewhere else (notification drawer)

As for the visual specs - the spacing is the same as our buttons, and there's a 24px spacer between the button text and the arrow icon.

![image](https://user-images.githubusercontent.com/30935938/62484850-13142280-b789-11e9-9f3a-0ab39418cf9d.png)

**Comment by lwrigh** [comment]
@mceledonia @mcarrano This looks great to me! I think it helps to differentiate the view more button even more so from the toast notifications so that looks good to me.

**Comment by mcarrano** [comment]
Thanks @lwrigh and @mceledonia . Let's call this design complete then. I will move to the HTML/CSS backlog for implementation. @LHinson @rachael-phillips FYI

**Comment by mcarrano** [comment]
I will look to get this feature on the roadmap.

**Comment by mcarrano** [comment]
Let's keep this open. I still would like to get it in at some point.
