### ISSUE TITLE
update docs to reflect stance on placeholder text.

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#1201]
as per [this discussion](https://github.com/patternfly/patternfly-react/pull/1067) I think it would be good to document our recommendations for placeholder text. I know we've discussed in the past but couldn't easily find any official docs on it.

**Comment by rachael-phillips** [comment]
@mcarrano have you seen this conversation? Would love to hear your thoughts. Right now placeholder text is in the backlog and we haven't prioritized it or created an issue for it. Is this something you would like to consider in the future?

**Comment by mcarrano** [comment]
We've had several lengthily conversations on this @rachael-phillips . I think we ended up saying that placeholder text can be used as a syntax hint, but nothing else. @stacymcauliffe can you confirm? This is mentioned in your Forms guidelines, correct?

**Comment by stacymcauliffe** [comment]
We did talk about this at length in terms of a11y concerns and how we wanted to recommend placeholder text be used. 

We determined that placeholder text could be provided, but we would only recommend using it for syntax hints in circumstances where data needs to be input in a certain format. 

So, imaging we're asking a user to input an employee serial number, we could provide placeholder text that stated "e.g. 5CVN123" to help users understand the format that the information needs to be provided in. 

![image](https://user-images.githubusercontent.com/35926653/53816305-5431ad80-3f31-11e9-9f31-18312e81ca42.png)

To manage the a11y concerns, contrast of placeholder text will be bumped up to meet a11y requirements once the field is in focus. When the user starts typing, the hint disappears and is replaced with their input. 

You can read more about how we're approaching help on forms here: https://v2.patternfly.org/design-guidelines/usage-and-behavior/forms#provide-the-right-kind-of-help

I think the plan was to address this new styling for [V2 of the form demo](https://github.com/patternfly/patternfly-next/issues/919).

**Comment by rachael-phillips** [comment]
Ok great, thank you!

**Comment by mcoker** [comment]
This is in the design docs @ https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms#placeholder-text
