### ISSUE TITLE
Ensure PR template is up to new requirements

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#1225]
Once the PF4 repo goes into PF let's confirm that the template used for new PR's is correct.

One thing to confirm is that the proper pass off to PF react happens. If we have updated HTML the dev working core will need to ensure an issue gets created on the React side to update the corresponding code.

**Comment by mcoker** [comment]
@rachael-phillips I believe we talked about this in the last sprint planning or retro, creating a PR template. Do you know if there is an issue open to track that?

**Comment by rachael-phillips** [comment]
Hi @mcoker no, I don't believe there is an issue open to create a PR template, but yes, it did come up in retro, and I definitely think it's a great idea and we should move forward with it. Do we want to use this issue?

**Comment by mcoker** [comment]
Works for me!

**Comment by mcoker** [comment]
@evwilkin wdyt about this? should we provide an issue/PR template?

**Comment by evwilkin** [comment]
@mcoker this couldn't hurt, and may be helpful to streamline issues & PRs as well as match the experience in the pf-react repo.  For reference, here is the issue template from pf-react:
>
```
**Describe the issue. What is the expected and unexpected behavior?**

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
<!-- PatternFly-React Codesandbox template: https://codesandbox.io/s/serverless-cherry-q9t3f -->

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**
```

And here is the PR template:
>
```
<!-- What changes are being made? Please link the issue being addressed. -->
**What**: Closes #

<!-- Are there any upstream issues or separate issues you need to reference? -->
**Additional issues**:
```
