### ISSUE TITLE
Documentation updates about what elements can have hover styles

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#1228]
As part of discussion for #1211, we thought it would be worth adding something like the following to one of our documents:

> When defining hover styles, these styles should be applied to the clickable element.

And/Or

> While the default styles applied to an element might not provide a visual indication of target area, the styles that display on hover should. To ensure that these styles accurately convey to the target area of an element where the user can click, hover styles should be applied to the clickable element of a component, and not to a larger wrapping element.

I'm not sure if this is a better fit for [Contribution](https://pf-next.com/contribution) or [Guidelines](https://pf-next.com/guidelines), or somewhere else.

**Comment by christiemolloy** [comment]
@lareplog consult @jgiardino if you have any questions

**Comment by mcoker** [comment]
cc @jessiehuff wdyt about this, and any idea where it could go if we want to add it?

I'll also mention that we follow this as a general rule, but there are exceptions where hover styles are defined by a wrapping element when it has interactive children that consume the available space in the parent. An example is [favorites in app launcher](https://www.patternfly.org/v4/documentation/core/components/applauncher#favorites) where the item background change on hover is triggered on the parent `li`.

**Comment by jessiehuff** [comment]
@mcoker Are there any set of CSS guidelines that gets maintained for others contributing to core? I think the documents that Jenn provided above have gone away, and the only locations I can find that look similar are https://github.com/patternfly/patternfly#guidelines-for-css-development and https://pf4.patternfly.org/contribution. I'm open to whatever you'd like to do for this. If there are set of guidelines shared by core contributors where it makes sense to add this, I'm open to that, or we can close this issue. However you'd prefer to handle documenting the rules core contributors are following. 🙂

**Comment by mcoker** [comment]
@jessiehuff either https://pf4.patternfly.org/guidelines or https://pf4.patternfly.org/contribution is where we would put something like this. I think it would best live under the guidelines page, maybe under https://pf4.patternfly.org/guidelines#nested-calc-functions.

**Comment by jessiehuff** [comment]
@mcoker Sure, that works for me. 🙂
