### ISSUE TITLE
Create common toggle and context menu components

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#1429]
I would like to propose creating common components for a toggle button and context menu that are used in components like dropdown, app launcher, options menu, select, context selector, etc.

The toggle button and context menus in our current dropdown menus are 90% the same, with relatively small variations in how they present themselves per component. These differences could be built into the shared components themselves and the variations exposed with the use of modifier classes, and instead of dropdown, options-menu, select, etc, we could have a common "dropdown" component that is modified based on whether you're building a select menu, app launcher, etc, or maybe we continue to support each individual type of dropdown component, and those components simply reference the shared toggle and context menu components with defaults that apply to that specific component.

Modular dropdown design recomendations here: https://docs.google.com/document/d/1GyVgog_SbErqbYyF08_N2rfLDUgwAVbdKP5udBjdxYI/edit?usp=sharing

**Comment by jgiardino** [comment]
One idea is that to have 3 types of components:

- Dropdown - basically a wrapper, similar to how card is a wrapper, and just controls positioning of the toggle relative to the menu
- Menu Item
- Toggle

Then maybe the demos are where we show different variations of these components based on the design documentation we have. 

It might also be nice to decouple the a11y stuff from the component level, at least the aspects that are heavily tied to context (like form or not a form), use case (like menu of options vs actions), and/or specific javascript implementations (like the keyboard behavior that's required when using aria-haspopup). These could potentially be documented at the Demo level.

**Comment by karelhala** [comment]
@jgiardino this is really great approach how to do this! This will heavilly impact the implementation of dropdown in react (and eventually in any framework) component. The best way to implement this (interaction in JS) would be to build on top of current implementation and just improve the API with new capabilities.

With this approach we will not be limited at all in using dropdown
* horizontal menu [1]
* Custom datepicker (this would be really good!)
* Notification drawer (accordion with some styling)
* Literally anything conumer might think of

Currently I can think of 4 elements as dropdown item
* `button` - to interact with dropdown (selectable item - both with and without checkboxes and horizontal menu?)
* `a` - to navigate
* `input` - to filter group, not every dropdown implementation supports this (they usually allow to filter trough all items), but it would be really cool to allow consumers to filter trough part of the items and rest to be static
* `div` - container to hold any item consumer wishes to show in dropdown menu

[1] (just a quick mock-up)
![52737876-b2700e00-2fcd-11e9-9054-95e1157d2d73](https://user-images.githubusercontent.com/3439771/52947571-662f2000-3377-11e9-9741-7d973f9d82cd.JPG)

**Comment by dlabaj** [comment]
I think building these changes on top of drop down is a good idea, we should be able to add the additional api on the react side by expanding on the current api.

**Comment by jgiardino** [comment]
Just wanted to capture some requirements for a MenuItem component, based on some updates made to AppLauncher in https://github.com/patternfly/patternfly-next/pull/1916

Any variation of a menu item that exists today should be possible with the MenuItem component we would create for this issue. This should include a variation that indicates the menu item is an external link (i.e. opens the page in a new window/tab), similar to the way it's implemented in #1916.

**Comment by mcarrano** [comment]
Modular dropdown design recomendations  here: https://docs.google.com/document/d/1GyVgog_SbErqbYyF08_N2rfLDUgwAVbdKP5udBjdxYI/edit?usp=sharing
