### ISSUE TITLE
How to handle dropdowns in page header at different viewports

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#1430]
The way we show/hide dropdowns in the header is really specific, based off of the layout that we have in the page demo currently. This will easily cause issues and require more flexibility as folks introduce different variations of menus in the page header.

Also we should discuss how best to handle the collapsing/combining of menus in the header as the viewports change. In the [react page demos](http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout), for example, when the user menu is hidden at a mobile viewport, it is no longer accessible anywhere on the page. After chatting with @kybaker and @mcarrano about it, we decided to combine the contents of the user dropdown into the kebab menu on a mobile viewport, with a separator between the other items in the kebab and the user menu. We also discussed the potential to add groups to the dropdown menu, so that when the user menu collapses into the kebab dropdown in the page header, the actions from the user menu have a divider and group label (ie, "User") as an indicator for which actions are associated with the user menu in the kebab dropdown.

**Comment by rachael-phillips** [comment]
May be impacted by https://github.com/patternfly/patternfly-next/issues/1523

**Comment by mcoker** [comment]
The current masthead refactor work will address this.
