### ISSUE TITLE
Add Font Awesome 5 Regular Icons

### ISSUE THREAD

**Issue by AdamJ** [patternfly/patternfly#1457]
In the current selection of Font Awesome icons, only the solid options are available (both built into PatternFly 4, as well as part of the included CDN option).

Ideally, PatternFly 4 would also offer the Regular icon sets that are available for free (non subscription use), as part of the CDN option. The CDN URL for the Regular (free) icons is `https://use.fontawesome.com/releases/v5.7.2/css/regular.css`.

Currently, there are 150 Regular icons available to Font Awesome 5 Free users. https://fontawesome.com/icons?d=gallery&s=regular&m=free

**Comment by karelhala** [comment]
Are you talking about react icons [1]? If so there is Pr https://github.com/patternfly/patternfly-react/pull/1385 opened to add regular icons as well.

[1] http://patternfly-react.surge.sh/patternfly-4/styles/icons

**Comment by mindreeper2420** [comment]
@karelhala This is for adding the Regular icon set into Core, in the case where it is used without the React library. It would be added under this line: https://github.com/patternfly/patternfly-next/blob/9bbbc1af24bc4809054cbf3a3081265546cc1e04/src/patternfly/_icons.scss#L10

**Comment by bdellasc** [comment]
@mindreeper2420 looking at the available icon set for react, we have over 1500 Free Font Awesome (solid, regular and brand) icons. Would adding these regular icons to Core align the available set to the 1500+ react set? I can only see a small subset of the currently available (recommended) icons that core has and have no idea if this will close the gap I described above?

I think it's important to point out that our recommended icon list will only overlap with a small portion of the overall icon set, but they are available to use if we don't have a recommendation.

**Comment by mcoker** [comment]
bump
