### ISSUE TITLE
Re-evaluate 'on-running' icon

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#1533]
An issue was filed in patternfly-design requesting that we re-evaluate the 'on-running' icon as it conflicts with the OLM product logo. See https://github.com/patternfly/patternfly-design/issues/740 for details. Intended result would be to replace or introduce an alternative icon to the PF4 icon set.

**Comment by lboehling** [comment]
here are a few different ideas for the running icon. let me know what you all think!  

<img width="673" alt="Screen Shot 2019-06-13 at 4 42 19 PM" src="https://user-images.githubusercontent.com/46571616/59518364-825d4c80-8e93-11e9-8f66-709bcddbb12c.png">

@mcarrano @kybaker @bmignano

**Comment by mcarrano** [comment]
I actually like option 3 @lboehling . What do others think? Is this something you can bounce off of others on the product team @bmignano to see if it's acceptable?

**Comment by mcarrano** [comment]
In response to email from @bmignano on June 27:

> I was able to share the latest design options from #1533 with the OpenShift team today. In general, we liked Option 1 and 3 and are happy to move forward with either, but are curious how each option meets the needs of other products, since it would be a PatternFly recommended icon. (Option 2 is probably not a good fit for our needs, and it sounds like we may have used it in past to much confusion by users.)

> In general there was still some concern specifically about what 'Running' really means and how it should be visualized, since we have a couple of different meanings for it within the OpenShift console. For example, a Pod in a running state is different than a Build in a running state, and some feel they maybe should have different icons to represent that. However, this may just be a terminology issue and / or just an OpenShift specific problem. This is why we're curious which icons work for other products.

It does become hard to capture every nuance of meaning that an icon might have. If we adopt option 3, I'm hoping that users will factor in context when considering differences between 'running' when looking at Pods or Builds. That said, I agree that getting some further cross product input would be good before adopting option 3 into the icon set for PF4. I will float this out to the wider team for feedback.

**Comment by serenamarie125** [comment]
option 3 looks nice!  It looks similar to a heartbeat icon.  I'm not aware of any conflicts but I'm tagging a few others @beanh66  @cshinn @tlwu2013 @ncameronbritt to see if the heartbeat concept is something they have considered in cluster monitoring or UHC.

**Comment by rhwood** [comment]
IEC has [standards for power state icons](https://en.wikipedia.org/wiki/Power_symbol#Standards). Although these seem to be intended more for physical power switches, perhaps those might be useful?

**Comment by kybaker** [comment]
@rhwood That is interesting approach and will definitely keep these in mind as we create PatternFly icons into the future.

@lboehling I agree with Matt and Serena here. Given the experience with some of the other designs in the past with PF3 option 3 here seems like the way to go.

**Comment by mcarrano** [comment]
Thanks @kybaker Let's move this forward to implementation then.

**Comment by maryshak1996** [comment]
@lboehling @kyle
@bmignano just sent me this and option three looks really great! just one quick comment about the scalability. I wonder if it might benefit from removing that last bump? In openshift, we'd be using this icon in very small contexts and that part looses definition a bit as I scale down, making the icon itself a little less crisp. just some food for though!

**Comment by lboehling** [comment]
[PF-Running-Icon.svg.zip](https://github.com/patternfly/patternfly-next/files/3443064/PF-Running-Icon.svg.zip)

**Comment by mcarrano** [comment]
@bdellasc Is this accounted for in the updated icon set? If so, I will close this out. Thanks.

**Comment by bdellasc** [comment]
It will be once we get the SVG path fixes done to the JSON. Please leave it open for now.
