### ISSUE TITLE
Review utility classes and propose new utility classes

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1534]
Prior to Launch we should review the utility classes we currently have to ensure they are up to date, and also propose new utility classes that may be useful. 

In the display utility for `display: none` , `visibility: hidden` should also be used. 

Another suggestion:

`.pf-u-truncate {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}`

**Comment by mcoker** [comment]
`.pf-u-nowrap { white-space: nowrap; }` would be a good one, for example to wrap around 2 or more things so they wrap together when the content around it wraps (like 2 words in a paragraph you want to keep together)

**Comment by mattnolting** [comment]
__We can remove__
- `.pf-u-flex`
- `.pf-u-display-inline-flex`
- `.pf-u-display-inline-grid`
- `.pf-u-display-flex-row`, `.pf-u-display-flex-row-reverse`, `.pf-u-display-flex-columns`, `.pf-u-display-flex-column-reverse`
- `.pf-u-justify-content-*`
- `.pf-u-align-items-*`
- `.pf-u-align-content-*` i suspect this will rarely be used
- `.pf-u-flex-wrap`, `.pf-u-flex-nowrap`, `.pf-u-flex-wrap-reverse`

__Add to utilities__
- `.pf-u-display-initial`

__Add to `.pf-l-flex`__
- `.pf-m-inline-flex`
- `.pf-m-align-items-{flex-start, flex-end, center, baseline}`
- `.pf-m-align-self-{flex-start, flex-end, center, baseline, stretch}`
- `.pf-m-flex-wrap`, `.pf-m-flex-nowrap`

Add to `.pf-l-grid`
- `.pf-m-inline-grid` to `.pf-l-grid`

Update
- documentation for `.pf-u-hidden`

I also question the need for `!important` for all utilities..

**Comment by srambach** [comment]
+1 for `.pf-u-truncate`, would have used that today

**Comment by castastrophe** [comment]
It would be really helpful if the utility styles  were extends and the class extend them. That would make it easier for the web component project to directly extend styles from PF.
