### ISSUE TITLE
Chart colors: Modify base color order to improve contrast in unordered charts

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly#1551]
When unordered line charts with multiple values utilize the chart color system, contrast is hindered by the order of the base colors. Because blue, cyan, and green are ordered consecutively, we end up in a situation like below where there is more likely to be similar colors next to each other such as a light blue and a light cyan.

![image](https://user-images.githubusercontent.com/30935938/54205597-08d94b00-44ad-11e9-934b-7589871c5b1b.png)

Note the light blues, greens, and cyans that fall close to each other. We can help to avoid this by changing the ordering of the base colors, splitting these up by placing more contrasting colors between them.

The overall ordering system won't change at all, just the order that the base colors are placed in. 

I need to experiment with this over the next couple weeks and will provide a new chart color order once complete.

@cshinn @kybaker @rachael-phillips @mcoker

**Comment by mceledonia** [comment]
I think the key here (instead of trying to devise another color system for unordered charts) is to only recommend the chart color order for ordered/sequential charts, where we can predict the locations of the colors on the graph. Essentially anything other than a line chart, at least in terms of current PF charts.

We might recommend a set of colors for the multi line chart but I think for now we can leave it up to the users.

**Comment by cshinn** [comment]
Here's a proposed color order for unordered charts (like line charts) that reduces the number of similar colors used for smaller numbers of series
![colors](https://user-images.githubusercontent.com/3300756/58729990-d7d82a80-83b8-11e9-84bc-754447ef3c53.png)

It's a little easier to digest when organized by color families
![color rows](https://user-images.githubusercontent.com/3300756/58730290-aad84780-83b9-11e9-8f9d-1a6e2e9a2098.png)

**Comment by mceledonia** [comment]
Thanks Chris, just to reiterate this is just for charts that are unordered, such as a line chart where any two colors can end up anywhere on the graph.

@dlabrecq @mcoker @gdoyle1

**Comment by dlabrecq** [comment]
We will have chart color themes for blue, green, etc. I'm assuming this would this be the multi-color theme? 

By default, the charts will use the blue theme. Unless, we want the line chart to use the multi-color theme by default?

**Comment by gdoyle1** [comment]
@mceledonia @cshinn Would it be good to add this proposed scheme to our chart colors styles page too (https://www.patternfly.org/v4/design-guidelines/styles/chart-colors)? Also @dlabrecq - Michael created a multicolor color order for ordered charts in his charting doc (https://docs.google.com/document/d/1cw10pJFXWruB1SA8TQwituxn5Ss6KpxYPCOYGrH8qAY/edit?usp=sharing). We'd prob call this one something else? Since we already have that name in use.

**Comment by cshinn** [comment]
@gdoyle1 this is basically a small alteration of the multicolor order (I kept the principles of the color system, just swapped the order that the color families show up) If there's no particular reason for the color family order in the multicolor order, this could replace it without any decrease in "performance" but I'll defer to @mceledonia on that one

**Comment by mceledonia** [comment]
I could go either way on that, it's not particularly necessary but wouldn't hurt... it would be a lot of updates to make though which I'm ok with avoiding. @cshinn @dlabrecq It sounds like this could exist as it's own theme... "Unordered chart multicolor order" does that make sense to you guys?

**Comment by dlabrecq** [comment]
I don't understand difference between ordered charts are Vs unordered charts? IMO, this is the new order for the multi-color theme?

**Comment by cshinn** [comment]
It's a pretty small difference. basically it just lets you get a bit farther down the list before you get two colors that look similar. It might help differentiability for charts with ~14 series, but when you get more than that, it's functionally identical to the current order

**Comment by cshinn** [comment]
Up to you guys whether this benefit is worth the overhead

**Comment by dlabrecq** [comment]
Sounds confusing having two multi-color themes. Are devs going to understand when to use the multiple, mutil-color themes with ordered Vs unordered charts? I don't quite get it myself.

**Comment by gdoyle1** [comment]
@dlabrecq Doesn't matter to me - I'm fine with updating all the chart documentation to match. 

I believe ordered vs unordered data refers to how they populate the chart. For example, a bar chart is ordered since each variable has a set location on the chart. A line chart is not since we do not have control over where the data populates per variable (and therefore the lines can intercept). The same could occur in a dot chart (although we don't have those).

**Comment by dlabrecq** [comment]
Unless we also define which chart components can use each multi-color theme, it would be preferable to support one multi-color theme for all charts.

**Comment by mcarrano** [comment]
@mceledonia @gdoyle1 Is this still an issue or can I close this?
