### ISSUE TITLE
icon request for "module"

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#1552]
@schizari pulled together [findings for a survey](https://docs.google.com/presentation/d/1WYuOEYn4eOnQR-jh97ya4NsAS6w4qBhcp3JQTBVkaQY/edit?usp=sharing) where we collected feedback about icons for "package" and "module". Based on the findings, it seems like participants prefer seeing a visual relationship between these icons, where a "module" shows multiples of a "package".

Updates requested in this issue include:
- A new [patternfly icon](https://v2.patternfly.org/design-guidelines/styles/icons) for "module" (refer to the description included in the findings linked above) 
- An updated `bundle` icon (used to represent "package") if necessary
  - The "module" icon should be a collection of packages, but the current package icon might not work well when scaled down
  - If the `bundle` icon is updated, it should still be visually similar to what it is today. 

cc'ing @rachael-phillips and @Rohoover

**Comment by lboehling** [comment]
Hi! I updated the "bundle" icon so that it is isometric and styled like FA icons, and made a "module" icon. Let me know what you think!
<img width="999" alt="Screen Shot 2019-06-18 at 2 35 57 PM" src="https://user-images.githubusercontent.com/46571616/59712099-7e566500-91da-11e9-98a3-799d94f97719.png">

@jgiardino @mcarrano

**Comment by jgiardino** [comment]
Thanks for working on this, @lboehling! It's very exciting to see a Module icon start to take shape!

Ultimately, the Module icon will need to get rendered at the same size as the Bundle icon in the UI. Without seeing the updated module icon at that size, it's hard to judge how well it would hold up.

I'm also wondering if all of those lines are needed on the bundle, or if we can start to remove some for simplicity but keep some for consistency with the old version. Maybe eliminating some of the lines will help when the module icon gets scaled down? 

In the FA icons below, the way the sides are shaded help reinforce the dimensional aspect of the cube. And I feel like it's really easy for my brain to process the 3d structure being represented in their Cubes icon. Whereas in the Module icon above I feel like it's more of an ambiguous shape, like the rabbit-duck, where my brain sometimes sees a fidget spinner and sometimes sees a stack of bundles. 

Also, I think these FA icons are currently used in other products for representing other things. Would we want there to be similar aspects to these in terms of size, spacing and dimension? But still have aspects that are obviously different to avoid confusing the two? 

![image](https://user-images.githubusercontent.com/21063328/59718480-4a823c00-91e8-11e9-9b3b-a9bbfb003ac3.png)

**Comment by mcarrano** [comment]
What are the next steps here then @lboehling @jgiardino ? I agree that we should evaluate the module icon at actual size. Are there alternatives we could explore?

**Comment by lboehling** [comment]
@mcarrano @jgiardino here are some alternate icons that are more aligned with the look/sizing of the fa-cube and fa-cubes icons. I also adjusted the sizing so you can see them all at the same size. 

<img width="423" alt="Screen Shot 2019-06-20 at 1 54 19 PM" src="https://user-images.githubusercontent.com/46571616/59944326-75f86700-9432-11e9-92e0-02e0bf73c930.png">

**Comment by jgiardino** [comment]
Thanks for working on these variations, @lboehling! 

I included a few random thoughts below, but I'd love to hear what others on the team think.

I like options 1 and 2 the best. It's hard for me to judge if the lines are better in one or the other. It seems to be easier to discern what the 3 dimensional shape is when the shadow is present, but the shadowing is flipped to the right side versus the left side. Do we have guidelines on what side the shadow should be on? It seems odd being on the right, but that could just be an expectation I derived from looking at the FA icons too much.

Just as a comparison, I took option 2 and flipped the shadow, and then also tried what would happen if we remove the line from one of the cube sides. I'm not sure if this is too similar to the FA cubes icon, though, which last I checked was being used in some product for something (maybe "containers").  

![image](https://user-images.githubusercontent.com/21063328/60040873-f5cb3f00-9687-11e9-82b3-0fd201d68af2.png)

If you do a google search for "software package icon" images, there is a similar icon to this and option 2, except some show the line on the top as tape that goes halfway down the side, and that seems to help reinforce the idea of a "package".

![image](https://user-images.githubusercontent.com/21063328/60041661-f6fd6b80-9689-11e9-80f6-2ef9f9bc1864.png)

![image](https://user-images.githubusercontent.com/21063328/60041677-ffee3d00-9689-11e9-921f-72ea6e260a93.png)

![image](https://user-images.githubusercontent.com/21063328/60041764-290ecd80-968a-11e9-9bdd-c8eb93ff76f5.png)

![image](https://user-images.githubusercontent.com/21063328/60041829-46dc3280-968a-11e9-9333-9b62e06c4f4e.png)

**Comment by mcarrano** [comment]
@lboehling @jgiardino and I met to discuss next steps. Lucia will create another iteration on 'package' based on Jenn's feedback. We will introduce this as a new icon called 'package' to not impact people who are already using the existing 'bundle' icon. We will therefor introduce 2 new icons, 'package' and 'module' which is defined as a group of packages.

**Comment by lboehling** [comment]
Here are the new iterations for "package" and "module."
<img width="485" alt="Screen Shot 2019-06-27 at 5 03 42 PM" src="https://user-images.githubusercontent.com/46571616/60300812-c9b8f380-98fd-11e9-80d6-978022a9f0c3.png">
[package-module-icons.zip](https://github.com/patternfly/patternfly-next/files/3336620/package-module-icons.zip)

**Comment by mcarrano** [comment]
I agree. These look great. Thanks, Lucia!

**Comment by mcarrano** [comment]
@kybaker @mceledonia @jgiardino Please review the latest iteration of icons for Package and Module and if you approve. I will move this over to CSS for implementation. This will add these as new icons and leave Bundle unchanged. @LHinson @rachael-phillips making you aware.

**Comment by mceledonia** [comment]
These look good to me, thanks @lboehling @mcarrano

**Comment by schizari** [comment]
@jgiardino @mcarrano @lboehling looks great! please let me know if you'd like to put the latest proposal into testing alongside other variations to investigate affordance. We could easily replicate the same study that initiated this icon request.

**Comment by mcarrano** [comment]
@jgiardino do you think we benefit from further testing on this? I'm OK either way. Otherwise I think we can move forward with adding the new 'module' icon design to the library.

**Comment by jgiardino** [comment]
I chatted with @schizari this week about whether we need to do additional testing. We decided that we should move forward with the icon designs that @lboehling provided, on the assumption that any feedback we get wouldn't result in major changes to the design. But if we ever do have a research activity in the future related to icons in PF, we would like to include these icons as part of that study.

**Comment by rachael-phillips** [comment]
Thanks for the update, @jgiardino !

**Comment by mcarrano** [comment]
@bdellasc This was some work that was done last year and it's unclear if these recommendations ever made it to the official PF icon set. Can you verify?

**Comment by bdellasc** [comment]
No, I hadn't seen them before today. I'll fold them into the other work that's happening. Thanks for the heads up @mcarrano.
