### ISSUE TITLE
Button Design in Dark Mode 

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1556]
In #1516 the input group background changed to white and now design would like to explore other options for buttons in dark mode.

**Comment by mceledonia** [comment]
Update here - we are going to align with the digital team's solution for this, with slight modifications to fit our system better. Working on the details today and meeting with Kyle and Matt Coker tomorrow to confirm the direction.

**Comment by mcoker** [comment]
> Kyle and Matt Coker

🤠

**Comment by mceledonia** [comment]
Updating here, still some hover values that I need to confirm, left those out for now...
@kybaker @christiemolloy 

--

Primary Default
Fill: 06C

Primary Hover
Fill: ?

--

Secondary Default
1px Border: 2B9AF3

Secondary Hover
2px Border: 2B9AF3

--

Destructive Primary Default
Fill: CE2615

Destructive Primary Hover
Fill: ?

--

Text Button Primary Default 
Text color: 2B9AF3

Text Button Primary Hover
Text color: 73BCF7

**Comment by mcoker** [comment]
@mcarrano @mceledonia looks like we're still missing hover colors for some of these? Also just want to confirm that "Text" style is our link style button?

**Comment by mcoker** [comment]
@mceledonia is actively working on dark theme, this can be done in that work.
