### ISSUE TITLE
Review all PF components in all browsers and devices that we support

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1558]
Before the next release, I think its imperative that we review all PF Core components in all the browsers and devices that we support.

**Comment by mcoker** [comment]
@mcarrano wdyt about this one? This could be a good task for an intern or designer to ensure the components match the intended designs in each browser.

**Comment by mcarrano** [comment]
Sure, it could be @mcoker . But this issue is quite old. Any reason to believe we have a need to do this? If not, I would just close.

**Comment by mcoker** [comment]
@mcarrano there is no specific need, I'm just in favor of the idea in general. Will go ahead and close.
