### ISSUE TITLE
Investigate method to limit width of layouts in full-width containers

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#1593]
We have some instances where we likely want to limit the width of content in a layout in a container that is full-width. For example, in the page component, the main sections allow content to be full-width, but we probably don't want text/content and forms to span the entire width of the viewport, and have some sort of reasonable `max-width` instead.

There may be other components we want to limit the width of, and pages other than the page component where the width should be limited, too. 

I imagine this is a layout of some sort that could be applied to any combination of component/layout in any other component/layout.

<img width="2147" alt="Screen Shot 2019-03-18 at 10 23 33 AM" src="https://user-images.githubusercontent.com/35148959/54541553-26ecf280-4968-11e9-9e76-4931497b1f4b.png">

cc @mceledonia @kybaker @mcarrano

**Comment by mcarrano** [comment]
Good question @mcoker . This has come up before relative to forms layout. IMO there should be a way to set a max-width on a form so you don't get what you show above.

**Comment by mcarrano** [comment]
@rachael-phillips @LHinson We should get this one on the roadmap. It is tightly coupled with #919

**Comment by rachael-phillips** [comment]
That's good to know. Thank you, @mcarrano. I will put this on the roadmap. So when we say it is tightly coupled does that mean when we complete Forms V2 we must complete this issue as well?

**Comment by mcarrano** [comment]
I think so. @kybaker and @mceledonia would be in a better position to comment.

**Comment by jpramos123** [comment]
Hello guys,

I'm facing a similar point with width.

I don't want the table getting the entire width.

Can you help me with a workaround or a solution?

![image](https://user-images.githubusercontent.com/13910652/83213775-5c2ecc00-a139-11ea-8a8b-dc38e06c4feb.png)

**Comment by mcoker** [comment]
Hi @jpramos123 for the time being, could you add a unique class to your app's CSS that you apply to elements you want to limit the width of? The class could apply to individual elements (such as the table or data-list), or a wrapper that contains multiple elements. Something like:

```
.app-layout-maxwidth {
  max-width: 1000px;
}

...

<table class="pf-c-table app-layout-maxwidth">...
<ul class="pf-c-data-list app-layout-maxwidth">...

// or 

<div class="app-layout-maxwidth">
  <table class="pf-c-table">...
  <ul class="pf-c-data-list">...
```

**Comment by jpramos123** [comment]
@mcoker Thanks for your guidance!

As I'm working with React, I used the same logic using React syntax:

`    
.app-layout-maxwidth {
  max-width: 1000px;
}

...

render() {

        const {columns, rows} = this.state;

        return(
            <PageSection>
                <div className="app-layout-maxwidth">
                    <DateInput/>
                    <Table aria-label="Sales Table" cells={columns} rows={rows}>
                        <TableHeader/>
                        <TableBody/>
                    </Table>
                </div>
            </PageSection>
        )
    }`

**Comment by mcoker** [comment]
Closing in favor of https://github.com/patternfly/patternfly/issues/2910
