### ISSUE TITLE
Context Selector - add examples for variations 

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#1608]
During review and discussion of https://github.com/patternfly/patternfly-react/pull/1526, a question came up regarding whether the button is needed. As a result of this discussion, the following variations should be available for the context selector:

1. **No search, just a menu** - this would be used when there aren't that many menu items
2. **Search field with search icon** - this would be used when the menu items are filtered while typing in the search field
3. **Search field with search icon as button** - this would be used when filtering the menu items on every key change would be really expensive 🤑and instead would want to wait until Enter or button click event to filter. This is the variation we have now.

When adding the example for variation 2, we should use the InputGroup component similar to the following:
![image](https://user-images.githubusercontent.com/21063328/54707516-a967e480-4b17-11e9-9ab3-bb423ef984e1.png)

**Comment by mcoker** [comment]
@jgiardino do you know if this is still something we should add demos of and build support for into the react components? We have the same search box in select, tree view, and app launcher, too.
