### ISSUE TITLE
Clean up SCSS/includes

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#1622]
This is a follow-up to https://github.com/patternfly/patternfly-next/pull/1467. We talked about renaming and potentially reorganizing some of the files so it's more intuitive to find and include files in a project.

First steps should be to come up with a plan that we can review as a group before beginning. For this release, we should not move `patternfly.scss` or `patternfly-base.scss`.

cc @dgutride

**Comment by evwilkin** [comment]
Current SASS files:
https://github.com/patternfly/patternfly/blob/master/gulpfile.js#L11

**Comment by ddonahue007** [comment]
Scope of this PR is to move most of the top level scss files into a directory structure that hopefully makes more sense.  I have listed out below what you should see in 'dist' after running `npm run build-patternfly`. (only the base level files)

## BREAKING CHANGES ## 

dist/
├── README.md
├── RELEASE-NOTES.md
├── addons
      ├── _chart-globals.scss
      ├── patternfly-addons.css
      ├── patternfly-addons.scss
      ├── patternfly-charts.css
      └── patternfly-charts.scss
├── assets
├── base
      ├── _base.scss
      ├── _common.scss
      ├── _fa-icons.scss
      ├── _fonts.scss
      ├── _globals.scss
      ├── _icons.scss
      ├── _pf-icons.scss
      ├── _shield-inheritable.scss
      ├── _shield-noninheritable.scss
      ├── _themes.scss
      ├── _variables.scss
      ├── patternfly-common.css
      ├── patternfly-common.scss
      ├── patternfly-fa-icons.css
      ├── patternfly-fa-icons.scss
      ├── patternfly-fonts.css
      ├── patternfly-fonts.scss
      ├── patternfly-globals.css
      ├── patternfly-globals.scss
      ├── patternfly-icons.css
      ├── patternfly-icons.scss
      ├── patternfly-pf-icons.css
      ├── patternfly-pf-icons.scss
      ├── patternfly-shield-inheritable.css
      ├── patternfly-shield-inheritable.scss
      ├── patternfly-shield-noninheritable.css
      ├── patternfly-shield-noninheritable.scss
      ├── patternfly-themes.css
      ├── patternfly-themes.scss
      ├── patternfly-variables.css
      └── patternfly-variables.scss
├── components
├── icons
├── layouts
├── package.json
├── patternfly-base.css
├── patternfly-no-reset.css
├── patternfly.css
├── patternfly.min.css
├── patternfly.min.css.map
├── sass-utilities
├── site
└── utilities
