### ISSUE TITLE
Should the login live outside of the login container?

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1631]
I can foresee cases where someone would want to use the login outside of its layout, for example in a popover, or in the context of another page.

We should investigate this and see what products need. If so we should separate the login from its layout in the current login component that we have.

cc: @mcarrano @rachael-phillips

**Comment by rachael-phillips** [comment]
@mcarrano what are your thoughts here?

**Comment by mcarrano** [comment]
@christiemolloy and I had discussed this a bit. Making this change would make our login approach more flexible and modular, but I am not aware of any particular product requirement. I assume this would be a breaking change so we should proceed with caution. 

Perhaps get more input from PF stakeholders?

**Comment by mcoker** [comment]
@mcarrano wdyt, still something we should look at doing?

**Comment by mcarrano** [comment]
No one has asked for this. Let's close.
