### ISSUE TITLE
Card updates

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#1633]
- Add example of `article` with `header` and `footer` elements https://www.w3.org/TR/html52/sections.html#example-86aedc40
- Add example of card when whole card is a link (allowed in html5, https://www.w3.org/TR/html52/textlevel-semantics.html#example-e6ee3b01)

**Comment by mattnolting** [comment]
Suggested structure for updates
<article class="pf-c-card">
  <a href="#">
    <header class="pf-c-card__header">Header</header>
    <div class="pr-c-card__body">Body</div>
    <footer class="pf-c-card__footer">Footer</footer>
  </a>
</article>
```

**Comment by rachael-phillips** [comment]
Same question here :) are you working on this right now?

**Comment by mcoker** [comment]
ping @kybaker - when we spoke recently about mega menu, seemed like you had feedback on making an entire card clickable (outside of the context of the mega menu)?

**Comment by mattnolting** [comment]
@rachael-phillips I am not working on this right now, although I did recently implement for Cloud Services. Here's what we did: https://cloud.redhat.com/

This approach uses an absolutely positioned `<a>` which, after testing with VoiceOver, I don't think is the correct approach. 
Here's what I'm thinking
```
<article class="pf-c-card pf-m-link-card">
  <a class="pf-c-card__card-link" aria-label="Link to something" href="#">
    <header class="pf-c-card__header">Header</header>
    <div class="pr-c-card__body">Body</div>
    <footer class="pf-c-card__footer">Footer</footer>
  </a>
</article>  
```

**Comment by kybaker** [comment]
@mcoker After viewing Matts proposal I don't have a problem with this. I added the 'Getting Started' text to these cards specifically to give the user an indication they are actionable. If Matt want to extend the clickable area to the whole card it is an improvement. Thank you for letting me know.
