### ISSUE TITLE
Add `pf-m-plain` modifier support for `<ul>`, `<ol>`

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#1635]
Currently, many mockups present `<ul>`, `<ol>` with no list styling. Need to add this with enhanced CSS.

One example: https://redhat.invisionapp.com/share/R5QLEKZ9JXA#/screens/348804737

<img width="597" alt="Screen Shot 2019-03-26 at 11 52 48 AM" src="https://user-images.githubusercontent.com/5385435/55012489-e0c60d80-4fbd-11e9-9bca-f32673998f33.png">

**Comment by rachael-phillips** [comment]
Same question here :) are you working on this right now?

**Comment by mattnolting** [comment]
I am not working on this right now:)

**Comment by mcoker** [comment]
@mcarrano should we keep this and add it to the roadmap?

**Comment by mcarrano** [comment]
I guess we should.

**Comment by mcarrano** [comment]
Please keep this open. It's on the roadmap.
