### ISSUE TITLE
Form input background color in dark mode

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly#1647]
We need a dark themed version of input fields for dark mode. Keeping the current white background in a dark theme not only looks bad but also causes a multitude of issues with our button styling. For example, the secondary blue outline optically disappears when between the bright white fill of the button and dark color of the background.

Utilizing a more proper background color for inputs will solve these issues and look more refined.

Luckily the bottom border color is still accessible on the dark background so we can keep that color the same while just changing the input background.

This should extend to any applicable form input element, such as input groups and dropdowns. 

New input background color:

#282D33
$pf-color-black-900

With the background color change we also have to change the color of the input text, which will now be white 

#ffffff

![image](https://user-images.githubusercontent.com/30935938/55098891-1e499a00-5095-11e9-8782-002318d9a3d5.png)
Check out the optical issue that the contrast of the current design creates - the bottom border color is the exact same in both of these, but practically disappears when next to the white background.

FYI
@kybaker @rachael-phillips @LHinson @mcoker

**Comment by mceledonia** [comment]
linking #1556 as this is related

**Comment by mcoker** [comment]
Thanks michael! `$pf-color-black-900` is now `#151515` after the new brand updates, and that's also what the default white background color (`$pf-global--BackgroundColor--100: $pf-color-white`) changes to in a dark theme (`$pf-global--BackgroundColor--dark-100: $pf-color-black-900;`).

So adding this in would make the background of the form control match the default dark mode background color. 

FWIW, here's what that looks like:

<img width="1018" alt="Screen Shot 2019-03-29 at 4 43 22 PM" src="https://user-images.githubusercontent.com/35148959/55264261-c9975200-5241-11e9-8546-6e635c4d2326.png">

Also note the disabled states, and default grey bottom border. And FWIW, this is what the active border looks like.

<img width="992" alt="Screen Shot 2019-03-29 at 4 43 49 PM" src="https://user-images.githubusercontent.com/35148959/55264313-ed5a9800-5241-11e9-97ae-7d5919cdd3f3.png">

What do you think? And I can put this up on a branch if you want to have a deploy link to look at.

**Comment by mceledonia** [comment]
@mcoker Thanks for the heads up, I will need to revisit this today with the new color variable in mind. We don't want it to be the same color as the background and we also are going to want to change the outer border colors (all but bottom) as well. 

I will need to provide separate color values for the disabled and read only states, the defaults are not going to work as we can see above :) 

I will get on this today!

**Comment by mceledonia** [comment]
![image](https://user-images.githubusercontent.com/30935938/57624634-5da64a00-7560-11e9-853e-d8ed814b7356.png)

Default
Fill: 393F44
Bottom Border: 85888C 1px
Text: FFFFFF

Hover
Fill: 393F44
Bottom Border: 85888C 2px

Error
Fill: 393F44
Bottom Border: C9190B 1px
Text: FFFFFF

Error Hover
Fill: 393F44
Bottom Border: C9190B 2px
Text: FFFFFF

Disabled
Fill: 4D5258
Bottom Border: None
Text: D2D2D2

**Comment by mcarrano** [comment]
@mcoker do you have what you need from design on this one? Can we queue up for CSS?

**Comment by mcoker** [comment]
I'm a little confused about this part

```
Default
Fill: 393F44
Bottom Border: 85888C 1px
Text: FFFFFF

Hover
Fill: 393F44
Bottom Border: 85888C 2px
```

The bottom border colors are the same, but visually are different. Also the `:hover` border is visually 1px, not 2px. Should we update the hover and focus state to be the same (2px)? Or only change color on hover, and change color and border-width on focus like it is now in non-dark mode?

**Comment by mcoker** [comment]
@mceledonia is actively working on dark theme and this work can be included in that effort.
