### ISSUE TITLE
Safari 12.1 includes scroll reset position when updating inner html on content bug

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly#1688]
https://bugs.chromium.org/p/chromium/issues/detail?id=833837 documents the bug as it appeared in Chrome (I'm linking to this Chromium bug as it details the bug including test cases as there is not yet an open Bugzilla for Webkit).

The bug is visible in http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/examples/page-layout-expandable-nav once `div#___gatsby` and `div[role="group"]` have `height: 100%` added (note this is a separate bug with the test page).

Note how clicking `Authentication` results in the nav scrolling back to the top.

![aNnTJGNlS6](https://user-images.githubusercontent.com/895728/55506615-e1951a00-5623-11e9-9347-c143525e8087.gif)

Bug causes OpenShift web console to be barely usable in Safari 12.1.  The trigger here is hovering over an `a`.

![2kGrnEAlSL](https://user-images.githubusercontent.com/895728/55506754-3d5fa300-5624-11e9-84a8-a21e8b68807b.gif)

OpenShift web console Bugzilla where issue initially reported: https://bugzilla.redhat.com/show_bug.cgi?id=1695446

Possible workaround:  remove the use of grid for layout of `pf-c-page`.

attn: @mcoker, @priley86, @janwright73

**Comment by rhamilto** [comment]
^ @spadgett

**Comment by rachael-phillips** [comment]
@rhamilto is this still a problem?

**Comment by rhamilto** [comment]
> @rhamilto is this still a problem?

As far as I know, yes.  We implemented a [workaround in OpenShift](https://github.com/openshift/console/pull/1384).

**Comment by rachael-phillips** [comment]
Ok, thanks for the info!
