### ISSUE TITLE
Investigate Padding on Buttons

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1703]
We're running into a issue where plain buttons have a default padding/target-area. When we put these buttons into different contexts like data-list/data-table, the default padding means that we need to add a negative margin onto the button in order for it to align with content.

I'm wondering if we can explore potential solutions to this issue.. i.e. adding the padding as a pseudo-element.

**Comment by mcoker** [comment]
@christiemolloy do you still think we should explore a solution for this?
