### ISSUE TITLE
How should Breadcrumbs Wrap

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1713]
Right now when the breadcrumb component wraps, the text is very tight. We could add a margin or truncate text. Lets investigate what other systems are doing.

<img width="430" alt="Screen Shot 2019-04-09 at 1 26 57 PM" src="https://user-images.githubusercontent.com/20118816/55821638-f3ffcf80-5acb-11e9-8743-b02404122072.png">

**Comment by mcoker** [comment]
Resolved this in the v4 release.
