### ISSUE TITLE
Make wizard nav 250px by default

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#1737]
Follow up to https://github.com/patternfly/patternfly-next/issues/1736

Remove the modifier and make the default width 250px.

**Comment by rachael-phillips** [comment]
@mcoker @LHinson will we move forward with this at this time considering it is a breaking change?

**Comment by LHinson** [comment]
I think we should plan to introduce this breaking change in our August release. This impacts OpenShift Migration Tool (On OpenShift schedule, June code freeze) --- I think they will be ok to wait on the change but will be meeting with them to confirm once they have a demo to share.
