### ISSUE TITLE
first/last-child bug in table drop column support

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#1769]
We currently apply unique padding to the first/last child of table rows, and this custom padding breaks if the first and/or last child is hidden using the drop column modifiers.

**Comment by christiemolloy** [comment]
@mcoker what do you think about adding a modifier to a td that adds the extra padding to the left or right of the cell at a certain breakpoint if its going to be the first or last child at that breakpoint. Does that seem maybe too hard to calculate for a user?

**Comment by mcoker** [comment]
Yeah, I think that's asking too much, and I doubt most people would notice the padding isn't correct to begin with so they wouldn't think anything needs to be adjusted. ideally we can figure out a way to do it so the user doesn't have to do anything.

**Comment by mattnolting** [comment]
@mcoker @christiemolloy I explored a possible solution and it seems just too complex to do with pure CSS for the `:first-child` and impossible for `:last-child`. I think the best solution is to remove the modified padding on `first/last` cell. The second best (and only other) solution is to leverage JS to `:first-child:hidden + :next-child-not-hidden => update padding` and `:last-child:hidden + :prev-child-not-hidden => update padding`. 

```
.pf-c-table tr > * {
  // @include pf-hidden-visible(var(--pf-c-table--cell--hidden-visible--Display));

  @each $breakpoint, $breakpoint-value in $pf-c-table--breakpoint-map {
    $breakpoint-name: if($breakpoint != "base", -on-#{$breakpoint}, "");

    @include pf-apply-breakpoint($breakpoint, $pf-c-table--breakpoint-map) {
      &.pf-m-hidden#{$breakpoint-name} {
        display: none;
      }

      &.pf-m-visible#{$breakpoint-name} {
        display: table-cell;
      }

      &.pf-m-hidden#{$breakpoint-name}:first-child ~ :not([style*='display: none']) {
        background-color: orange;
        padding-left: 24px;
      }
    }
  }
}
```

**Comment by mcoker** [comment]
We can close this for now and revisit if it comes up as a bug.
