### ISSUE TITLE
Pagination - set to disabled on loading page

### ISSUE THREAD

**Issue by boaz0** [patternfly/patternfly#1785]
Is there a way to make pagination disabled?

For instance, I have a table of machines and the user wants to see machines in the last page, when she/he clicks on the last page arrow the client side is sending a request to the server and till the client receives a response, I would like the user not to be able to change the pagination and wait for the new data to be rendered.

**Comment by rachael-phillips** [comment]
Hi @boaz0 is this still an issue for you? Sorry for the delay here!

**Comment by boaz0** [comment]
It's not a blocker but it's still needed.

**Comment by rachael-phillips** [comment]
@mcoker making you aware of this one.

**Comment by mcoker** [comment]
I'm curious what @mcarrano thinks here. How do you think we should display the pagination in this state?

**Comment by mcarrano** [comment]
I think that @boaz0 raises a valid point. Seems like this is something that should be built into the React component. From a CSS standpoint, do we need to change anything? Do we need a "disabled state" pagination or can the controls that make up the pagination just be set to disabled via JS code?

**Comment by mcoker** [comment]
If you just disable the form elements in pagination currently, this is what it looks like.

<img width="351" alt="Screen Shot 2019-06-20 at 9 57 49 AM" src="https://user-images.githubusercontent.com/35148959/59859183-e7a4b800-9341-11e9-9218-d96b32d0f095.png">

We don't have a disabled variation of the options menu, but I think that was just an oversight and it should be added, and it would look like our disabled dropdown component.

<img width="264" alt="Screen Shot 2019-06-20 at 9 58 38 AM" src="https://user-images.githubusercontent.com/35148959/59859244-02772c80-9342-11e9-9eca-2e3f5696d07d.png">

So something like this...

<img width="352" alt="Screen Shot 2019-06-20 at 10 00 43 AM" src="https://user-images.githubusercontent.com/35148959/59859427-49fdb880-9342-11e9-829f-673e129d7b5b.png">

If that looks OK, I can open an issue to create a disabled variation of the options menu, then pass the rest off to react.

**Comment by mcarrano** [comment]
Yes, I think that makes sense @mcoker

**Comment by mcoker** [comment]
@mcarrano added https://github.com/patternfly/patternfly-next/issues/1962. Also we don't have a disabled version of the select component. Should we add that, too?

**Comment by mcoker** [comment]
Also added an issue to add the example in core - https://github.com/patternfly/patternfly-next/issues/1963.

And here's the react issue for when #1963 is complete - https://github.com/patternfly/patternfly-react/issues/2315

**Comment by mcarrano** [comment]
Sounds good. Thanks @mcoker !

**Comment by mcoker** [comment]
Looks like this has since been resolved via https://github.com/patternfly/patternfly-react/issues/2315

<img width="434" alt="Screen Shot 2020-08-10 at 2 45 15 PM" src="https://user-images.githubusercontent.com/35148959/89824097-31d59380-db18-11ea-80ba-91e3aa26ef10.png">
