### ISSUE TITLE
Recommended width of input forms

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly#1792]
When using the [form components,](https://www.patternfly.org/v4/documentation/core/components/formcontrol) the forms is super long and it looks ugly on the screen. 
We want to make it shorter, what is the recommended width of an input form?

**Comment by terezanovotna** [comment]
![Screen Shot 2019-05-15 at 14 53 16](https://user-images.githubusercontent.com/36040135/57777199-917c9d80-7721-11e9-9203-feb3efc233ca.png)

here is another example from live environment. @rachael-phillips any idea how the input component should be scaled so it's not that long?

**Comment by rachael-phillips** [comment]
Hi @terezanovotna sorry for the delay here. This one slipped past me. Is this still an issue?

@mcoker any input here for Tereza? This looks like a bug in her application

**Comment by mcoker** [comment]
@rachael-phillips @terezanovotna I have also opened an issue around this (https://github.com/patternfly/patternfly-next/issues/1593) and looks like it's being addressed in #919 (https://github.com/patternfly/patternfly-next/issues/919#issuecomment-496571266).

Do you know if #919 is ready to be worked on? I don't see the latest designs in the issue. Assuming it has been addressed in the designs and is a matter of implementing at this point, I'm comfortable closing https://github.com/patternfly/patternfly-next/issues/1593. We can leave this open if you'd like @terezanovotna until that work is complete and this issue has been fixed on your end.

**Comment by rachael-phillips** [comment]
@mcoker Let me ask them to post the latest designs - it should be ready to work on, and we hope to deliver it in mid August.

**Comment by mcoker** [comment]
@terezanovotna apologies for the delay here!! We just approved designs that include the ideal form width, and the [max-width of form fields is 880px](https://marvelapp.com/prototype/eh3c7d4/screen/71128974).

This is from https://github.com/patternfly/patternfly-design/issues/858, and we have a corresponding issue in core to implement these changes in an upcoming milestone at https://github.com/patternfly/patternfly/issues/3380 if you would like to track the progress.

Let me know if you have any more questions, or if it's OK to close this issue.
