### ISSUE TITLE
Add Language Selector to Login page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#1821]
The language selector was removed from the Login page during implementation due to problems with spacing and placement in the login form. At the time it was decided that language selection should be moved to the area outside of the login form. This requires an update to the Select component so it may live on a dark background.

This issue addresses the work required to add the language selector as a single select list outside of the login form.

**Comment by mcarrano** [comment]
@mcoker I have opened this new issue to address the Language Selector in the login page that was deferred earlier. Feel free to edit if I missed anything. @mceledonia I remember we talked about this a while ago, but can't remember if we actually had designs. If so, can you attach them here? I will close out the prior related issues as I don't think they are relevant any longer.

@LHinson @rachael-phillips FYI. Another item to be slotted on the roadmap.

**Comment by matthewcarleton** [comment]
one thing to consider when creating the list of options to have the appropriate language attribute.
```
<ul>
<li lang="en">english</li>
<li lang="fr">francais</li>
</ul>
```
@mcoker you probably already thought of this but wanted to mention it just in case :)

**Comment by mcoker** [comment]
pro tip! thanks @matthewcarleton!

**Comment by mceledonia** [comment]
Here's the latest dark theme dropdown styling, now we just need to figure out the exact placement and spacing of the dropdown in the login page.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/30935938/58187531-ee79d580-7c84-11e9-8d96-c5838d062da4.png">

**Comment by lboehling** [comment]
I mocked up a few placements for the language dropdown. 

In the mobile design, this dropdown can either fall in the header above the login card, or in the footer below the login card. I also included a mobile mockup where the dropdown expands to the full width of the mobile screen to make it an easier target. I think this makes the mobile mock look more balanced.
![Screen Shot 2019-05-31 at 11 19 11 AM](https://user-images.githubusercontent.com/46571616/58716035-2f18d380-8396-11e9-8e4c-256f2152cf23.png)
![Screen Shot 2019-05-31 at 11 19 47 AM](https://user-images.githubusercontent.com/46571616/58716085-4788ee00-8396-11e9-846d-2be2692bd07f.png)

If it’s important to surface the dropdown before the login fields on mobile, I would suggest placing the dropdown either in the top far right of the screen (A) or in between the PF logo and product description on the desktop layout (B). 
![Screen Shot 2019-05-31 at 11 18 38 AM](https://user-images.githubusercontent.com/46571616/58716112-52dc1980-8396-11e9-8a90-5c599e24e840.png)

If placing it in the header on mobile pushes the login fields too far down, we can place it in the footer. In this case, the dropdown would be placed above the terms of use text links on desktop (and below the SSO icons if present) (C). 
![Screen Shot 2019-05-31 at 11 19 38 AM](https://user-images.githubusercontent.com/46571616/58716121-57a0cd80-8396-11e9-8c3f-9cac0305174a.png)


working file: https://sketch.cloud/s/nLxQl?settings=nLxQl

**Comment by mcarrano** [comment]
@lboehling this is looking good. I feel it's important for the language selector to come before the login form on mobile. Therefore on the desktop version, it makes sense after the PF logo as you've shown. @mceledonia @kybaker What do you think?

**Comment by mceledonia** [comment]
@lboehling @mcarrano Agreed, I think having it above the form on mobile is the way to go.. I'm ok with either of those options, I think the one inline with the logo looks best but it raises a few questions... Does the field grow/shrink with longer language selections, or do we keep it a static width and truncate? Resizing also means resizing the logo as the field runs into it. 

Full width below the logo looks less clean to me but probably is the safest option to avoid the above, but if my concerns aren't valid or we have a good solution for that already I think we should go with the inline option.

Nice work!

**Comment by lboehling** [comment]
@mcarrano Here are the specs for mobile/desktop placement of the language selector: https://marvelapp.com/c110cie 

Original design document: https://sketch.cloud/s/nLxQl

**Comment by mcarrano** [comment]
Looks great @lboehling . Thanks!

**Comment by mcarrano** [comment]
Moving to CSS backlog. Design is complete.

**Comment by mcarrano** [comment]
Will add this to the roadmap.

**Comment by mcarrano** [comment]
I am going to reopen this issue and keep in our backlog. It's still a valid need, although there is not really any priority at this time.

**Comment by mcarrano** [comment]
@nicolethoen thanks for the reminder about this. No one has asked for this feature and therefore I think I will close this and we can revisit should it come up again in the future.

**Comment by mcoker** [comment]
@mcarrano the [core login docs](https://www.patternfly.org/v4/components/login-page/html) still have a dropdown in the examples, but the [react login docs](https://www.patternfly.org/v4/components/login-page) don't. Is that OK? I see the language selector is listed in the [login design docs](https://www.patternfly.org/v4/components/login-page/design-guidelines#elements), so that makes sense. In core, currently the login header expects the dropdown component to be used there for it to lay out properly. If we want to show an example of a language selector in the core docs, I'd like to fix that and add an element that positions any kind of menu to be used there (select, composable menu/toggle, etc). It would be an easy update.

**Comment by mcarrano** [comment]
@mcoker thanks for pointing out those inconsistencies. Perhaps we should update these to make them all consistent, at least. If I recall, there was some issue with what we were using for this list. It should be a select of some type and not a dropdown. If that's an update we need to make, I can open a new/fresh core issue and then we can move to React for follow up.

**Comment by mcoker** [comment]
> If that's an update we need to make, I can open a new/fresh core issue and then we can move to React for follow up.

@mcarrano I think it would be good to update and should be pretty easy. Thanks!

**Comment by mcarrano** [comment]
Opened https://github.com/patternfly/patternfly/issues/4745 to make this update. Once that is in, we should open a new React issue to make the core and React examples consistent.
