### ISSUE TITLE
Rename expandable component

### ISSUE THREAD

**Issue by ncameronbritt** [patternfly/patternfly#1828]
This is a very petty issue, but almost all (if not all) components have names that are nouns, whereas ["expandable"](https://www.patternfly.org/v4/documentation/react/components/expandable/) is an adjective (expandable what?). IMO this makes the naming of this pattern inconsistent with the rest of PF. 

Alternatives: "Expandable section." In PF3 this pattern was called "Expand/Collapse Section." "Accordion" or "accordion section" also work. 

I take no position on whether or not the component should be renamed in the code, but I think we should use a noun to refer to it in documentation.

**Comment by rachael-phillips** [comment]
@mcarrano making you aware. What are your thoughts on renaming this component?

**Comment by mcarrano** [comment]
I'd be fine with that as I agree with @ncameronbritt that the current naming is inconsistent with our standard. I believe this change needs to be made in the code so not sure of the effect.
