### ISSUE TITLE
Clarify Chip Group Behavior

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#1837]
The Chip Group component was introduced to manage the behavior of a group of chips used in either a toolbar (i.e. filter chips), a type-ahead select, or for tagging. The current implementation and application raises some question about desired handling of overflow conditions, i.e. what happens when there are too many chips to fit into the parent container. 

Currently this is set as a hard-coded number of chips but it somehow needs to be made more dynamic and detect when to go into overflow based on the size of the parent. Additionally it would be good to arrive at a consistent experience that would support all use cases where the chips are used.

Some background and questions raised by the current design and implementation are documented here: https://docs.google.com/document/d/1bmsgR28EdJ1FsroTBn0crxBB4xdiGPkVGpQ__yaWeG4/edit?usp=sharing

**Comment by mcarrano** [comment]
@mceledonia @mcoker @tlabaj @jgiardino I created this issue as a follow-up to our meeting. Feel free to add any additional information I may have missed. Next steps are to clarify the design intent. @rachael-phillips @LHinson we will need to get this on the roadmap. I believe it will be a breaking change.

@rblackbu want to also make you aware as it may affect the approach for displaying a list of tags.

**Comment by rachael-phillips** [comment]
@mcarrano @LHinson  I'll add this to the unplanned section of the release planning sheet so that we can discuss in our next roadmap planning meeting.

**Comment by mcarrano** [comment]
I have created an initial design proposal here: https://docs.google.com/document/d/1bmsgR28EdJ1FsroTBn0crxBB4xdiGPkVGpQ__yaWeG4/edit?usp=sharing  Comments welcome.

**Comment by mcarrano** [comment]
On June 26, @kybaker @mceledonia @tlabaj @rblackbu @rachael-phillips @trahman73 and I met to review the above proposal. Notes are captured in the Google doc. Next steps - @kybaker will elaborate on visual treatments of chips and chip groups with an eye towards creating a common element to be used in a variety of use cases.

**Comment by mcarrano** [comment]
During an Aug 8 meeting with @tlabaj and @mcoker we agreed that the Chip Group examples should be refactored to be more consistent with the design intent expressed above. This will require refactoring that should be scheduled as a breaking change. Moving to CSS backlog for future consideration.  @LHinson @rachael-phillips FYI.

**Comment by mceledonia** [comment]
Spacing updates for chip group: 
![image](https://user-images.githubusercontent.com/30935938/78710746-dda97100-78e3-11ea-92df-8b040385f75f.png)
- Font color of chip group label changed to secondary text color

**Comment by mcarrano** [comment]
@christiemolloy while making the structural changes described in this issue, we were also hoping to get these styling changes in.

cc @mcoker
