### ISSUE TITLE
Missing paginated table demo + unable to change per page on small screens

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly#1840]
I have talked to @terezanovotna where to show pagination with table and she told me that the best approach would be to add it on top and on bottom of table, so I did that with different pagination variants, but it would be really awesome to have this example in demo pages so others know this as well and they will not have to ask any UX person.

Additional issue rose however when I shrink the view to small screen pagination on top says 18 items and on bottom only page selector is visible and user is unable to change per page on small screens. So I guess we should change the count of all items to be clickable and show per page selector if user clicks on it. This way we will have fully operable paginated content (not limited to table) on limited screens.

**Comment by mcarrano** [comment]
Thanks for raising this issue @karelhala . Does this demo provide the example you are looking for? https://www.patternfly.org/v4/documentation/core/demos/datatable-full?component=Data%20table%20-%20simple%20demo

Regarding the behavior of the pagination on small screens, looks like we did make a decision to hide the 'Items per page' control on the lower pagination component. @mcoker do you remember why? It does look like we could fit the entire pagination below the table.

**Comment by karelhala** [comment]
@mcarrano yeah, that solves the first half thank you! I was not aware of that the site changed. Can we add some toast notification to old version https://v2.patternfly.org/ that the site changed? So that if some devs are used the old one are not using old version of these components?

**Comment by mcarrano** [comment]
@karelhala I did not realize the old URL was out there and in use. @rachael-phillips @jschuler can we add a message as suggested or just have this URL redirect to the production site?

**Comment by rachael-phillips** [comment]
Yes, the new site url is https://www.patternfly.org/v4/. When in doubt visit patternfly.org and click on the new banner. I will open an issue for this on the org repo.

**Comment by rachael-phillips** [comment]
We've deleted https://v2.patternfly.org now.

**Comment by rachael-phillips** [comment]
@karelhala is this still an issue?
