### ISSUE TITLE
Inline variation of copy to clipboard

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#1845]
from https://github.com/patternfly/patternfly-react/issues/2044

We could

1. offer different sized widths like `pf-m-[sm,md,lg,xl]` that a user can use to define the width of the component.
1. refactor the component to use a `<span contenteditable>` instead of `input` (similar to how we use contenteditable on the `.pf-c-clipboard-copy__expandable-content` element). That will allow the component to scale to exactly the width of the content inside of it.

#1 would probably be the easiest, but I think #2 would be the most robust. Not sure if we can do that without introducing a breaking change though. @jgiardino can you think of any downsides to using `<span contenteditable>` instead of an `input` in this component?

**Comment by jgiardino** [comment]
I'm not aware of any. I haven't done much testing, and I only did a quick search online. The following wcag technique mentions how you could make an element with `contentEditable` have an accessible label: https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html

**Comment by mcoker** [comment]
@mcarrano should we leave this one open?

**Comment by mcarrano** [comment]
It's really stale. I'd say let's close and see if it comes around again. Anyone object?
