### ISSUE TITLE
Horizontal Nav items focus border issues

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly#1849]
![image](https://user-images.githubusercontent.com/11633780/58123624-414a8300-7bda-11e9-8b9b-2b4ade4609f8.png)

![image](https://user-images.githubusercontent.com/11633780/58123656-56bfad00-7bda-11e9-9b7b-62003f69e289.png)

related: https://github.com/patternfly/patternfly-react/issues/2054

**Comment by mattnolting** [comment]
relates to: #2001 

Let's update this during next breaking change period.

**Comment by mattnolting** [comment]
@rachael-phillips we can safely add this to without breaking change.
