### ISSUE TITLE
New Data Table Expansion Variant

### ISSUE THREAD

**Issue by yuvalgalanti** [patternfly/patternfly#1853]
Hi, 

I want to propose a new data table that supports some views I'm currently working on for openshift and CNV. 

The idea is to create an expandable row with tabs that appear only when the row is expanded.
In the current data tables, we have:
1. expandable rows behavior - this type of table gives us the option to expand a row to see some more information. 
2. Compound-expandable data table - Use a compound expandable list when you want multiple expansion panels that relate to specific table columns where it would not make sense to combine all of this information into a single, simple expansion.

The new suggestion I want to push is to have tabs under the row expansion. 
Why:

- When we want to show in the row the most important information for the presented item, but we still want to have more information available that will not fit a regular expansion. The content presented on the row is just a glimpse of the content we want to present, and we can't treat a single figure as tab because it doesn't make sense, the tabs titles are different. 

- Try to avoid a third level drill down. for example, I'm in the pod's list in openshift and drilled to a single pod, in one of the tabs under the pod I'm seeing another list, so instead of allowing another drill down that in many cases takes the user out of context, we will allow detailed expansion.

In terms of development, I believe it should be fairly easy to connect the tabs component with the Expandable data table component. 

![Data Table](https://user-images.githubusercontent.com/44394257/58398350-7c770700-805d-11e9-8a7e-7fe064ca11f8.png)

**Comment by lizsurette** [comment]
@yuvalgalanti - I chatted with the PF team today about this and here is what they said/suggested:

The design looks excellent. One thing to note is that there is an update coming to the Tabs visual design where they will look more like classic tabs. Reach out to @kybaker for the latest.

With respect to documentation and implementation, rather than adding this to the Data Table Design Pattern, we should be able to build this with the existing Expandable Data Table (https://www.patternfly.org/v4/documentation/core/demos/datatable) component and then include the Tabs (https://www.patternfly.org/v4/documentation/core/components/tabs) component inside. Basically, use the pieces that PatternFly provides already as building blocks.

Something else that was suggested by @mcarrano is to consider contributing the implementation of this to the "Demos" section of PatternFly which is meant for showing off examples of putting existing components together: https://www.patternfly.org/v4/documentation/core/demos/datatable

What do you think?

**Comment by Rohoover** [comment]
@lizsurette 
Looking at the PF4 work on the other tables, should the blue highlight extend up to encompass the open row as well?

**Comment by LHinson** [comment]
that's correct @Rohoover

**Comment by yuvalgalanti** [comment]
Thanks, @Rohoover  
I updated the image above.

**Comment by yuvalgalanti** [comment]
> @yuvalgalanti - I chatted with the PF team today about this and here is what they said/suggested:
> 
> The design looks excellent. One thing to note is that there is an update coming to the Tabs visual design where they will look more like classic tabs. Reach out to @kybaker for the latest.
> 
> With respect to documentation and implementation, rather than adding this to the Data Table Design Pattern, we should be able to build this with the existing [Expandable Data Table](https://www.patternfly.org/v4/documentation/core/demos/datatable) component and then include the [Tabs](https://www.patternfly.org/v4/documentation/core/components/tabs) component inside. Basically, use the pieces that PatternFly provides already as building blocks.
> 
> Something else that was suggested by @mcarrano is to consider contributing the implementation of this to the "Demos" section of PatternFly which is meant for showing off examples of putting existing components together: https://www.patternfly.org/v4/documentation/core/demos/datatable
> 
> What do you think?

**Comment by yuvalgalanti** [comment]
> @yuvalgalanti - I chatted with the PF team today about this and here is what they said/suggested:
> 
> The design looks excellent. One thing to note is that there is an update coming to the Tabs visual design where they will look more like classic tabs. Reach out to @kybaker for the latest.
> 
> With respect to documentation and implementation, rather than adding this to the Data Table Design Pattern, we should be able to build this with the existing [Expandable Data Table](https://www.patternfly.org/v4/documentation/core/demos/datatable) component and then include the [Tabs](https://www.patternfly.org/v4/documentation/core/components/tabs) component inside. Basically, use the pieces that PatternFly provides already as building blocks.
> 
> Something else that was suggested by @mcarrano is to consider contributing the implementation of this to the "Demos" section of PatternFly which is meant for showing off examples of putting existing components together: https://www.patternfly.org/v4/documentation/core/demos/datatable
> 
> What do you think?

I totally agree @lizsurette. 
I will push this forward, thanks!

**Comment by yuvalgalanti** [comment]
Hi @lizsurette @mcarrano. 
So @yaacov did a quick demo to check if just taking those two components can work and it doesn't seem like it. we will have to do some UI changes in the tabs component to support this implementation.

![localhost 8000 components table  (1)](https://user-images.githubusercontent.com/44394257/59666529-a97e8b80-91bd-11e9-8c8a-05113a3a6425.png)

**Comment by mcarrano** [comment]
I agree that this does not look very good @yuvalgalanti . But there are a couple of things I'd want to explore before committing to making a new Table variant. First, I know that we are considering a new tab style that might work better here. @kybaker can you take a look and comment regarding whether that styling will address this better?

@mcoker can you also take a look at this? Seems like there should be some padding built is and maybe it's a matter of using the proper layout. Any suggestions?

**Comment by mcoker** [comment]
@mcarrano @yuvalgalanti the expandable content area (`.pf-c-table__expandable-row-content`) should have top/bottom padding by default, which will create space between the top of the expandable content area and the top of the tabs component.

Here I added tabs to the expandable content area of a table, and used the [Stack layout](https://www.patternfly.org/v4/documentation/react/layouts/stack/) with a gutter to create space between the tabs and the tab content below it. You can see my markup on the right.

<img width="1623" alt="Screen Shot 2019-06-18 at 10 48 40 AM" src="https://user-images.githubusercontent.com/35148959/59699359-117da380-91b7-11e9-901f-df18c9f2617b.png">

**Comment by yuvalgalanti** [comment]
@mcoker @mcarrano Ya, in the example I shared we played with the padding and that's why you see it close to the top of the expandable content area

**Comment by mcarrano** [comment]
Is this still an open request @yuvalgalanti? Were you ever able to solve this?

**Comment by yuvalgalanti** [comment]
> Is this still an open request @yuvalgalanti? Were you ever able to solve this?

sorry for the late response, I somehow missed that. I think we ended up not doing that and created a secondary drill down for showing the information we needed.  so, for now it's not really needed.

**Comment by mcoker** [comment]
@yuvalgalanti just wanted to follow up and say the new tabs design referenced in this issue is in the latest version of PatternFly. Is it OK to close this issue, or would you like to leave it open and explore this some more?
