### ISSUE TITLE
Add the ability to have favorites in a table view 

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly#1860]
In OpenShift we have a need to allow users to pin or favorite certain items in a table view for quicker access when scanning long lists. The primary use case is for the projects table because users can have hundreds of these but typically only interact with a few at a time. There are other use cases within OpenShift to add this mechanism to tables as well, such as Roles. For this case, we would like to "favorite" a few important roles by default and then extend the behavior to allow users to add or remove from the favorites set by default.

After a number of design iterations, we landed on the following design for the use cases described above: http://openshift.github.io/openshift-origin-design/web-console/future-openshift/pinning/pinning

Seems like this would be worth contributing as a generic component for PF. @bmignano worked on the original designs and can help with a design contribution if desired @mcarrano!

**Comment by mcarrano** [comment]
@beanh66 Thanks for submitting this. I think it will be a useful feature. Once this is slotted on the PF roadmap, I will be happy to work with @bmignano on the design. @LHinson @rachael-phillips please note.

**Comment by rachael-phillips** [comment]
@mcarrano thanks for looping me in - I've added it to the component status unplanned section for the time being. Let's continue to discuss with @LHinson on where it should live

**Comment by mcarrano** [comment]
@beanh66 @bmignano We are talking about moving forward with this and I just wanted to check in to see if the designs posted on May 27 are still the desired approach. If so, we can talk about next steps.

**Comment by mcarrano** [comment]
Per today's PF Weekly mtg I will add this to our design backlog. @bmignano if you have bandwidth to work on this, I'd be glad to have you lead that effort. @LHinson @rachael-phillips let's consider where this can be slotted on the PF roadmap.

**Comment by bmignano** [comment]
@mcarrano Happy to continue working on this!

**Comment by mcarrano** [comment]
That's great @bmignano. I will assign this to you and set up some time for us to discuss next steps.

**Comment by mcarrano** [comment]
@bmignano @mceledonia where do you feel like we stand with this following last week's review? I think we are in good shape excepting maybe a couple of minor loose ends. Is this something we can wrap up this week?

**Comment by gdoyle1** [comment]
Hey @mcarrano @LHinson ! 
OpenShift is planning on adding favorites in table view and our "project selector" (which is a dropdown right now and _I think_ could use the same type of styling as favorited items in application launcher) for our 4.7 release in August! 
Do you think we could get this back on the roadmap for that timeline?

**Comment by mcarrano** [comment]
Can you tell me more about the "project selector" @gdoyle1 ? Is this just a Select list with favorites? Seeing a mockup would be good. Someone else was asking for similar functionality and it would be good to talk about best approach.

As for this issue (table favorites), does the design expressed here in this issue still meet the requirements?

**Comment by gdoyle1** [comment]
@mcarrano Yes this issue still meets the requirements of table favorites (we would want that star in the column header with sort functionality). More info about the project selector below...
1. What the project selector looks like currently. The +/- gives you the ability to add that project as a "favorite". Once that project is added as a favorite, it can be set as your "default" project by selecting the star. You can only have 1 project set as default.
<img width="370" alt="Screen Shot 2020-05-07 at 1 41 46 PM" src="https://user-images.githubusercontent.com/30870144/81326933-8d4f3b80-9068-11ea-941e-b24f9890d674.png">
2. Here's what I was proposing as a possible design update for that and used the application launcher styling and symbols to create it (excluding the label)
<img width="805" alt="OPENSHIFT  Favoriting in project selector 3" src="https://user-images.githubusercontent.com/30870144/81327037-b1ab1800-9068-11ea-845d-c3eeb026ec1e.png">

**Comment by mcarrano** [comment]
@gdoyle1 thanks for the information of the Project Selector. I do prefer your proposal as this is much more similar to how we handled favoriting in the Application Launcher. Can you open a new issue for this in patternfly-design? While these are related (table favorites and select favorites) they should be tracked as two separate issues. I'd be glad to work through the design with you on the later. We may want to consult with @mcoker on the best way to approach the menu enhancements as I know we don't have a direct way to add these actions to dropdowns in general right now.

**Comment by gdoyle1** [comment]
@mcarrano Yes I can do that!

**Comment by mcarrano** [comment]
@beanh66 Is this something that is still needed for OpenShift?

**Comment by gdoyle1** [comment]
@mcarrano yes we'll still need that in OpenShift!

**Comment by mcarrano** [comment]
Keep open
