### ISSUE TITLE
Remove class on the Accordion Toggle Icon

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1888]
Related to: #1887  Remove these lines as there is no need for them anymore.

  --pf-c-accordion__toggle-icon--LineHeight: var(--pf-global--LineHeight--md);

    .pf-c-accordion__toggle-icon {
      line-height: var(--pf-c-accordion__toggle-icon--LineHeight);
    }

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/3016
