### ISSUE TITLE
Update spacer for wizard cancel action

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#1894]
Currently in the wizard there is a 16px spacer for the cancel button
<img width="883" alt="Screen Shot 2019-06-05 at 1 00 56 PM" src="https://user-images.githubusercontent.com/287880/58971566-1e030480-8792-11e9-9421-36488dda6bd0.png">
The white space around this action is misleading as well because it is done with padding so the click area is much larger than it appears visually.

For an action that is so destructive I propose we use a 48px spacer to avoid accidentally hitting this cancel action instead of the back button. 

<img width="597" alt="Screen Shot 2019-06-05 at 1 08 19 PM" src="https://user-images.githubusercontent.com/287880/58972067-142dd100-8793-11e9-8369-2674269cd877.png">

**Comment by rachael-phillips** [comment]
@mceledonia @kybaker @mcarrano  what do you think about this proposed change? Would love to hear your thoughts!

**Comment by mcarrano** [comment]
I'd be OK with it.

**Comment by mceledonia** [comment]
Yeah, makes sense to me!

**Comment by mcarrano** [comment]
@mcoker would this just be a straight forward change? Do you need anything from design?

**Comment by mcoker** [comment]
@mcarrano seems straight forward enough. I wonder if this is a pattern we'll use elsewhere and if we should either just make this change manually in any components where we use a cancel button, offer an action row as a layout that allows for a modifier for the cancel button and spaces it appropriately. I pitched the action row layout to the CSS devs and the team wasn't super excited about it, so we can just start here and explore that option later if it comes up.

**Comment by matthewcarleton** [comment]
@mcoker I'm happy to do this work since I'm to blame for it in the first place :)
It makes sense to include the spacing in the wizard, I think we'd need to investigate where else we have a cancel button and maybe space it appropriately. That might be a good reason to have a per component approach rather than a canned action row. WDYT?

**Comment by mcoker** [comment]
@matthewcarleton sounds great!

**Comment by mcarrano** [comment]
@mcoker This is consistent with our current design guidance, but did we ever make this update to the Wizard examples?

**Comment by mcoker** [comment]
@mcarrano nope, but this is something we could integrate into the action list component, and use that in the wizard. https://github.com/patternfly/patternfly/issues/2021

Should we hold off for that, or go ahead and introduce a spacer for the cancel button in the wizard now?

**Comment by mcarrano** [comment]
I think it makes sense to wait for the Actions component.

**Comment by mcarrano** [comment]
What do you want to do with this one @mcoker ?

**Comment by mcoker** [comment]
@mcarrano if we were to use the action list here, we wouldn't be able to do it until it's out of beta. Is this something you'd like to see soon? And would it be the default or an opt-in - in case we consider it a visual breaking change. It should be quick and easy to do if we just want to add that spacing to the existing actions.

**Comment by mcarrano** [comment]
Let's go ahead and make the change in that case @mcoker . This will make the wizard consistent with our design guidance.

**Comment by mcoker** [comment]
Do we want to consider the layout when actions wrap? Here's what happens now

<img width="348" alt="Screen Shot 2020-10-12 at 12 48 30 PM" src="https://user-images.githubusercontent.com/35148959/95776565-35a5a380-0c8a-11eb-9bcd-fea8e3d592a8.png">


We could do something like this instead:

<img width="381" alt="Screen Shot 2020-10-12 at 12 54 38 PM" src="https://user-images.githubusercontent.com/35148959/95776562-350d0d00-0c8a-11eb-9147-95ef6c24ade2.png">

**Comment by mcarrano** [comment]
Are you asking what we should see on mobile @mcoker ? I assume that the top image is what we see now?

**Comment by mcoker** [comment]
@mcarrano yep or just in general if actions wrap - mobile or when the actions have a lot of text in them and the viewport is narrow, for example.

**Comment by mcarrano** [comment]
Yeah, I guess I wouldn't do anything special here because it's hard to know what the buttons will be in advance. I think it's OK to just wrap them as you are currently.
