### ISSUE TITLE
Definition List component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#1919]
Create a definition list component that allows for either vertical or horizontal arrangement of label-value pairs. See https://github.com/patternfly/patternfly-next/issues/1624 for designs.

**Comment by rachael-phillips** [comment]
OpenShift request for enhancing read state as part of this story which is captured in 2420: https://github.com/patternfly/patternfly-next/issues/2420

**Comment by ajacobs21e** [comment]
@mcarrano any updates on this? I'd like to use this design for a docs product. Thanks!

**Comment by mcarrano** [comment]
Is this anywhere on our roadmap @LHinson @rachael-phillips ?

**Comment by maryshak1996** [comment]
Just updated the mockups to correctly show inline edit (even though inline edit functionality is not in the scope of this -- just for accuracy): https://www.sketch.com/s/e03f4f98-8ae6-4caa-991c-0cf1338456bf

**Comment by mcoker** [comment]
Met with design this morning and decided:

* The component should mimic a form layout
  * horizontal and vertical label/value layouts
  * label should be 14px, value should be 16px
  * We can start with the label column width matching form (150px or use an equivalent relative unit)
    * Maybe explore a `minmax`
    * Should be overridable via some `--Width` var (via CSS or a react prop)
  * Column and row gap should match form (16px & 24px)
* We should create the `dt` with future elements being added in mind. Probably just making it a flex layout with a specific `__text` element for starters, so we can add stuff adjacent to `__text` later, and it's already flex so we can control the layout.
* Anything can go in `dd`
