### ISSUE TITLE
Description list demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#1921]
https://marvelapp.com/prototype/6e72b59

Create a demo to show how a definition list can be built in PatternFly (using the Description list component).

---

From the design looks like we can consider creating 4 things:
* Basic demo - not sure how useful that is? Might serve as a good baseline for other demos.
* Editable demo - this could also go in the inline edit component. We had an example for an editable `<dl>` that's commented out - probably makes sense to re-enable that with the new description list component. Then we could simply show the list term/item as editable with the edit icon as shown in the designs.
* Description list in a drawer - unless this shows something unique, I don't think this is useful. Pretty much anything can go in a drawer.
* Complex content demo - the demos with tables in the list item are probably good to show.

**Comment by mcoker** [comment]
@mcarrano do you want to add this to the roadmap?

**Comment by mcarrano** [comment]
Keep open
