### ISSUE TITLE
Change default breakpoint for left hand navigation

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly#1929]
I've noticed in cloud.redhat.com that the breakpoint for the left nav is low. For example, right before the breakpoint, the left nav takes 37% of screen space, and spacing takes another 8%. Content is squished into 55% of the space (which may sound ok, but look at the screenshot).

This is the default breakpoint from PatternFly.
I'd like to propose that the default breakpoint is earlier. As seen in the screenshot below, if the breakpoint is when the left nav is ~25% of the total width there is a lot more content space on the screen.
I don't have a particular px width in mind, but maybe around 1130px/1100px?

![image (5)](https://user-images.githubusercontent.com/23172038/59525222-cfe1b580-8ea3-11e9-9a99-1623507487fb.png)

**Comment by rachael-phillips** [comment]
Sorry for the delay here @katierik I've been on pto. Thank you for bringing this to our attention! @mcarrano @mceledonia making you aware. For a bit of history, why did we decide to place the breakpoint where it is currently, and would we be open to changing it in the future given this experience? I'm curious how this change would impact us across applications.

**Comment by rachael-phillips** [comment]
@mcarrano @mceledonia ping :)

**Comment by ryelo** [comment]
Yeah, this is weird because the breakpoint that is defined currently doesn't account for a navigation/sidebar.

I'm not sure how many users will be collapsing the navigation, so maybe we could use a temporary solution to just increase that breakpoint to a higher px value for the time being?

**Comment by mcarrano** [comment]
@rachael-phillips I'm not aware of how the current breakpoint was determined, but can see the problem. @kybaker and @mcoker are probably the best people to consult with on this.

**Comment by katierik** [comment]
Hi - Wanted to follow up on this. @kybaker and @mcoker can you give some insight into the choice of breakpoints? This does not seem like an efficient use of space.
![Xnip2019-12-19_10-09-18](https://user-images.githubusercontent.com/23172038/71184368-aab17380-2247-11ea-9ee5-c5af6126d81e.jpg)
(Screenshot is 967x840, navigation takes ~30% of the total real estate)

**Comment by Rohoover** [comment]
On the point of Icon only, it's a popular feature in Satellite where users frequently swap between pages while simultaneously wanting to have as much content space as possible. It would be great if this was built into PF.

**Comment by kybaker** [comment]
@Rohoover We have discussed that option in the past and decided that currently on a global scale it would be untenable to create an icon for each (or even most) navigational items across our applications. 

@katierik The current breakpoints we selected when we started the project were aligned with bootstrap and a few other established design systems. I do however think we should reconsider the navigation breakpoint. One thing that I think may be contributing to the issues you have in your screenshot is the table is not collapsing to a mobile state like the one shown in PF which distorts the content.

<img width="926" alt="Screen Shot 2019-12-19 at 11 00 05 AM" src="https://user-images.githubusercontent.com/2205964/71188341-c1a79400-224e-11ea-98fc-9efaa50f4859.png">

**Comment by kybaker** [comment]
@mcarrano What do you think?

**Comment by Rohoover** [comment]
Any reason to not make that feature (icon only) optional? Leave it to teams to work out the necessity of icon only and then that team to assign icons? 

At this point Satellite will need to make a one off, which makes transition to PF4 harder.

**Comment by mcarrano** [comment]
I agree with @kybaker 's point about icons. I wonder if there's another way to approach this. Perhaps the navigation can be revealed if the user hovers over the left edge of the viewport. Is that something that woud be technically feasible @mcoker ?

**Comment by mcoker** [comment]
> Perhaps the navigation can be revealed if the user hovers over the left edge of the viewport.

As long as there is part of the navigation displayed in the hoverable area, yes. It's technically possible to create an invisible hoverable area that overlays the left side of the page that triggers the navigation to be shown, but any content underneath the hoverable area would likely be inaccessible.

**Comment by katierik** [comment]
Can we spin the icon-only nav into a new issue? (Probably my fault for bringing it up here ;) but I think we have 2 different issues))

**Comment by katierik** [comment]
> @katierik The current breakpoints we selected when we started the project were aligned with bootstrap and a few other established design systems. I do however think we should reconsider the navigation breakpoint. One thing that I think may be contributing to the issues you have in your screenshot is the table is not collapsing to a mobile state like the one shown in PF.
> 
Yes, it is not in the mobile format... but that doesn't solve the issue. We still need the space.

Collapsing down to the mobile table is a **degraded** experience for the user. We have tables for easy comparison & scanning, and also the information density they provide. The mobile style table has much less information density, is much more difficult to compare down a single value (e.g. comparing the # of systems for each item). 
The mobile version of the table is a necessary bandaid when on very small screens, but for a window almost 1000px wide its not a fix.

**Comment by LHinson** [comment]
+1 for a new issues. Let's chat more in the new year to understand both the PF and product perspective and bit more between folks. Once we chat there, we can determine how to move forward and what that issue is. Thanks everyone!

**Comment by katierik** [comment]
I created a new issue for the icon-only nav: https://github.com/patternfly/patternfly-next/issues/2569

**Comment by mcoker** [comment]
This was updated, the new breakpoint is 1200px.
