### ISSUE TITLE
Rename vars in Accordion

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1938]
Related to #1932

During the breaking change period, rename these vars in the Accordion component to better align with our naming standards:

- Change `--pf-c-accordion__toggle-text--expanded--Color` to `--pf-c-accordion__toggle-text--m-expanded--Color`
- Change `--pf-c-accordion__toggle-text--expanded--FontWeight` to `--pf-c-accordion__toggle-text--m-expanded--FontWeight`

**Comment by mcoker** [comment]
we should change the var to be inline with the selector, so it's `--pf-c-accordion__toggle--m-expanded__toggle-text--[Color/FontWeight]`
