### ISSUE TITLE
Overpass text vertical alignment is not correct

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#195]
When filing #194, I noticed the text alignment for Overpass is not correct. The text's baseline should be properly aligned within the buttons, but it is not.

When using Open Sans or nearly any other font, the text is correct. When using Overpass, it's shifted up a few pixels and feels unpolished.

Overpass:
![overpass-buttons](https://user-images.githubusercontent.com/10246/39588737-a9bdd1f0-4efc-11e8-8246-2cb5cb425da4.png)

Not Overpass (Source Sans):
![screenshot-2018-5-3 pf next](https://user-images.githubusercontent.com/10246/39588751-b14b6068-4efc-11e8-8c4b-4dd8e02c1ff6.png)

(GitHub seems to be scaling images up for some odd reason. Sorry.)

---

Both of these issues stem from the fact that Overpass is nice for headlines, but it's bad for body text and UI text.

**Comment by matthewcarleton** [comment]
Hey @garrett ya this is a known issue that I think will also be resolved with the switch to the new font.

**Comment by garrett** [comment]
FWIW, this is _still_ a problem. Literally _everything_ is misaligned at https://pf4.patternfly.org/ — and in all browsers I've checked: Firefox, Chrome, WebKit. And this is confirmed with the font that the site is using, not a local font.

Other fonts don't have this problem. Overpass still has a bogus baseline, as it was never intended as a UI font, but as a headline.

**Comment by garrett** [comment]
Here are a bunch of screenshots taken on Firefox on Linux... however, it's the same issue in all browsers (it's just easier to screenshot page sections on Firefox):

![Screenshot_2019-04-09 PatternFly 4(7)](https://user-images.githubusercontent.com/10246/55785663-22bd7c00-5ab3-11e9-839e-a012c9305698.png)

![Screenshot_2019-04-09 PatternFly 4(6)](https://user-images.githubusercontent.com/10246/55785665-22bd7c00-5ab3-11e9-9149-1b4a5620cc77.png)

![Screenshot_2019-04-09 PatternFly 4(5)](https://user-images.githubusercontent.com/10246/55785666-23561280-5ab3-11e9-9d18-2fab8a3f35e9.png)

![Screenshot_2019-04-09 PatternFly 4(4)](https://user-images.githubusercontent.com/10246/55785668-23561280-5ab3-11e9-8758-619032bc78e9.png)

![Screenshot_2019-04-09 PatternFly 4(3)](https://user-images.githubusercontent.com/10246/55785670-23561280-5ab3-11e9-9715-c588587e78e6.png)

![Screenshot_2019-04-09 PatternFly 4(2)](https://user-images.githubusercontent.com/10246/55785671-23eea900-5ab3-11e9-81ab-e86a873cf922.png)

![Screenshot_2019-04-09 PatternFly 4(1)](https://user-images.githubusercontent.com/10246/55785673-23eea900-5ab3-11e9-953a-07d9954ab5b6.png)

![Screenshot_2019-04-09 PatternFly 4](https://user-images.githubusercontent.com/10246/55785674-23eea900-5ab3-11e9-8c87-9013c05e4b24.png)

Again, using another font (either a well tested sans serif or a native system-provided sans serif font) for the non-headline text would solve this issue.

**Comment by garrett** [comment]
## DejaVu Sans

For a point of comparison, here's what a few widgets look like in DejaVu Sans.

![Screenshot_2019-04-09 PatternFly 4(17)](https://user-images.githubusercontent.com/10246/55787175-04a54b00-5ab6-11e9-874b-c0de36ac7623.png)

![Screenshot_2019-04-09 PatternFly 4(8)](https://user-images.githubusercontent.com/10246/55786822-48e41b80-5ab5-11e9-8eb1-e863e6688a66.png)

**Comment by garrett** [comment]
The same problem occurs on Edge on Windows 10:

![pf4-buttons](https://user-images.githubusercontent.com/10246/55871659-697ea500-5b8b-11e9-9fdb-33ba0d1cddd0.png)

![pf4-alerts](https://user-images.githubusercontent.com/10246/55871641-608dd380-5b8b-11e9-94b4-e68fd3172685.png)

![tabs](https://user-images.githubusercontent.com/10246/55871666-6b486880-5b8b-11e9-96d4-9ba38b5ab0fb.png)

It also happens on Chrome on Windows 10 too... but it looks just like the other screenshots.

**Comment by LHinson** [comment]
This is related to #1524 
There are plans to update the font and move away from overpass.  That timeline is still being discussed. CC @kybaker

**Comment by rachael-phillips** [comment]
@mcoker and @matthewcarleton are aware, as well.

**Comment by garrett** [comment]
This has been fixed by switching to the Red Hat fonts. Thanks!
