### ISSUE TITLE
change var in options menu

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1971]
In #1973 we added a disabled variation that changes the background color of the toggle. For consistency lets change this var to be BackgroundColor instead of Background.

At the breaking change period change this to use BackgroundColor instead of Background: `--pf-c-options-menu__toggle--Background: transparent;`

**Comment by rachael-phillips** [comment]
Hi @christiemolloy what is the importance or urgency of making this change? Is this something we would want to bring in in our August breaking change release? cc @mcoker
