### ISSUE TITLE
Update content component to accept inline notification

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#1976]
Currently when an inline notification gets dropped into the content component it's `h4` inherits margin from the content component.
The content component styles should be more strict to not impact component styles.

**Comment by gregsheremeta** [comment]
cc @gregsheremeta

**Comment by mcoker** [comment]
@matthewcarleton do you still want to leave this open? The content component isn't currently designed to accept components, but rather blocks of HTML that is formatted as page content. In this use case, I would likely have a structure like:

```
.pf-c-content
.pf-c-alert
  .pf-c-alert__description
    .pf-c-content could go here, too
.pf-c-content
```

**Comment by matthewcarleton** [comment]
@mcoker we can close it if you think it's more reasonable to go that route. I've learned to use the content component the way you've outlined it and so others probably have too :)
