### ISSUE TITLE
Support Fixed Height and Pagination in Page

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1992]
Currently in the card view demo, at mobile the pagination switches to "20 items" and the cards inside the page main section scroll infinitely.

@sbuenafe-rh asked me about a paginated version of the page. @gdoyle1 had designs where there would be pagination at the top and bottom of the screen, and the main-section would have a fixed height.

@rachael-phillips do you know if theres any plan for this on the roadmap?

**Comment by rachael-phillips** [comment]
Hi @christiemolloy would this just be an example we include in the card view demo?

**Comment by christiemolloy** [comment]
We would probably have to add a modifier to the page section so that it scrolls, and then update the toolbar and pagination component too.

@gdoyle1 do you want to add your design here?

**Comment by gdoyle1** [comment]
@christiemolloy @rachael-phillips This is what I was thinking (first two wireframes) that would allow for sticky bottom pagination and scrolling in content view. https://marvelapp.com/928ei6b

**Comment by mcoker** [comment]
@christiemolloy is this still something you'd like to see support for? Was this resolved with sticky bottom pagination?
