### ISSUE TITLE
Increase width of Pagination input

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly#1996]
We had a request for allowing at least 4-digit inputs in Pagination in https://github.com/patternfly/patternfly-react/issues/2344. Right now it only accommodates two digits.

**Comment by rebeccaalpert** [comment]
This is still open on the React side.

**Comment by mcoker** [comment]
Hey @rebeccaalpert, we made an update in core to support a react issue that was opened around the width of the nav input - https://github.com/patternfly/patternfly-react/issues/3530

Here is the react PR adding support for that - https://github.com/patternfly/patternfly-react/pull/3534

Also you can always manually set the width of the input by declaring this CSS var either globally via the `.pf-c-pagination` selector, or scoped to a particular pagination on your app with a selector specific to that instance of the component.

```
.pf-c-pagination { // or use a different selector to target a specific pagination instance
    --pf-c-pagination__nav-page-select--c-form-control--width-chars: 5; // where 5 is your custom value
}
```

Let me know if that works out or if you need more help in getting it to work as you'd expect it to.
