### ISSUE TITLE
modal action spacing

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#1999]
This is related to #1894 

Currently the spacing for actions in the modal are pretty tight
<img width="606" alt="Screen Shot 2019-06-27 at 9 37 43 AM" src="https://user-images.githubusercontent.com/287880/60266847-4bd5f780-98bf-11e9-8752-60a8776ab947.png">
You can see the margin(orange) is pretty narrow so this could result in an accidental click. This poses some accessibility concerns IMO.

It could look like this with a 24px spacer:
<img width="692" alt="Screen Shot 2019-06-27 at 9 56 50 AM" src="https://user-images.githubusercontent.com/287880/60268073-f18a6600-98c1-11e9-9e05-16fef3a1a551.png">

One thing I have noticed with the modal currently is that the actions don't wrap. So if there more than two actions on a small viewport (or just actions that had longer strings of text) it would break outside the container.

This can be fixed with adding `flex-wrap: wrap;` to `.pf-c-modal-box__footer` but that opens up a larger conversation about spacing between rows of buttons and between the buttons themselves.

@mcoker I'd like to talk to you more about this to get your thoughts and see what the best approach is.

**Comment by mcoker** [comment]
bump let's take this into consideration with https://github.com/patternfly/patternfly/issues/2021
