### ISSUE TITLE
Add shadow global variables to CSS

### ISSUE THREAD

**Issue by jennyhaines** [patternfly/patternfly#20]
Hi there! We need the following shadow styles added to the CSS (I just learned about shadow layering, so the CSS is edited from the original version):

**For Tiles & Modals:**
Shadow 1:
box-shadow: 0px 1px 2px 0px rgba (3,3,3,0.2)

Shadow 2:
box-shadow: 0px 2px 1px 1px rgba (3,3,3,0.12), 0px 4px 11px 6px rgba(3,3,3,0.05)

Shadow 3:
box-shadow: 0px 3px 7px 3px rgba (3,3,3,0.13), 0px 11px 24px 16px rgba(3,3,3,0.12)

**For Other UI Elements (including toggles and submenus):**
shadow-sm-right:
box-shadow: 4px 0px 10px -4px rgba (3,3,3,0.12)

shadow-sm-left:
box-shadow: -4px 0px 10px -4px rgba (3,3,3,0.12)

shadow-sm-bottom:
box-shadow: 0px 4px 10px -4px rgba (3,3,3,0.12)

shadow-sm-top:
box-shadow: 0px -4px 10px -4px rgba (3,3,3,0.12)

shadow-md-right:
box-shadow: 5px 0px 10px -4px rgba (3,3,3,0.25)

shadow-md-left:
box-shadow: -5px 0px 10px -4px rgba (3,3,3,0.25)

shadow-md-bottom:
box-shadow: 0px 5px 10px -4px rgba (3,3,3,0.25)

shadow-md-top:
box-shadow: 0px -5px 10px -4px rgba (3,3,3,0.25)

shadow-lg-right:
box-shadow: 12px 0px 10px -4px rgba (3,3,3,0.07)

shadow-lg-left:
box-shadow: -12px 0px 10px -4px rgba (3,3,3,0.07)

shadow-lg-bottom:
box-shadow: 0px 12px 10px -4px rgba (3,3,3,0.07)

shadow-lg-top:
box-shadow: 0px -12px 10px -4px rgba (3,3,3,0.07)

![shadows_artboard 4 copy](https://user-images.githubusercontent.com/24898297/37485445-da908550-2861-11e8-8396-f70b17a4599e.png)

This will fulfill Jira story [PTNFLY-2824](https://patternfly.atlassian.net/browse/PTNFLY-2824)

**Comment by jennyhaines** [comment]
FYI: @jgiardino

**Comment by andresgalante** [comment]
Hi @jennyhaines two questions:

- Are this "unicorn colors"? lol (I mean unique outside the color pallet).
- Do we have inset shadows or left/right shadows? like the one the left or icon on the notification drawer

**Comment by jennyhaines** [comment]
Hi @andresgalante @jgiardino - I'll provide those left/right shadows in the comments here later today! These shadows weren't intended to be unicorn colors... I had the color be set to PF-Black (#030303). I used an online box shadow code generator to create the CSS.

**Comment by andresgalante** [comment]
@jennyhaines just two more question:

I assume those px values are unrelated to our spacers, right?

Do we want the shadows to grow if the typography is bumped up or to always stay the same?

Thanks!

**Comment by andresgalante** [comment]
@jennyhaines sorry! here is one more, I noticed there is a "press" button effect, that'll requiere an inset shadow too, right?

**Comment by jennyhaines** [comment]
@andresgalante - I updated the shadow styles to also include the small, medium, and large sizes of one-sided shadows in their different orientations (left, right, bottom, and top). This gives us 12 different shadows to use with UI elements. For example, the submenu below would use "shadow-lg-right", and the toggles and button groups would use "shadow-md-left" or "shadow-md-right":

<img width="708" alt="submenu" src="https://user-images.githubusercontent.com/24898297/37485730-ab5d866a-2862-11e8-887b-742c398ec21b.png">

<img width="681" alt="toggles" src="https://user-images.githubusercontent.com/24898297/37485736-af9d2906-2862-11e8-93ca-8ddec942aebf.png">
<img width="551" alt="toggles2" src="https://user-images.githubusercontent.com/24898297/37485830-f11daa86-2862-11e8-8224-e245441175ec.png">

**Comment by jennyhaines** [comment]
@andresgalante - as for the inset shadow, if you were to select the middle button from the button group, the shadow should be _box-shadow: inset 0px 0px 10px 0px rgba(3,3,3,0.25)_

<img width="862" alt="toggle3" src="https://user-images.githubusercontent.com/24898297/37486707-afab2a76-2865-11e8-9dda-4bd91bf048a1.png">

**Comment by LHinson** [comment]
closed by #70
