### ISSUE TITLE
Ellipses in Pagination input on overflow

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly#2000]
Hey - PatternFly React received a bug report (https://github.com/patternfly/patternfly-react/issues/2374) about ellipses in the Pagination input. I was able to recreate it on my Mac by typing in 22 and removing focus from the input. It looked related to a text-overflow: ellipsis style. Can you guys work on a fix?

> A bug report to our app says "Page number is lost and replaced w/ "..." if I click to the last page. See attached images.".
> It was created on Mac, I was not able to reproduce it on Fedora Firefox nor Chrome.
> ![image](https://user-images.githubusercontent.com/6286045/60249670-8cd10a80-98c5-11e9-97c8-f7edafea38c8.png)

**Comment by rebeccaalpert** [comment]
This is still open on the React side.

**Comment by mcoker** [comment]
cc @mcarrano @mceledonia 

We apply ellipsis to overflow text in the form-control component inputs. In this case, the react component seems to do a good job of setting the appropriate width for the input depending on the number that can go into the input (meaning there shouldn't be overflow), but in the case that there is overflow, would you prefer the ellipsis or for it just to cut off whatever the value is?

#### ellipsis
<img width="408" alt="Screen Shot 2020-08-06 at 10 27 33 AM" src="https://user-images.githubusercontent.com/35148959/89550831-c44ffd00-d7cf-11ea-9b3f-e3c0dd602eed.png">

#### no ellipsis
<img width="411" alt="Screen Shot 2020-08-06 at 10 27 45 AM" src="https://user-images.githubusercontent.com/35148959/89550844-c7e38400-d7cf-11ea-8582-84bbbcb9d71a.png">

**Comment by mceledonia** [comment]
I would still prefer the ellipsis for overflow but in the top example it seems to get cut off far too early. Can we have it truncate to where the ellipses are closer to the right edge, thus allowing for more characters? Looks like there should be plenty of room there for: [23...]

**Comment by mcoker** [comment]
@mceledonia since this is a `type="number"` input, the right space is reserved for the element controls. This is how it appears on hover and focus:

<img width="152" alt="Screen Shot 2020-08-06 at 12 09 05 PM" src="https://user-images.githubusercontent.com/35148959/89561198-c456f980-d7dd-11ea-93bd-6783081f1753.png">

**Comment by mcarrano** [comment]
I remember earlier conversations about this and I thought that the field was sized to take at least two digits or up to 99 pages. Is that not the case? Over that, I agree the ... is a good solution.

**Comment by mcoker** [comment]
> I remember earlier conversations about this and I thought that the field was sized to take at least two digits or up to 99 pages. Is that not the case?

It is, you can see the default behavior in the [core pagination examples](https://www.patternfly.org/v4/documentation/core/components/pagination). And you can see how the react component will automatically adjust the input width based on the maximum number of characters allowed in the input in the [react pagination examples](https://www.patternfly.org/v4/documentation/react/components/pagination).
