### ISSUE TITLE
Transparent border around dropdown, select, etc menus allows content underneath to show

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2019]
From https://github.com/patternfly/patternfly-react/issues/2095

You end up with text showing through to the left of the menu

<img width="248" alt="Screen Shot 2019-07-03 at 1 27 45 PM" src="https://user-images.githubusercontent.com/35148959/60616123-6532e400-9d96-11e9-9863-3537f7ecee48.png">

**Comment by sg00dwin** [comment]
Additional examples from OpenShift console
<img width="364" alt="Screen Shot 2019-07-03 at 3 48 04 PM" src="https://user-images.githubusercontent.com/1874151/60620739-fd869400-9da9-11e9-8e55-ba7cb1d45018.png">
<img width="239" alt="Screen Shot 2019-07-03 at 3 29 51 PM" src="https://user-images.githubusercontent.com/1874151/60620747-05decf00-9daa-11e9-8f46-cd874d6c7b23.png">
