### ISSUE TITLE
Create action list component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2021]
**Updated design:** https://docs.google.com/presentation/d/1Kh8wGM27X5shhSyVpZbgjV3uidpOmlz-CLYWHhxEMEI/edit?usp=sharing

---

Let's create a layout that spaces and positions actions properly for use in the wizard, modal, and form, and anywhere you need a list of actions that would be spaced similarly.

cc @matthewcarleton @mcarrano 

Can we talk about the specifics needed for this layout? Maybe some examples of types of buttons that would go in this layout? And how they should behave responsively and maintain the proper spacing?

Could this also be used in places like the data list?

<img width="1212" alt="Screen Shot 2019-07-03 at 4 06 38 PM" src="https://user-images.githubusercontent.com/35148959/60625163-9cac8b00-9dac-11e9-862c-050f9ae4dedd.png">

**Comment by matthewcarleton** [comment]
Thanks for creating this @mcoker 
This would be a good fit for the wizard action spacing issue #1894  and the modal issue #1999 
I'd assume any type of button can be used in this layout.
vertical spacing should be easy enough for wrapping actions. 
The more complicated issue is the spacer modifier for link type actions. 
Once wrapped we'll see the possibility of this:
<img width="357" alt="Screen Shot 2019-07-04 at 1 02 47 PM" src="https://user-images.githubusercontent.com/287880/60678874-3b43f500-9e5c-11e9-806c-6024f589ecea.png">

This layout will also have to handle left aligned and right aligned actions.

**Comment by mcarrano** [comment]
Sounds good. I will add this to the design backlog. @LHinson @rachael-phillips FYI

**Comment by mattnolting** [comment]
> Could this also be used in places like the data list?

I think we'd use the overflow menu in data list.

**Comment by christiemolloy** [comment]
@mcarrano do you know if there are design stories done yet for this?

**Comment by mcarrano** [comment]
No, not specifically @christiemolloy .  @mcoker do you think that the Overflow Menu component handles this? Do we need a new layout? If so, is input from design needed for this?

**Comment by mattnolting** [comment]
@mcarrano I think this is a valid layout, but in components like `table` and `data-list`, where the layout switches to grid and buttons are added to a dropdown, (where we're already emulating overflow behavior) `.pf-c-overflow-menu` would handle that.

**Comment by mcoker** [comment]
@mcarrano I do think it would be good to have a simpler action list layout for spacing and aligning actions, and this could handle the spacing differences between regular actions and a cancel action, too.

**Comment by mcarrano** [comment]
Based on conversation with @mcoker today, we decided that this should be a new component that allowed for grouping a set of actions. As in the Overflow menu, these actions might be text buttons, icon buttons, or some combination. The consumer could specify spacing between elements (e.g. I want to move Cancel away from other buttons). The Action list will also stack actions when the viewport becomes too small to fit horizontally. We should consider whether this should be combined with the Overflow menu or if they should be kept separate as they have similar (but not the same) usage.

@LHinson @rachael-phillips we should consider priority. Not aware of any immediate product need. @mcoker anything to add?

**Comment by mcoker** [comment]
@mcarrano that summarizes it, thanks!

**Comment by mmenestr** [comment]
I've create the following doc outlining all the different action list proposals which I just went over with @mcoker. @mcarrano let me know if you have any questions!

https://docs.google.com/presentation/d/1Kh8wGM27X5shhSyVpZbgjV3uidpOmlz-CLYWHhxEMEI/edit?usp=sharing

**Comment by mcarrano** [comment]
This looks great @mmenestr . If @mcoker is good with this then I think we are done. Would you like me to close and create a clean issue or just re-tag this for CSS @mcoker ?

**Comment by mcoker** [comment]
@mcarrano looks good to me. Updated the original description and issue labels.

**Comment by mcarrano** [comment]
Sounds good. Thanks for your work on this @mmenestr !

**Comment by mcarrano** [comment]
Will add this to the roadmap.
