### ISSUE TITLE
PatternFly or Font Awesome icons?

### ISSUE THREAD

**Issue by rhwood** [patternfly/patternfly#2022]
The design guidelines for [Alerts and Notifications](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/alerts-and-notifications) uses Font Awesome icons, but PatternFly has [defined analogous icons](https://www.patternfly.org/v4/design-guidelines/styles/icons).

Which should be used?

The icons in question are:
`pf-icon-info` <-> `fa-info-circle`
`pf-icon-warning-triangle` <-> `fa-exclamation-triangle`
`pf-icon-error-circle-o` <-> `fa-exclamation-circle`
`pf-icon-ok` <-> `fa-check-circle`

**Comment by mcarrano** [comment]
@kybaker @mceledonia Can one of you take a look at this and let me know which are the correct icons to use in alerts? If the documentation is wrong, I will open an issue to fix that.

**Comment by kybaker** [comment]
@mcarrano The icons show in the alerts are the correct ones. The icons is the PF library are legacy from PF3.  https://pf4.patternfly.org/components/Alert/examples/

**Comment by rhwood** [comment]
Where is it documented in PF4 that icons in the PF library are legacy from PF3? I'm not seeing that at https://www.patternfly.org/v4/design-guidelines/styles/icons or https://pf4.patternfly.org/icons?

(I'm utilizing PatternFly, and would like to use the right icons, and had assumed, barring any statements to the contrary, that the PF4 provided icons they are the right ones.)

**Comment by mcarrano** [comment]
@rhwood I agree that this is a problem and we will address it. For now, you can be assured that the 'fa' icons called out in the design documentation and the Alert component examples are the correct ones. @LHinson @rachael-phillips FYI

**Comment by rachael-phillips** [comment]
@mcarrano is this something we can address on the website copy or do we need to take additional steps?

**Comment by mcoker** [comment]
@mcarrano do you still think this is something we should try and address? I looked on https://www.patternfly.org/v4/design-guidelines/styles/icons and didn't see anything regarding which icons to use when.

**Comment by mcarrano** [comment]
I think we can close this @mcoker . The Icons page should now be showing the correct icons.
