### ISSUE TITLE
Buttons in the Data List component

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#2029]
I was reviewing the data list component....
@mcarrano is it true that the recent addition of the `pf-hidden-visible-{breakpoints}` means that buttons should collapse to a kebab before they stack. That's how it looks, at 992px (lg breakpoint) width that looks like this, but it seems unintentional i think because of the min-max issue we've seen before:

<img width="723" alt="Screen Shot 2019-07-09 at 2 19 25 PM" src="https://user-images.githubusercontent.com/20118816/60913487-83e12100-a255-11e9-9adf-f50a25b71604.png">

If so, I think we can remove the following classes from the data list component when the breaking change period happens, or maybe just when we make a layout for buttons: cc: @mcoker 

```
  --pf-c-data-list__item-action--not-last-child--MarginRight: var(--pf-global--spacer--md);
  --pf-c-data-list__item-action--not-last-child--MarginBottom: var(--pf-global--spacer--md);
  --pf-c-data-list__item-action--not-last-child--lg--MarginBottom: 0;
```

**Comment by christiemolloy** [comment]
closing this issue in favor of: #2021

**Comment by mcoker** [comment]
@christiemolloy did you mean to close this?

**Comment by christiemolloy** [comment]
Nope @mcoker
