### ISSUE TITLE
The Wizard is another implementation of Modal

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly#2046]
The following issue was submitted to the react repo [#2114](https://github.com/patternfly/patternfly-react/issues/2114)  It needs to be investigated by core first. 

> PatternFly should reuse its own components and it should use the Modal component.
> 
> The wizard's render function starts with
> 
> isOpen && ReactDOM.createPortal(
>         <FocusTrap focusTrapOptions={{ clickOutsideDeactivates: true }}>
>           <Backdrop>
>             <Bullseye>
> Instead of that it should be wrapped only the Modal component. (And Modal component needs to be updated to be able to use here.) Or a consumer should be able to put modal there in his own implementation, if he wants to do. There is no reason to control this in the Wizard component, when you have another component, which does it. ( => Less code to test => less code to maintain => less code to break => more satisfied consumers and happy faces)
> 
> <Modal isOpen>
>   ...
> </Modal>
> or in user's implementation
> 
> <Modal isOpen>
>    <Wizzard {...props} />
> </Modal>
>

**Comment by matthewcarleton** [comment]
+1 we also have the need for the wizard to be in-page in OpenShift so it would great if the parts of the wizard could live outside of the modal that wraps it. Being in-page may also require some additional design updates as well, not sure if that would be part of this effort or not. 
FYI @rachael-phillips @LHinson

**Comment by mcoker** [comment]
I tried this locally and looks like we will need the following changes

#### Wizard
* remove in-page variation, make default
* remove full-height/full-width variations

#### Modal
* add full-height/full-width variations to modal, or some way to support the wizard's default size
* add option to remove modal padding
* add option to remove modal close button
