### ISSUE TITLE
Documentation Select/Table

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#2055]
The select and table components are both examples of components that have multiple .md files that are linked to the examples. 

The select component repeats most of the"attributes" and "applied to" classes at each example, however the table doesnt (each new step just adds the classes that haven't been seen before).

We should be consistent, what do people think? cc: @mcoker @mattnolting @matthewcarleton @jgiardino @srambach

**Comment by mattnolting** [comment]
@christiemolloy I think the first example should be the most basic example, while each example subsequent example would highlight new attributes/classes/configs. Then a "master" table of attributes/classes could be included at bottom of page (table currently lacs). 

For example, the first example of `pf-c-select` documentation would include base `pf-c-select` selector and the `pf-c-select`'s core components. The next example would highlight modifiers and/or extended configurations, etc...

**Comment by mattnolting** [comment]
Also, I think this approach is only necessary for more complex components that have many variations/configs.

**Comment by matthewcarleton** [comment]
+1 on what @mattnolting is saying. I think it's helpful to see each variation and it's corresponding attributes/classes/configs. It could also be helpful to state in each that the basic example attributes/classes/configs are required as well with a link down to the "master" table. I also agree this approach is only needed for larger more complex components.

**Comment by christiemolloy** [comment]
I think the idea of having a master list of attributes/classes will resolve a lot of the issues with people struggling to find certain classes etc. sounds good to me -- so looks like we need to update the select docs

**Comment by jgiardino** [comment]
Ultimately this information is consumed in the patternfly website, e.g. here:
https://www.patternfly.org/v4/documentation/core/components/select/
and not in the workspace, e.g. here:
https://pf4.patternfly.org/components/Select/examples/

Currently the website only pulls in one .md file for documentation. The separate ones that are included in Table and Select aren't surfaced in the website. Before we make changes to how this information is organized across different files, we should decide how we want this information pulled in to the website (and also what limitations exist, if any).

There were some discussions in the past about accommodating separate .md files for separate examples, but I don't remember if they were out of scope at that time or if there were underlying technical limitations that prevented us from updating the page design to accommodate this structure. Cc'ing @rachael-phillips and @jschuler who were working on the website at that time.
