### ISSUE TITLE
Card header height issue/question

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#2076]
I'm not sure if it's intentional but when adding an item to the card head the height shifts b/c of the padding. This is an odd visual on a page with multiple cards using the card head in different ways.
Without `.pf-c-card__head > .pf-c-card__actions > .pf-c-dropdown`
<img width="893" alt="Screen Shot 2019-07-18 at 10 13 16 AM" src="https://user-images.githubusercontent.com/287880/61460274-c6d18180-a944-11e9-9e99-56688b057fc4.png">
With `.pf-c-card__head > .pf-c-card__header + .pf-c-card__actions > .pf-c-dropdown`
<img width="901" alt="Screen Shot 2019-07-18 at 10 12 47 AM" src="https://user-images.githubusercontent.com/287880/61460344-ed8fb800-a944-11e9-956e-dc3295a588c4.png">
Also it seems a bit odd that if the order of the `.pf-c-card__head` children doesn't place `pf-c-card__actions` first the spacing is off.
<img width="892" alt="Screen Shot 2019-07-18 at 10 13 52 AM" src="https://user-images.githubusercontent.com/287880/61460400-0ef0a400-a945-11e9-9f02-7db830f5ce64.png">
Maybe I'm missing something please correct me if I'm wrong here: @mcoker @christiemolloy

**Comment by christiemolloy** [comment]
I would expect that if one card has a larger component in its header, then the height of the header increases. Are you suggesting to make a fixed height for the card header. so that no matter what you put in the header they're all equal?

In that third example thats a really good point I will investigate further to see if we can find a fix

**Comment by mcoker** [comment]
> I would expect that if one card has a larger component in its header, then the height of the header increases.

Agreed. If it's a common enough use case that a dropdown/button will be in some headers but not all, we could add a `min-height` to the card header that matches the height of the dropdown/button components.

**Comment by matthewcarleton** [comment]
@christiemolloy @mcoker ya generally I would agree that the content should set the height but a min-height could be a nice addition to allow for a bit more consistency. We could probably cover a lot of use cases with a min-height addition.

**Comment by rachael-phillips** [comment]
@matthewcarleton what priority do you think this for us to get done and how urgent?

@kybaker @mceledonia is this something you think we want to account for?

**Comment by matthewcarleton** [comment]
@rachael-phillips this came from discussions from the OpenShift side so I'd say it would be nice to have sooner rather than later. It's not a huge effort so we should be able to tackle it.

**Comment by kybaker** [comment]
@rachael-phillips I think this adds needed flexibility to the cards.

**Comment by mcoker** [comment]
Do we want to make a specific accommodation for the buttons/dropdown height, or do we want to support matching card header heights regardless of what a user puts in it (a large image in 1, for example).

What it looks like now:
<img width="1168" alt="Screen Shot 2019-08-02 at 1 07 56 PM" src="https://user-images.githubusercontent.com/35148959/62390002-e5c83a00-b526-11e9-81f0-285e4739d919.png">

What it would look like:
<img width="1174" alt="Screen Shot 2019-08-02 at 1 11 22 PM" src="https://user-images.githubusercontent.com/35148959/62390077-0abcad00-b527-11e9-8894-a2608527a283.png">

**Comment by matthewcarleton** [comment]
@mcoker I'm leaning towards the second option to be more flexible. Hopefully we won't see scenarios like this where one is much larger than any other. I'd hope that a designer/dev would see this as an opportunity to provide a smaller large image to make it more consistent.

**Comment by mcoker** [comment]
@matthewcarleton agree, that seems to make more sense than just supporting a button. And since the `min-height` isn't fixed for buttons, it means that the height can remain the size it needs to support whatever content is inside of it.

That said, I don't think we can do this in core unless we offered a fixed set of modifiers for different heights? It is something we could potentially do in react, similar to the `matchHeight` prop you would pass to the `CardView` component in the pf3 react. There is a demo in the ["base card w/ height matching example"](https://patternfly-react.surge.sh/patternfly-3/index.html?knob-Match%20Height=true&selectedKind=patternfly-react%2FCards&selectedStory=Base%20Card%20w%2FHeightMatching&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs).

**Comment by mcoker** [comment]
@tlabaj would you mind checking this out and seeing if this is something we can do in react?

**Comment by mcoker** [comment]
@matthewcarleton is this still something you'd like to see addressed?

**Comment by matthewcarleton** [comment]
> @matthewcarleton is this still something you'd like to see addressed?

I think it's a nice addition. What do you think? It seems like others agree too.

**Comment by mcoker** [comment]
@matthewcarleton Agree, I just wonder what kind of problem we're trying to solve. I retract my idea bout the `min-height` :) I think the idea is that card elements/sections should be able to align when used in a grid. I think this is something we could solve with subgrid, though there could be a JS solution, too, if it were an immediate concern. We also have an open issue to create compact menu toggles here, which could be a solution as well - https://github.com/patternfly/patternfly/issues/2344

I haven't heard of this being requested by anyone else, so I'm in favor of a subgrid solution when that feature lands. WDYT?

**Comment by matthewcarleton** [comment]
ya the dropdown is what brought this up to start so if we are solving that issue with an update there I think that covers the initial scope of this request. I do love subgrid and it will be a pretty fancy solution. Happy to close.
