### ISSUE TITLE
Select doesn't have a separator

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#2078]
Theres code in the select component that I believe isn't being used, I don't see the select having a separator element. cc: @srambach  @mcoker 

```

.pf-c-select__separator {
  height: var(--pf-c-select__separator--Height);
  margin-top: var(--pf-c-select__separator--MarginTop);
  margin-bottom: var(--pf-c-select__separator--MarginBottom);
  background-color: var(--pf-c-select__separator--BackgroundColor);
}
```

Theres also a .hbs file in the component called `select-multi.hbs` but the classes inside say dropdown? I think we can also remove it.

**Comment by srambach** [comment]
Is it just not in an example, or is it not a valid thing to do? There is a select in my product that has separators.
![image](https://user-images.githubusercontent.com/19825616/61561441-ffed1d00-aa3c-11e9-9ef5-33a24de60bcc.png)

**Comment by christiemolloy** [comment]
@mcarrano could you clarify here? If you believe the separator can be in the select component then I'm happy to add an example in. FWI I'm working on an issue to create a divider component #2080 so it can be part of the issue.

**Comment by LHinson** [comment]
@christiemolloy FYI there is an issue open to investigate [react-select component](https://github.com/patternfly/patternfly-react/issues/2531) for PatternFly. For that reason, I'd like to hold off investing in our custom component until we've determined the best path fwd. 

This investigation is being prioritized by @rachael-phillips for this upcoming sprint that starts on tuesday.

**Comment by mcarrano** [comment]
@christiemolloy if we do go forward with this, I think having a separator is unusual but can be useful in certain use cases as @srambach shows. In this case the separator helps because it comes with a section heading. Does our current separator allow for that?

**Comment by christiemolloy** [comment]
Spoke with @mcarrano @rachael-phillips and @LHinson about putting this issue on hold for now until we define a common approach for menus

**Comment by ValerieKenyon** [comment]
I'd be interested in working on this, if/when the time comes.  But I'm not seeing the `select-multi.hbs` file in the current code base (April 2020).

**Comment by mcoker** [comment]
Hey Valerie, my apologies for not getting back to you on https://github.com/patternfly/patternfly/issues/2336#issuecomment-611159898, we've been busy this week wrapping up a release milestone, but should wrap up early next week. I believe this issue is going to be resolved via https://github.com/patternfly/patternfly/pull/2944#discussion_r409186298. It looks like there is a separator in the select! We're removing it in favor of using our divider component instead, but that work is still in progress. I can check back in early next week and coordinate with you on a new issue if that's OK.

**Comment by ValerieKenyon** [comment]
That's great at my end, I've got some other projects I'm working on.

**Comment by mcoker** [comment]
Divider is supported now.
