### ISSUE TITLE
Edit Typography Global variables in CSS

### ISSUE THREAD

**Issue by jennyhaines** [patternfly/patternfly#21]
Hi there! We need the typography styles edited in the CSS. I've attached a couple images with the new header styles! I want line heights mapped to each of header styles, and you'll notice that some are Regular (500) weight, and others are Semibold (600) weight. Also, I know that we are using Menlo font in all instances of text editors and the Google Code Prettify pattern. Is it possible to change this font to "Overpass Mono" instead? (It would be nice to keep it all in the same Overpass family!) Thank you.

![typography-05](https://user-images.githubusercontent.com/24898297/37118698-1b81dbda-2223-11e8-8648-b69ce730a735.png)

![typography-04](https://user-images.githubusercontent.com/24898297/37118712-269d56a2-2223-11e8-9608-4b1655f89848.png)

This will fulfill Jira story [PTNFLY-2825](https://patternfly.atlassian.net/browse/PTNFLY-2825)

**Comment by andresgalante** [comment]
@jennyhaines thanks a lot! 

Should I assume that we have 3 line height sizes across the system? `1.5`, `1.4`, and`1.25` ?

**Comment by jennyhaines** [comment]
Hi @andresgalante - I'm fine with condensing down to three line heights instead of four. How about we change the Hero Title to 1.3? That way we have Hero title, H1, and H2 at the same line height of 1.3, and then H3 is 1.4, and H4, H5, and H6 are 1.5?

We just need the H3 to have a taller line height than 1.3 and shorter than 1.5... seems like 1.4 is the sweet spot.

**Comment by andresgalante** [comment]
Hi @jennyhaines sorry that I missed it before, we only have 6 heading sizes, not 8.

Do you want to rethink it or just remove one of them?

**Comment by LHinson** [comment]
@andresgalante will you update this issue with the specific questions/concerns that visual's need to address?

**Comment by andresgalante** [comment]
yes, we had a talk about it, we'll add the 7 sizes as variables. The only action is to define vertical rhythm on a text content area.

**Comment by jennyhaines** [comment]
@andresgalante - 

Same seven type variables, except without H1,H2, H3...etc labels, and took out the "em" unit:
![pf_next_typography_artboard 5](https://user-images.githubusercontent.com/24898297/37428921-211fb70c-27a4-11e8-84fa-c6ab00245bde.png)

Here are the spacers for the text styles. I don't see a need to add a text style for "block quote". I don't see when we'd need to use that in our products.
![pf_next_typography_artboard 6](https://user-images.githubusercontent.com/24898297/37428934-26c40546-27a4-11e8-9915-68d6796547fc.png)

**Comment by jennyhaines** [comment]
@jgiardino @andresgalante Now that we have new spacers, here is the new spacing between typography styles in a content block! So sorry for all of the changes :) 
![pf_typographyspacers](https://user-images.githubusercontent.com/24898297/37713467-6d713e0c-2ced-11e8-924b-a711b845711f.png)

**Comment by jeperry** [comment]
Out of curiosity, is this system based on a recognized type scale?  See https://type-scale.com/

**Comment by mcarrano** [comment]
Per Apr 26 Design Mtg -- We are good to move forward with this with the understanding that the goal here is to set some foundational type styles that can be used throughout pf-next. A more comprehensive guide to type usage should be documented elsewhere. I have opened https://github.com/patternfly/patternfly-next/issues/188 to addrress Typography Guidelines more globally.
