### ISSUE TITLE
Accordion custom `AccordionToggle`

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly#2116]
We have a requiremenets with accordion where we have to add some other components in accordion toggle header and it looks like there is `max-width` set to some variable. Can we remove it and change it to`flex-grow: 1;`?

**Comment by rachael-phillips** [comment]
@karelhala thanks for filing!  what are you trying to put into the accordian?

**Comment by karelhala** [comment]
I would like to insert absolutely anything in there, I would expect that the `AccordionToggle` for instance level with user icon
```html
<button class="pf-c-accordion__toggle pf-m-expanded" aria-expanded="true">
  <span class="pf-c-accordion__toggle-text" style="
    flex-grow: 1;
    padding-right: 1rem;
  ">
  <div class="pf-l-level">
    <div class="pf-l-level__item">
        Custom title
    </div>
  <div class="pf-l-level__item">
    <i class="fas fa-user" aria-hidden="true"></i>
  </div>
  </div>
  </span>
  <i class="fas fa-angle-right pf-c-accordion__toggle-icon" aria-hidden="true"></i>
</button>
```

Would look like this 
![Screenshot from 2019-08-01 09-40-16](https://user-images.githubusercontent.com/3439771/62274551-652f0e00-b440-11e9-9f3f-21ed53651059.png)

Just a `flex-grow: 1;` and some padding would be sufficient I guess (we want to be able to add anything in the header not only level layout).

**Comment by rachael-phillips** [comment]
@tlabaj making you aware of @karelhala 's response here.
