### ISSUE TITLE
Implement an indefinite loading bar

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly#2155]
With the spinner soon becoming a thing (#279), can we also take a look at an indefinite loading bar? 

Use case for this is when you don't know the final size that the loading bar is representing, or want to use it as an alternative to a spinner.

**Comment by mcoker** [comment]
@SpyTec returning to this - we just added a [Skeleton component](https://pf4.patternfly.org/documentation/core/components/skeleton). Is that what you were looking for, or is this a request for something else?

**Comment by SpyTec** [comment]
@mcoker I suppose I don't need an indefinite loading bar if we have skeleton components. Should anyone else need it they can create a new issue :)
