### ISSUE TITLE
Suggested color for success status icon & charts

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly#2169]
It would be helpful to have a suggested color to use for the success status icon as well as successful states in charts.  We would need this to pass the color contrast check, since sometimes the icon is used without a label.

**Comment by serenamarie125** [comment]
Could be related to #2168

**Comment by mcarrano** [comment]
@serenamarie125 Do you think that the changes made around https://github.com/patternfly/patternfly-next/issues/2320 addressed this? If so, I will close.

**Comment by mcarrano** [comment]
Green success color has since been updated to #486B00. See https://www.patternfly.org/v4/design-guidelines/styles/colors for more information, will close.
