### ISSUE TITLE
Support for text input and search icon with no border between

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2172]
Re: https://github.com/patternfly/patternfly-react/issues/1767

We have this design for filters that we do not currently support:

<img width="463" alt="Screen Shot 2019-08-20 at 4 29 32 PM" src="https://user-images.githubusercontent.com/35148959/63387172-6205ae80-c36a-11e9-8509-c66b8c520128.png">

We currently support the text input + search icon in the input group component, but the styling is different:

<img width="487" alt="Screen Shot 2019-08-20 at 4 38 46 PM" src="https://user-images.githubusercontent.com/35148959/63387195-7184f780-c36a-11e9-9656-f51312cc7b4a.png">

We currently have an issue (on hold) to update the button styling in the input group to match other form control elements, which will look similar to the filter design above. That issue is - https://github.com/patternfly/patternfly-next/issues/1926

However, even after implementing #1926, the filter design will not match the input group design since the input group draws a border between the text input and search icon/button, and there will be unique hover/focus/active styles for the search button in the input group that I'm assuming we would not want to persist in the filter design search as it is currently. As an example, in the input group, if you hover over the search button, we apply bottom border styles to the button that I'm assuming we wouldn't want to persist in the filter search design.

@mcarrano @kybaker can we update the filter group design to simply use the input group component for the search filter? That would just mean we introduce a left border to the search icon/button. Or do we want to offer a variation of the input group where there is no border between a form control field and a button adjacent to it, that also has unique interaction styling so that the form control field and button share a common bottom border so their hover/focus/active states can be styled together instead of independently as they are currently in the input group?

Also they have a design that has the same changes, except it's just an icon beside the text input instead of a button. For example, this (below) except with no border between the `$` sign and the text input beside it. Do we want to support that as a variation in the input group component, too, or would you advise they use the existing component styles there (and retain the border between the `$` and the text input)?

<img width="478" alt="Screen Shot 2019-08-20 at 5 01 34 PM" src="https://user-images.githubusercontent.com/35148959/63387900-3e436800-c36c-11e9-96ba-dcff5c37c205.png">

cc @dlabrecq @boaz0

**Comment by mcarrano** [comment]
@mcoker You raise some great questions about what we actually want here. I agree that using the input group as it currently exists does not seem like the right answer, but I'm not sure we would generally want to create a boarderless variant of the input group. Perhaps we should have a unique component that is a search field? In the second example of the currency input are the "$" and ".00" interactive or just static labels? If the later, I agree it's a bit odd to draw a border around them. Could this also be accomplished by placing text labels and a simple input inline? e.g. $ <input field> .00

We also need to consider how keyboard interaction should work here.

**Comment by mcoker** [comment]
@mcarrano 

> Perhaps we should have a unique component that is a search field? 

That's definitely an option, either a search component or search variation of the input group.

Re: the second example, I'm not sure the context for that element, I'll let @boaz0 reply, though I'm assuming they are just static labels.

Assuming so, what would be the use cases for the examples shown on the input group page? https://pf4.patternfly.org/components/InputGroup/examples/

Would we ever want to use the search field or `$` input (where I got the screenshot from) that are examples on that page? If not, we might consider removing them.

**Comment by mcarrano** [comment]
I've created this issue that should address this problem. https://github.com/patternfly/patternfly-next/issues/2175

**Comment by boaz0** [comment]
@mcarrano the "$" and ".00" in the second example are static
