### ISSUE TITLE
Datalist: support ability to nest an expandable datalist inside an expandable datalist

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#2177]
Currently, if I nest an expandable DataList component inside an expandable DataList list item, the toggles of children list items will inherit the display state of the parent toggle, due to how the css is defined here: https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/DataList/data-list.scss#L218

Instead, the css selector should only result in applying the display state to the immediate child toggle, and not all descendant toggles that are nested.

One possible way to do this is to have more specific descendant selectors. This is not as ideal, but also not a breaking change.

Ultimately, the toggle could include a `pf-m-expanded` modifier that we use to apply the correct styling to the toggle. This would be a breaking change.

**Comment by jgiardino** [comment]
Also, I haven't tested this in the expandable Table component, but I would expect similar updates there if needed.

**Comment by mcoker** [comment]
@jgiardino is there a product need for this with a release date you'd like to see this addressed by?

**Comment by jgiardino** [comment]
@mcoker I reached out to the product team that would need this. The following is the reply I received:

> It is not necessary to fix it soon. The new web ui is still TechPreview and the old one will be kept as default until the new web ui has enough functionality. And it will take some time.

So no specific dates yet, but this doesn't sound urgent.

**Comment by mcoker** [comment]
@mcarrano can we add this to the roadmap?

**Comment by mcarrano** [comment]
@jgiardino Is this still a need? I'm not sure that I like nesting lists like this. But if you still think it's a need, I'm happy to discuss.

**Comment by jgiardino** [comment]
The use case that prompted this issue is a need for something like a [tree view](https://github.com/patternfly/patternfly-react/issues/4652) but with the ability to include additional details like status and actions within the view. At the time of creating this issue, the only way to solve that use case was to apply some customizations to the data list to support this. In doing so, I noticed the issue that I opened here.

If there are plans to add similar features to the tree view component, then that would be the preferred component for this use case.

**Comment by mcoker** [comment]
I would still be in favor of seeing what's needed to address this. Even if we don't recommend users do it, I'd consider it a bug as it is that the expanded styles aren't scoped properly.

**Comment by mcarrano** [comment]
Thanks @jgiardino and @mcoker I'll add to the roadmap for further consideration.

**Comment by srambach** [comment]
This is still a bug and should be fixed.

**Comment by Andrei-Stepanov** [comment]
Hello, we hit this in our app. Please if possible take a look.
![pf](https://user-images.githubusercontent.com/12443962/116747668-8ac6be00-a9fe-11eb-88d2-205129a4bffb.png)

**Comment by Andrei-Stepanov** [comment]
Also reported at : https://github.com/patternfly/patternfly-react/issues/5728

**Comment by SpyTec** [comment]
> Hello, we hit this in our app

Since it wasn't mentioned, the app that Andrei's team is working on is used by a lot of people and have already caused confusion for RHEL developers in the internal mailing list

**Comment by Andrei-Stepanov** [comment]
@mcoker thank you for quick fix! :-) :+1:

**Comment by mcoker** [comment]
@Andrei-Stepanov you're welcome! This will be available in our next release targeted for the end of next week.
