### ISSUE TITLE
Focus state for `* + *`, specifically in `.pf-c-data-toolbar.pf-m-input-group` and `.pf-c-data-toolbar.pf-m-filter-group`

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2184]
Investigate solution for adjacent elements focus issues.

> sweeet. The only issue with this (and in the input group) is if you focus on an element that's to the left of another element in the group, the focus ring is hidden behind the right element, since the right element overlaps the left and has a higher stacking order since it comes after in the DOM.

Maybe we could use `:focus-within`? Here's a codepen as an example - https://codepen.io/mcoker/pen/BaBKORg. I tried it in the toolbar and needed to add a `z-index`, too, but didn't look at it much further as to why. Not sure that we want to add a `z-index`, which could cause random issues with that element popping out from underneath other elements.

_Originally posted by @mcoker in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzAzMzU2MjIw/timeline/more_items_

**Comment by mcoker** [comment]
@mattnolting is this something you still think we should address?

**Comment by mattnolting** [comment]
@mcoker I think we can close in favor of #3131
