### ISSUE TITLE
Spacing of children for certain components

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly#2195]
When we want to add children to some specific components it would be really good to also specify spacing of these children.

### Currently identified components
* Tabs
* Button
* Accordion -  related to https://github.com/patternfly/patternfly-next/issues/2116
* Badge
* Breadcrumb item
* Chip

### Spacing variants
Spacing could be either `sm`, `md`, `lg` for static spaces and `justify` if we want to have same spacing between all children.

The spacing can be enabled by `pf-m-[sm|md|lg]-spacing` for static and `pf-m-justify-spacing` for same spacing between children.

**Comment by karelhala** [comment]
It is quite large list of components so I ordered them by priority (most crucial is tabs). This issue was created because there is request to allow icons in tab components https://github.com/patternfly/patternfly-react/pull/2681 and https://github.com/patternfly/patternfly-react/issues/2623.

The initial proposal was to add custom styling for icons, however that is not ideal because we'd lock ourselves and allow only certain flow (icon text). This proposal allows to change order and also allows to add two texts in tab and specify spacing between them.

**Comment by karelhala** [comment]
@rachael-phillips actually this issue was requested in https://github.com/patternfly/patternfly-react/pull/2766 where I wanted to allow custom elements in tabs component. I found out that there is already PR to allow that https://github.com/patternfly/patternfly-react/pull/2681 so I closed the 2766. But the designers were unhappy how the text with icons looked so we agreed to create issue to add spacing in these components. Right now there are 2 issues opened in core to add icons to tabs https://github.com/patternfly/patternfly-react/issues/2623 and https://github.com/patternfly/patternfly-react/issues/2536 so at least 2 products need the tabs spacing.

**Comment by kybaker** [comment]
@rachael-phillips @mcoker It would be good to explore whether this could be covered by having full page demos with each one of the components laid out with the proper spacing. Right now there is not a great place to reference how each one of the components fit in a full page.

**Comment by mcarrano** [comment]
Per discussion with @kybaker and @mcoker this is best addressed as a demo to show how the flex layout can be used to properly space children inside of a component.

**Comment by christiemolloy** [comment]
@mcarrano and @kybaker It looks like we need some designs here to demonstrate the spacing for the components listed above. Or if tabs is the only component that is high on the priority - then just for tabs.
