### ISSUE TITLE
Add template to our GitHub issues 

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly#2199]
This request is to add a template to our GitHub issues, so that we can glean more information about each issue that is filed. 

https://docs.google.com/document/d/1wl1jROxHBhfGTIc4_YhW4g4VPsP6gIPTI3ctW_lLOLM/edit?usp=sharing

**Comment by rachael-phillips** [comment]
Relevant issue: about: #2211

**Comment by mcoker** [comment]
keep open
