### ISSUE TITLE
Badge 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#22]
Introduce the badge component and apply pf.next styling

**Comment by cliffpyles** [comment]
html/jsx: https://github.com/patternfly/patternfly-next/pull/39

**Comment by mceledonia** [comment]
Image
![badges](https://user-images.githubusercontent.com/30935938/40019468-52f32304-578d-11e8-9860-7db0958f8ab6.png)

Sketch File
[Converted Components MC_May14.zip](https://github.com/patternfly/patternfly-next/files/2002286/Converted.Components.MC_May14.zip)
 ("Badges" page)

**Comment by mceledonia** [comment]
Badges PDF with design examples and spec

[badgesPDF.pdf](https://github.com/patternfly/patternfly-next/files/2023598/badgesPDF.pdf)

**Comment by michael-coker** [comment]
Re: the text colors in the right column in the top of the design (pills against a dark background), the text colors are

> the gray is our secondary text color which should be #909496, the blue is our primary blue (the one kyle just changed to slightly darker blue)
