### ISSUE TITLE
Address nested <ol> in the wizard toggle <button>

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2202]
Only [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) is permitted in the [<button>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) element, so we need to address the `ol.pf-c-wizard__toggle-list` in `button.pf-c-wizard__toggle`.

Should we just remove the list and use `<span>`s to style the toggle text instead?

cc @jgiardino @jessiehuff

**Comment by jessiehuff** [comment]
I think this is still a valid issue, and it sounds like your solution would work here! 🙂
