### ISSUE TITLE
Need disabled state for icons in the PF library

### ISSUE THREAD

**Issue by vconzola** [patternfly/patternfly#2204]
Currently, all the icons in the PF library are shown in an active (selectable) state. We need an option to display icons in a disabled state. For example, an edit icon in a table row when the row is not selected.

**Comment by rachael-phillips** [comment]
Hi @vconzola we've seen this issue, and I'll get back to you on next steps.

**Comment by vconzola** [comment]
@evwilkin Did this ever get into a PF backlog? Is it being addressed? Thanks.

**Comment by evwilkin** [comment]
@vconzola I haven't seen any work around this issue. @mcarrano do you know if this ever made it to design?

**Comment by mcarrano** [comment]
@mcoker @mceledonia @gdoyle1 Don't we have a disabled state for actions that are represented by an icon (i.e. an icon button)?

**Comment by mcoker** [comment]
@mcarrano yeah, we update the color of disabled elements (button component, dropdown toggles, etc), and that updates the icon color to `--pf-global--disabled-color--100`/`$pf-color-black-600`

**Comment by mcarrano** [comment]
@vconzola does that answer your question? The icon is not an element unto itself, it is always enclosed in another interactive element that would take the disabled state styling.

**Comment by vconzola** [comment]
@mcarrano Yes, thanks for following-up.

**Comment by mcarrano** [comment]
Great. I will close this one then.
