### ISSUE TITLE
Bug in table cell word-break

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2205]
Noticed this problem with the table component. We set this, which may have something to do with it.

```
.pf-c-table td {
    word-break: break-word;
}
```

<img width="988" alt="Screen Shot 2019-08-29 at 12 39 49 PM" src="https://user-images.githubusercontent.com/35148959/63963217-26e63800-ca5a-11e9-823b-6dea12dc2ca8.png">

**Comment by mattnolting** [comment]
Another solution, 
- remove `word-break` on tds
- add a modifier `.pf-m-word-break` for long strings, like urls
- add a wrapper to table #2265 

@mcoker @christiemolloy @matthewcarleton wyt?

**Comment by mcoker** [comment]
Per our discussion, moving this out of the current milestone and into a breaking change milestone to re-evaluate whether cells should allow word-break or not and what options we make available to change that behavior.
