### ISSUE TITLE
Faceted (aka Checkbox) filter demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2219]
Create a demo that shows a faceted filter in a toolbar as used to filter the contents of a table. See https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#faceted-checkbox-filters For design direction.

**Comment by mcoker** [comment]
@mcarrano do you want to keep this open? I don't see this demo anywhere on the site yet.

**Comment by mcarrano** [comment]
Yes, I think we should close. We still may want this demo, but I'd rather open a fresh issue. Do you agree @mcoker ?
