### ISSUE TITLE
Type-ahead filter demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2220]
Create a demo to show a type-ahead filter used in a toolbar to filter table data. See design direction here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#faceted-checkbox-filters

**Comment by mcoker** [comment]
@mcarrano do you want to add this to the roadmap?

**Comment by mcarrano** [comment]
I am going to close in favor of: https://github.com/patternfly/patternfly/issues/457
