### ISSUE TITLE
Investigate padding/styles for browser-native number increment/decrement buttons on <input type="number" />

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly#2222]
When using the patternfly-react `<TextInput type="number" />` component (which just renders an HTML5 `<input type="number" />` element) I notice that Chrome and Firefox both render natively-styled (not consistent) up and down arrow buttons within the text field, which sit touching the number if the field is right-aligned.

Example in Chrome:
![chrome_input_number](https://user-images.githubusercontent.com/811963/64356860-89e34c00-cfd1-11e9-8296-9936e0d3e250.png)

Example in Firefox:
![firefox_input_number](https://user-images.githubusercontent.com/811963/64356870-8f409680-cfd1-11e9-8e27-c02dbe94c691.png)

This looks a little funky, and it could probably use some special CSS to make it fit the Patternfly design. These increment/decrement pseudoelements can be styled or hidden with CSS: https://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box

Edit: these example screenshots were taken on a Linux system, the buttons look different on other platforms.

**Comment by mcoker** [comment]
@kybaker @mcarrano should we have a spike and see what can style here and try and talk about how to improve the styling?

**Comment by mcarrano** [comment]
Yes, that makes sense @mcoker

**Comment by mcoker** [comment]
Hey @mturley what's the priority of this, do you see it addressed by a particular date?

**Comment by mturley** [comment]
Hey @mcoker , I don't think this is high priority, it was just a question that came up in the Migration Analytics project (in the cloud.redhat.com environment). A developer there was confused by the weird-looking buttons and asked what, if anything, they should do about it. I told them I'd open this issue and let them know if/when they should upgrade, but if it's not something we intend to fix I'll let them know.

**Comment by mturley** [comment]
I think this would be solved by a component implementation of https://github.com/patternfly/patternfly/issues/362, so I'll close it.
