### ISSUE TITLE
Update - `.pf-c-page` and `.pf-c-page__header` background colors 

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2240]
- `.pf-c-page`'s background-color is set to `var(--pf-global--BackgroundColor--dark-100)` (#151515), which is a remnant from the original dark themed dashboard and causes this bug when a dropdown is opened at end of `.pf-c-page__main-section`. `--pf-c-page--BackgroundColor` should be updated to `var(--pf-global--BackgroundColor--light-300);` (#ededed).

![64392610-82e12b80-d01b-11e9-9b5b-3824d1e4e7fc](https://user-images.githubusercontent.com/5385435/64613019-270ffd00-d3a3-11e9-963c-d6bdeb2af64c.png)

- `.pf-c-page__header`'s background-color should be set to `var(--pf-global--BackgroundColor--dark-100)` (#151515), as it loses the original page background-color when `.pf-c-page`'s background-color is updated.

**Comment by mcoker** [comment]
Per our discussion, moving this out of the current milestone and into a breaking change milestone to reevaluate if this is still needed, or we should leave it as-is. @mattnolting feel free to close if you think it's no longer an issue.
