### ISSUE TITLE
Spinner artifacts in Firefox

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2257]
I'm seeing this in Firefox

<img width="217" alt="Screen Shot 2019-09-12 at 10 44 39 AM" src="https://user-images.githubusercontent.com/35148959/64799568-95db8a80-d54a-11e9-9f94-76e315a2b84a.png">

**Comment by srambach** [comment]
@mcoker Can you give me some more information on how to reproduce this?

**Comment by mcoker** [comment]
@srambach I just have to open the spinner component example page in Firefox and the artifacts are visible. I'll follow up outside of github with a video.

**Comment by srambach** [comment]
Gathered from others: the spinner artifacts appear in both FF and chrome on some 2015 Macbooks.
It is difficult to reproduce and seem to be based on your local machine and the graphics backend of the browser. I have been unable to reproduce on my touchbar Macbook, even when turning off graphics switching. As all animations are currently in the composite layer, I have no ideas on how to fix this other than a change to a simpler design.

**Comment by mcoker** [comment]
@mcarrano can we add this to the roadmap? @mceledonia has reported still seeing artifacts.
