### ISSUE TITLE
Table - horizontal scroll issue

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2265]
relates to #2205 

Because `.pf-c-table` relies on a breakpoint to change layout to `grid`, in some instances the table layout breaks down before it hits the prescribed breakpoint because it contains a lot of information. 

![Screen Shot 2019-09-13 at 10 37 41 AM](https://user-images.githubusercontent.com/5385435/64871126-92abd180-d612-11e9-91a1-b5a981873757.png)

Suggestion:
```
<div class="pf-c-table-container">
  <table class="">
    content
  </table>
</div>

.pf-c-table-container {
  overflow-x: auto;
}
```

**Comment by mcoker** [comment]
Adding this to the 2020.04 milestone so we can work on it with https://github.com/patternfly/patternfly-next/issues/2205

**Comment by mattnolting** [comment]
@mcoker shall we create `.pf-c-overflow-container` and wrap all tables by default?
