### ISSUE TITLE
Address Wizard in Dark Mode

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#2267]
An issue came up in this PR with the wizard in dark mode :

<img width="746" alt="Screen Shot 2019-09-13 at 3 04 43 PM" src="https://user-images.githubusercontent.com/20118816/64891309-94d85500-d63f-11e9-922b-1e6b821a988b.png">

https://github.com/patternfly/patternfly-next/pull/2259#pullrequestreview-288223153

**Comment by christiemolloy** [comment]
After investigating this issue I believe we have to put it on hold until we sort out how to handle dark/light theme for components. Right now there is a block of dark theme styles for the button component nested inside of `pf-t-dark`. The wizard component is set to `@include pf-t-light` however in dark mode `pf-c-button` still inherits the dark styles because of the way those overrides are nested in the `placeholders.scss`. We need to arrive at a solution with the dark/light theme before we move forward with this issue.

**Comment by mcoker** [comment]
We can figure this out in the current dark theme effort.
