### ISSUE TITLE
Typeahead Select - remove unused variables

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2270]
- https://github.com/patternfly/patternfly-next/pull/2255/files#diff-bb2808f04482f63704d91791d6694ccaR30
- https://github.com/patternfly/patternfly-next/pull/2255/files#diff-bb2808f04482f63704d91791d6694ccaR299

**Comment by mcoker** [comment]
Closing in favor of https://github.com/patternfly/patternfly/pull/3019/
