### ISSUE TITLE
Page header links has default link color

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly#2295]
If you put an anchor link `<a>` in a Page header, it will default to the `--pf-global--link--Color`. It feels like this should have the same color as when it's a clickable button 

![example](https://user-images.githubusercontent.com/6598829/65427232-27cc7880-de12-11e9-89e0-cf7e3a6b0703.png)

**Comment by christiemolloy** [comment]
Hi @SpyTec thanks for submitting this issue. I wanted to confirm. Are you suggesting that if the user has text rather than an image inside of `pf-c-page__header-brand-link`, the text should be white and remove its underline? Or are you referring to the help icon on the right side? If so I think that should be a button component.

<img width="742" alt="Screen Shot 2019-10-07 at 9 47 25 AM" src="https://user-images.githubusercontent.com/20118816/66317478-936d1600-e8e7-11e9-876f-70f8cd6759f8.png">

**Comment by SpyTec** [comment]
Well, I might have chosen a bad example. But if there are links in the toolbar that will bring the user to a new page I would want to use anchor links instead of buttons. 

For things like help icon, if it brings up the About Modal, having it be a button wouldn't be too much of an issue as it's an action. But for other types of links I definitely would like to use anchor links 

For brand link, if it isn't an anchor link I believe it shouldn't be marked as such as it's not a link.

**Comment by christiemolloy** [comment]
Thanks for the context @SpyTec so typically when there is an anchor link it should be styled as a link to communicate its "link" properties. However in this situation, I can see your case for styling it link a button with white text and removing the underline. @mcoker @kybaker thoughts?

**Comment by christiemolloy** [comment]
@SpyTec I followed up with design. We should always default to the global link color and styling for PatternFly links. Feel free to override the styling in your project to be white, if you want :)

**Comment by rachael-phillips** [comment]
@SpyTec can I go ahead and close this?

**Comment by SpyTec** [comment]
Not sure I'm following. Anchor links have different styling depending on what component it is. The one I'm thinking of right now is the sidebar component which looks like this:
![image](https://user-images.githubusercontent.com/6598829/66379381-9cc4b400-e9b5-11e9-8ffe-76d167459b1f.png)

and not default colour:
![image](https://user-images.githubusercontent.com/6598829/66379409-a817df80-e9b5-11e9-8d76-70a33b7ddf00.png)

Should the latter instead be the default? I personally don't find that appealing, likewise for the top navigation toolbar
