### ISSUE TITLE
Dropdown 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#23]
Add the dropdown component

**Comment by kybaker** [comment]
Dropdown uses the same color, border, states, shadows variables which have been defined for the whole system. 

[Design PDF](https://drive.google.com/open?id=1GAdC7tYlMVDCqiBcrJC_r3gc-KNB_Kwm)

**Comment by LHinson** [comment]
@crobson @mcarrano If we limit the scope of this to a basic dropdown (single select), is there concerns/issues with this?

**Comment by mcarrano** [comment]
No concern @LHinson . It just means that we will need to address other components elsewhere. But to be clear, I assume we mean a drop down like this http://www.patternfly.org/pattern-library/widgets/#dropdowns.  Not a single-select drop-down list, right?

**Comment by catrobson** [comment]
+1 on this being the dropdown that Matt linked to only so we can sort through the other dropdown types and how to handle them.  Thanks!

**Comment by jgiardino** [comment]
@kybaker It looks like the examples in the [Design PDF](https://drive.google.com/file/d/1GAdC7tYlMVDCqiBcrJC_r3gc-KNB_Kwm/view) that you provided above are examples of the type of select menu that would appear in a form. 

Is your expectation that we'd use these same styles for the type of dropdown that we show here?: http://www.patternfly.org/pattern-library/widgets/#dropdowns

Or do you have another set of styles to use for these dropdowns?

**Comment by kybaker** [comment]
@jgiardino The dropdown you see in the PDF and the dropdown in the PatternFly should function the same. It is the same component.

**Comment by jgiardino** [comment]
Thanks, @kybaker. As @mcarrano mentions above, there are different types of dropdown menus, the kind that acts as a select menu in a form which can have a selected value, and the kind that offers a menu of actions that executes that action upon selection. 

For now, I'm working on the latter component, and have a couple of questions about how it should be styled:

- Will dropdowns have similar styling treatments that buttons do? For example pf-is-primary, pf-is-secondary?
- For the default state (i.e. no hover, not active) should the dropdown use the styles shown in the [pdf](https://drive.google.com/file/d/1GAdC7tYlMVDCqiBcrJC_r3gc-KNB_Kwm/view) for 'Dropdown (with selection made)' or 'Dropdown (with no selection made)'?

**Comment by kybaker** [comment]
@jgiardino:

- The dropdowns will only have a single type - no primary, secondary, etc. The dropdown does use a combination of blues and grays for the different state as you see in the pdf.
- For now the dropdown should keep the same functionality as our current PF3 dropdown where the state returns to default after a selection is made. We may need to change this in the future.
