### ISSUE TITLE
Update variables from the Data List

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#2305]
There are variables in the datalist.scss that need to be removed at the breaking change period. They have `// Remove at breaking change` comments next to them..

Related to this issue: https://github.com/patternfly/patternfly-next/pull/2289

Also let's review the datalist and update var names, specifically around the expanded/selected vars from https://github.com/patternfly/patternfly-next/pull/2491

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/3025
