### ISSUE TITLE
HTML structure of chip group in Data Toolbar

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#2309]
The HTML structure of the chip group in the Data Toolbar uses a list `<ul>` element to wrap the chip group, but the structure is created so that this list could never have more than one list item. If `ul.pf-c-chip-group.pf-m-toolbar` can only ever have one list item, then maybe a `<div>` should be used instead?

As part of this issue:

- Update the html to avoid instances where a `<ul>` can only ever include a single `<li>`
  - As part of this, it might be worth chatting with PF react dev on what structure is possible. 
- Create an issue in react to make updates based on updates made in core for this issue

example of Data Toolbar:
```
      <div class="pf-c-data-toolbar__item pf-m-shared-item"></div> <<< hidden on larger breakpoints
      <div class="pf-c-data-toolbar__item pf-m-chip-group">
        <ul class="pf-c-chip-group pf-m-toolbar"> <<< a list with only ever one list item
          <li>
            <h4 class="pf-c-chip-group__label">
              Risk
            </h4>
            <ul class="pf-c-chip-group">
              <li class="pf-c-chip"></li>
              <li class="pf-c-chip"></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="pf-c-data-toolbar__item pf-m-shared-item"></div> <<< hidden on larger breakpoints
      <div class="pf-c-data-toolbar__item pf-m-chip-group">
        <ul class="pf-c-chip-group pf-m-toolbar"> <<< a list with only ever one list item
          <li>
            <h4 class="pf-c-chip-group__label">
              Risk
            </h4>
            <ul class="pf-c-chip-group">
              <li class="pf-c-chip"></li>
              <li class="pf-c-chip"></li>
            </ul>
          </li>
        </ul>
      </div>
```
This is an example of Chip Group for comparison, which also has a `<ul>` element as a parent wrapper. But in this case, all groups are added as `<li>` list items in that wrapper. This seems to be the structure that was being used, except the extra divs that were added for smaller breakpoints result in the parent `<ul>` element being unnecessary:
```
<ul class="pf-c-chip-group pf-m-toolbar">
  <li>
    <h4 class="pf-c-chip-group__label">
      Category one
    </h4>
    <ul class="pf-c-chip-group">
      <li class="pf-c-chip"></li>
      <li class="pf-c-chip"></li>
    </ul>
  </li>
  <li>
    <h4 class="pf-c-chip-group__label">
      Category two
    </h4>
    <ul class="pf-c-chip-group">
      <li class="pf-c-chip"></li>
      <li class="pf-c-chip"></li>
    </ul>
  </li>
</ul>
```

**Comment by LHinson** [comment]
blocked by #2301
