### ISSUE TITLE
Need expand/collapse icons for topology view

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly#2327]
In PF4 topology, we have a grouping concept along with the ability to expand or collapse a grouping.  Working with @mceledonia we have a design which has an icon as part of the node label, and we would like to use the following icons:

<img width="52" alt="expand" src="https://user-images.githubusercontent.com/12504403/66049205-f8e09180-e4f8-11e9-9bbc-3d3fdb863e50.png">
<img width="52" alt="collapse" src="https://user-images.githubusercontent.com/12504403/66049206-f8e09180-e4f8-11e9-9335-a6674297b07b.png">

https://fontawesome.com/icons/expand-alt?style=solid
https://fontawesome.com/icons/compress-alt?style=solid

The problem is that these icons are part of Font Awesome Pro

@LHinson we need icons for implementation within by end of next week (10/11) to support OpenShift 4.3.

**Comment by serenamarie125** [comment]
I'm also including really LOW FI mockups to show where the icons intend to be used ( on the Knative Service node label )
![KnativeService-Iteration04](https://user-images.githubusercontent.com/12504403/66049473-73111600-e4f9-11e9-92e4-0c0febf8cc3b.png)
![KNativeService-Collapsed-Iteration04](https://user-images.githubusercontent.com/12504403/66049477-75737000-e4f9-11e9-87d3-8acf86e9cbc5.png)

**Comment by mceledonia** [comment]
@serenamarie125 @kybaker @LHinson @mcoker  I think we can easily recreate those as custom icons, but that brings in a larger question of how we want to handle custom icons in PF4. Do we utilize a secondary custom icon font library like PF3, or do we ensure we can smoothly utilize an SVG in place of the icon font?

**Comment by mcoker** [comment]
@mceledonia we have a custom icon font in pf4 that we uses to bring over pf3 fonts. You can see what's currently in that font here - https://pf4.patternfly.org/icons

We can add the font there, too. We add SVGs to that file via SVG data that we store in JSON here - https://github.com/patternfly/patternfly-next/blob/master/src/icons/definitions/pf-icons.json

We just need the width, height, and `<path>` data.

**Comment by mceledonia** [comment]
@mcoker That's great, I didn't realize we already had that in place. There's our answer!

**Comment by jeperry** [comment]
@katierik FYI this icon might come in handy for the expand/collapse action, if an icon is needed.

**Comment by mcarrano** [comment]
We do currently have expand and collapse icons in our free fa icon set that we ship with PatternFly. The recommendation is to use `fa-expand-arrows-alt` and `fa-compress-arrows-alt` to satisfy this use case. This issue will be closed.
