### ISSUE TITLE
Introduce "compact" modifier for dropdowns

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly#2344]
**Design need**
- Dropdowns don't really fit in card headers, especially compact card headers. This is a need from OpenShift dashboards which I'm recommending utilize compact cards.
---
**Compact modifier**
- Removes top/bottom padding spacing (0px) 

**Other things to note**
- I think the text should be right-aligned to the icon in this instance to avoid awkward/inconsistent spacing between the icon and text. See below
- Ensure "plain" modifier works with dropdown to allow for styling seen below.

![image](https://user-images.githubusercontent.com/30935938/66338037-49e3f180-e90e-11e9-9ac1-60ec8ec43026.png)

**In context:**

![image](https://user-images.githubusercontent.com/30935938/66338092-697b1a00-e90e-11e9-9998-0efd443745c3.png)

CC
@mcoker @mcarrano @kybaker @rachael-phillips @andybraren

**Comment by mcarrano** [comment]
I definitely agree that we need this @mceledonia . By 'dropdown' I think you mean Select lists. Do you think this should apply to both dropdowns and selects?

**Comment by mceledonia** [comment]
@mcarrano Yes I think so, but I haven't given it too much thought so let me know if you have any ideas on why not!

**Comment by andybraren** [comment]
Looks great! Using a `plain` modifier and right-aligning makes a lot of sense. We will likely have use cases for both Selects and Dropdowns in future dashboard cards @mcarrano, so designing both at once here is probably a good idea.

@mceledonia Do you think we'd need some sort of hover state styling for this? Not a lot of elements left to work with 🙂.

**Comment by mceledonia** [comment]
@andybraren Good question! We have the cursor change which is something, but we could go to blue if we really need to. Any thoughts there @mcarrano ?

**Comment by mcarrano** [comment]
I looked again at variations we have now. There is a Select-plain variant. See https://www.patternfly.org/v4/documentation/core/components/select#select---plain  Is this basically what you guys are looking for? There may be some improvements to be made to this, but it seems like it addresses the basic use case that you have. Thoughts?

**Comment by mcarrano** [comment]
I believe that we did add a modifier to fix the width of the select @mceledonia . @mcoker , is there any reason we can't achieve these card layouts using existing components?

We would need a 'plain' version of the dropdown only if we want to create an actions menu other than by using the kabob. So something like 'Actions v'  Do you anticipate anything like this @mceledonia @andybraren ?

**Comment by mceledonia** [comment]
I don't suspect we will need something like that (Actions v) but I think it's more of a spacing issue. I don't think that the plain modifier removes the top/bottom padding, just gets rid of the styling around it. Can you confirm this @mcoker ? 

In that case it would just be the addition of the compact modifier, so to achieve what I have above we'd use both a `plain` and `compact` modifier. If the plain modifier does do that, then we can go ahead and close this one. If not, the compact modifier would probably be something both the select and dropdown components could benefit from, to help with tight spaces like our compact cards.

**Comment by mceledonia** [comment]
Here's an example with the spec, the height of the select is now only as tall as the line height of the body text inside it (24px) which is also the same height as the header text, meaning the card header doesn't have to expand in height to accommodate the select at all. 

![image](https://user-images.githubusercontent.com/30935938/66424868-6fd7c780-e9dc-11e9-9dcd-5c5433359a89.png)

**Comment by mcoker** [comment]
> I don't think that the plain modifier removes the top/bottom padding, just gets rid of the styling around it.

@mceledonia that is correct.

**Comment by mcoker** [comment]
@mceledonia @mcarrano do we still want to introduce this? A dropdown toggle that matched the current font size and line-height could potentially solve some layout issues. Here is a related issue @matthewcarleton filed around cards - https://github.com/patternfly/patternfly/issues/2076

**Comment by mcarrano** [comment]
@mceledonia thoughts?
