### ISSUE TITLE
Make include of fonts and icons optional

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly#2346]
Since some apps are using custom fonts and are not using icons directly from stylesheets we should allow consumers to exclude these fields from build by passing `$pf-global--font: false` and `$pf-global--icons: false` when importing `.scss` files.

**Comment by karelhala** [comment]
@rachael-phillips we have active workaround since day one in our application, however it bloats our build. So it's more of a nice to have feature.

**Comment by mcoker** [comment]
keep open

**Comment by mcoker** [comment]
leave open
