### ISSUE TITLE
Sentence case for component names needed instead of title case

### ISSUE THREAD

**Issue by janwright73** [patternfly/patternfly#2359]
"About modal box” instead of “About Modal Box”,
"Alert group" instead of "Alert Group"
"Background image" instead of "BackgroundImage"
"Chip group" instead of "Chip Group"
"Clipboard copy" instead of "ClipboardCopy"
"Context selector" instead of "ContextSelector"
"Data list" instead of "Data List"
"Empty state" instead of "Empty State"
"Form control" instead of "Form Control"
"Input group" instead of "Input Group"
"Modal box" instead of "Modal Box"
"Notification badge" instead of "Notification Badge"
"Options menu" instead of "Options Menu"
"Tab content" instead of "TabContent"

"Box shadow" instead of "Box Shadow"

"About modal" instead of "About Modal"
"Basic forms" instead of "Basic Forms"
"Card view" instead of "Card View"
"Data list" instead of "Data List"

"Data toolbar" instead of "Data Toolbar"
"Overflow menu" instead of "Overflow Menu"

**Comment by janwright73** [comment]
@redallen @mcoker - think this issue covers the title vs sentence case regressions.  happy to help fix.

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/2401
