### ISSUE TITLE
Add selectable row variant to DataTable

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2371]
Want to support selectable rows in a DataTable separate from the checkbox select such that clicking on the body of a row will select it. This should be implemented as a new variant that can be consumed. Default appearance and behavior remains unchanged. It must be possible to enable row selection independent of checkbox selection and row expansion (i.e. it can exist with or without these separate features.

The selectable hover styles shouldn't be tied to only selectable rows - we should call it "hoverable" or something generic that can apply to other use cases where the row is interactive. From the conversation in https://github.com/patternfly/patternfly/issues/3273

See designs below:

Mock Ups: https://marvelapp.com/69dc1eg/screen/62345709
Mock up video

Background doc for context: https://docs.google.com/document/d/1gt561Ez-8j4-9WidAlQ2ZR12pvrvGD_i_S-eL4EFZdY/edit#heading=h.h7ibgfekw7rm

cc @LHinson @rachael-phillips @mcoker

**Comment by mcarrano** [comment]
Wasn't this implemented @mcoker ?

**Comment by mcoker** [comment]
@mcarrano nope, this feature is just on data lists.

**Comment by mcarrano** [comment]
Keep open
