### ISSUE TITLE
Bug: Add breakpoint for padding in the DataToolbar component

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#2398]
Components like the card, table, data list etc. have a padding left/right of 24px at full screen and then on mobile that padding decreases to 16px, we should update this here in this case:

its happening in the Mobile developer console:

<img width="676" alt="Screen Shot 2019-10-24 at 3 54 06 PM" src="https://user-images.githubusercontent.com/20118816/67520517-02cc5f00-f677-11e9-8708-758a2a6d3786.png">

**Comment by mcoker** [comment]
closing per https://github.com/patternfly/patternfly/pull/3403/
