### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#24]
Add progress bar 

Design Folder: https://drive.google.com/open?id=1ObtKD1QavVL3p1hQ0aIXpoaJCzLHDYDx

- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [x] CSS 

Contacts: 
- Visual @mceledonia 
- CSS @srambach

**Comment by mceledonia** [comment]
[Progressbar.pdf](https://github.com/patternfly/patternfly-next/files/2278533/Progressbar.pdf)
![progressbar_blue](https://user-images.githubusercontent.com/30935938/43967116-ae0c85c0-9c91-11e8-9401-69eac607bb18.gif)
![progressbar_purp](https://user-images.githubusercontent.com/30935938/43967117-ae17eeec-9c91-11e8-9794-7d250bea737e.gif)
![progressbar_yella](https://user-images.githubusercontent.com/30935938/43967118-ae26aedc-9c91-11e8-9fa5-555758fe02f4.gif)

**Comment by mcarrano** [comment]
@mceledonia Can you add the designs you presented yesterday to the design folder referenced above?
