### ISSUE TITLE
Options menu expandable enhancement

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly#2412]
The OpenShift Dev console team would like to add an enhancement to the options menu component to add an expandable section of the options menu. We will add more details about the behavior and screenshots with the design. 

Cc @Veethika @serenamarie125

**Comment by rachael-phillips** [comment]
@mcarrano we identified today that this is no longer a need for DevTools at this time. Do you mind if we close it and I remove this from the spreadsheet? https://docs.google.com/spreadsheets/d/1FFN7klXLeiDjCQNZmcek0LSb9ACccmvhiJwezjLxITA/edit?usp=sharing

**Comment by mcarrano** [comment]
Yes, that's fine with me @rachael-phillips . Looks like this request is quite old.

**Comment by rachael-phillips** [comment]
@mcarrano let's discuss when we meet today. I've been learning more about the background here.

**Comment by rachael-phillips** [comment]
@serenamarie125 after our Slack thread yesterday, I discussed this with @mcarrano, and he thinks that this issue is redundant with: https://github.com/patternfly/patternfly/issues/1429, so we are going to close it.
