### ISSUE TITLE
Input group example should not be using the Dropdown

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly#2413]
The Dropdown is not intended for use as an input.  The example should either use the Select or the Form Control Select Input. 
See related React Issue: https://github.com/patternfly/patternfly-react/issues/3217

**Comment by mcoker** [comment]
@mcarrano just want to make you aware. This will replace the input group example that has a dropdown component with a select component.

<img width="608" alt="Screen Shot 2019-10-29 at 12 40 31 PM" src="https://user-images.githubusercontent.com/35148959/67793694-50671400-fa49-11e9-8400-7a8a33fe79ae.png">

**Comment by mcarrano** [comment]
Yes, I think that makes more sense.

**Comment by ValerieKenyon** [comment]
I'd like to work on this and I came up with this so far: 
![Screen Shot 2020-04-05 at 16 27 35](https://user-images.githubusercontent.com/35377991/78509200-80ce7f00-775a-11ea-9c5e-d4ba48075d85.png)

**Comment by mcoker** [comment]
Hey @ValerieKenyon the select component is set to consume 100% of the available width of the container it's in. The best way to adjust that is probably to style `.pf-c-select` inside of `.pf-c-input-group`, and just set `width: auto;`.

**Comment by ValerieKenyon** [comment]
OK thanks @mcoker

**Comment by ValerieKenyon** [comment]
How does this look?

![Screen Shot 2020-04-08 at 09 00 48](https://user-images.githubusercontent.com/35377991/78788523-f19fb200-7979-11ea-9597-07db18cad54b.png)

and I replaced "dropdowns" with "selects"

![Screen Shot 2020-04-08 at 09 00 59](https://user-images.githubusercontent.com/35377991/78788624-109e4400-797a-11ea-8691-4571860a92f5.png)

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/2934
