### ISSUE TITLE
Add additional breakpoint value to overflow menu

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#2426]
In the Mobile Developer Console we are using the Overflow Menu feature. I have set an xl breakpoint on the component however we need a larger breakpoint because of the really long buttons that exist in the data list item. If we could have an extra breakpoint of 2xl that would be great!

<img width="826" alt="Screen Shot 2019-11-06 at 10 18 00 AM" src="https://user-images.githubusercontent.com/20118816/68311101-14eacc00-007f-11ea-8668-734c83d74cd1.png">

**Comment by christiemolloy** [comment]
@mattnolting what do you think?

**Comment by mattnolting** [comment]
@christiemolloy sounds good to me. We would need to add the new breakpoint to Core documentation and React would add the bp.

**Comment by mcoker** [comment]
Overflow menu supports a 2xl breakpoint https://www.patternfly.org/v4/documentation/react/components/overflowmenu
