### ISSUE TITLE
Fedora package with v4

### ISSUE THREAD

**Issue by xsuchy** [patternfly/patternfly#2439]
I am using PatternFly in several projects (e.g. Copr) and we use v3. I would love to migrate to v4 one day, but I need to use rpm packages. v3 is packaged in Fedora as `xstatic-patternfly-common`. It would be nice to provide (another) package in Fedora which contains v4 of Patternfly.

**Comment by janwright73** [comment]
Adding some highlights from a related discussion to this issue request:

Not as much "value in maintaining an rpm for web libraries in today's landscape. Modern web apps are built with webpack. During a webpack build, JavaScript, CSS, images, fonts, etc. are pulled out of their original source files and repackaged into one or more app payload files. It's no longer considered good practice to hardcode a reference to a library like PatternFly (perhaps available on the web server via rpm installation, but more commonly copied and pasted into the app source) with script and link tags." 

**How can I reference JS without using a script tag?**

"You can build the whole thing via Webpack[0], to be honest. Where you can apply optimization like minify, uglify, three shaking etc.
Configuration in Webpack has almost no limits (and brings huge headaches).
You will generate index via Webpack plugin[1] - It is possible to use a template for example and then feed it with your bundled assets.
(And yes you still need <scripts>, but you are not hardcoding it)

you typically end up with one generated <script> tag that references a webpack bundle entry point, and from there the webpack bootstrap magic begins.
example of a generated and cachebusted entry point: 
  <script type="text/javascript" src="bundle.main.js?67ab912919f8d5c45020"></script></body>

[0] https://webpack.js.org/
[1] https://webpack.js.org/plugins/html-webpack-plugin/
"

**What tool do you use to track necessity for a security update of some part of the bundle?**

"Depends on your project, I suppose. github occasionally notifies [3] project owners about vulnerabilities it finds when scanning package.json.
package.json sample:
  "dependencies": {
      "handlebars": "4.1.2",
      "handlebars-loader": "1.7.0",

Selection_203.png

[3] https://help.github.com/en/github/managing-security-vulnerabilities/about-security-alerts-for-vulnerable-dependencies"

**Comment by xsuchy** [comment]
This makes me sad :(

**Comment by redallen** [comment]
Hey @xsuchy ,

You can install PatternFly 4 globally and reference our CSS and static assets with `npm install --global @patternfly/patternfly`. That will save a copy of PatternFly to `~/node_modules/@patternfly/patternfly` that you can reference in many projects. If you need a specific version in an environment without `npm` you can even access the `.tar.gz` file yourself at https://registry.npmjs.org/@patternfly/patternfly/-/patternfly-4.50.4.tgz.

Thanks!
- Zack
