### ISSUE TITLE
Stylelint errors should fail build locally and in CI

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2452]
We have a bunch of specific rules in [.stylelintrc](https://github.com/patternfly/patternfly-next/blob/master/.stylelintrc) that should fail the build locally and in CI if the rules don't pass a lint check. Currently we have to run `npm run lint:styles` manually to verify that there are no violations.

cc @redallen

**Comment by redallen** [comment]
`lint:sass` runs in CI currently.
