### ISSUE TITLE
blueprint component changes

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2454]
* Remove the ["magic comment" comment](https://github.com/patternfly/patternfly-next/blob/master/build/blueprints/template/files/src/patternfly/__typeDirectory__/__namePascalized__/__nameDasherized__.scss#L1-L2) from the blueprint scss 

* update ["title" in the component MDX file](https://github.com/patternfly/patternfly-next/blame/master/build/blueprints/template/files/src/patternfly/__typeDirectory__/__namePascalized__/examples/__namePascalized__.md#L2) to use sentence case instead of title case. ie, `title: 'Data toolbar'` instead of `title: 'Data Toolbar'`

cc @evwilkin @redallen

**Comment by redallen** [comment]
Closed in #3235
