### ISSUE TITLE
Toggle column visibility in tables

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly#2461]
We have a case where there are many possible columns in a table that a user may want to sort/filter by in specific circumstances, but are not necessary to be used most of the time. Showing all of the columns all of the time is too much horizontal space to be practical and responsive.

To solve this, requesting the rectabular feature of toggle column visibility (https://reactabular.js.org/#/features/toggling-column-visibility) be incorporated into the PF4 table. This would also require a design pattern advising where to locate this functionality on a table in the UI.

This is an extension of the conceptual design done for PF3: https://blog.patternfly.org/content-views/table-view-showhide-columns-conceptual-design/

**Comment by rachael-phillips** [comment]
@mcarrano will look into from the design perspective and follow up.

**Comment by maryshak1996** [comment]
Working doc:
https://docs.google.com/document/d/1pEzrC8a3xSUeZL80LFDA3TM9es6nIP6zr4aAVoQfEHU/edit?usp=sharing

**Comment by mcarrano** [comment]
I've opened a design issue for further iteration and tracking here: https://github.com/patternfly/patternfly-design/issues/784

**Comment by maryshak1996** [comment]
Some very minor updates around how to access the column management have been posted to the working doc: https://docs.google.com/document/d/1QRCmAHcSrJ4uPlQsUiRLcezz9wo2zdIdAML1wBLTXYI/edit?usp=sharing

**Comment by mcarrano** [comment]
I believe this was addressed by the column management demo here: https://www.patternfly.org/v4/documentation/core/demos/table/column-management-modal Will close.
