### ISSUE TITLE
Support latest LTS version of node

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly#2462]
I encountered the following errors, with the latest LTS version of node (v12.3.0), while attempting to install and build PatternFly core.

<img width="783" alt="Screen Shot 2019-11-22 at 10 50 09 AM" src="https://user-images.githubusercontent.com/17481322/69440730-58983380-0d17-11ea-8299-34e0339d0534.png">

I could only install and build successfully using a much older version of node (v8.16.2). It's a pain to maintain old version of node just to build PatternFly core, only to reinstall the latest LTS version for all other UI projects.

**Comment by ddonahue007** [comment]
Verified,  I am hitting the same issues as well...

**Comment by mcoker** [comment]
@redallen wdyt?

**Comment by redallen** [comment]
We now support Node 12 across all PatternFly projects.

Closing.
