### ISSUE TITLE
`.pf-c-nav__simple-list .pf-c-nav__link:focus` styles can result in two items being active when using React Router

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly#2463]
See https://bugzilla.redhat.com/show_bug.cgi?id=1774702 and the override fix at https://github.com/openshift/console/pull/3542.

Because React Router does not change focus when routing, it's possible to end up with a nav item that looks active even though it shouldn't.  The workaround is to remove `.pf-c-nav__simple-list .pf-c-nav__link:focus` styling and only apply if `.pf-c-nav__simple-list .pf-c-nav__link:focus:hover` is true.

**Comment by christiemolloy** [comment]
@rhamilto This may not be a fix that we can implement in PatternFly Core because the solution to only apply focus styles when the element is `hovered` could negatively impact keyboard users who should see the focus styles without necessarily having to be hovered over a nav item.

**Comment by christiemolloy** [comment]
Hi @rhamilto any thoughts on the comment that I left? Were you able to find a workaround?

**Comment by rhamilto** [comment]
Hi, @christiemolloy.  Yeah.  I listed the workaround in [my original comment](https://github.com/patternfly/patternfly-next/issues/2463#issue-527389185).  It's up to y'all regarding a possible fix.  I documented this here for anyone else in the community who may experience the same issue.

**Comment by christiemolloy** [comment]
@rhamilto I did see your workaround thanks for including that. I'm still a little hesitant about affecting all keyboard users to solve this problem, but I'll defer to @jessiehuff @tlabaj and @mcoker to see if they have any further insight.
