### ISSUE TITLE
Opt-in to remove modal background

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly#2492]
@lwrigh would like to see the option to add an opt-in to remove the blur grey background on modal, as pictured in our examples here: https://www.patternfly.org/v4/documentation/react/components/modal

@tlabaj looked into this, and there is not a way to remove the background right now. 

@mcarrano from your perspective on design could we provide an option to opt-out of the grey blur background that comes along with the modal? cc @mceledonia

**Comment by mcarrano** [comment]
@lwrigh can you say more about your need for this? Currently screening the background is a standard part of our modal approach. Is it the blur that's the issue or the background in general?

**Comment by lwrigh** [comment]
> @lwrigh can you say more about your need for this? Currently screening the background is a standard part of our modal approach. Is it the blur that's the issue or the background in general?

@mcarrano In RHV some of the table views behind various modals are pretty information dense and sometime users reference the information that's in the background when filling out fields in the modals. With the blur, that information in the background becomes obscured. It's mainly the blur that's the issue. The background itself without the blur is currently in RHV on the PF3 modal dialogs and seems to be working for users.

**Comment by mcarrano** [comment]
This is more of a visual issue. Would like to hear what @kybaker and @mceledonia think. Should we support both blurred and unblurred background?

**Comment by lizsurette** [comment]
@lwrigh - Brought this up today in a PF meeting and @matthewcarleton mentioned it's applied via CSS so possible to override the CSS parameter for a quick fix. The team will consider removing this all together or at least making it an option due to browser performance reasons as well. FYI @mcarrano

**Comment by lwrigh** [comment]
Great that sounds good to me. Thanks for keeping me in the loop! @lizsurette I'll let my team know when you guys come to a conclusion but let them know about overriding the CSS parameter in the mean time.

**Comment by mcarrano** [comment]
@rachael-phillips @LHinson removed the design tags from this as this could be easily implemented by removing the blur effect in CSS. Should decide whether this would be offered as an opt-in, and new variant, or a global change. Later would most likely be considered breaking.
