### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#25]
Need attributes
Need to write the HTML as regular HTML
https://deploy-preview-11--pf-next.netlify.com/components/button/

**Comment by mcarrano** [comment]
Assigned @stacymcauliffe to draft design/usage documentation for this component. Should be added as design.md within a "docs" folder for the Button component.

**Comment by stacymcauliffe** [comment]
Working draft is here: https://docs.google.com/document/d/1_pRKid8LUvGEdD6c_4M-3AxQMg74PGVAULESTb1uvno/edit?usp=sharing

**Comment by jennyhaines** [comment]
@stacymcauliffe @mcarrano - Here are the design specs for the buttons! Thanks for implementing!
![buttons](https://user-images.githubusercontent.com/24898297/37832591-6b9d52bc-2e7f-11e8-9bd1-bc4c7379f8c0.png)

**Comment by jennyhaines** [comment]
*I should note that the button text size is 16 regular! (normal body text style)

**Comment by LHinson** [comment]
@stacymcauliffe has opened #129 to introduce design docs

**Comment by srambach** [comment]
If there is not yet an icon button design, I'll leave that out and another issue can be created to add it once designed.

**Comment by LHinson** [comment]
Tagging @kybaker to help address the icon button issue. Do we have this now or do we need a new issue?
