### ISSUE TITLE
Table and data-list padding updates

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2503]
Currently our table component, when in desktop layout has padding of 24px left and right `(td:first-child, td: last-child)`. The mobile view has 16px left and right. When paired with a `data-toolbar` the difference in padding causes a visual misalignment. At one point, @mceledonia had design updates that addressed this by reducing table padding globally. To match this alignment in the toolbar would require another modifier, that matches the `table` or `data-list` breakpoint value. 

**Table**
```Before spacer adjustment```
![Screen Shot 2019-12-10 at 3 20 12 PM](https://user-images.githubusercontent.com/5385435/70565714-a9ee5280-1b60-11ea-84e5-3b52154174eb.png)

```After spacer adjustment```
![Screen Shot 2019-12-10 at 3 19 58 PM](https://user-images.githubusercontent.com/5385435/70565733-b377ba80-1b60-11ea-8f79-dd042bebba8b.png)

```Responsive - no change```
![Screen Shot 2019-12-10 at 3 23 25 PM](https://user-images.githubusercontent.com/5385435/70565971-2aad4e80-1b61-11ea-8e30-c7dc878853d8.png)

**Data List**
```Before spacer adjustment```
![Screen Shot 2019-12-10 at 3 28 37 PM](https://user-images.githubusercontent.com/5385435/70566323-d3f44480-1b61-11ea-91d5-f27f8164df65.png)

```After spacer adjustment```
![Screen Shot 2019-12-10 at 3 27 21 PM](https://user-images.githubusercontent.com/5385435/70566331-d9ea2580-1b61-11ea-832e-4a80ce807432.png)

```Responsive - no change```
![Screen Shot 2019-12-10 at 3 28 14 PM](https://user-images.githubusercontent.com/5385435/70566362-ed958c00-1b61-11ea-899e-69428cf3c994.png)

**Comment by mcoker** [comment]
@mattnolting is this issue resolved with the toolbar insets, or is there more that needs to be done?

**Comment by mattnolting** [comment]
@mcoker toolbar insets take care of this
