### ISSUE TITLE
Status colors not AA-compliant over black

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly#2509]
Current status colors do not pass AA-compliancy over dark backgrounds. We should have dark-mode versions of the status icon and text colors.

**Comment by mceledonia** [comment]
Somewhat related is [this doc](https://docs.google.com/document/d/1siuDlhByeUGxB79LlNvquQJSdEyk4wzjAgl5wZSPJu4/edit?usp=sharing) I'm working on auditing the accessibility requirements of our colors. Status colors are a big one, and if we need them on our masthead we should determine what the requirements are, and remedy them if they don't meet the ratios.
