### ISSUE TITLE
About Modal shows no headings or landmarks in voiceover

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly#2536]
When using voiceover and navigating to the rotor, the about modal shows no headings or landmarks (in Safari)- this is a serious issue for screen readers as it cuts off a major form of navigation.

**Comment by jessiehuff** [comment]
Thought that I saw this issue resolved, but still seeing it in the latest audit, and also with Modal and Popover. :(

**Comment by mcoker** [comment]
@jessiehuff do you know if this is still an issue we should look into addressing?

**Comment by jessiehuff** [comment]
@mcoker Thanks for noticing this one! I just checked, and it does look like it's been solved, likely with the new changes that have been made to org. So it looks like we can keep this one closed. 🙂
