### ISSUE TITLE
Popover shows no headings or landmarks in voiceover

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly#2538]
When using voiceover and navigating to the rotor, the popover shows no headings or landmarks (in Safari)- this is a serious issue for screen readers as it cuts off a major form of navigation.

**Comment by mcoker** [comment]
@jessiehuff is this still an issue that we should address?

**Comment by jessiehuff** [comment]
Oddly enough, this does still seem to be an issue. It doesn't happen in react, but when I go to the html tab and open VO, it only sees the "Width auto" example. It just shows one header: "1. Popover header", one form control: "Close, button" (both of which look to be the Width auto example).

**Comment by jessiehuff** [comment]
Still an issue, though probably not the most pressing one since I think it's likely a documentation issue.

**Comment by mcoker** [comment]
@jessiehuff looks like it's an issue with `role="dialog"` - [modal examples](https://www.patternfly.org/v4/components/modal/html) have the same issue. The react examples behave the same once either a popover or modal dialog are opened.

Maybe we should remove the `role` from the static examples and note the role in the documentation and add it anywhere we have a modal/popover open?

**Comment by mcoker** [comment]
@jessiehuff wdyt about this issue? Should we keep it open?
