### ISSUE TITLE
Proposed change to badge state names

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly#2543]
The current badge state names are "unread" and "read". This makes sense in a notification drawer context but not in others, for example the count of selected items in a multi-select dropdown. The Design System Collaborative talked through some options for renaming these states:

- Primary // Secondary
   - matches button naming & color conventions, although in this case is the grey the primary?
- Default // Selected
   - "selected" maybe doesn't make sense since the user didn't take an action to select something
- Default or Inactive // Active
   - "active" has a different meaning for interactable elements. We like the term 'inactive' though.

We need further discussion to come to a consensus on proposed new names. Please add suggestions here. 

@kylebuch8 @samlinville @dcaryll @coreyvickery

**Comment by rachael-phillips** [comment]
@mcarrano making you aware of this issue. Is this something you would like to transfer to patternfly-design or no need?

**Comment by mcarrano** [comment]
@ajacobs21e @rachael-phillips I understand why "read" and "unread" may not have been the best choices. If we want to rename these, there is really not any design work to be done. However these names are baked into the CSS, so changing them could result in a breaking change. Thought @mcoker ?

**Comment by mcoker** [comment]
@mcarrano it would be a breaking change. We could add in the new variation names and leave the old ones in place in the code to avoid a breaking change, then remove the old ones in a breaking change release, though I'm not sure if that would cause confusion.
