### ISSUE TITLE
Create variable map for the system

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly#2550]
Will be working on a sheet that maps all components to global variables

Have started on the colors here: https://docs.google.com/spreadsheets/d/1T5gllFGnwROOI-03JeLYlxpeOcXn8zVFesVTfv8jq7A/edit?usp=sharing and will be adding to this

cc: @kybaker @mceledonia @mcoker

**Comment by gdoyle1** [comment]
This has finally been completed! Here's the spreadsheet with the full system variable mapping: https://docs.google.com/spreadsheets/d/1T5gllFGnwROOI-03JeLYlxpeOcXn8zVFesVTfv8jq7A/edit?usp=sharing. I spoke with Zack and created an issue for this to be investigated implementation-wise https://github.com/patternfly/patternfly-react/issues/3521.

**Comment by rachael-phillips** [comment]
@mcoker @mcarrano what do next steps look like here? I haven't heard much since the design issue was completed.

**Comment by gdoyle1** [comment]
This was completed through this issue https://github.com/patternfly/patternfly-react/issues/3521 so I'm going to close this
