### ISSUE TITLE
Move back to patternfly/patternfly repo

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly#2596]
In preparation for the Q2 milestone - we'd like to recommend the following approach to the code:

1) Move patternfly-next code into patternfly/patternfly repository
2) Move patternfly/patternfly existing code into a patternfly-3 branch
3) Create a patternfly-{milestone name?} branch on patternfly/patternfly to hold new changes while patternfly-next code continues to release

**Comment by evwilkin** [comment]
Resolved by @redallen
