### ISSUE TITLE
Form component: Basic form elements (first version)

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#26]
Introduce a v1 of the form component, consisting of all basic form elements. Elements include: 
- Labels
- Text Inputs
- Checkboxes 
- Radios
- Textareas
- Selects
- Datalists
- required fields 
- form validation

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD 
- Visual: @mceledonia 
- CSS: @mattnolting

**Comment by jennyhaines** [comment]
@LHinson @andresgalante @jgiardino 
Here are some form examples that I've worked on:

Basic Form in PF Next Template that need to be implemented:
![pfnext_form](https://user-images.githubusercontent.com/24898297/37712772-45667bfe-2ceb-11e8-8d17-8be46626a83c.png)

...and in-context examples as proof that this design works in our actual products: 
![openshift_form](https://user-images.githubusercontent.com/24898297/37712771-4557bff6-2ceb-11e8-85c8-44130d5e853c.png)

***I will attach the annotated design with spacers later today (by noon)

**Comment by jennyhaines** [comment]
Here is all of the information about the construction of form elements:

![components_artboard 8](https://user-images.githubusercontent.com/24898297/37722919-7e9195a4-2d03-11e8-91f6-3dee098aea7b.png)

![components_artboard 9](https://user-images.githubusercontent.com/24898297/37722927-83138380-2d03-11e8-9636-a705b31ad06c.png)

![components_artboard 10](https://user-images.githubusercontent.com/24898297/37722937-86859c56-2d03-11e8-88e1-d6aa56b27f3b.png)

![components_artboard 11](https://user-images.githubusercontent.com/24898297/37722945-8a2f126a-2d03-11e8-83ec-c764a17cc633.png)

**Comment by mcarrano** [comment]
@jennyhaines I see that your examples only include top aligned labels. Shouldn't we include left and right aligned label examples also?

**Comment by jennyhaines** [comment]
Here is all of the *Updated* information about the construction of form elements:

![components_buttons](https://user-images.githubusercontent.com/24898297/37737159-5e27d910-2d29-11e8-970f-5e8756275375.png)

![components_dropdowns-formfields](https://user-images.githubusercontent.com/24898297/37737165-61e16008-2d29-11e8-8826-2460a3101d62.png)

![pf_components-search-pagination](https://user-images.githubusercontent.com/24898297/37737171-65680de4-2d29-11e8-86b4-c9820313667e.png)

![pf_component-checkboxes-controls](https://user-images.githubusercontent.com/24898297/37737180-692679de-2d29-11e8-85fd-0ab41d25cbf6.png)

**Comment by jennyhaines** [comment]
@mcarrano - yes, I will include left and right aligned just incase we need them. I recommend that top aligned be the default go-to, though. I'll attach those tomorrow!

**Comment by mcarrano** [comment]
OK. I bring this up because we've been doing a lot of work on refactoring the way form labeling will appear for PatternFly 3 and I don't want to loose that. This is summarized here: https://github.com/patternfly/patternfly-design/issues/505 @matthewcarleton has also been involved with this rework. Glad to discuss if you have questions.

**Comment by jennyhaines** [comment]
@mcarrano - I'll make sure I'm referencing the form field design doc here when working on the PF-Next form design! [https://docs.google.com/document/d/1PcxszZ1S53Oacf7XZddnvba42RjMGr5R_QtQHZUqq98/edit#heading=h.3luq4z3f42oz](https://docs.google.com/document/d/1PcxszZ1S53Oacf7XZddnvba42RjMGr5R_QtQHZUqq98/edit#heading=h.3luq4z3f42oz)

**Comment by mcarrano** [comment]
We currently have Several design documents that address various aspects of Forms. They include:
* Data Input- http://www.patternfly.org/pattern-library/forms-and-controls/data-input/
* Errors and Validation - http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/
* Field Labeling - http://www.patternfly.org/pattern-library/forms-and-controls/field-labeling/
* Help on Forms - http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/
* Inline Edit - http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/
* Progressive Disclosure - http://www.patternfly.org/pattern-library/forms-and-controls/progressive-disclosure/
* Expand/Collapse Section - http://www.patternfly.org/pattern-library/forms-and-controls/expand-collapse-section/

We should account for these as we design forms for pf-next. @LHinson I am going to move this into Discovery as I think it would be worth doing an overall analysis of what we have now and how we may want to approach this going forward.

**Comment by andresgalante** [comment]
@kybaker On the login screen we have an alternative form style. Do we want to create 2 forms styles?
