### ISSUE TITLE
Introduce Toogle Button Group

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2625]
Introduce a new component called Toggle Button Group. This will be a groups of buttons that allow for selecting one items among a list of options (similar to a group of radio buttons). See design mockups below.

![image.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/606fc990-89fb-4c3b-b57c-98187866f3b5)

cc @mcoker @rachael-phillips @LHinson

**Comment by mceledonia** [comment]
In addition we will offer a variation with a white background for usage on our light gray background color. Only change for the variation is the button background to #FF. 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/30935938/85146570-b6441e00-b21b-11ea-9c45-0d8febd94f46.png">

**Comment by rachael-phillips** [comment]
@mcarrano @mceledonia we are trying to learn more about this toggle button group design. Could we apply this design to a set less than 3 or is this component offered because it should be applied to a group of 3 or more buttons?

**Comment by mcarrano** [comment]
@rachael-phillips While the example shows three buttons, I think it could be applied to 2 or more buttons. Do you agree @mceledonia ?
