### ISSUE TITLE
Reduce or eliminate the need for card backgounds

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2652]
Reduce the usage of the card layout to only dashboard or dashboard-like layouts. For pages with just a table or a list view, or a single form, we should investigate whether or not the card layout is more effective than a full page layout. 
This also involves ensuring we have full front end support for full page layouts.

Technical feedback from @mcoker 
Depending on what design provides for visuals, there may be enhancements to the variable system which would be a breaking change. 
PatternFly team effort: 
Design: medium-large effort
Applying the theme (core) = medium
Variable updates = medium - large 
Impact to the consumer: If someone is modifying global variables, that will impact a user more than someone who is using PatternFly as-is. 

Design work in progress here: https://github.com/patternfly/patternfly-design/issues/798

cc @LHinson

**Comment by mcoker** [comment]
closing via https://github.com/patternfly/patternfly-design/issues/846
