### ISSUE TITLE
Revise masthead for better scalability and usefulness

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2655]
Some possible updates:

- Consider reducing the height of the masthead to save on screen footprint

- Accommodate Context selector / app switcher in the masthead. See some rough concept ideas here: https://marvelapp.com/project/4674979 

- Rethink avatar behavior - current design proposals in https://github.com/patternfly/patternfly-next/issues/2482

Design work in progress here: https://github.com/patternfly/patternfly-design/issues/801

cc @mcoker @LHinson

**Comment by mcarrano** [comment]
@mcoker @mattnolting Do we still need this issue open?

**Comment by mcoker** [comment]
cc @mattnolting feel free to close this if the changes are covered in https://github.com/patternfly/patternfly/issues/2800, or if you want to update #2880 with anything from this issue. Doesn't seem like we need 2 issues.

**Comment by mattnolting** [comment]
Good to close, everything's covered in #2800
