### ISSUE TITLE
Revise Label visuals

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2656]
Want to update the Label component. Goals include: color coding, adding icons, and introducing a removable label.

Final designs here: https://marvelapp.com/87942e3

cc @mcoker @LHinson

**Comment by mcoker** [comment]
@mcarrano what's the use case for a clickable label? Is it a link or button that performs an action? Or is it "selectable", similar to data list rows?

**Comment by mcoker** [comment]
Also do we have named states for the colors - similar to alerts?

**Comment by mcarrano** [comment]
@mcoker The main use case I've seen for clickable labels is to use as a link. As for the color states, no these do not map like alerts. Consumers can use the colors how ever they want.
