### ISSUE TITLE
Integrate regression testing into workflow

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly#2673]
#2599 is certainly useful and wanted. However, it is painful workflow experience to have to update snapshots which might not always be the same ones that were taken in CI. There should be an easy way to update snapshots on a PR to match the ones in CI without having to setup Browserstack and run the whole suite locally.

This auto-updating implementation should leverage Git LFS.

**Comment by castastrophe** [comment]
@redallen I'd love to share some of our lessons learned and how we're approaching visual regression testing so you can see if it's something you'd be interested in incorporating.  I can't share the link because unfortunately, the repo is in the internal Gitlab instance at this time.
