### ISSUE TITLE
Radio buttons being cut off 

### ISSUE THREAD

**Issue by katerinapat** [patternfly/patternfly#2677]
We're using the Radio component and as it looks in the following screenshot the buttons are being cut off. 
![bs_macmav_Chrome_61 0](https://user-images.githubusercontent.com/3369346/68215502-a60a6600-ffdf-11e9-8359-ee04cf009393.jpg)

The problem appears when I use Chrome or Safari on Mac. Firefox works perfectly.

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/2799
