### ISSUE TITLE
Fix: `.pf-c-accordion` class name issue

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2696]
`.pf-c-accordion__expanded-content` should be `.pf-c-accordion__expandable-content` and modified by `.pf-m-expanded`

**Comment by mattnolting** [comment]
`.pf-c-accordion__expanded-content` should `.pf-c-accordion__expandable-content` and modified by `.pf-m-expanded`

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/5180
