### ISSUE TITLE
Simple Vertical Nav

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#27]
Introduce a simple single level vertical nav menu

Here is the simplest version of the vertical navigation which includes the mobile version.
[Design PDF](https://drive.google.com/open?id=1tAG-u-pAomS6r_HCjgvXLl8UgLDHToFK)

Incorporate findings based on [accessibility research](https://docs.google.com/presentation/d/13BD6dvDQdmrQGiqgdrje-Y9lXMVp2fhWWPR2Ljn_Qps/edit?usp=sharing) that has been done. Reach out to @jgiardino for more details.

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD @mcarrano 
- Visual @kybaker 
- CSS @mattnolting

**Comment by mceledonia** [comment]
https://drive.google.com/open?id=1jhcS86VwivuhcmsXNKJam8uCxe8hgLQN

**Comment by LHinson** [comment]
@mceledonia I see the link is for an .ai file, can you add something viewable for those without adobe?

**Comment by mcarrano** [comment]
I did a quick review of what we have in PatternFly 3 and it raises some questions about interaction details:

* Pinning - will we support pinned menus in pf-next navigation.
* Levels - in PatternFly 3 we are supporting up to 3 levels of navigation. Any reason we would not continue to support this?

Just want to confirm the assumptions we are currently working with.

**Comment by LHinson** [comment]
Thanks @mcarrano 

Regarding pinning, it's an important note however, I think we can make it out of scope for the first -next navigation at the very least. I have had initial conversations about deprecating this feature however it does require more follow up on the design side.... this is probably part of that larger conversation about navigation. 

+1 re: 3 levels, I think the design supports it but its just not shown.

**Comment by kybaker** [comment]
[Here is a PDF](https://drive.google.com/open?id=1OF02WbLl7jng6Ljr5aCh_-ieVi0hnUBV) of the current styling applied to each state. This design mirrors the current functionality as well as a few changes in the mobile state which account for Next modularity as discussed with CSS.

**Comment by stacymcauliffe** [comment]
Attaching [a working draft of the usage docs](https://docs.google.com/document/d/1wgXuPzmZsPTR0ujJGXZsgSsBL2OwI5aSGU3WJ8EuCvM/edit?usp=sharing) for this component. Still very much in progress :)

**Comment by mcarrano** [comment]
Overall, I think that the visual design and documentation represent a good start. There were just a couple of general questions that occurred to me as I read through this.

* In the current vertical nav, the masthead and the navigation function as a system. So when the menu collapses to mobile, for example, the utility items that are part of the masthead collapse into the vertical menu. I'm wondering how this will work with a more modular approach where the vertical menu and the utility items are not part of the same component. @andresgalante @matthewcarleton any thoughts here?

* I'm wondering whether the design doc should contain a section on behaviors, i.e. what actions are triggered on-click, on-hover, etc. This is not part of our current design doc and caused us considerable grief in getting the JS implementations consistent. These behaviors won't be demonstrated by the core components if they are limited to HTML/CSS. Thoughts @LHinson @stacymcauliffe ? I could take a stab at writing this section is you agree it's important.

**Comment by matthewcarleton** [comment]
@mcarrano From my discussions with @mceledonia, @kybaker and @andresgalante I believe the idea is the utility items would no longer collapse into the vertical but would collapse into it's own kebab menu.

**Comment by mcarrano** [comment]
OK. I see that in the design @matthewcarleton . This seems like a reasonable solution, my only concern is spacing. We probably will also want the notification icon in the mobile masthead if a notification drawer is being used.  But this is really more about the masthead than navigation. 

@LHinson do we have a feature in the queue for the masthead? Do we need one?

**Comment by kybaker** [comment]
@mcarrano Visually we are in a good place. We have reviewed this before but my concern would be that @matthewcarleton has seen it again.

**Comment by matthewcarleton** [comment]
This raises a question about A11y for me. For the active state we are using a light grey for the background, Blue for text/icon/border and a border. 
The background for anyone with poor eyesight, a low quality screen, or other possible issues won't see that. Which is ok b/c of the bottom border/blue. 
The one thing we need to consider is for colour blind users who don't see blue (Tritanopia), it's pretty rare so we are fine to leave this but this is a good opportunity to decide what we support for that and document it. @jgiardino do you have any thoughts on this?

Should we not have a mobile view for this as well?

**Comment by jgiardino** [comment]
The current color value for blue (#0088ce) fails the level AA color contrast requirements.
