### ISSUE TITLE
PatternFly font: Add icons, fix SVGs

### ISSUE THREAD

**Issue by bdellasc** [patternfly/patternfly#2707]
**Background**
This is a follow-up issue to issue: [Audit the PatternFly icon sets](https://github.com/patternfly/patternfly-design/issues/787). There are some icons that need to be added to the PF font and some that need to be fixed. They are all listed in the ["Additions & fixes to PatternFly font (final)" tab](https://docs.google.com/spreadsheets/d/1FwcP3qQm6zseNT-MKM2BwEmlu1La6KSmWe7i-9JzNFw/edit?usp=sharing). 

All PatternFly icon SVG source files [located here](https://drive.google.com/drive/folders/1ssGHFdiN8IThbp3qkRhKbLP8himaxs_9?usp=sharing). They were gathered from a number of places, so we'll need to test generating a new font with them.

For reference, I took a screen capture of the current PatternFly font as shown in Font Book. Although some of these have new Font Awesome icon recommendations, we need to fix/maintain the old icons since some may still be using them.

Marked the ones where I see problems:
![FixPFIcons](https://user-images.githubusercontent.com/17882357/77704950-bcb45800-6f94-11ea-96b4-b9656ffa331e.jpg)

**Deliverables**
- [x] @mcoker will upload the SVGs to GitHub
- [x] @mcoker will generate a TEST font file based on the new SVG set (named differently from current PatternFly font)
- [x] @bdellasc will test the font file, compare unicode mappings compared to current font
- [ ] @bdellasc will provide feedback and iterate with @mcoker 

cc @mcarrano @rachael-phillips @LHinson @gdoyle1 @mceledonia

**Comment by bdellasc** [comment]
@mcoker I wasn't sure which label/labels should be applied to the issue. Please feel free to mark it as you see fit.

**Comment by gdoyle1** [comment]
Can we add the calendar icon fix to this issue? Documentation in #2966 
@mcoker @bdellasc

**Comment by bdellasc** [comment]
This affects some other icons as well. The calendar isn't the only one that is in the regular style icon set. Quick glance through the spreadsheet, it looks like:

- fa-question-circle
- fa-window-restore
- fa-calendar-alt
- fa-clock
- fa-comments

We went around and around about the question mark icon usage (solid vs outline) and had finally landed on a good solution. I'm wary of opening that issue up again. We might want to meet about this to figure out the right next steps.

@gdoyle1 @mcoker

**Comment by mcoker** [comment]
@bdellasc is this safe to close now?

**Comment by bdellasc** [comment]
Yes, I fixed the issues highlighted/circled in the image in the issue description. Those fixes should be reflected in the updated icon set we've been collaborating on. 

Just verifying with @mcoker and @evwilkin that we agreed the FontAwesome Regular **(far)** font would be available, but not a default icon font that devs would receive? They have the option of adding **far** to their environment if they utilize any of the following icons we recommend:
- fa-question-circle
- fa-window-restore
- fa-calendar-alt
- fa-clock
- fa-comments

If that is also true, then the issue is resolved.

**Comment by mcoker** [comment]
@bdellasc we don't bundle far with core, only fas. If users want to use any icon set outside of fas or pficons, they will need to include that themselves. The best way to do that would be via a CDN link to the icon set they need.

**Comment by bdellasc** [comment]
OK, maybe we should spin off a new issue to make sure the documentation for devs explains that. Otherwise, it might be confusing for folks if we don't provide those far icons in core when we're recommending them in the icon recommendation table.

**Comment by mcoker** [comment]
@bdellasc added https://github.com/patternfly/patternfly-org/issues/2105 to clarify how to include `far` icons
