### ISSUE TITLE
Layout gutter size

### ISSUE THREAD

**Issue by PanSpagetka** [patternfly/patternfly#2725]
When I am using any layout, for example `Stack` I am having trouble with configuring gutter size. According to [documentation](https://www.patternfly.org/v4/documentation/react/layouts/stack) this component accepts `'sm' | 'md' | 'lg'` as a value for gutter size. But in practice there is only one gutter size. Doesn't matter what value I pass as a prop.

**Comment by karelhala** [comment]
ping @mcarrano @mcoker

**Comment by mcoker** [comment]
@PanSpagetka the gutter sizes were implemented incorrectly in patternfly-react and we have an issue to remove support for those values in our upcoming breaking change release https://github.com/patternfly/patternfly-react/issues/1982.

If you're building a more custom layout, I would recommend using the [Flex layout](https://www.patternfly.org/v4/documentation/react/layouts/flex).

**Comment by mcoker** [comment]
@PanSpagetka just wanted to follow up and see if you were able to find a solution?
