### ISSUE TITLE
Introduce draggable rows to Data List

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2728]
Want to allow the user to manually sort rows in a data list via drag and drop. This will be required to support column reordering and other potential use cases in the future. 

See designs for table column management here: https://docs.google.com/document/d/1QRCmAHcSrJ4uPlQsUiRLcezz9wo2zdIdAML1wBLTXYI/edit?usp=sharing

**Comment by mcarrano** [comment]
This is on the roadmap. Keep open.

**Comment by jgiardino** [comment]
I provided a comment regarding the implementation of this in #3401, but wanted to share a few other things to consider if this interaction pattern is expanded to support other use cases than what's provided in the design document. 

The design shows this in the context of a modal, which means that the reorder wouldn't really happen until the user exits the modal. But in the larger context of a data view, where a user could reorder list items, the keyboard interaction might potentially trigger an update on that list item with each arrow key press, unless there is also an additional save/commit action associated with the reorder. For example, if I'm moving a list item 10 spaces down, is there an api call made 10 times to update the position? Is that ok, or should there be an option for consumers that let them avoid this?
