### ISSUE TITLE
Update pf-bg-svg() SCSS function so it replaces characters correctly

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2740]
Right now this will cut off the first character from whatever color is passed, which works for hex values but not other color types (or `currentColor`)

https://github.com/patternfly/patternfly-next/blob/ef69afc9d099ff7b36ae9b820831ffabfa534c8c/src/patternfly/sass-utilities/functions.scss#L18-L22

**Comment by ValerieKenyon** [comment]
Hi, I'm interested in working on some of the PatternFly GitHub issues.  I think this would be a good beginning issue for me.  I've been working on setting up my development environment.  I'd like to confer with someone on the project to make sure I'm following best practices, before I submit a PR.

**Comment by mcoker** [comment]
Hi @ValerieKenyon thanks for the offer to contribute! For this we would just want to update the function to support any color a user might pass. Ideally this should support a string like `currentColor`, a hex value such as `, a color function like `rgba()`, etc.

You can see our usage of `pf-bg-svg()` in https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/FormControl/form-control.scss if you want to test and verify the solution works.

And since this will likely end up a breaking change, we're currently working on a [v4 branch](https://github.com/patternfly/patternfly-next/tree/v4) that you should submit your PR against.

Here is a link to some [basic setup information](https://github.com/patternfly/patternfly-next/blob/master/README.md), and we also have additional [contribution guidelines](https://github.com/patternfly/patternfly-next/blob/master/src/site/pages/contribution.md) and [code guidelines](https://github.com/patternfly/patternfly-next/blob/master/src/site/pages/guidelines.md). 

We also follow [semantic release](https://github.com/semantic-release/semantic-release/blob/master/README.md) for release versioning and write commit messages in past tense, so you can issue a PR with `fix()` in the commit message, for example `fix(scss function): updated pf-bg-svg() to accept any color`.

If you have any questions, you can reach out on the [PatternFly slack](https://patternfly.slack.com/), and I'm on there with the same username if you want to contact me directly. Reach out if you have any questions.
