### ISSUE TITLE
input type="range"  : style to match progress

### ISSUE THREAD

**Issue by ndotb** [patternfly/patternfly#2746]
In a form control where input type="range" is desired, the tag renders with a bland gray bar & handle from vanilla chrome/firefox styling.  A pretty blue bar with a big square for a handle would be nice.

**Comment by mcoker** [comment]
Hey @ndotb, can you describe your use case for the range input in a little more detail, and do you have any designs you could share to show it in use in your application?

**Comment by ndotb** [comment]
I try to avoid many of the html5 input types as they have been implemented on desktop browsers, but the the range control is very good for applying quantitative values to qualitative traits.  Kind of like when you rate your pain level at the doctor's office on the Wong-Baker scale with the smiley faces.

I would need to rough out css, but here's some simple mocks for a "how would you rate your experience" type of prompt:

normal
![image](https://user-images.githubusercontent.com/20463809/75396755-4c49e680-58c3-11ea-967f-8cec3ea3ee95.png)

with high threshold
![image](https://user-images.githubusercontent.com/20463809/75396974-bc586c80-58c3-11ea-9bb2-62cdbd548e2e.png)

with low threshold
![image](https://user-images.githubusercontent.com/20463809/75397132-27a23e80-58c4-11ea-9d5b-9dae8d0a30e6.png)

**Comment by mcoker** [comment]
Thanks! We have an open feature request for a slider component that I think would serve the use case here https://github.com/patternfly/patternfly-next/issues/296 

cc @LHinson @mcarrano @rachael-phillips what is the status of the slider component?

**Comment by rachael-phillips** [comment]
Hi @mcoker it is not on the roadmap at this time, but I will place this in the spreadsheet for future conversations.
