### ISSUE TITLE
Icon "blueprint" missing a bit of the line

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly#2747]
The "blueprint" icon has a bit of the line missing:
![Xnip2020-02-25_16-18-55](https://user-images.githubusercontent.com/23172038/75288631-bb9fd780-57ea-11ea-9a83-cb24bbff7810.jpg)

Compare to how it is in the sketch library:
![Xnip2020-02-25_16-20-48](https://user-images.githubusercontent.com/23172038/75288660-ca868a00-57ea-11ea-88e3-0dafc16ba2e0.jpg)

The bug in the SVG leads to a bug when used.

**Comment by mcoker** [comment]
+ @mceledonia 

We just need the updated SVG path data. Here's the existing path for the blueprint icon.

https://github.com/patternfly/patternfly-next/blob/72790c83d8cc1704f831e42ba06bf828c67d029f/src/icons/definitions/pf-icons.json#L51

**Comment by katierik** [comment]
Exported the icon from Sketch to SVG and it gave me this:

`<path d="M16.578125,6.875 L16.578125,5.4375 C16.578125,5.23958333 16.5416667,5.05729167 16.46875,4.890625 C16.3958333,4.72395833 16.2916667,4.56770833 16.15625,4.421875 C16.0104167,4.28645833 15.8541667,4.18229167 15.6875,4.109375 C15.5208333,4.03645833 15.3385417,4 15.140625,4 L15.140625,4 L14.28125,4 L14.28125,5.15625 L15.140625,5.15625 C15.1822917,5.15625 15.21875,5.1640625 15.25,5.1796875 C15.28125,5.1953125 15.3125,5.21354167 15.34375,5.234375 C15.375,5.265625 15.3984375,5.29947917 15.4140625,5.3359375 C15.4296875,5.37239583 15.4375,5.40625 15.4375,5.4375 L15.4375,5.4375 L15.4375,6.875 L16.578125,6.875 Z M5.140625,6.3125 L5.140625,5.4375 C5.140625,5.39583333 5.1484375,5.359375 5.1640625,5.328125 C5.1796875,5.296875 5.203125,5.265625 5.234375,5.234375 C5.25520833,5.21354167 5.28385417,5.1953125 5.3203125,5.1796875 C5.35677083,5.1640625 5.390625,5.15625 5.421875,5.15625 L5.421875,5.15625 L6.296875,5.15625 L6.296875,4.015625 L5.421875,4.015625 C5.234375,4.015625 5.0546875,4.04947917 4.8828125,4.1171875 C4.7109375,4.18489583 4.55729167,4.29166667 4.421875,4.4375 C4.27604167,4.57291667 4.16927083,4.72395833 4.1015625,4.890625 C4.03385417,5.05729167 4,5.23958333 4,5.4375 L4,5.4375 L4,6.3125 L5.140625,6.3125 Z M9.71875,5.15625 L9.71875,4.015625 L7.421875,4.015625 L7.421875,5.15625 L9.71875,5.15625 Z M13.15625,5.15625 L13.15625,4.015625 L10.84375,4.015625 L10.84375,5.15625 L13.15625,5.15625 Z M18.578125,20.015625 C18.7760417,20.015625 18.9583333,19.9817708 19.125,19.9140625 C19.2916667,19.8463542 19.4427083,19.7395833 19.578125,19.59375 C19.7239583,19.4583333 19.8307292,19.3046875 19.8984375,19.1328125 C19.9661458,18.9609375 20,18.7760417 20,18.578125 L20,18.578125 L20,8.875 C20,8.67708333 19.9661458,8.4921875 19.8984375,8.3203125 C19.8307292,8.1484375 19.7239583,7.99479167 19.578125,7.859375 C19.4427083,7.71354167 19.2890625,7.60677083 19.1171875,7.5390625 C18.9453125,7.47135417 18.765625,7.4375 18.578125,7.4375 L18.578125,7.4375 L8.859375,7.4375 C8.66145833,7.4375 8.47916667,7.47135417 8.3125,7.5390625 C8.14583333,7.60677083 7.98958333,7.71354167 7.84375,7.859375 C7.70833333,7.99479167 7.60416667,8.1484375 7.53125,8.3203125 C7.45833333,8.4921875 7.421875,8.67708333 7.421875,8.875 L7.421875,8.875 L7.421875,18.578125 C7.421875,18.7760417 7.45833333,18.9609375 7.53125,19.1328125 C7.60416667,19.3046875 7.70833333,19.4583333 7.84375,19.59375 C7.98958333,19.7395833 8.14583333,19.8463542 8.3125,19.9140625 C8.47916667,19.9817708 8.66145833,20.015625 8.859375,20.015625 L8.859375,20.015625 L18.578125,20.015625 Z M5.140625,9.734375 L5.140625,7.4375 L4,7.4375 L4,9.734375 L5.140625,9.734375 Z M18.578125,18.875 L8.859375,18.875 C8.81770833,18.875 8.78125,18.8671875 8.75,18.8515625 C8.71875,18.8359375 8.6875,18.8125 8.65625,18.78125 C8.625,18.7604167 8.60416667,18.7317708 8.59375,18.6953125 C8.58333333,18.6588542 8.578125,18.6197917 8.578125,18.578125 L8.578125,18.578125 L8.578125,8.875 C8.578125,8.83333333 8.58333333,8.79427083 8.59375,8.7578125 C8.60416667,8.72135417 8.625,8.69270833 8.65625,8.671875 C8.6875,8.640625 8.71875,8.6171875 8.75,8.6015625 C8.78125,8.5859375 8.81770833,8.578125 8.859375,8.578125 L8.859375,8.578125 L18.578125,8.578125 C18.6197917,8.578125 18.65625,8.5859375 18.6875,8.6015625 C18.71875,8.6171875 18.75,8.640625 18.78125,8.671875 C18.8020833,8.69270833 18.8203125,8.72135417 18.8359375,8.7578125 C18.8515625,8.79427083 18.859375,8.83333333 18.859375,8.875 L18.859375,8.875 L18.859375,18.578125 C18.859375,18.6197917 18.8515625,18.6588542 18.8359375,18.6953125 C18.8203125,18.7317708 18.8020833,18.7604167 18.78125,18.78125 C18.75,18.8125 18.7161458,18.8359375 18.6796875,18.8515625 C18.6432292,18.8671875 18.609375,18.875 18.578125,18.875 L18.578125,18.875 Z M5.140625,13.171875 L5.140625,10.859375 L4,10.859375 L4,13.171875 L5.140625,13.171875 Z M6.859375,16.59375 L6.859375,15.453125 L5.421875,15.453125 C5.390625,15.4427083 5.35677083,15.4296875 5.3203125,15.4140625 C5.28385417,15.3984375 5.25520833,15.3802083 5.234375,15.359375 C5.203125,15.328125 5.1796875,15.296875 5.1640625,15.265625 C5.1484375,15.234375 5.140625,15.1979167 5.140625,15.15625 L5.140625,15.15625 L5.140625,14.296875 L4,14.296875 L4,15.15625 C4,15.3541667 4.03385417,15.5364583 4.1015625,15.703125 C4.16927083,15.8697917 4.27604167,16.0260417 4.421875,16.171875 C4.55729167,16.3072917 4.7109375,16.4114583 4.8828125,16.484375 C5.0546875,16.5572917 5.23958333,16.59375 5.4375,16.59375 L5.4375,16.59375 L6.859375,16.59375 Z" id="pficon-blueprint"></path>`

cc @mceledonia

**Comment by mceledonia** [comment]
Weird.. Not sure what's going on there. Here's a re-exported SVG which seems to be rendering properly in FF/Chrome.

[pficon-blueprint.svg.zip](https://github.com/patternfly/patternfly/files/4471444/pficon-blueprint.svg.zip)

**Comment by bdellasc** [comment]
That's odd. @katierik were you using the PF font or the icon in the design kit components? Is your design kit up-to-date?

I found that some of the icons in the current PF font are broken (pieces of the SVGs are shifted). I created a separate story for all the icons with errors here, including the one @katierik referenced (circled in red). I circled the broken ones: https://github.com/patternfly/patternfly/issues/2707

Once we get the new and corrected SVGs added to a test PF font, @mcoker was going to generate a new test font file for me to try out. I want to make sure we don't inadvertently change the unicode strings for each icon in the new test font. It looks like they are generated in ascending order, based on the SVG names. If we're adding new icons, it may shift the unicodes around which would break the font for folks using the current version of the PF icon font. This could result in the wrong icons appearing for the icon they intended on using.

CC @gdoyle1 @mceledonia

**Comment by katierik** [comment]
I was using the icon in the design kit, which was up to date. 🤷‍♀️

**Comment by jeromemarc** [comment]
any update on this icon?

**Comment by bdellasc** [comment]
Yes, we identified the issue with the SVG, as well as other similar problems within the custom icon set. We're working on getting them fixed.

**Comment by bdellasc** [comment]
@katierik This issue was fixed with the latest icon edits. You can see the updated icon [here](https://www.patternfly.org/v4/guidelines/icons)

**Comment by evwilkin** [comment]
Closing per note above - this is now resolved.
