### ISSUE TITLE
Dev:lite - workspace remembers removed things

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2768]
I've noticed that if I add then remove components or examples, removed components are still listed in `/workspace/components` and removed examples are listed in the dir listing in `/workspace/components/componentname/` as `/workspace/components/componentname/deleted-example.html`

**Comment by redallen** [comment]
The removed examples are difficult to fix. The removed components are a little easier.

Not a high priority ATM, but I'll see if I can get to it by the end of the week!

**Comment by evwilkin** [comment]
Closed by #2984
