### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2770]
Need to either update the docs or include `build` in `dev`

![Screen Shot 2020-03-04 at 9 34 08 AM](https://user-images.githubusercontent.com/5385435/75889699-50ae5c00-5dfb-11ea-923c-b497bf611e85.png)

**Comment by mcoker** [comment]
This was added to the dev docs in the [repo README](https://github.com/patternfly/patternfly/blob/master/README.md)
