### ISSUE TITLE
Reduce top/bottom padding on bottom pagination when used with a compact table

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2774]
To support this design, let's talk about how best to achieve this reduced spacing. https://marvelapp.com/dge08b4/screen/66345393

**Comment by mcoker** [comment]
ping @mcarrano @mceledonia wdyt? Should we add a variation for pagination for use with compact tables/data-lists?

**Comment by mcarrano** [comment]
My 2 cents is that I'd prefer to not create more pagination variants. Can this be accomplished by adjusting spacing in the compact table layout?

**Comment by mcoker** [comment]
@mcarrano not really. The spacing around the pagination component is built into the pagination component itself. With the way it's built currently, we would need to have a compact pagination variation to support compact spacing when used with a compact table/data-list, and normal spacing when used with a normal table/data-list. We could explore updating the default spacing?

Or it would be a departure from anything we've done currently, but inline with theming, there could be a compact theme on a container that uses a compact variation or styling of components placed inside it - though that's not something I think we could solve in the short-term.

**Comment by mcarrano** [comment]
I see. Is there a demo that shows what this looks like now? I'd like to evaluate to decide whether it's worth making this change.

**Comment by mceledonia** [comment]
Another option here is to just refactor the existing spacing to be more compact. I agree we should take a look at its current state first to help decide.

**Comment by mcoker** [comment]
Here are a couple of screenshots from modifying the example on https://www.patternfly.org/v4/documentation/core/demos/table/basic

<img width="1604" alt="Screen Shot 2020-06-23 at 2 26 27 PM" src="https://user-images.githubusercontent.com/35148959/85449678-aa2ec800-b55d-11ea-9910-ab3bc930491d.png">

<img width="1604" alt="Screen Shot 2020-06-23 at 2 26 44 PM" src="https://user-images.githubusercontent.com/35148959/85449694-ad29b880-b55d-11ea-97e5-292ca9256a19.png">

**Comment by mcarrano** [comment]
I could live with this. What do you think @mceledonia ? ^^^
