### ISSUE TITLE
Horizontal nav w/ primary level only

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#28]
Introduce horizontal nav w/ primary level only

**Comment by mceledonia** [comment]
https://drive.google.com/open?id=1jhcS86VwivuhcmsXNKJam8uCxe8hgLQN

**Comment by LHinson** [comment]
Closing this issue as it will be addressed within #207

**Comment by mcarrano** [comment]
Hmmm... Up to you @LHinson but you may want to keep this open to track Horizontal Nav as a separate component. I see the PF-Next nav system as including a Primary Horz Navbar, and Multi-Level Vertical Navbar, and a tab bar that can be used for local sub-nav. These can be combined in various combinations to create different page templates per the wireframes I created. Sorry if that wasn't clear.
