### ISSUE TITLE
Page header - structural refactor

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2801]
**Modify structure to accomodate** 
- Toggle (nav-toggle) action area
- Brand area
- Tools area
- Horizontal nav area

`Tools` and `nav` should stretch full height as border treatments should touch the bottom of `-`pf-c-page__header`. 

**Note:** after some investigation, a flex layout (at least for the desktop/large layout) seems to be the best approach here as the only the `header__brand` area is required. All others areas (toggle, tools, nav) are optional, therefore creating rigid `grid` areas with a `column-gap` relies on column definitions that aren't dependable. 

Designs that reflect this new structure can be found here: https://marvelapp.com/4d9chi8

**Comment by evwilkin** [comment]
Closing in favor of #2800
