### ISSUE TITLE
Increase font weight for wizard active steps

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#2804]
Wizard active step needs heavier weight.
Sub-steps have it. 
Better a11y :)
<img width="306" alt="Screen Shot 2020-03-10 at 2 34 51 PM" src="https://user-images.githubusercontent.com/287880/76341818-51079500-62dc-11ea-903b-ba5678f90345.png">

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/2805
