### ISSUE TITLE
Header dropdown styling

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2808]
This issues should be addressed directly after, or with #2801

- Dropdowns should be full height of header

> I wonder if we should just make the dropdown enhancement, then the page enhancements once we finish the overall masthead story? Some questions:
> 
> * If someone is using another dropdown in the header, do we want the bottom border styles applied?
> * Would we want the underline styles to apply to the existing user dropdown without the avatar?
> * Can we handle the bottom border better so that the sides aren't angled?
> * Since we can include this in the breaking release, do we want to support using the avatar outside of the dropdown menu anymore?
> 
> Here's a screenshot of another dropdown in the header with the underline styles, also showing the angled sides.
> 
> <img alt="Screen Shot 2020-03-10 at 5 50 09 PM" width="471" src="https://user-images.githubusercontent.com/35148959/76366462-0e53b600-62f8-11ea-8067-fbcab0550853.png">

Line 170
```
  // Dropdown
  --pf-c-page__header--c-dropdown__toggle--before--BorderBottomWidth: var(--pf-global--BorderWidth--sm);
  --pf-c-page__header--c-dropdown__toggle--before--hover--BorderBottomColor: var(--pf-global--active-color--400);

  // Toggle
  --pf-c-header--c-dropdown__toggle--before--BorderColor: transparent;
  --pf-c-header--c-dropdown__toggle--before--BorderWidth: 0;
  --pf-c-header--c-dropdown__toggle--before--BorderBottomColor: transparent;
```

Line 215-233
```

  .pf-c-dropdown {
    .pf-c-avatar {
      --pf-c-page__header-tools--c-avatar--MarginLeft: 0;
    }
  }

  .pf-c-dropdown__toggle {
    --pf-c-dropdown__toggle--BorderTopColor: transparent;
    --pf-c-dropdown__toggle--BorderRightColor: transparent;
    --pf-c-dropdown__toggle--BorderBottomColor: transparent;
    --pf-c-dropdown__toggle--BorderLeftColor: transparent;
    --pf-c-dropdown__toggle--hover--BorderBottomColor: var(--pf-c-page__header--c-dropdown__toggle--before--hover--BorderBottomColor);

    &::before {
      border-bottom-width: var(--pf-c-page__header--c-dropdown__toggle--before--BorderBottomWidth);
    }
  }

```

**Comment by mcoker** [comment]
@mattnolting do you want to keep this open as part of the masthead work?

**Comment by mattnolting** [comment]
@mceledonia @mcarrano https://marvelapp.com/prototype/4d9chi8/screen/67194843 is this still the valid? Should all bottom borders of dropdowns in masthead align to bottom?

**Comment by mcarrano** [comment]
I think that was the intent. Can you confirm @mceledonia .

**Comment by mcarrano** [comment]
This is still an issue, correct? Part of masthead work?

**Comment by mattnolting** [comment]
> This is still an issue, correct? Part of masthead work?

@mcarrano Yes, it's part of the masthead work. I'll add to the epic.

**Comment by mattnolting** [comment]
Ping
