### ISSUE TITLE
Fix: drawer__panel tab focus

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2811]
https://github.com/patternfly/patternfly-react/issues/3887

> Describe the issue. What is the expected and unexpected behavior?
A drawer component with a drawer panel in the hidden state will become visible if you add a component to that panel, and tab through the page to all focusable components. The hidden panel should not become visible.
Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.

> You can add a button to the drawer panel in the example code on the react site, and reproduce the bug by tabbing through the example page. The hidden drawer panel will appear when the focus reaches the component residing on the panel.
Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?

> What is your product and what release version are you targeting?
Exists in openshift 4.4.

**Comment by mcoker** [comment]
Closing in favor of https://github.com/patternfly/patternfly/issues/3129
