### ISSUE TITLE
Data list item expandable content border

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#2815]
At smaller breakpoint, when the expandable content has more than 600px of content, and scrolls, the left before is not extending to the height of the full container.

<img width="477" alt="Screen Shot 2020-03-13 at 10 44 23 AM" src="https://user-images.githubusercontent.com/20118816/76631197-a7ace300-6517-11ea-9b09-1e51bea5b0da.png">

**Comment by mcoker** [comment]
@christiemolloy looks like this was fixed. Can you confirm?
