### ISSUE TITLE
Expanded Select component and Page component 

### ISSUE THREAD

**Issue by alexfdezsauco** [patternfly/patternfly#2819]
An expanded Select component and cause wrong behavior at the end of the Page

![image](https://user-images.githubusercontent.com/1785664/76691583-91d81480-6622-11ea-8267-0e88bfdc4d92.png)

The symphony is a black area rendered instead and expansion of the page or section. 

To see a repo of this issue you scroll to the end of this http://blorc-patternfly.wildgums.com/components/select and expand the select component.

**Comment by alexfdezsauco** [comment]
@mcoker Any idea about this one?

**Comment by alexfdezsauco** [comment]
**WORKAROUND**: padding-bottom: 100%

        <main role="main" class="pf-c-page__main" tabindex="-1">
            <section class="pf-c-page__main-section" style="padding-bottom: 100%">
                @MainContent
            </section>
        </main>

![image](https://user-images.githubusercontent.com/1785664/77228117-7a85b380-6b5b-11ea-90a6-3119144c8d3d.png)

**Comment by mcoker** [comment]
Hey @alexfdezsauco thanks for reporting this! We have an issue to address that and it will be going out with our upcoming major version release - https://github.com/patternfly/patternfly/issues/2240

**Comment by marshmalien** [comment]
We noticed a similar issue while using the Select component in Ansible Tower. When the select menu contains a large number of select options, it stretches to fit the content and pushes the page down. The scenario below would be a better experience if the select menu started to scroll once it hit a specified height. 

![select](https://user-images.githubusercontent.com/15881645/78153241-d9271900-7408-11ea-976b-b1e6334127de.gif)

**Comment by mcoker** [comment]
@marshmalien typically we recommend a [typeahead select](https://www.patternfly.org/v4/documentation/react/components/select#typeahead) for select lists with more than 10 options. https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/data-input#select-lists

cc @mcarrano

**Comment by marshmalien** [comment]
@mcoker We are using the `typeahead multi` variant in this example.

**Comment by mcarrano** [comment]
I do see the problem @marshmalien . For a type-ahead you can potentially have hundreds of items before the user starts typing to filter the list. @mcoker , is it possible to constrain the height of the menu and expose a scroll bar? If we did, would that need to be set as a pixel height, number of items, or something else? We would need to figure out what that max height should optimally be.

**Comment by mcoker** [comment]
@marshmalien sorry about that, I see that now. @mcarrano yes, we can simply use a pixel height or approximate a height of a certain number of items by calculating the item font-size and outer padding. We could also have size variations, and for that height to be overridable in react.

**Comment by alexfdezsauco** [comment]
@mcoker Could be also possible add an scroll for large list even when typeahead is used?

**Comment by mcoker** [comment]
@alexfdezsauco sorry for the delay. With the react select component, we have a `maxHeight` prop that limits the menu height and applies scrolling. Will that work?

**Comment by mcoker** [comment]
@marshmalien not sure if you saw my comment about using the `maxHeight` react prop to limit the height of the select menu - curious if you can confirm whether or not that will work for your use case, too?

**Comment by marshmalien** [comment]
@mcarrano Exposing a `maxHeight` prop would work for us. Thanks!
