### ISSUE TITLE
Update blue and cyan 600/700 color variables

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly#2825]
Let's update 600/700 values instead of removing them to keep each color with a consistent amount of values.

`cyan-600` = `#002323`
`cyan-700` = `#000F0F`

`blue-600` = `#002952`
`blue-700` = `#001223`

Here's a quick before/after, other colors don't seem to have this issue just blue/cyan.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/30935938/76788320-10eb5b00-6791-11ea-9a1d-99dd2a131236.png">

@mcoker @christiemolloy

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/2832
