### ISSUE TITLE
Potential extension to our Form Pattern: Form value calculator

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly#2827]
## Requesting new features, enhancements, or design changes to PatternFly 
In the case where a form field entry will actually be changed based on a calculation, this addition to the form will show the calculation along with the calculated value for the user to preview which value they are ultimately setting.

So far, this is something that is need in the OpenShift Container Storage (OCS) extension of OpenShift.

Here are a few screenshots to show the currently implemented flow of this feature...

Empty field:
<img width="551" alt="Screen Shot 2020-02-21 at 8 50 59 AM" src="https://user-images.githubusercontent.com/208455/75039923-af80e680-5487-11ea-98e9-9113566133ed.png">

User starts typing, the calculation begins and preview is shown next to the field:
<img width="562" alt="Screen Shot 2020-02-21 at 8 50 50 AM" src="https://user-images.githubusercontent.com/208455/75039972-ca535b00-5487-11ea-81c5-85eee1f9a67b.png">

As user continues to type, calculation continues. Value is Saved on "Add" action.
<img width="586" alt="Screen Shot 2020-02-21 at 8 50 38 AM" src="https://user-images.githubusercontent.com/208455/75040004-dc34fe00-5487-11ea-84e8-b3e83847aa69.png">

If accepted, this would be a new feature to the Form Pattern in PatternFly.

FYI @yuvalgalanti

**Comment by lizsurette** [comment]
That sounds great, thanks for the update @mcarrano!

FYI @yuvalgalanti

**Comment by mcoker** [comment]
keep open
