### ISSUE TITLE
Feature Request: Tables with scrollable body and header fixed

### ISSUE THREAD

**Issue by alexfdezsauco** [patternfly/patternfly#2838]
Could be possible officially support tables with scrollable body and header fixed?

**Comment by mcoker** [comment]
Hey @alexfdezsauco, are you referring to a sticky header like https://codepen.io/mcoker/pen/QWbxVKa? Or do you mean limiting the height of the table body in some way so that the overall table is shorter than the amount of rows in the body, and the body scrolls while the header remains fixed?

**Comment by alexfdezsauco** [comment]
Well, I'm looking for the second one, but the example could work for me. Thanks.

**Comment by mcoker** [comment]
cc @mcarrano WDYT? This is something we could support in patternfly.

**Comment by mcarrano** [comment]
Yes, I would be in favor of this. It's frustrating if the table is very long and the column headers scroll off the page.

**Comment by mcoker** [comment]
@mcarrano do we need a design issue? Or is https://codepen.io/mcoker/pen/QWbxVKa accurate for the intended design/behavior?

**Comment by mcarrano** [comment]
I think what you have in the codepen is great @mcoker . I see no need for more design work.

**Comment by mcoker** [comment]
@mcarrano great, thanks! Added this issue to our backlog.

**Comment by alexfdezsauco** [comment]
Could be possible also implement the second one 

> do you mean limiting the height of the table body in some way so that the overall table is shorter than the amount of rows in the body, and the body scrolls while the header remains fixed?

The sample in codepen is great if you have an only one table in the page, but what if you need more than one.

**Comment by mcoker** [comment]
@alexfdezsauco here's another codepen showing how you could do that assigning a height to the `<Card>` component that wraps the table, and applying `overflow: auto`. In combination with the sticky header feature, you could put multiple scrolling tables on a page with sticky headers.

https://codepen.io/mcoker/pen/gOpZxGq

**Comment by alexfdezsauco** [comment]
Great

**Comment by katierik** [comment]
+1-ing this as multiple PMs have asked me about this functionality for cloud.redhat.com
