### ISSUE TITLE
Break to use old version after moving PatternFly-Next repo to PatternFly/PatternFly

### ISSUE THREAD

**Issue by danieloh30** [patternfly/patternfly#2843]
We have an angular-patternfly-based app using the following bower.json
    "devDependencies": {
        "patternfly": "3.17.0",
        "angular-patternfly": "3.17.0",
        "bootstrap-switch": "3.3.2",
        "isotope": "2.2.2",
        "imagesloaded": "4.1.1",
        "angular-route": "1.5.10",
        "keycloak": "1.9.8"
    },

I know these are ancient versions, but it did break when the switch was made. The failure can be seen with:

git clone https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m4-labs
cd cloud-native-workshop-v2m4-labs/coolstore-ui
npm install

If there's an easy workaround to keep this obviously old code working, I would much appreciate knowing what it is! Thank you!

**Comment by redallen** [comment]
https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m4-labs/pull/3 might be an immediate fix.

https://github.com/bower/registry/pull/292 is a better fix, but we have to wait on someone like @sheerun to review + merge it.

**Comment by redallen** [comment]
https://github.com/bower/registry/pull/292 has been merged and all our bower packages are as they were before
