### ISSUE TITLE
Update mobile pagniation to show menu

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2879]
Per https://github.com/patternfly/patternfly-design/issues/812, need a way to display navigation options (i.e. next page, previous page) when the top toolbar shrinks for mobile viewports. Solution is to provide access to options menu and add these actions to the menu. Design mocks here: https://sketch.cloud/s/DZyej/a/wzLo3D

**Comment by mcarrano** [comment]
@mcoker I've opened this issue to reflect requested design change to the Pagination component. If this will be breaking, can it be rolled into the breaking change release? It fixes the issue above filed from product.

cc @tlabaj @LHinson @rachael-phillips

**Comment by mcoker** [comment]
Met with @mcarrano and @mattnolting today and decided to take a different direction with this. Closing in favor of https://github.com/patternfly/patternfly/issues/3021
