### ISSUE TITLE
Clarification of Filter, Vertical Line, Search icon within search/filter bar

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly#2889]
When looking at the different search/filter bars within PF Org documentation some have the text italic, some do not and additionally there is a vertical line in some instances and not in others. What is the correct use?

![Screen Shot 2020-03-26 at 2 57 45 PM](https://user-images.githubusercontent.com/18266453/77686353-35a2b800-6f73-11ea-9e89-6aad2b27bde9.png)
![Screen Shot 2020-03-26 at 2 57 57 PM](https://user-images.githubusercontent.com/18266453/77686355-363b4e80-6f73-11ea-97d2-39dbda50c168.png)

**Comment by mcoker** [comment]
@Rohoover sorry for the delay! Do you still need clarification on this?
