### ISSUE TITLE
Multi-column form variation

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly#2890]
Multiple people have shared some use cases where they could use a multi-column form format in their products.

Currently, you can only have one input field per line in a form. This new multi-column variation or capability would allow for multiple input fields on a single line, as presented in this mock up.
The First name and Last name fields show an example of 2 fields on the same line, while the Credit card information show an example of 3 fields on the same line.

![image](https://user-images.githubusercontent.com/51165119/77694606-ae5c4100-6f80-11ea-933f-ddf903687c0b.png)

**Comment by mmenestr** [comment]
@mcarrano ^

**Comment by mcarrano** [comment]
@mcoker @LHinson would be great to get this on the roadmap as an enhancement to Forms. Related to https://github.com/patternfly/patternfly/issues/919

**Comment by mmenestr** [comment]
@mcarrano Thinking we can close this now that we have established that multi column forms can be made using the layouts offered in PF. So we wouldn't need a new form variation specifically for multi-column forms!

**Comment by mcarrano** [comment]
OK. Done.
