### ISSUE TITLE
fix(tabs, buttons): elements with `::before` and `::after` pseudos for border styling need to be selectable

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2893]
Update css for borders that use `::before` and `::after` pseudos for border styling. 

```
.pf-c-button {
  user-select: text;

  &::before,
  &::after {
    pointer-events: none;
  }
}
```

![Screen Shot 2020-03-27 at 12 36 16 PM](https://user-images.githubusercontent.com/5385435/77778565-94296e00-7027-11ea-8f35-9c0959bd7831.png)

**Comment by mcoker** [comment]
keep open
