### ISSUE TITLE
Update stylelint and audit rules

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2956]
Stylelint is on v13 and we're on v9.

We also use the following extends:
* https://github.com/stylelint/stylelint-config-standard 
* https://github.com/kristerkari/stylelint-config-recommended-scss

Let's see what's new compared to v9 and in the extends and audit our ruleset and see if we can make improvements.

**Comment by mcoker** [comment]
@redallen can you verify what version of stylelint we're on and if there is any harm in updating? There are other some stylelint related packages we could check on to see if there are newer versions - https://github.com/patternfly/patternfly/blob/1a1a1a84c6e1efaa65b1b872c0aa306755b868fb/package.json#L96-L101

**Comment by redallen** [comment]
We're using 9.10.1. I see no harm in upgrading and have opened #3427.
