### ISSUE TITLE
Decrease card layout gap from 24px to 16px

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly#2958]
Missed this one with the spacing cut-down effort, we want to reduce the `grid-gap` between cards in a dashboard from 24px to 16px. Leaving the layout/page margins as they are at 24px. 

![image](https://user-images.githubusercontent.com/30935938/79231883-b9461b00-7e34-11ea-9765-d7cdea2c0fbd.png)

Related: #2653 

CC @mcoker @mattnolting @mcarrano

**Comment by mcoker** [comment]
This was addressed in https://github.com/patternfly/patternfly/pull/2962/
