### ISSUE TITLE
Update to calendar icon

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly#2966]
Our current datepicker input group uses the "fas fa-calendar-alt" icon (in React CalendarAltIcon) 
https://www.patternfly.org/v4/documentation/core/components/inputgroup#inputgroup
Based on the icon effort, we want to update our current and future use of the calendar icon to _only_ be "far fa-calendar-alt" (in React OutlinedCalendarAltIcon).

This has already been updated in the design kit as well as documented in the icons spreadsheet that will be reflected on the PF icons page

**Comment by mcoker** [comment]
Since this is `far`, and we don't ship that with core, it will need to be added to our `pficons` font. cc @bdellasc

**Comment by gdoyle1** [comment]
Ok should I leave this issue open and reference it in the font issue that Brian created? @mcoker

**Comment by mcoker** [comment]
@gdoyle1 has this since been resolved?

**Comment by gdoyle1** [comment]
@mcoker I think we should close this one in favor of the one you created on expanding how developers can pull in FAR icons! I believe that's where this landed according to the PatternFly font: Add icons, fix SVGs issue mentioned above
