### ISSUE TITLE
Expose align-center for Flex

### ISSUE THREAD

**Issue by DarrienG** [patternfly/patternfly#2976]
While I'm not totally certain, my guess is that `Flex` is based off of a `Flexbox`.

These are the properties available in a Flexbox:

```
justify-content: flex-start | flex-end | center | space-between | space-around | space-evenly
```

Of them, flex-start == align-right, flex-end == align-left and the others are reasonably easily achievable with the tools given except for `center` aligning.

Could a flexModifier `align-center` be added?

**Comment by mcoker** [comment]
@DarrienG sorry for the delay on this issue. `justify-content: center` is supported via `.pf-m-justify-content-center{-on-[breakpoint]}` in the flex layout. You can find that in the [core documentation](https://www.patternfly.org/v4/documentation/core/layouts/flex#documentation). If you're using the react `<Flex>` component, the prop is `justifyContent` and you can specify that at different breakpoints - you can read more about that in the [react documentation](https://www.patternfly.org/v4/documentation/react/layouts/flex#props). Let me know if that answers your question or if you still need help with it!

**Comment by DarrienG** [comment]
Looks good to me. Thanks for the help!
