### ISSUE TITLE
PF4 Modal: there is not class that can be used to create medium sized modals

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#2979]
Similar to pf-m-sm and pf-m-lg we would need a pf-m-md.

Our use case is that we have a lot of modals where the elements inside are configured to expand to the full width with `width: 100%`. It would be ideal to have a class to limit the max width of the modals - but pf-m-sm is too small whilist of-m-lg is too big for our examples.
We can of course can adjust the scss variables, but I was hoping for some cleaner solution by getting a pf-m-md class from you.
Is that possible?

Thanks in advance.

**Comment by mcoker** [comment]
I like it. wdyt @mceledonia @mcarrano

**Comment by mcarrano** [comment]
Makes  sense to me.
