### ISSUE TITLE
Tooltips take too long to view, don't respond to clicks

### ISSUE THREAD

**Issue by dsesami** [patternfly/patternfly#2982]
FieldTooltips take a whole 2+ seconds to show the hover text, and don't respond to clicks. This has led several people who have tried to use tooltips to think that they were broken.

![Screenshot_20200420_101926](https://user-images.githubusercontent.com/19942822/79762197-6d8de880-82f0-11ea-943c-dfd0b14a2b0a.png)

This is just an example of the pop-up hover text I am referring to. The speed which the text fades in should be increased, and maybe the tooltip should immediately pop up if clicked; this is intuitive behavior, IMO.

**Comment by unlikelyzero** [comment]
Note: the AWX PF Project has had some feedback in this area
https://github.com/ansible/awx/issues/6067
https://github.com/ansible/awx/issues/6066

**Comment by kialam** [comment]
@dsesami @unlikelyzero you can control how fast the tooltips appear and disappear on mouse over and mouse out by passing it either the [`entryDelay` and/or `exitDelay` prop. ](http://patternfly-react.surge.sh/documentation/react/components/tooltip#props)

**Comment by dsesami** [comment]
based on @kialam's advice, closing this issue and following up in the awx issues.
