### ISSUE TITLE
addition of transition effects in patternfly components

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly#2986]
This request is to add some life to patternfly components by addition transition effects such as for colors of borders and backgrounds on hover.

Perhaps there's an official design stance on why there aren't any transitions. If so please clarify.

**Comment by mcoker** [comment]
cc @mcarrano @mceledonia

**Comment by christianvogt** [comment]
bump

**Comment by mceledonia** [comment]
@christianvogt We actually have a team who have been meeting bi-weekly to discuss and move this forward. Here's our running meeting doc, happy to send you an invite if you're interested! 

To summarize: We want to add animation to enhance functionality and experience, initially with less of an emphasis on delight/ornamentation to avoid over-animating. We want our animation style to be fast/snappy/smooth to avoid power users having to wait on animations and/or having animations lag behind user action. 

We're auditing components that can most benefit from animation and transitions and starting there, all the while considering how or if we can build animation from a systematic/variable based approach. We're also trying out a few animation design tools to enable more people to actually create them.
