### ISSUE TITLE
Add an 80px spacer

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2989]
We've had a design request to add an 80px spacer for websites that desire larger padding between components. See https://github.com/patternfly/patternfly-design/issues/827 for the design discussion.

cc @mcoker @LHinson

**Comment by coreyvickery** [comment]
@mcarrano Any movement on this yet?

**Comment by mcarrano** [comment]
I believe that this is part of our current milestone. Can you confirm @mcoker ?
