### ISSUE TITLE
Progress - add warning state

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2995]
This is an update to the progress component - https://www.patternfly.org/v4/documentation/core/components/progress

The component currently supports 3 states - normal (blue), success (green), and danger (red).

This issue will add a new "warning" state (orange). A use case is for the warning state is an operation that completed with warnings.

Here is a rough draft for the implemenation: https://codepen.io/mcoker/pen/gOaLgWB?editors=1100

cc @vconzola @mcarrano

**Comment by sparsh-99** [comment]
@mcoker Can you please elaborate on your issue??

**Comment by mcoker** [comment]
@sparsh-99 I updated the issue description - let me know if any of that is still unclear or you have any other questions.

**Comment by sparsh-99** [comment]
Ok, all you are saying to add more states in progress component.

**Comment by mcoker** [comment]
@sparsh-99 correct, the issue is to add a warning state.
