### ISSUE TITLE
Nav updates - nav active border colors and others

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#2996]
https://github.com/patternfly/patternfly/pull/2978#issuecomment-617325546

> On the dark version that color is correct, but on the light version we can use the standard active color. We need it that color in dark theme for contrast requirements.

**Comment by mattnolting** [comment]
Adding @gdoyle1's comments from https://github.com/patternfly/patternfly/pull/2955

> 1. Nav group section titles should be var(--pf-global--FontWeight--semi-bold) which equals 700 weight in Sketch library
>    --> This matches to RHT medium and is the same weight as used in Application launcher, light nav and form labels
> 2. Dark nav selected items use var(--pf-global--FontWeight--normal) but should be var(--pf-global--FontWeight--bold) so it is RHT medium (unless this has changed @mceledonia ?)
