### ISSUE TITLE
Border removed once Button is disabled inside another component

### ISSUE THREAD

**Issue by nixocio** [patternfly/patternfly#2997]
When the Button prop `isDisabled` is set to True inside another component, the `border` of Button is removed.

![border_button](https://user-images.githubusercontent.com/9053044/79913343-6ef30a00-83f1-11ea-8b46-418f8c909e6d.gif)

PF Version

```text
    "@patternfly/patternfly": "^2.71.3",
    "@patternfly/react-core": "^3.153.3",
    "@patternfly/react-icons": "^3.15.15",
    "@patternfly/react-tokens": "^2.8.12",
    "ansi-to-html": "^0.6.11",
```

**Comment by mcoker** [comment]
cc @mcarrano, this is a result of the control button's disabled state styling

**Comment by mcarrano** [comment]
It does seem odd @mcoker Can you recall why we did that? cc @mceledonia

**Comment by mcoker** [comment]
@mcarrano nevermind, we have an issue where we're going to update that styling that we will get in this milestone - https://github.com/patternfly/patternfly/issues/2701

**Comment by mcoker** [comment]
Hi @nixocio! Just wanted to follow up on this and say that we have updates coming to the button's disabled state that should resolve this issue. The PR is https://github.com/patternfly/patternfly/pull/3049, and I have put together a demo that shows how that update would in the use case you reported in this issue. https://codepen.io/mcoker/pen/xxwpeEa

Do you mind looking that over and letting me know if that works as you would expect it?

**Comment by nixocio** [comment]
hi @mcoker, thanks for working on this. I will take a look.

**Comment by nixocio** [comment]
It seems to be fixed! 

![search_icon_fixed](https://user-images.githubusercontent.com/9053044/81195081-60792680-8f8b-11ea-960e-40fd8d85255e.gif)

**Comment by mcoker** [comment]
@nixocio great, thanks for verifying! This new design will be available in our upcoming v4 release. If you need the design now, you can use the CSS I provided in the codepen to set the `border-radius` and disabled `background-color`.

**Comment by mcoker** [comment]
resolved via https://github.com/patternfly/patternfly/pull/3049
