### ISSUE TITLE
Progress label issues

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly#3002]
**Describe the issue. What is the expected and unexpected behavior?**

1) **Missing text-align**

When a long label is used in the progress component, it looks like `text-align` is changed from right to left:

![image](https://user-images.githubusercontent.com/32869456/78646594-91e1d200-78b9-11ea-83bb-546feb334007.png)

```jsx
<>
<Progress value={2} title="Title" min={0} max={5} label="Short label" valueText="Short label" />
<Progress value={2} title=" cgfdgfdg" min={0} max={5} label="Very looooooooooooooooooooo ddsfsf dsfdsfdsfdsdsfsddsfdsfoooddoooooooooooooooooooooooongLabel" />
</>
```

It is because the text is not actually aligned, the element is only moved by flex to end.

2) **Wrapping long labels**

![image](https://user-images.githubusercontent.com/32869456/78646754-d1a8b980-78b9-11ea-814b-669ced2c62de.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

1. go to demo
2. put a long label

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug. 

Workaroud: custom css styles

**What is your product and what release version are you targeting?**

Sources UI

**Comment by mcoker** [comment]
@mcarrano @mceledonia could you advise on how the left/right labels should align with a lot of text? Here's how they look currently with more text in either/both sections.

Text on the left
<img width="1020" alt="Screen Shot 2020-08-24 at 4 09 59 PM" src="https://user-images.githubusercontent.com/35148959/91096959-7c7d0280-e624-11ea-98a8-64f3c2bb8ba2.png">

Text in both sections
<img width="1018" alt="Screen Shot 2020-08-24 at 4 10 26 PM" src="https://user-images.githubusercontent.com/35148959/91096953-7ab33f00-e624-11ea-9080-743336de15ef.png">

Text on the right
<img width="1021" alt="Screen Shot 2020-08-24 at 4 10 13 PM" src="https://user-images.githubusercontent.com/35148959/91096956-7c7d0280-e624-11ea-938e-0d86d8b784be.png">

Also @rvsia can you include a design of your use case where you're experiencing this issue? It would help us understand how to adjust the layout and we may have feedback about how to best add content to the progress component.

**Comment by mcoker** [comment]
@rvsia there is a PR here if you would like to review it to confirm it will solve your issue - https://github.com/patternfly/patternfly/pull/3436

**Comment by rvsia** [comment]
@mcoker hey, thanks for the update! Unfortunately, we are no longer using the progress component in our product, but these changes make sense to me.
