### ISSUE TITLE
General CSS updates

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3010]
Per @gdoyle1's feedback - https://github.com/patternfly/patternfly/pull/2955#issuecomment-614111236

Differences btwn code and sketch library:
I assume the following needs to be updated in code

* ~~Nav group section titles should be var(--pf-global--FontWeight--semi-bold) which equals 700 weight in Sketch library~~ - confirmed title text should be normal
  * --> This matches to RHT medium and is the same weight as used in Application launcher, light nav and form labels
* ~~Dark nav selected items use var(--pf-global--FontWeight--normal) but should be var(--pf-global--FontWeight--bold) so it is RHT medium (unless this has changed @mceledonia ?)~~ confirmed font weight should never change with a state change
* ~~Empty state titles are var(--pf-global--FontWeight--normal) but should be RHD medium... it looks like they are RHD regular in this PR~~ we are only using one font now, so this has been updated to RHT bold
  * --> Sketch library has them as RHD medium
* Pagination options menu items are using both 16px and 14px text - the full option should be 16px text and all black text. Also the pagination options menu toggle in general has some weird spacing going on --> Sketch library has menu items as 16px and all black text

cc: @mcarrano @mcoker

**Comment by mcoker** [comment]
@gdoyle1 @mceledonia 

> Nav group section titles should be var(--pf-global--FontWeight--semi-bold) which equals 700 weight in Sketch library

Just to verify, does this mean that the font-weight should be 500 in overpass and 700 in RHT?

Per the new designs (https://marvelapp.com/21a8a2g6/screen/66437066), the title looks regular font weight.

> Dark nav selected items use var(--pf-global--FontWeight--normal) but should be var(--pf-global--FontWeight--bold) so it is RHT medium (unless this has changed @mceledonia ?)

Per the new designs from https://github.com/patternfly/patternfly/issues/2650 ([expanded links](https://marvelapp.com/21a8a2g6/screen/66466643), [top-level links](https://marvelapp.com/21a8a2g6/screen/66466531), [grouped links](https://marvelapp.com/21a8a2g6/screen/66437062)), everything is normal font-weight.

> Empty state titles are var(--pf-global--FontWeight--normal) but should be RHD medium... it looks like they are RHD regular in this PR

You can see here in the webfont source files that RHD regular is font-weight 300, and RHD medium is font-weight 400.

https://github.com/RedHatOfficial/RedHatFont/blob/455894397368a416491cabdb353223656340fd85/webfonts/red-hat-font.css#L1-L21

We don't use RHD regular (300) as far as I'm aware. You can see in patternfly that `--pf-global--FontWeight--normal` is 400:

https://github.com/patternfly/patternfly/blob/11497ba463924b59b586b033d87625810c3c7b52/src/patternfly/sass-utilities/scss-variables.scss#L214

And here's a screenshot from what I'm seeing in the empty state component (RHD 400)

<img width="1131" alt="Screen Shot 2020-04-22 at 8 14 05 PM" src="https://user-images.githubusercontent.com/35148959/80048570-2c572d80-84d6-11ea-9229-f8cd3ce1dba0.png">

> Pagination options menu items are using both 16px and 14px text - the full option should be 16px text and all black text. Also the pagination options menu toggle in general has some weird spacing going on --> Sketch library has menu items as 16px and all black text

The small/grey font was added to match designs at some point via https://github.com/patternfly/patternfly/issues/1666. But I'd love to remove it if we can and just use the options menu component as it is there.

Just to confirm, you're saying the menu items (and toggle spacing) should look like this?

<img width="453" alt="Screen Shot 2020-04-22 at 8 26 10 PM" src="https://user-images.githubusercontent.com/35148959/80049083-9a502480-84d7-11ea-8103-24dad35b7c1e.png">

as oppposed to this?

<img width="420" alt="Screen Shot 2020-04-22 at 8 26 15 PM" src="https://user-images.githubusercontent.com/35148959/80049088-a0460580-84d7-11ea-87df-09c8e5be02c4.png">

**Comment by gdoyle1** [comment]
@mcoker Discussed in Slack ...
1. TBD on the group nav text style
2. Yes you're right - selected items should be normal weight!
3. Idk what I was seeing in Empty states before but that looks normal so ignore what I said (sorry)
4.  Pagination screenshot looks perfect
