### ISSUE TITLE
Tab Content Positioning for vertical tabs

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly#3030]
It would beneficial for consumers if there was a style that they could apply to the Tab content that would position it next to the tabs when the Tab buttons are vertical.  Right now the Tab content get placed right below the Tabs.

cc @mattnolting

**Comment by mcoker** [comment]
We would need some kind of parent container for the tabs and tab content components. I would expect someone to use one of our layouts, like the split or flex layout. Maybe this could be solved with a demo? wdyt @tlabaj 

cc @mcarrano

**Comment by mcarrano** [comment]
We do have an open issue to create some layouts for Tab demos here: https://github.com/patternfly/patternfly-design/issues/853 Maybe this should be addressed as part of that issue?

**Comment by mcoker** [comment]
@mcarrano yes, I'm OK with closing this issue and addressing this once https://github.com/patternfly/patternfly-design/issues/853 is resolved assuming we'll have a demo  for vertical tabs.
