### ISSUE TITLE
Add toolbar and pagination to demos

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3040]
In https://github.com/patternfly/patternfly/pull/3039 we removed the legacy toolbar component from the following demos that we should add back

* Removes the toolbar & pagination from card view demo
  * Basic toolbar and pagination
* Removes toolbar & pagination from data-list demo
  * Basic toolbar and pagination all demos
  * no pagination demo
  * compact pagination demo
* Removes toolbar & pagination from table demos
  * Basic toolbar & pagination on all demos
  * compact pagination demo
  * column management dropdown
  * column management action

cc @mcarrano

**Comment by mcarrano** [comment]
I will add this to the feature roadmap.
