### ISSUE TITLE
accessibility documentation for aria-pressed on toggles

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#3041]
Related to this PR #3038 and this issue #3011, when we were removing the workspace styles for `pf-m-hover`, `pf-m-focus`, `pf-m-active`, and `pf-m-disabled` we kept the `pf-m-active` that was set on elements like buttons and toggles across multiple components. @mcoker discovered that these were necessary to force the styling of that element in the `:active` state.

The button component references in the documentation: `aria-pressed="true or false"` "Indicates that the button is a toggle. When set to "true", `pf-m-active` should also be set so that the button displays in an active state. **Required when button is a toggle** " 

None of the other components include a reference to `aria-pressed` but we are wondering since now we are intentionally leaving in `pf-m-active`, if `aria-pressed` is required for all of these toggle elements?

@jessiehuff do you have any recommendations?

**Comment by jessiehuff** [comment]
Hey @christiemolloy! I think the big thing to note here is that there's not necessarily a one-to-one mapping between this class and `aria-pressed`. Looking at issue #3011, those examples would all actually map to `aria-expanded.` When describing if `aria-pressed` is necessary, I'd say it's when something toggles an on/off state. An example would be if you had a toolbar with a button in it that bolded text. When you press the button, you can toggle between bolded or normal text. I would consider that an on/off state. Often the term "toggle" is used to talk about opening or expanding something as well. However, a dropdown, select, app launcher, etc. is more of an expanded state. You would be expanding a menu or list of options. It can be a little tricky, especially with the mixing of terminology that can confuse the two.
