### ISSUE TITLE
The last button in a data list item has different alignment styling

### ISSUE THREAD

**Issue by dsesami** [patternfly/patternfly#3059]
![download](https://user-images.githubusercontent.com/19942822/81002581-77970780-8e17-11ea-9d0a-4608ade8e2d2.png)

Whenever you have multiple buttons in a row here, starting at <993px screen size, the last action button has a different alignment.

Relevant AWX code snippet that renders that button is here: https://github.com/ansible/awx/blob/008cd9985a27c8e39ac15303462a4421aac32992/awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.jsx#L96

**Comment by AlexSCorey** [comment]
The !last items get `margin-bottom: var(--pf-c-data-list__item-action--not-last-child--lg--MarginBottom);` or `margin-right: var(--pf-c-data-list__item-action--not-last-child--lg--MarginBottom);` when `@media-screen(max-width: 992px)`

**Comment by mattnolting** [comment]
Fixed by breaking change release
