### ISSUE TITLE
Fix - Select borders

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3076]
Select bottom border, when expanded, is beveled and disrupts visual spacing. This is result of having multiple `border-width`s on the select. In other components with similar presentation, we split the borders with `::before` and `::after` pseudos. 

![Screen Shot 2020-05-07 at 9 02 09 AM](https://user-images.githubusercontent.com/5385435/81297696-ab557580-9041-11ea-9325-e1032d09e323.png)

Also, margining is visually affected by a thicker bottom border, this could be fixed by offsetting the bottom border.

One solution could be: 
```
.pf-c-select__toggle {
  &::before,
  &::after {
    positioning, border styles, shared stuff
  }

  &::before {
    static border styling
  }

  &::after {
    border-color, etc
    top: calc(100% + var(--pf-c-select__toggle--after--BorderBottomWidth)); // shouldn't disrupt z-indexing
  }
}
```

**Comment by mcoker** [comment]
keep open
