### ISSUE TITLE
pf-c-page is sometimes limited in height for no apparent reason

### ISSUE THREAD

**Issue by Rudi3** [patternfly/patternfly#3082]
Example: [https://k0jtu.csb.app/](https://k0jtu.csb.app/) (from official patternfly examples)

`pf-c-page` is only `571px` high even though my viewport is larger (for example 1500x1000); tested on multiple browsers.

It also happens in my own test application, possibly when the content is smaller than the viewport!?

**Comment by mcoker** [comment]
Hi @Rudi3, all of the ancestor elements of `<Page>`/`.pf-c-page` up to the `<body>` element need `height: 100%;`. In the example you posted, you just need to add `#root { height: 100%; }`.

This is mentioned in the [Page layout demos](https://www.patternfly.org/v4/documentation/react/demos/pagelayout#component-title).

**Comment by Rudi3** [comment]
I see. I missed that. Thank you! I guess it's not really a big problem with the demo if it's mentioned.
