### ISSUE TITLE
Text in the chip is getting cut off

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#3083]
Because we set `overflow: hidden` on `pf-c-chip__text`the text is being cut off on the y-axis. I wonder if we could look into a way to only set `overflow: hidden` on the x-axis.

Related to #3079

<img width="327" alt="Screen Shot 2020-05-08 at 9 20 22 AM" src="https://user-images.githubusercontent.com/20118816/81409881-e624df80-910d-11ea-876f-3acf280a8272.png">

**Comment by mcoker** [comment]
Can you still reproduce this? I'm not seeing it

<img width="140" alt="Screen Shot 2020-05-12 at 6 03 19 PM" src="https://user-images.githubusercontent.com/35148959/81754108-f1b03780-947a-11ea-8b4e-a2123380fb0c.png">

**Comment by christiemolloy** [comment]
Yeah I can't see it anymore, will close the issue :)

**Comment by mcoker** [comment]
Looks like it's happening in the select typeahead, and it's due to the `line-height` on `chip-group__list-item`

**Comment by mcoker** [comment]
<img width="270" alt="Screen Shot 2020-05-13 at 6 36 29 PM" src="https://user-images.githubusercontent.com/35148959/81876639-c8f67380-9548-11ea-8006-b26d5a582aad.png">
