### ISSUE TITLE
Box Component

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#31]
* Review what has been introduced and update to match current conventions
* Document

**Comment by cliffpyles** [comment]
https://github.com/patternfly/patternfly-next/pull/38

**Comment by jennyhaines** [comment]
@cliffpyles -

Here is a basic card design to work from with the spacers in place. I am working on different sizes right now for the cards and will post once I have them!

![cards-basicdesign](https://user-images.githubusercontent.com/24898297/37732441-63f2f7b6-2d1b-11e8-9b4e-aeaef163dcc8.png)

**Comment by mcarrano** [comment]
@LHinson why are we changing the name of this from Card to Box? We refer to cards in many places in our documentation (i.e. card view, dashboard cards) so I'm concerned that renaming this will confuse PF users.

**Comment by LHinson** [comment]
@mcarrano my understanding is that "box" has defined styles and spacing that can be used for various components such as card, modal, etc. So we will still have the idea of "card" but a card is created by using the box component. 

That said, let's add this to the -next design agenda to talk though and get on the same page.

**Comment by mcarrano** [comment]
Per the Apr 26 Design Meeting, some clarification is needed around what a Box is and what it is used for. To follow up on this (and based on discussion) I offer the following definition:

A Box is a generic rectangular container that can be used to build a variety of other components (patterns?). A Box is a rectangular element that has the following attributes:
* A margin that describes the spacing around the box
* A border style, i.e. border color, shadow, etc
* Some padding between the border and the content of the box
* Box content that populates the interior of the box
* The size of a Box can be variable and is driven by it's content

The Box itself should be agnostic of it's content. Examples of usage of a Box include, but are not limited to cards (dashboard cards and others), dialogs, and alerts.

@andresgalante please review and comment on this definition. Is this consistent with your definition of what a box is? Does the current visual design provide enough information to move forward with this?

**Comment by srambach** [comment]
A couple of questions - 
- We've made the rule that margins are set by the container of the component. So I can't really put a margin on a box; it would have to go on the thing that's placing the boxes, like a gallery layout via its gutter.
- @jennyhaines I don't see any border styles defined in the mockup - is there a definition for these?
- For the purpose of this component, I assume that content of the box is not differentiated to something like title, main content, footer, etc - these would be parts of a card, which is a type of box but is not included in this task? Please correct me if I'm wrong.
@andresgalante @LHinson @mcarrano

**Comment by jennyhaines** [comment]
@srambach - there is no border style for cards, but cards should have the CSS-defined small box shadow by default, and medium box shadow on hover. (pf-global--sm--BoxShadow and pf-global--md--BoxShadow)

**Comment by srambach** [comment]
Per discussion with @andresgalante, I'll create the generic skeleton box/card that will contain a header, body, and footer. I'll talk with @kybaker to figure out the next steps to flesh out how the varying content that we think of as card variations fits into the skeleton.

**Comment by dgutride** [comment]
Closed via https://github.com/patternfly/patternfly-next/pull/217
