### ISSUE TITLE
Progress bar styling does not match sketch library

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly#3106]
The colors for the success bar in the documentation here: https://www.patternfly.org/v4/documentation/react/components/progress does not match the color in the sketch library. The version in the sketch library is a darker green.

![image](https://user-images.githubusercontent.com/23172038/81826609-f837c100-9505-11ea-877b-90b5b2d5d4a7.png)

It appears that the layer style color is incorrect (or the documentation is incorrect)

![image](https://user-images.githubusercontent.com/23172038/81826778-1ef5f780-9506-11ea-84db-05c7a88e6436.png)

cc @gdoyle1

**Comment by mcoker** [comment]
Hey @katierik, we updated `$pf-global--success-color--100` (`$pf-color-green-500`) to `#3e8635`  in https://github.com/patternfly/patternfly/pull/2817, which will be available in the v4 release.

You can verify that in the v4 staging site - http://patternfly-v4.surge.sh/documentation/core/components/progress

**Comment by gdoyle1** [comment]
@katierik @mcoker The design kit has already implemented those colors changes, but you'll see them in the newest release! I spoke with Katie offline about this and we verified that if her devs are using that variable `$pf-global--success-color--100`, then it will update once PF does

**Comment by mcoker** [comment]
@katierik can you verify if this is still an issue? https://pf4.patternfly.org/documentation/core/components/progress

**Comment by katierik** [comment]
Good to close!

**Comment by katierik** [comment]
Good to close!
