### ISSUE TITLE
Investigate impact of increasing line height + fixed width of icons to 24px across components

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly#3107]
We recently discovered a disconnect between design and implementation regarding icons. Design was assuming a 24px line height (+width) box around each icon, where in implementation the line height is 1em which for our standard size is 16px, and the width is the width of the icon itself.

We want to investigate the impact of changing to 24px line height/width would have across components so we can best determine a path forwards toward alignment.

The purpose of the 24px bounding box is to align well with our base font line height, allowing text, buttons, inputs, etc. all align well on the same line with icons when present. 

The end goal of this spike is to align design + implementation, whether it means design aligning with implementation or vice versa. The end goal of the approach we'd determine is to have an icon implementation which makes it seamless for our base size icons to align with text/buttons/inputs/etc. when on the same line.

Some key components to note:

- Alerts
- Icon Button
- Link Button
- Chips + Chip Group
- Clipboard Copy
- Data Toolbar
- Dropdown (caret spacing)
- Input groups
- Label
- Pagination

If we can get a navigable copy of the system with the change I'm happy to do the audit of the components. 

CC @mcoker @bdellasc @gdoyle1 @mcarrano

**Comment by bdellasc** [comment]
@mceledonia This issue was fixed with the latest icon updates.

CC: @mcoker @evwilkin @gdoyle1

**Comment by evwilkin** [comment]
Resolved in https://github.com/patternfly/patternfly/pull/3398
