### ISSUE TITLE
Search form control input doesn't support readonly, disabled, aria-invalid="true", or pf-m-success

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3117]
Seems like the form control should support `readonly` and `disabled` at a minimum. 

@mcarrano can you verify:

* If the form control is readonly or disabled, should the search icon remain in the input, or should the text input just take on the default readonly/disabled styling?
* Should the search input support the success and error/invalid states? Not sure if that's a valid use case of that type of input.

**Comment by mcarrano** [comment]
@mcoker Disabled makes sense, but not sure why we would ever want a 'read-only' search input. Also not sure what success would mean, but it's possible that someone might validate the contents of a search field if there were specific constraints, e.g. spaces or special characters are not allowed, etc. Are these new states an "ask" from someone?

IMO the search icon should remain if the field is disabled, but maybe go gray?

**Comment by mcoker** [comment]
@mcarrano no one is asking for them yet, they're just bugs we found in testing.

**Comment by mcoker** [comment]
Supports disabled now. Can revisit if use cases for the other states come up.
