### ISSUE TITLE
Drawer: Hidden drawer becomes visible by tabbing through the page.

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly#3129]
**Describe the issue. What is the expected and unexpected behavior?**
A drawer component with a drawer panel in the hidden state will become visible if you add a component to that panel, and tab through the page to all focusable components. The hidden panel should not become visible.
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

You can add a button to the drawer panel in the example code on the react site, and reproduce the bug by tabbing through the example page. The hidden drawer panel will appear when the focus reaches the component residing on the panel.
**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**
Exists in openshift 4.4.

**Comment by jcaianirh** [comment]
@mcoker  We have a bug fix sprint ending May 29, would this bugfix make it into react by then? This would be for a fix in master and not v4 breaking changes for react.

**Comment by mcoker** [comment]
Hey @jcaianirh, with everyone wrapping up the v4 release, I don't think we'll be able to do a v3 release before 5/29. Do you have a workaround you can apply in the interim? I'm happy to work with you on one if you need.

**Comment by jcaianirh** [comment]
@mcoker thanks for the info. The bug was pushed out officially based on your info above, but lets chat and see if there is a solution that might be simple enough to implement and not cause regressions...if so we may be able to close it and then readdress after the official pf fix is ready.
