### ISSUE TITLE
Box tabs enhancement for screens with gray content backgrounds

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly#3150]
Can we have an option to reverse the box tab colors for those using a gray background in their content area? The new box tabs give a gray fill to the unselected tabs, which makes them look like they are selected when the content area is below is also gray. 

<img width="666" alt="Screen Shot 2020-06-01 at 10 14 05 PM" src="https://user-images.githubusercontent.com/46571616/83526838-0057a080-a4b5-11ea-8e43-654b137daaf1.png">

I think having an option to reverse the colors would connect the active tab to the content area much better when gray bkgs are in use (See Apicurio example below). 

<img width="708" alt="Screen Shot 2020-05-29 at 11 00 33 AM" src="https://user-images.githubusercontent.com/46571616/83526837-0057a080-a4b5-11ea-82fc-87b9cce441be.png">

**Comment by mcoker** [comment]
@lboehling yep no problem. Is there a timeframe you're aiming to see this done by?

cc @mcarrano @mceledonia

**Comment by lboehling** [comment]
@mcoker no rush for this, we can also use the new open tab styling here if we need to. 

I still feel like this may be a common use case (especially for card views!) What do you think @mcarrano?

**Comment by mcarrano** [comment]
I like the idea of this because It's always been problematic where the boxed tabs don't match the content background. It would be good to have a more flexible solution. @LHinson can we get this somewhere on the roadmap?
