### ISSUE TITLE
Custom Search input component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3151]
Want to introduce a custom search input that includes the following features:

* Ability to clear the field with a single click.
* Ability to display the number of matches has the user types.
* Can be used in search or find use cases. When used as a find widget, the user will be able to navigate through matches using navigation embedded into the field.

Designs: (see design links posted by @maryshak1996 below.

**Examples needed**

1. Basic - search field that includes a clear button
2. Search field with badge - adds optional badge to reflect search results
3. Find field - find variant that includes navigation buttons

**Comment by maryshak1996** [comment]
### Design files
Marvel: https://marvelapp.com/e9ge7g7
Sketch: https://www.sketch.com/s/10959c66-4198-42c3-b0cd-ca79d19d21a6

**Comment by mcarrano** [comment]
@mcoker @LHinson I have opened this issue that addresses three separate design requests as referenced above. Through doing the design work, we realized that introducing this custom search component would be the best way to provide this functionality. I have also updated the roadmap to reflect this.
