### ISSUE TITLE
Investigate best way to associate modal forms with buttons in modal footer

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3153]
https://github.com/patternfly/patternfly-react/issues/3397

When a `<form>` exists in the modal body, what is the best way to associate `<button>`s in the modal footer with the form?

One way is to use the `form` attribute on the `button` element. https://codepen.io/mcoker/pen/GRoRJQX

Let's investigate different ways to do this and make a recommendation.

**Comment by nicolethoen** [comment]
I think this may still need to be addressed before this react issue can be done. https://github.com/patternfly/patternfly-react/issues/3397
