### ISSUE TITLE
Split Layout in Table Cell & Switch Button

### ISSUE THREAD

**Issue by alexfdezsauco** [patternfly/patternfly#3160]
I have an issue with using the  Split layout in a table cell with buttons and switch.

Here is the repro: https://blorc-patternfly.wildgums.com/components/table 

int the "Action Column Table (Buttons)" demo.

Any clue?

![image](https://user-images.githubusercontent.com/1785664/83973427-409f9000-a8b4-11ea-841a-a3bd241063e3.png)

**Comment by mcoker** [comment]
Hi @alexfdezsauco, what is the design you're trying to achieve?

**Comment by alexfdezsauco** [comment]
I just want to split a cell with an Split Layout. But when I put the Switch into an SplitItem the Switch is not render correctly. Looks like the SplitItem doesn't expand correctly.

**Comment by mcoker** [comment]
@alexfdezsauco sorry for the delay in responding.In this instance, I would apply the CSS `white-space: nowrap;` to that switch component, or even to the parent split layout as none of the elements in this layout should wrap like that.
