### ISSUE TITLE
popover timing

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#3179]
The animation for the popover is a bit strange. You can see the Block that defines the pointer on the popover stay longer than the rest of the popover once it's been dismissed. Please appreciate how hard it was to get a screenshot of this :) :) :)
<img width="228" alt="Screen Shot 2020-06-11 at 3 39 04 PM" src="https://user-images.githubusercontent.com/287880/84426477-b16ae300-abf9-11ea-8111-b6f27ebe20c0.png">

**Comment by mcoker** [comment]
This has to do with the react library, which is where the transitions are defined. @jschuler is working on this in https://github.com/patternfly/patternfly-react/issues/3722
