### ISSUE TITLE
ChipGroups: close chip group button wraps at smaller widths

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#3182]
Reproducible in the React Toolbar documentation for the Toolbar with filters example.

![image](https://user-images.githubusercontent.com/26305082/84826508-08edc200-aff1-11ea-945c-3e4fd1c6dd84.png)

![image](https://user-images.githubusercontent.com/26305082/84826308-c330f980-aff0-11ea-884a-d7fe80e58f20.png)

**Comment by mcoker** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@nicolethoen @mcoker Is it possible to make this so the chip group collapses when it runs out of space like this rather than wraps?

**Comment by nicolethoen** [comment]
@mcarrano There is already a breakpoint that exists that will default to 'xl' but that the consumer can control that chooses when the chip groups all collapse.

**Comment by mceledonia** [comment]
Just chiming in here - I think our solution should be in the realm of the X / clear actions always being given priority over chips, i.e. chips should start dropping/truncating rather than the close actions moving.
