### ISSUE TITLE
New focus state in chrome affects "Selectable" Data List component 

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#3204]
The new focus state is affecting the focus state for the selectable data list component. See PF screenshot and product screenshot:

<img width="1042" alt="Screen Shot 2020-06-22 at 2 36 44 PM" src="https://user-images.githubusercontent.com/20118816/85323391-ea2a7800-b495-11ea-9265-d3ad58a25f14.png">
<img width="1130" alt="Screen Shot 2020-06-22 at 2 36 51 PM" src="https://user-images.githubusercontent.com/20118816/85323394-eac30e80-b495-11ea-8171-80c012abdf9c.png">

**Comment by mcoker** [comment]
related https://github.com/patternfly/patternfly/issues/3131
