### ISSUE TITLE
Audit/review global variable usage

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3211]
I would like to review our global vars with design to identify the current vars, how they're implemented, identify any gaps/changes needed just in general but also in the context of upcoming theming stories see and if our global vars need to be updated to support those scenarios. 

cc @mcarrano @mceledonia

**Comment by mceledonia** [comment]
Agreed, I'd like to get this done before getting too far along with the theming effort implementation.

**Comment by mcoker** [comment]
Closing for now for our weekly meetings.
