### ISSUE TITLE
Can we start validating HTML

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly#3223]
Go to any page within the documentation site, copy the generated HTML from the DOM and run it through an [HTML validator](https://validator.w3.org/nu/#textarea) of your choice, you'll find that we have a surprising number of errors.

- Many of these errors are duplicate of the same issue across many elements
- Many of the errors stem from the documentation site and not necessarily the components themselves
- Many of these errors lead to other errors

<img width="400" alt="Screen Shot 2020-06-29 at 2 51 24 PM" src="https://user-images.githubusercontent.com/5942899/86044568-3f2b3880-ba18-11ea-868d-d189053b51f9.png">

We can improve the quality of the framework by adding some aspect to our development process to check for these types of errors. Is it something we can do? Should it be a general requirement that the HTML produced from core be valid according the HTML5 specification in general? How about the docs site? I think they'll both have their own unrelated issues.

I'm happy to help build a solution for this if needed, just let me know!

**Comment by mcoker** [comment]
@redallen and @jschuler added `lint:hbs` and I remember there was HTML validation, but I think that's still being worked on? https://github.com/patternfly/patternfly/pull/2894

**Comment by redallen** [comment]
`lint:hbs` used to find missing closing tags in our HTML while generating workspace snippets. I refactored it in #2894 in favor of a direct `yarn gulp snippets` which better ties into our HTML build process. It is currently passing.

I think that checker is rather strict. It says https://google.com has 101 site problems...
![image](https://user-images.githubusercontent.com/47335686/86046850-f2496100-ba1b-11ea-883b-9b22ad2dd2cb.png)

And it also notes:
> This tool is an ongoing experiment in better HTML checking, and its behavior remains subject to change

I looked for good HTML validation packages on NPM to replace `lint:hbs` and could not find any after trying a few. The nu checker is an [open source Java program](https://github.com/validator/validator/tree/20.3.16) that we might potentially be able to get working but would take substantial effort.

**Comment by seanforyou23** [comment]
Good stuff, thanks for catching me up! In case a CI job is difficult to achieve, we could simply spot-check pages to get the benefit without the overhead. It's easy to pick through the flagged errors and identify ones we feel are relevant and worth addressing. The main point is about validating the HTML and less about the CI part of it (I'll update the issue description to make this more clear).

> This tool is an ongoing experiment in better HTML checking, and its behavior remains subject to change

Yes, this disclaimer has been there for a very long time. I've used it a lot over the years and the developer experience is actually quite nice. You get the common "Suppressing further errors from this subtree" error at points where it's impossible to determine the exact number of actual errors because it doesn't know, given the piece of DOM in question, which validation rules to apply to certain child nodes because it's in error state. You work your way through these like layers of an onion and often many further errors are later revealed as you fix the errors from the outer DOM parts. From my experience, they usually end up all having simple and logical explanations that aren't too hard to fix and ultimately make the software better. This is also useful when you have competing implementation approaches and are trying to decide between one or the other. If only one implementation is involves valid HTML, it tends to help move the conversation along..

What do people think about the value of engaging in this effort in general though? For the entire component-suite and or docs site, it will surely generate some work items to be addressed so I wanted to be conscious of this and ask, do we feel it's worth doing in the first place?

No is an acceptable answer 😛

**Comment by mcoker** [comment]
I'm definitely in favor! In the example above, we're using `<div>`s in `<button>`s, which is invalid and something we need to fix. These tools go a long way in enabling and helping us write better code.
