### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly#3227]
We should change the naming of our main branches across all of PatternFly from master to main.

**Comment by seanforyou23** [comment]
Could we consider the name `default` as the main branch instead? It aligns with Mercurial SCM and might be more familiar/intuitive than `main`.

**Comment by evwilkin** [comment]
Updated recommendation from Github: https://github.com/github/renaming

**Comment by evwilkin** [comment]
Update 9/21 - Github to rename new repos to `main` starting next month, provide steps for updating existing repos to by EOY: https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

**Comment by evwilkin** [comment]
We're planning on making the switch to `main` when Github provides an automated process for this, sometime before the end of the year.

**Comment by mcoker** [comment]
@redallen ok to close now?

**Comment by redallen** [comment]
Yep! Finished renaming yesterday.
