### ISSUE TITLE
Enhancement(Text): Add size & color mods to Text component

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly#3246]
This request is to add size and color modifications to the Text component, stemming from a user request to be able to easily update the font color:

![Screen Shot 2020-07-06 at 9 53 03 AM](https://user-images.githubusercontent.com/8651509/86600810-8d878c80-bf6e-11ea-800e-cdb3ef975e1d.png)

**Comment by mattnolting** [comment]
Should consider adding `.pf-m-truncate, -break-word, -nowrap, -wrap, -fit-content` to this.

**Comment by mattnolting** [comment]
@mcoker @mnolting @jenny-s51 @mcarrano After discussion, probably best to flesh out this solution before moving forward. 

We discussed 
- Making utilities for 
-- `pf-u-font-size-`
-- `pf-u-font-weight-`
-- `pf-u-font-color-`
-- `pf-u-background-color-`
- Allowing react components to access global variables

**Comment by mcoker** [comment]
I wonder if `text` would be a better utility name, since it includes things that aren't necessarily font properties (truncation, wrapping, etc)

**Comment by mceledonia** [comment]
@maryshak1996 @mcarrano These look good to me!
