### ISSUE TITLE
Bug(Model demo): modal demo text is overlapping and cutoff

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly#3252]
The [Core modal demo](https://www.patternfly.org/v4/documentation/core/demos/modal) is not displaying the text content correctly, see screenshot
<img width="605" alt="Screen Shot 2020-07-06 at 4 16 09 PM" src="https://user-images.githubusercontent.com/8651509/86635431-115a6c80-bfa1-11ea-95d0-2c7ba5a15c54.png">

**Comment by mcoker** [comment]
fixed in https://github.com/patternfly/patternfly/pull/3217/
