### ISSUE TITLE
Setting font-size on html tag causing very hard to solve bugs

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly#3254]
https://github.com/patternfly/patternfly/blob/3678127f4ec1910f1f08edc748063cfe0095c256/src/patternfly/base/_common.scss#L17

Got asked for help on a CSS issue that relates to this line of CSS. This is an extremely strong choice that should be made by the site owner, not a framework that may be included as one of many.

Could it be made so a build flag lets the SCSS now if it's a full page experience or a page component (in which case it shouldn't be setting anything global)

**Comment by mcoker** [comment]
@wesruv agree, this is something that should probably be part of the global reset, which can be excluded via `$pf-global--enable-reset: false;` or by using `@patternfly/patternfly/patternfly-no-reset.css`. However, excluding this block if the reset is excluded would be a breaking change, so for now I've added a flag to exclude this line in this PR - https://github.com/patternfly/patternfly/pull/3275. And we can move that block so it's part of the global reset in a breaking change release. Will that work for you?

**Comment by wesruv** [comment]
Sounds good to me! Thanks for the fast response!
