### ISSUE TITLE
In page wizard - wizard body should scroll, not the entire wizard

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3255]
In our in page wizard demos, the page scrolls normally, so the entire wizard scrolls if the wizard content exceeds the available height. The wizard should fill the available space and any overflow in the navigation or body should scroll independently in those individual sections, and the footer should be sticky to the bottom of the body section.

Looks like `.pf-c-page__main-wizard` just needs `min-height: 0;` for it to work properly.

I didn't see a react demo for an in page wizard, so we should verify using `.pf-c-page__main-wizard` is the ideal way to include a wizard in the page. If it would require a user specify the wizard section instead of a regular section, and that might lead to inconsistencies, we may also consider adding `min-height: 0;` to `.pf-c-page__main-section` so that the wizard will work in a regular section.
  * That would remove the border we apply to `.pf-c-page__main-wizard`, but if we add `flex-shrink: 0;` to the divider (which seems reasonable), then a horizontal divider could be used there to create the border.

We need to create a follow-up issue in react to create an in page wizard demo once this is sorted out.

related - https://github.com/patternfly/patternfly-design/issues/888

**Comment by matthewcarleton** [comment]
@mcarrano can we prioritize this again? We would benefit from it on the OpenShift side.

**Comment by mcarrano** [comment]
@matthewcarleton this is currently on the roadmap for February 2021. Will that work?

**Comment by matthewcarleton** [comment]
thanks @mcarrano that works - just confirming it hadn't slipped :)

**Comment by DaoDaoNoCode** [comment]
@mcoker Hi, I tried to add `min-height: 0` to `.pf-c-page__main-wizard` or `.pf-c-page__main-section` to try to fix this, but it doesn't work. Do you know why this happens?

**Comment by mcoker** [comment]
@DaoDaoNoCode try also adding `flex-shrink: 1;`. I have a codepen with a demo here - https://codepen.io/mcoker/pen/XWjvVBq

**Comment by DaoDaoNoCode** [comment]
@mcoker It looks good! And it seems that we can also get rid of `.pf-c-page__main-wizard` right? I see you use `.pf-m-wizard` instead. I believe we can put a wizard component inside a normal page section. And I agree we still need more options about whether to using a divider or use a prop `type=wizard` in page section.

**Comment by mcoker** [comment]
@DaoDaoNoCode that demo is just showing what's needed to get it to work. I don't think we want to add `flex-shrink: 1; min-height: 0;` to `.pf-c-page__main-section` as that could cause other issues with different products using different kinds of content in page sections. If we need to introduce those changes to `.pf-c-page__main-section`, it's best done either as a different element (`.pf-c-page__main-wizard`), or a modifier (`.pf-m-wizard` - not advised, as that's inconsistent with `.pf-c-page__main-[breadcrumbs/nav/etc])`, so that we don't inadvertently cause issues with layouts that have been built with the current CSS.

Another thing to explore is that we may be able to make changes to the wizard layout that make it behave properly within a regular `.pf-c-page__main-section` element.

**Comment by DaoDaoNoCode** [comment]
@mcoker Thank you, that makes sense, please let me know when we decide whether to use `.pf-c-page__main-wizard` or not, so that I could implement next step in React repo. Also, I will continue exploring the possibility to make changes directly in Wizard component.
