### ISSUE TITLE
Fix a11y issues in Documentation/Core/Dropdown

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#3262]
https://www.patternfly.org/v4/documentation/core/components/dropdown

There is 1 type of a11y issue(the rest are covered in separate issues):

1. Heading levels should only increase by one

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by jessiehuff** [comment]
This is actually due to the `<h1>` group headings in the dropdown: 

![Screen Shot 2020-07-08 at 7 38 02 PM](https://user-images.githubusercontent.com/28281340/86980707-93d65e00-c152-11ea-90ae-901913943ceb.png)
