### ISSUE TITLE
Styling to support onRowClick event on react tables

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3273]
re: https://github.com/patternfly/patternfly-react/issues/3267

For rows with an `onRowClick` event function specified:

* Should we just share the selectable styling?
  * Should they use the same class? If so, if they diverge in the future, that may be breaking.
  * Should there be different classes that share styles so they can diverge?
* Do we want to differentiate the styles so that there is a visual difference between something that is selectable versus actionable?

cc @mcarrano @lboehling

**Comment by mcarrano** [comment]
Selectable rows have a checkbox. Rows that take an onClick event should take on the selectable row styling (hover + selected state as defined by @lboehling ). The two things can co-exist within the same row, if desired. Does that make sense? Maybe we don't need these as separate things because in my opinion they are the same thing - a row that triggers an event when clicked.

**Comment by mcoker** [comment]
> Selectable rows have a checkbox.

I'm not considering that use case when referring to selectable rows - only the feature @lboehling designed for data-list - https://www.patternfly.org/v4/documentation/react/components/datalist#selectable-rows

Though from our conversation today, I think we can create a single style for a hoverable/actionable row that can be used when hovering/clicking a row performs an action (the `onRowClick` support for this issue, selecting a row similar to data-list, or some other thing in the future), and the naming shouldn't be tied to "selectable rows" like it is now for data-list. The name for a hoverable/actionable row is currently called "selectable." We would use "hoverable" instead, which would match the card. Then in a breaking change we can update the data-lists's name "selectable" to "hoverable." Sound like a plan?

**Comment by mcarrano** [comment]
Sounds good to me.

**Comment by mcarrano** [comment]
@mcoker Is this really a duplicate of https://github.com/patternfly/patternfly/issues/2371? If so, I will close my issue.

**Comment by mcoker** [comment]
If we want to create a more generic modifier that applies "hoverable" styles for row that we share between things like hovering a selectable row, a "clickable" row (that does some user-specified action), maybe styles we apply to hovering over a draggable row, etc, then we can do that in https://github.com/patternfly/patternfly/issues/2371 and close this issue. I updated https://github.com/patternfly/patternfly/issues/2371 to reflect creating a generic variation for "hoverable" styles. Feel free to close this issue if everything looks OK there.

**Comment by mcarrano** [comment]
Yes, I think this makes sense @mcoker . In my view, "selectable" and onRowClick are the same thing, i.e. the user takes an action to select a row either via a single click or keyboard action. The result of that event is left to the consumer. 

If that agrees with your interpretation of this, then , yes, let's close this issue.

**Comment by mcoker** [comment]
Will be done in https://github.com/patternfly/patternfly/issues/2371
