### ISSUE TITLE
add warning state to text inputs

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly#3277]
**Describe the issue. What is the expected and unexpected behavior?**

PF text inputs can be marked invalid which then sets `aria-invalid="true"` and visually adds an error icon background and red underline.

We have a need to show a warning indicator. The reason for the warning is because the value cannot be detected as an error case but we have detected that the value may require some additional steps by the user.

Design mock up:
![image](https://user-images.githubusercontent.com/14068621/81190854-599be500-8f86-11ea-8fd9-1233d050c9c7.png)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
enhancement

**What is your product and what release version are you targeting?**
Openshift Console 4.5+

**Comment by christianvogt** [comment]
@mcarrano 
April 17, 2020 :) Our 4.5 release has since closed.
So now it would be July 31, 2020.

**Comment by serenamarie125** [comment]
@mcarrano @christianvogt Code freeze for 4.6 release is July 31st.  Looks like feature freeze is end of September

**Comment by mcarrano** [comment]
Given that we are now in mid-July, this will not make it for 4.6 (our next PF release is Aug 4). But I will get this on our roadmap to be available for your 4.7 release. It should be a pretty straight forward update.

**Comment by stevengutz** [comment]
Am I the only one that thinks a request that happened in May that won't make it into PatternFly until the end of the year is a bit questionable?  Just a gentle reminder that this has potential revenue impact for OpenShift

**Comment by mcarrano** [comment]
@christianvogt @stevengutz Good news on this. We were able to squeeze this into our 2020.09 milestone that is targeted to be released within the week. Sorry this took so long to address. In the future I would like be able to reduce the turn around time on simple requests like this.
