### ISSUE TITLE
Bug: notification badge alignment

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3283]
<img width="472" alt="Screen Shot 2020-07-13 at 3 25 01 PM" src="https://user-images.githubusercontent.com/5385435/87344794-06fa1e80-c51d-11ea-9cf4-85f42538b554.png">

**Comment by mceledonia** [comment]
@mattnolting @nicolethoen 
[Attention Bell.svg.zip](https://github.com/patternfly/patternfly/files/4927182/Attention.Bell.svg.zip)
