### ISSUE TITLE
NotificationBadge: Updates to notification badge have been added to 4.23.1 that are not yet ready for use

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly#3292]
"@patternfly/patternfly": "4.23.1",
has changes to the pf notification badge is read state which changes the look of the icon. we need to time this with the notification badge updates that are upcoming. the read state also leaves a grey box around the icon see the screenshot.

![badge-icon](https://user-images.githubusercontent.com/35978579/87586124-10ff5700-c6ae-11ea-8ab8-6a85fe40fde4.gif)

**Comment by mcoker** [comment]
Thanks for the issue @jcaianirh, this should be closed via https://github.com/patternfly/patternfly/pull/3294

**Comment by jcaianirh** [comment]
@mcoker I updated pf dependency in package.json to 4.23.3, and am still seeing the issue see the screenshots below

![Screen Shot 2020-07-15 at 11 16 14 PM](https://user-images.githubusercontent.com/35978579/87622662-98ba8500-c6f1-11ea-8e2d-bac95da9a36a.png)
![Screen Shot 2020-07-15 at 11 17 37 PM](https://user-images.githubusercontent.com/35978579/87622639-8ccec300-c6f1-11ea-9150-9472cfde6582.png)

**Comment by mcoker** [comment]
@jcaianirh do you still need help with this or is it ok to close?

**Comment by jcaianirh** [comment]
@mcoker you've gone above and beyond. the core changes need to be updated in pf-react as well. the react component wins the race in overriding styles in openshift. all set, closing.
