### ISSUE TITLE
Wizard body content in modal no longer scrolls

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly#3310]
The wizard modal body no longer scrolls. This has led to the buttons being cut off at low resolution.

![Screenshot from 2020-07-19 17-16-57](https://user-images.githubusercontent.com/23172038/87983016-ad0dd180-caa5-11ea-95b2-da8c6829bfce.png)

Issue: https://issues.redhat.com/browse/POL-319

**Comment by mcoker** [comment]
@katierik can you confirm what version you're using? That should be fixed in `@patternfly/react-core@4.23.1` which includes the fix outlined in this PR - https://github.com/patternfly/patternfly/pull/3176

**Comment by josejulio** [comment]
Thanks @mcoker, we were testing with `@patternfly/react-core@4.18.5`. 
It works well on latest.

**Comment by katierik** [comment]
Awesome!
