### ISSUE TITLE
UX Bug: PageHeader wraps logo in a tag without an href, CSS makes link a pointer

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly#3332]
**Describe the issue. What is the expected and unexpected behavior?**

Logos in the nav bars are usually links, the PageHeader Component will make the logo a link without an href, and CSS added by Patternfly will make all `<a>` tags user the pointer.

https://github.com/patternfly/patternfly-react/blob/2e2676ce6bc34f5e20231ca066d26ea4c3ac95e4/packages/react-core/src/components/Page/PageHeader.tsx#L42

Not sure where the CSS is coming from, but this is the CSS making a mouse use a pointer on all `<a>` tags (even if they don't have an href):
```css
button, a {
    cursor: pointer;
}
```

My thought would be to only make the logo an `a` tag if there's an href. In this context an `<a>` tag without an `href` doesn't make much sense.

Alternatively the CSS selector could be changed to `a[href]`, instead of just `a`.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Use PageHeader component and don't specify a logo URL

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug, it's creating a UX issue

**Comment by mcoker** [comment]
@wesruv just following up on this. I filed an issue in react to see if we can do some sort of smart detection of the props passed to the logo and render a more appropriate element - https://github.com/patternfly/patternfly-react/issues/4665.

I don't think we can safely remove the cursor pointer from `a`, as currently (using the `<PageHeader>`'s `logoProps` prop as an example) if a user were to provide an `onClick()` function to an `a` element, we would still want to retain the cursor pointer. Seems like that is a likely use case with the page logo. This is something we can look into more in our next breaking change release.

I wanted to point out though that the [`<PageHeader>` component](https://github.com/patternfly/patternfly-react/blob/0a41546ddf75c05080078eadef2f4aa2ffb42722/packages/react-core/src/components/Page/PageHeader.tsx) supports a [`logoComponent` prop](https://github.com/patternfly/patternfly-react/blob/0a41546ddf75c05080078eadef2f4aa2ffb42722/packages/react-core/src/components/Page/PageHeader.tsx#L40) that lets you manage the element to use. I wasn't sure if you had seen that or not. In this case, assuming clicking on the logo does nothing, I would recommend using a `<span>` (or maybe a more appropriate element for your use case) instead.

**Comment by wesruv** [comment]
Thanks for the update!

Re: logoComponent, the logo needs to be a link, so I'm using the default logo/branding component now. Thanks for the info!
