### ISSUE TITLE
Stacked toolbar spacing bug for PF React toolbar component

### ISSUE THREAD

**Issue by fionayhlin** [patternfly/patternfly#3344]
Stacked toolbar example on the PF website [here](https://www.patternfly.org/v4/documentation/react/components/toolbar#stacked-example) has a spacing issue. 

<img width="1038" alt="Screen Shot 2020-07-29 at 1 40 31 PM" src="https://user-images.githubusercontent.com/49918197/88833936-13c77500-d1a1-11ea-95f7-c5ad67700022.png">

**Comment by gdoyle1** [comment]
fyi @mattnolting this is what we were discussing in slack!

**Comment by unlikelyzero** [comment]
Filed as a blocking issue against awx https://github.com/patternfly/patternfly/issues/3344

**Comment by unlikelyzero** [comment]
ping
