### ISSUE TITLE
Proprietary dependencies

### ISSUE THREAD

**Issue by notklaatu** [patternfly/patternfly#3345]
I'm unable to contribute to this project because both Sketch and Figma are proprietary tools, the former of which doesn't work on non-Mac platforms. This is confusing in part because the site says "We’re on a mission to help teams build consistent, accessible, and scalable enterprise product experiences—the open source way."  

I've downloaded the [.sketch file](https://resources-live.sketch.cloud/documents/64f642f8-2fdd-4201-92a8-0e510468ff9c.sketch) and I'm able to extract its contents. It contains PNG and JSON files, but very little context.

Is the only way to modify elements through Sketch or Figma? Are there plans to adapt to an open source workflow?

**Comment by mcoker** [comment]
cc @mcarrano

**Comment by mcoker** [comment]
Hi @notklaatu, there is an open issue in the [patternfly-design repo](https://github.com/patternfly/patternfly-design) where you can leave comments and track the progress: https://github.com/patternfly/patternfly-design/issues/900
