### ISSUE TITLE
Add GAP to toolbar!

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3348]
Flex gap is finally here, we need to add it to `toolbar`. Should have optional `row-gap` modifiers.

**Comment by KKoukiou** [comment]
This is not fixed, can be reopened. @mattnolting

**Comment by jamestalton** [comment]
ACM has been adding the gap to the toolbar to solve this issue.
It would be great is PatternFly addressed this.

**Comment by mattnolting** [comment]
@jamestalton I agree, we plan to address in the upcoming breaking change release.
