### ISSUE TITLE
Update description list spacing

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3367]
https://github.com/patternfly/patternfly-react/pull/4586#issuecomment-664485908

> @mcarrano @jenny-s51 I think that this is looking good! The only thing that I think that we should update would be the default spacing in between columns from 16px to 24. The tightness of the columns makes it a little difficult to distinguish between where one description pair starts and another ends (screenshot of what I'm referring to below)
> <img alt="Screen Shot 2020-07-27 at 12 01 51 PM" width="357" src="https://user-images.githubusercontent.com/19824574/88564302-0c696580-d001-11ea-8b1a-d09279595e77.png">

@maryshak1996 After looking at the description-list spacing, it still didn't look right. Does this make sense?
What needs to happen to match the spec
- Line height for `__term` and `__description` needs to be set to `var(--pf-global--LineHeight--sm)`
- Line height for `__text` needs to be set to `inherit`
- `pf-c-description-list__group` `column-gap` needs to be updated to `var(--pf-global--LineHeight--sm)`

Also, were the `__term` s supposed to be bold?

**Updated tasks**
- [ ] Line height for __term and __description needs to be set to var(--pf-global--LineHeight--sm); Line height for __text needs to be set to inherit
- [ ] add `pf-m-compact` - reduces overall spacing
- [ ] add `pf-m-fluid` - allows for horizontal `groups` to use fluid value for `__term` and `__description`.

**Comment by mcoker** [comment]
@maryshak1996 @mattnolting just wanted to check the status of this - is this something we still need to update?

**Comment by mcarrano** [comment]
@mattnolting @mcoker Thoughts on this? Is this still something we should do?

**Comment by mcoker** [comment]
@mcarrano I'll defer to y'all. 

FWIW this is what it looks like now:
<img width="394" alt="Screen Shot 2020-12-07 at 10 29 48 AM" src="https://user-images.githubusercontent.com/35148959/101377258-35371c80-3877-11eb-92d7-54c73673248f.png">
<img width="734" alt="Screen Shot 2020-12-07 at 10 30 04 AM" src="https://user-images.githubusercontent.com/35148959/101377252-349e8600-3877-11eb-8a2c-13cf06af6d15.png">
<img width="408" alt="Screen Shot 2020-12-07 at 10 29 57 AM" src="https://user-images.githubusercontent.com/35148959/101377255-35371c80-3877-11eb-9f8f-924bf5d80e6c.png">
<img width="591" alt="Screen Shot 2020-12-07 at 10 29 52 AM" src="https://user-images.githubusercontent.com/35148959/101377257-35371c80-3877-11eb-9ce1-b53b7e3554a1.png">


And this is what it looks like with the changes recommended in this issue:

<img width="315" alt="Screen Shot 2020-12-07 at 10 29 40 AM" src="https://user-images.githubusercontent.com/35148959/101377309-44b66580-3877-11eb-906c-12fd8c3030f8.png">
<img width="585" alt="Screen Shot 2020-12-07 at 10 29 29 AM" src="https://user-images.githubusercontent.com/35148959/101377311-44b66580-3877-11eb-9560-9b68cd606d2a.png">
<img width="393" alt="Screen Shot 2020-12-07 at 10 29 25 AM" src="https://user-images.githubusercontent.com/35148959/101377312-454efc00-3877-11eb-99ee-f7f0ca81db12.png">
<img width="469" alt="Screen Shot 2020-12-07 at 10 29 20 AM" src="https://user-images.githubusercontent.com/35148959/101377313-454efc00-3877-11eb-81c8-ce16e512f615.png">

**Comment by mattnolting** [comment]
> The only thing that I think that we should update would be the default spacing in between columns from 16px to 24.
We updated this, `column-gap` is now 24px.

- These are the things I still think we need to update:
 Line height for __term and __description needs to be set to `var(--pf-global--LineHeight--sm);` Line height for __text needs to be set to inherit

This layout came up recently in conversation, as something we need to support (we can't currently)

![image](https://user-images.githubusercontent.com/5385435/101382132-9665ec80-3885-11eb-9ab1-b8fe8e083c84.png)

But, we could support this by adding `pf-m-compact` and `pf-m-fluid`.
- `pf-m-compact` - reduces overall spacing
- `pf-m-fluid` - allows for horizontal `groups` to use fluid value for `__term` and `__description`. 

![Screen Shot 2020-12-07 at 12 18 14 PM](https://user-images.githubusercontent.com/5385435/101382771-57846680-3886-11eb-9eb9-b9469683f066.png)

**Comment by mcarrano** [comment]
So sounds like what we need here is the option for a tighter vertical spacing (i.e. "compact").  My only question is whether we should offer two spacing options or if we should just make the default spacing tighter. @maryshak1996 @mceledonia what are your thoughts?

**Comment by mattnolting** [comment]
@mcarrano I think we need a compact and default version, as I'm seeing Product designs using both. And I think nested `description lists` would logically use a `compact` variant.

**Comment by mcarrano** [comment]
Will add this to the roadmap.

**Comment by mcarrano** [comment]
@mattnolting Can we consider https://github.com/patternfly/patternfly-design/issues/1056 as part of this work? Let's discuss.
