### ISSUE TITLE
Ensure notification badge and notification drawer item state is used correctly in demos

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3371]
For example, the drawer demo does not contain a notification drawer. Should we update that to be some other type of icon that could toggle a drawer open/closed?

The notification drawer demos all use the read notification badge state, but have unread (and potentially attention state) items. Let's ensure we're showing the correct items in the notification drawer, and the notification badge used in the demo reflects the drawer contents.

Also review anywhere else this may be an issue.

**Comment by mcarrano** [comment]
@mcoker does this issue require any React follow-up?

**Comment by mcoker** [comment]
@mcarrano this only updated our examples so the badge was appropriate based on the contents of the notification drawer. As long as the notification badge demos in react look ok to you, it should be fine - https://patternfly-react.surge.sh/components/notification-drawer/react-demos

We did include a demo for the attention state. Maybe the react demos could be updated to add the attention state when there is an unread attention state item?
