### ISSUE TITLE
Introduce modal alert variation

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3374]
Want to introduce a new variant of the Modal component that allows for a status icon in the header. This would be used for modal alerts.

Designs:

![image.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/a348b756-ae6a-45ff-bd55-887bbf854f4f)

**Comment by mcarrano** [comment]
@mmenestr I was just discussing this with @mcoker and he pointed out that there is no such thing as a Compact modal. We just updated the default spacing to be more compact during the breaking change release. Wanted to check back to see why you specified the design this way. Are we missing something?

**Comment by mmenestr** [comment]
@mcarrano I just mapped it to the Sketch Symbol library 
![image](https://user-images.githubusercontent.com/51165119/93259412-d0838e80-f76d-11ea-8bc2-4afe48888ffb.png)

**Comment by mcarrano** [comment]
Yeah, that's what I thought @mmenestr . I think this might have been something that we reversed course on. @mceledonia  do you remember? In any case, we should probably open an issue against the design kit to align.
