### ISSUE TITLE
Inline style of svg in utilization chart causes wrong resize on zoom in/out

### ISSUE THREAD

**Issue by LeshemNoa** [patternfly/patternfly#3442]
The svg of the utilization chart component has inline style `height: auto`.
In Chrome, when I zoom in to 110%, the chart is resized but when I zoom back out to 100% it doesn't size back down. This issue is fixed by manually disabling this inline style property, but I can't override it altogether.

**Comment by mcoker** [comment]
cc @dlabrecq
