### ISSUE TITLE
Toolbar filters are narrower in Chrome

### ISSUE THREAD

**Issue by epwinchell** [patternfly/patternfly#3449]
Toolbar filters are narrower in Chrome than either Safari or Firefox. This becomes obvious when using long placeholder text, which forces an ellipsis. I was able to replicate the issue here: https://www.patternfly.org/v4/documentation/core/components/toolbar#toggle-group , using placeholder="Filter by exact username" 

Here's an example from the RBAC UI:
![Screen Shot 2020-09-03 at 2 08 04 PM](https://user-images.githubusercontent.com/1287144/92151325-f1072c80-edee-11ea-9d8e-9267a92e1e2f.png)

**Comment by mattnolting** [comment]
This appears to be part of `pf-c-input-group` rather that `pf-c-toolbar`
