### ISSUE TITLE
Add hover states for the unread and attention Notification badge

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3450]
The Notification badge should have hover states for the unread and attention states as see below.

![image (3)](https://user-images.githubusercontent.com/6619860/92162155-b5289300-edff-11ea-9157-550d5d9372a7.png)

This was an oversight in the original design.

cc @mceledonia

**Comment by mceledonia** [comment]
Color spec for hovers:

Unread/blue: `$pf-color-blue-500` aka `$pf-global--primary-color--200`
Attention/red: `$pf-color-red-200` aka `$pf-global--danger-color--200`
