### ISSUE TITLE
Filter panel component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3472]
The filter panel is a vertical sidebar that can hold a variety of items for filtering a dataset presented in a catalog view configuration. See https://marvelapp.com/prototype/24g4a7g6 and https://marvelapp.com/prototype/c18hjf1/screen/76941197 for designs.

**Comment by mcarrano** [comment]
Consider whether the panle can also be opened as a dropdown to cover the kind of use case identified in this issue: https://github.com/patternfly/patternfly-design/issues/912

**Comment by mcarrano** [comment]
Also want to consider the requirement to show/hide the panel as summarized here: https://github.com/patternfly/patternfly-design/issues/932

**Comment by mmenestr** [comment]
Also want to consider changing how we show number of items that match a certain selection. The initial design had them shown in parentheses right after the option 'name', but we want to change that to have them shown as grey right aligned text.
See mock: https://marvelapp.com/prototype/c18hjf1/screen/76941197

This is to match our proposal for doing the same thing in a select list.

**Comment by mcarrano** [comment]
I am going to close this for housekeeping purposes. We can reopen pending a larger discussion of implementing Catalog views.
