### ISSUE TITLE
Enhancement: form section demo

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3484]
Splitting #3395 into enhancement and demo.

https://github.com/patternfly/patternfly/issues/3395#issuecomment-673548285

![Screen Shot 2020-08-12 at 5 53 56 PM](https://user-images.githubusercontent.com/5385435/90072106-ce3c9900-dcc4-11ea-9a80-3023fe024f6a.png)

**Comment by mattnolting** [comment]
Ping

**Comment by nicolethoen** [comment]
We have form section demos now
