### ISSUE TITLE
Nested expandable button animation and transformation issues

### ISSUE THREAD

**Issue by alexfdezsauco** [patternfly/patternfly#3493]
Nested expandable button animation and transformation is inherited from the top most expandable.

**Comment by mcoker** [comment]
Hi @alexfdezsauco which component are you referring to?

**Comment by alexfdezsauco** [comment]
The Expandable  https://www.patternfly.org/2020.04/documentation/core/components/expandable/. Not sure why I can't paste an screenshot.  I'm tryting to nest expandable to create a tree view but doesn't work properly.  I don't migrated yet this https://github.com/WildGums/Blorc.PatternFly to the new PF (a lot of breaking changes).
