### ISSUE TITLE
Seemingly invalid CSS variables created

### ISSUE THREAD

**Issue by sosguthorpe** [patternfly/patternfly#3512]
The CSS variables created with path values (i.e. beginning `./assets`), which seem to be invalid. I believe they should be wrapped in quotes to be valid CSS variables. I'm seeing an error when attempting to use the patternfly SCSS in a project with the `mini-css-extract-plugin` plugin enabled.
Error: `(1:1) Unknown word`

Running the generated CSS through a validator also complains about those variables.

As a workaround I've created my own copy of the `/base/_variables.scss` file and quoted the values. Haven't noticed anything break as a result but I'm also unsure as to the extent of the usage so opted to raise an issue rather than a PR.

For an example see:
https://github.com/patternfly/patternfly/blob/3c4ee90115901b7e5bd61834ea77f80f29416909/src/patternfly/base/_variables.scss#L161

**Comment by mcoker** [comment]
@sosguthorpe thanks for the issue, I've issued a PR here if you would like to have a look - https://github.com/patternfly/patternfly/pull/3582
