### ISSUE TITLE
Tree View: confusing indentation difference of expandable vs non-expandable items

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly#3532]
I noticed something about the way the tree view handles indentation that indicates to me that there may be a CSS bug, but I'm not sure if it was an intentional design decision.

The `.pf-c-tree-view__list-item` is always positioned at the same horizontal position regardless of whether it is `.pf-m-expandable` or not. The `.pf-m-expandable` version has a ">" icon for the expand/collapse control, pushing the icon/checkbox/name/etc of the item farther to the right than its non-expandable siblings.

When we have a tree where some items are expandable and other sibling items are not, especially with checkboxes and icons, this leads to a confusing layout where it can appear that the expandable items are one level deeper than they are (or, non-expandable items can appear one level shallower than they are).

For example, I have a tree with data structured like this:

* All datacenters
  * Fake_DC
  * V2V_DC
    * Fake_Cluster
    * V2V_Cluster
      * esx13.v2v.bos.redhat.com
    * jortel

The TreeView component displays it like this:

![Screen Shot 2020-09-29 at 4 36 49 PM](https://user-images.githubusercontent.com/811963/94615185-52e37680-0275-11eb-87a5-2af87728ff59.png)

As you can see, any item with the expand/collapse arrow has its checkbox pushed to the right and aligned with its children, so it looks like V2V_DC is a child of Fake_DC when they are really siblings, and it looks like Fake_Cluster is a sibling of V2V-DC when it is really a child.

As a temporary solution, I added this CSS in our app:
```css
.pf-c-tree-view li.pf-c-tree-view__list-item:not(.pf-m-expandable) {
  padding-left: var(--pf-global--spacer--lg);
}
```

And now the tree looks like this:

![Screen Shot 2020-09-29 at 4 52 16 PM](https://user-images.githubusercontent.com/811963/94615310-8cb47d00-0275-11eb-9702-eff4d3e448b3.png)

The checkboxes and icons are now aligned as I would expect based on the data structure.

@christiemolloy @mcarrano is this an issue we should fix or an intentional design decision?

**Comment by mcoker** [comment]
cc @doruskova

**Comment by doruskova** [comment]
@mturley Thank you for finding this bug. This wasn't intentional from a design perspective. It should look like this: 
![tree](https://user-images.githubusercontent.com/32618096/94658673-66d5b980-0303-11eb-8876-bca21139d164.png)

The child needs to be indented with a checkbox to the right. I mean align just these children that are at the same level.

@mcoker Does it make sense to you? Let me know what you think :)
