### ISSUE TITLE
Wizard: no built-in way of adding border-top on the page section of an in-page wizard, per design guidelines

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly#3546]
Not sure if this belongs here or in patternfly-react.

[In the design guidelines for Wizard](https://www.patternfly.org/v4/components/wizard/design-guidelines#in-page-wizards), I see that an in-page wizard is supposed to have a grey border at the top of its page section, joining with the border-right on the wizard nav to form a T-shaped border on the page. Also, in order to get the wizard border to reach the edges properly I would need to remove the padding on that page section and rely on the Wizard's own padding.

![wizard-in-page c85b07e09e9785f9dd2ca6c5f79b5971](https://user-images.githubusercontent.com/811963/94918758-31ef7100-0481-11eb-8118-5e12e47939b7.png)

I'm not seeing a CSS class I can put on the page section wrapping my wizard to style it this way. Placing a wizard inside a page section looks like this:

![Screen Shot 2020-10-02 at 7 33 33 AM](https://user-images.githubusercontent.com/811963/94918971-990d2580-0481-11eb-86b2-c2d2543791e1.png)

This is the CSS I'm using in our app as a temporary fix (with a special `plan-wizard-page-section` class added to this section):

```
.pf-c-page__main-section.plan-wizard-page-section {
  border-top: var(--pf-global--BorderWidth--sm) solid var(--pf-global--BorderColor--100);
  padding: 0;
}
```

With the CSS:

![Screen Shot 2020-10-02 at 7 35 24 AM](https://user-images.githubusercontent.com/811963/94919104-e12c4800-0481-11eb-962c-f28c4ced41b7.png)

Maybe I shouldn't put it in a page section at all? It would still need the border.

**Comment by mcoker** [comment]
Hey @mturley we have a `.pf-c-page__main-wizard` element that does this, though I believe we're missing this element in react. We have an open core issue to look at that element to see if it is necessary, so we've held off on adding it to react yet.

However, you should be able to drop the divider component between page sections - will that work?

**Comment by mturley** [comment]
Ah, thanks @mcoker! Just dropping `className="pf-c-page__main-wizard"` onto my `<Wizard>` and unwrapping it from its PageSection works great. I'll close this and open an equivalent issue in pf-react to add a prop for that class.
