### ISSUE TITLE
Dual list selector component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3556]
Introduce a new dual list selector component per the designs here: https://marvelapp.com/prototype/12e47bhj

**Comment by mcarrano** [comment]
I think that it would also make sense to consider the ability to drag and drop between lists as well as use the buttons. @mmenestr @mcoker what do you think? We did not consider this as part of the original design but we could leverage approach for data list. What are your thoughts? This can always be considered as an add-on.

**Comment by mcoker** [comment]
@mcarrano sounds good to me!

**Comment by mmenestr** [comment]
Yes that seems fine to me! And just to go deeper in the specifications, let's say you have 2 items selected, and you try to click and drag - do both items get moved over, or does only the one item your cursor is over get dragged?

**Comment by mcoker** [comment]
cc @kmcfaul what do you think about @mmenestr's question above re: dragging more than one item at a time?
