### ISSUE TITLE
Low contrast on inline alerts when on grey background

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly#3570]
This alert style (info) looks strange on a grey background. A border would do wonders.

![15CC82D3-C06F-496D-BECA-A09780690FC3](https://user-images.githubusercontent.com/23172038/95387223-68cce900-08be-11eb-83f5-af629d95d85f.png)

**Comment by mcoker** [comment]
cc @mcarrano @mceledonia

**Comment by mcarrano** [comment]
I see what you are saying @katierik , but does this messaging always appear when there are no playbooks created? Can this messaging just be incorporated as part of the empty state? If we do keep this, I think a Hint would be more appropriate (https://www.patternfly.org/v4/components/hint) That also has the light blue fill, but includes a border that might help to set this off.
