### ISSUE TITLE
Fix: wizard nav clickability 

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3575]
Clickable area for wizard nav feels inconsistent with other dropdowns (in mobile viewport) and lists/nav components. We should consider increasing the clickable area of the button to fit its parent `li`.

@mcarrano @mceledonia wdyt?

![Screen Shot 2020-10-08 at 10 15 18 AM](https://user-images.githubusercontent.com/5385435/95470761-2bfd0280-094f-11eb-967a-8a95175a9b32.png)

**Comment by mcarrano** [comment]
Not sure I completely understand @mattnolting . Looks like the number and label are clickable. Are you saying to make the entire with of the item clickable, i.e. to the right edge of the stepper bar?
