### ISSUE TITLE
Alignment of "Help" icon 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly#3591]
We wanted to create a Sketch symbol for a modal with a "Help" icon. But, when I take a look at the HTML version
https://www.patternfly.org/v4/components/modal/html/#with-help-button
It looks that it should be aligned with a "Close" button, but it's not and it looks lower than the close button. Is it correct? Or is there any way of how to improve the alignment? We put our issue on hold to make sure that the alignment is correct (https://github.com/patternfly/patternfly-design-kit/issues/298) @mcarrano @mcoker 

<img width="1662" alt="Snímek obrazovky 2020-10-13 v 14 58 22" src="https://user-images.githubusercontent.com/32618096/95864312-7faf8780-0d65-11eb-90d5-b43b3b72a995.png">

**Comment by mcoker** [comment]
Hi @doruskova! Yep that's just an issue with the icon in the core pficon font. You can see the correct alignment in the react PR that implements the help button here - https://patternfly-react-pr-5002.surge.sh/components/modal#with-help

**Comment by doruskova** [comment]
@mcoker Thank you!
