### ISSUE TITLE
Table: don't rely on data-labels 

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly#3617]
In React's new composable table it's difficult to automatically add data-labels which makes [separating row logic from column logic difficult.](https://github.com/patternfly/patternfly-react/pull/4950#discussion_r510422740) Although I'm unsure the feasibility, it'd be a wonderful enhancement to not rely on these data labels for row headers on smaller viewports.

**Comment by mattnolting** [comment]
If `data-label` isn't used, a `label` element will have to be manually added to the DOM and all `td` content (not part of that label) will need to be wrapped in another element. So it equates to significantly more HTML. Don't know what the React implications would be.
