### ISSUE TITLE
Add icons for new, not started, and resources empty

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3624]
Add three new icons to the Core icon set (New, Not started, and Resources empty).

@mceledonia @bgilwa01 can one of you attach the related SVG files?

**Comment by doruskova** [comment]
@mceledonia Could you add the related SVGs so that I can update our symbol library? Thank you so much!

**Comment by mcoker** [comment]
new-process and not-started added to https://github.com/patternfly/patternfly-design/issues/921#issuecomment-725555786

**Comment by mceledonia** [comment]
Here's a zip with all 3 @mcoker @doruskova 
[pf-new-icons-nov11.zip](https://github.com/patternfly/patternfly/files/5526143/pf-new-icons-nov11.zip)
