### ISSUE TITLE
Update pficon font unicode to match PF3 font

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3626]
To support designers using the [unicode from the PF3 icon font](https://www.patternfly.org/v3/styles/icons/), 
let's update the unicode in the PF4 icon font to match the PF3 font, so that they don't have to update the unicode for each character when upgrading from to the PF4 font.

**Comment by mcoker** [comment]
@mcarrano can we add this to the roadmap? It's needed so we can add a copy unicode button to the icon table on the website - https://github.com/patternfly/patternfly-org/issues/1851#issuecomment-718039259

**Comment by evwilkin** [comment]
@evwilkin watching this issue 👀

**Comment by evwilkin** [comment]
Notes from investigation with @mcoker - this might be a better infrastructure team job. The trick was getting gulp-iconfont and gulp-iconfont-css to allow you to specify a unicode character for each SVG, and tying that into the CSS build (https://github.com/patternfly/patternfly/blob/master/scripts/gulp/icons.js)
