### ISSUE TITLE
(RFE) DescriptionList: missing option where the horizonal list can become vertical on small screens

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#3630]
In cockpit we would like to use isHorizontal for description lists (1 column), but we would like that they are responsive and convert into vertical for smaller screen sizes.
It would be useful to provide an option for that.

So instead of boolean it would be nice to have: isHorizontal: { "lg" } or something similar.

**Comment by KKoukiou** [comment]
it's nothing urgent, I already wrote some custom CSS which implements naively it locally.
Here is the relevant code:
https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/patternfly/patternfly-4-overrides.scss#L42..L47

**Comment by mattnolting** [comment]
Ping
