### ISSUE TITLE
Bug: Content/Text component 

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#3631]
If there is a select inside of the Content/Text component the `<ul>` in the menu is inheriting these styles:
```
.pf-c-content ul {
    padding-left: var(--pf-c-content--ul--PaddingLeft);
    margin-left: var(--pf-c-content--ul--MarginLeft);
    list-style: var(--pf-c-content--ul--ListStyle);
}
```

causing this

<img width="567" alt="Screen Shot 2020-10-29 at 3 00 57 PM" src="https://user-images.githubusercontent.com/20118816/97620383-e1bfec00-19f7-11eb-97ed-885851db80ed.png">

**Comment by mcoker** [comment]
@christiemolloy can this be closed?
