### ISSUE TITLE
Multiple tables on a single page pagination broken 'pagination1' and 'pagination1-page' extremely rigid

### ISSUE THREAD

**Issue by andrucris** [patternfly/patternfly#3652]
If I have more than one table on a page the pagination from the bottom toolbar is broken . I have noticed that some id-s are very fixed , eg pagination1' 'pagination1-page' , if I give dynamic id eg pagination1${id}' 'pagination1-page${id}' then the navigation between pages is not working . 
Please let me know how to handle multiples tables on a single page ( how to could assign correct id-s for the pagination components ) .
<img width="1053" alt="Screenshot 2020-11-09 at 21 56 42" src="https://user-images.githubusercontent.com/16562804/98589810-884c9c80-22d6-11eb-9080-c43a4bba0016.png">

**Comment by mcoker** [comment]
Hi @andrucris sorry for the delay! Just want to confirm that you're using PatternFly 3?
