### ISSUE TITLE
Menu enhancements, fit in dropdown

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3657]
Since we'll be using the `menu` inside `dropdown`s, `menu` needs some additional contextual CSS support. `pf-c-dropdown > pf-c-menu` needs to be `position: absolute` and respond to `pf-m-top` and `pf-m-right`.

Also, menu needs to replicate dropdown `pf-m-text` https://www.patternfly.org/v4/components/dropdown/html#dropdown-with-image-and-text

**Comment by mattnolting** [comment]
Ping

**Comment by nicolethoen** [comment]
We are planning to refactor menu like components to use Menu during a breaking change release. We will not be skinning menu to use dropdown classes or styles.
