### ISSUE TITLE
sticky header/footer: breakpoint improvements for increased font size and mobile

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#3660]
In the PatternFly-Cockpit sync up call, we talked about the sticky header & footer component (#3516).

I brought up the how this can be both good and bad for mobile and @jgiardino mentioned this also affects all browser sizes when fonts are increased.

Browsers don't support component-based sizing in CSS right now, so we'd have to try to guess at what best to do.

PatternFly could, by default, have breakpoints where sticky is enabled for larger horizontal _and_ vertical breakpoints (with font size taken into account for the vertical breakpoints). And then have an override option for someone who knows what they're doing to enable sticky for mobile too (in the cases where the author of the app _knows_ the content won't be more than 1 line tall, for example).

(We're already doing something like this in Cockpit, IIRC; but it's in our own custom components. It would be great to have this in PF itself, by default.)

**Comment by jgiardino** [comment]
Thanks for capturing this, @garrett!

My thoughts regarding breakpoints is that it would be great to consider font size instead of pixel size, for example:
`@media (max-width: 75em)`

I think this would allow us to support both changes in layout for smaller viewports as well as users increasing their browser font size for better visibility.

This came up in the context of sticky sections because both smaller viewports and larger font sizes can result in a sticky anything wreaking havoc on a screen, because sticky sections start to take away screen real estate from the scrollable contents.

Here's an example of the [demo](https://www.patternfly.org/v4/components/page/react-demos/#sticky-section-group) at 200% (per [WCAG 1.4.4](https://www.w3.org/WAI/WCAG21/quickref/#resize-text)):
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/21063328/98831989-491f6800-240a-11eb-83b2-33cfa2ee8f78.png">

**Comment by garrett** [comment]
@jgiardino I was thinking min-height for a media query too — as the height is the issue with these sticky headers/footers. I suggested mixing min-height with min-width as mobile generally compresses the space and wraps the elements. For your screenshot, I think min-height alone would help fix the problem.

But then, what would the ideal min height be?

Does PatternFly currently do vertical breakpoints?

**Comment by mcoker** [comment]
> Does PatternFly currently do vertical breakpoints?

@garrett not currently

**Comment by mcoker** [comment]
@garrett @jgiardino I think we can start by adding breakpoint support to the sticky/overflow modifiers using our existing viewport width breakpoints. A complex example -

```
<div class="pf-c-page__main-section pf-m-sticky-top pf-m-static-on-md pf-m-overflow-scroll-on-md pf-m-sticky-bottom-on-xl pf-m-overflow-visible-on-xl">
```

As far as using ems for the breakpoint values, I think we would need to investigate that and maybe offer it as an opt-in until a breaking change release if we make that the default.

We don't currently offer viewport height breakpoints, but could look at that, too. I'd like to see what you have in cockpit if you're already doing that, as well as discuss this with the larger team to see how this would fit into patternfly as a whole.

Do you have a workaround currently, or a timeframe for when you would at least like to be able to use the viewport width breakpoint modifiers?

**Comment by garrett** [comment]
We're currently using breakpoints to optimize for Cockpit being displayed in VMs @ 1024×768 that include `orientation: landscape` combined with `max-width` and `max-height`.

I remember adding some sticky mobile overrides at some point to Cockpit, but we're not currently using them. We've either removed them (due to a redesign), or I'm remembering something from a mockup.

What I'm suggesting is something like turning off sticky display when the height is below a certain value. Or inverting that and only turning it on when the height is above a certain value. 

We could consider various typical sizes of screen viewports for mobile devices and desktops, convert the px to rem, so font scaling is considered, and have classes that only apply in various breakpoints. Similar to pf-on-{breakpoint-size}, we could introduce the concept of vertical breakpoints with similar classes. There could be -v for vertical (and -h for horizontal, which would be the default without a -v or -h).

Something like this:

```scss
.sticky {
  position: sticky;
  top: 0;
}
@media screen and (max-height: 41rem)  {
  .sticky.pf-on-sm-v {
    position: static;
  }
}
@media screen and (max-height: 50rem)  {
  .sticky.pf-on-md-v {
    position: static;
  }
}
...etc...
```

I've collected a bunch of screen sizes (virtual viewport heights in the case of phones) and DPR (device pixel ratios) for both mobile and desktop and have computed a rem (although em at a media query level should also equal rem, as rem == root em), and tried to classify the REM heights.


Phone | viewport width | viewport height | Device Pixel Ratio | REM (vpx heigh / 16) | Classification
-- | -- | -- | -- | -- | --
iPhone SE | 320 | 568 | 2 | 35.5 | SM
IPhone 6/7/8 | 376 | 667 | 2 | 41.6875 | MD
Pixel 2 | 411 | 731 | 2.625 | 45.6875 | MD
IPhone 6/7/8 Plus | 414 | 736 | 3 | 46 | MD
Galaxy S9/S9+ | 360 | 740 | 4 | 46.25 | MD
iPad horizontal | 1024 | 768 | 2 | 48 | MD
iPhone X/XS | 375 | 812 | 3 | 50.75 | LG
Pixel 2 XL | 411 | 823 | 3.5 | 51.4375 | LG
iPhone XR | 414 | 896 | 2 | 56 | LG
iPhone XS Max | 414 | 896 | 3 | 56 | LG
iPad vertical | 768 | 1024 | 2 | 64 | XL


Desktop | width | height | Device Pixel Ratio | REM (px height / 16) | Classification
-- | -- | -- | -- | -- | --
Netbook | 1024 | 600 | 1 | 37.5 | SM
720p | 1280 | 720 | 1 | 45 | SM
Quad HD / 1440p @ 2x | 2560 | 1440 | 2 | 45 | SM
UWQHD @ 2x | 3440 | 1440 | 2 | 45 | SM
Desktop (small) | 1024 | 768 | 1 | 48 | MD
Netbook | 1366 | 768 | 1 | 48 | MD
2560×1600 | 2560 | 1600 | 2 | 50 | LG
Desktop (medium) | 1440 | 900 | 1 | 56.25 | LG
1600×900 | 1600 | 900 | 1 | 56.25 | LG
Quad HD / 1440p @ 1.5x | 2560 | 1440 | 1.5 | 60 | XL
Desktop (typical) | 1280 | 1040 | 1 | 65 | XL
1080p (Full HD) | 1920 | 1080 | 1 | 67.5 | XL
Dell 4K UHD @ 2x | 3840 | 2160 | 2 | 67.5 | XL
Dell 8K @ 4x | 7680 | 4320 | 4 | 67.5 | XL
Desktop (typical) | 1600 | 1200 | 1 | 75 | XL
WUXGA | 1920 | 1200 | 1 | 75 | XL
Quad HD / 1440p @ 1x | 2560 | 1440 | 1 | 90 | 2XL

From this data, I think we probably want to use the following classifications somewhere around these breakpoints:

- SM: < 40 rem
  - iPhone SE size
  - netbook
- MD: 40 - 47 rem
  - Standard phone size
  - 720p (and HiDPI multiples with effective 720p sizes)
- LG: 48 - 59 rem
  - XL phone size
  - small to medium desktops
- XL: 60 - 79 rem
  - iPad, vertical
  - typical desktops
- 2XL: > 80 rem
  - Quad HD when not in HiDPI (which is absurd)
  - impractically dense screens

We'd need to be careful to consistently use the low end or the high end with rem/em, as there's a difference more than 1 pixel (which is why a lot of people use px for breakpoints). However, using em-based breakpoints should cover font sizing issues (unlike px, which is device-based or device-multiplier-size-based).

What do you think?

**Comment by mcoker** [comment]
@garrett looks good to me, thanks! @mcarrano has added it to the roadmap for next year.

**Comment by garrett** [comment]
not stale, bot
