### ISSUE TITLE
Introduce Large (marketing) card variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3670]
Introduce a large card variant per the design here:

![image](https://user-images.githubusercontent.com/6619860/98989437-1acb8680-24f7-11eb-972d-f709221d45eb.png)

This will satisfy marketing use cases. Along with this want to introduce a modifier to add rounded corners to any card.

@gdoyle1 can you provide spec for intended corner radius?

**Comment by gdoyle1** [comment]
@mcarrano it's there with #2! I added the variable (it's = 3px radius, same as our buttons)

**Comment by mcoker** [comment]
@mcarrano @gdoyle1 @ajacobs21e do you have a preference for how we name the rounded corners variation? We could call it `pf-m-border-radius` or `pf-m-rounded` or something like that, also assuming we may add this same class to other components.

Also would we want to consider something that's flexible so that we can apply a size modifier in the future to support like `pf-m-border-radius--sm/md/lg`?

**Comment by mcarrano** [comment]
No big preference about naming. Maybe shorter is better? Not sure about the size modifier. Adding @mceledonia to this discussion.

**Comment by mcoker** [comment]
I'm also kind of confused about the examples above where the title is part of the body. Does that mean the user will not be using the card component's title element, and that title is just something they've built on their own using the title component or content component with a heading element? Adding the title to the top specs would help, too. 

It can be a bit confusing looking at our examples. The card is made up of 4 sections - header, title, body, footer. They all have their own space defined between each other. And title can go in header, in which case the title's spacing is removed and adopts the spacing from header.

Here is the default layout where you can see the card title (the text just says header)
<img width="375" alt="Screen Shot 2020-11-17 at 4 28 55 PM" src="https://user-images.githubusercontent.com/35148959/99458483-3b7a4e80-28f2-11eb-9621-445b110df8cc.png">


And here is a header with a title below it
<img width="454" alt="Screen Shot 2020-11-17 at 4 29 05 PM" src="https://user-images.githubusercontent.com/35148959/99458530-4af99780-28f2-11eb-853d-b31b31daab7f.png">

Here is that same layout but focused on the title to show it's spacing
<img width="575" alt="Screen Shot 2020-11-17 at 4 29 11 PM" src="https://user-images.githubusercontent.com/35148959/99458557-564cc300-28f2-11eb-8287-07cb2cf4878e.png">

Here is a title in a header
<img width="446" alt="Screen Shot 2020-11-17 at 4 29 22 PM" src="https://user-images.githubusercontent.com/35148959/99458609-6d8bb080-28f2-11eb-9ae5-5a236377fb6c.png">

And here is the same layout, focused on the title showing it has no spacing applied
<img width="455" alt="Screen Shot 2020-11-17 at 4 29 27 PM" src="https://user-images.githubusercontent.com/35148959/99458647-7c726300-28f2-11eb-93f6-d40ecdadb28e.png">
