### ISSUE TITLE
Jump links subsections - active item/section styling

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3683]
Re: https://github.com/patternfly/patternfly/pull/3632#issuecomment-728528421

Right now there is no way to mark the top-level item with a subsection as current without marking the whole subsection current. Should we be able to do that? In what ways do we want to support active styling with subsections?

cc @mcarrano @lboehling @ajacobs21e

**Comment by ajacobs21e** [comment]
mobile experience https://www.sketch.com/s/f6a52c25-8657-4680-9d3e-4c09131e6ed0/a/Qzdz0G

**Comment by mcoker** [comment]
@DaoDaoNoCode this is ready to work on. The styling should only apply to the active link, not the entire section. 

* When a top-level item of a subsection is current, only the immediate child `.pf-c-jump-links__link` element of `.pf-c-jump-links__item.pf-m-current` should get the blue border and text color styles.

We want to change from this:
<img width="284" alt="Screen Shot 2020-11-25 at 1 20 22 PM" src="https://user-images.githubusercontent.com/35148959/100272567-ffae3d00-2f20-11eb-9caa-a623724ffa12.png">

To this:
<img width="303" alt="Screen Shot 2020-11-25 at 1 19 56 PM" src="https://user-images.githubusercontent.com/35148959/100272578-050b8780-2f21-11eb-9441-6f52ac500015.png">

After making this update, you may see that the nested jump links list (`.pf-c-jump-links__list`) has a grey border that is overlapping the blue border of the current top-level item. That's really a bug, there is no need for nested `__list`s to have a grey border, so you could just disable that grey border on a nested list. You can do that a number of ways, but an easy way would be to change the border-color to transparent or the border-width to 0.

Let me know if you have any questions!

**Comment by mcoker** [comment]
The design for reference:

<img width="1143" alt="Screen Shot 2020-11-25 at 1 59 55 PM" src="https://user-images.githubusercontent.com/35148959/100276086-93363c80-2f26-11eb-81b3-c1a7a24a1b4f.png">
