### ISSUE TITLE
table documentation breaking ToC

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly#3693]
looks like some of the text is throwing off the ToC here
https://pf4.patternfly.org/components/table
cc @redallen

**Comment by redallen** [comment]
In this case I'd rather fix the long formatted title "Long strings in table cells will push content. Add a width modifier to thead th to limit string length or add .pf-m-truncate to tbody td." than fix allowing formatted `code` snippets in the title.

**Comment by jschuler** [comment]
yes I agree would be better to fix the titles
