### ISSUE TITLE
Proposal: Rename Touchspin component to "Number Input" before it is out of beta

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly#3710]
Not sure if anyone else agrees, but I've mentioned this desire in a few different threads about the Touchspin component. It's still in beta, so if we're going to consider a name change I think now is the time.

The name Touchspin is a relic from PatternFly 3, which came from the https://plugins.jquery.com/bootstrap-touchspin/ plugin we were using. It is so named because the plugin was touchscreen-friendly and you could "spin" the number up and down. We're not using this plugin anymore, or Bootstrap at all, and I can't find any other usage of that name anywhere online that doesn't refer to that specific plugin. Also, all of our PF4 components are touchscreen friendly, so the "Touch" part of the name becomes even less meaningful now.

Seeing the name "Touchspin" in the menu doesn't explain at all to a consumer what the component is for (inputting a number in a form). I strongly feel that we should name it something like "Number input" or "Numeric input".

Context: Slack discussions, Discussion in https://github.com/patternfly/patternfly/issues/362#issuecomment-549337804
cc @mcarrano @mcoker @christiemolloy @srambach @kmcfaul

**Comment by mcarrano** [comment]
@mturley Yes, this was a legacy from PF 3 and Bootstrap, but looks like we all agree with renaming. We will start this work in core with this issue: https://github.com/patternfly/patternfly/issues/3706

**Comment by mturley** [comment]
Awesome, thanks @mcarrano ! This issue is a duplicate then, I'll close it. We can open a corresponding React issue when it's changed in core.
