### ISSUE TITLE
[RFE]: Draggable data list with checkboxes needs a design improvement for multi line items

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#3712]
In cockpit we are trying to implement something like this:
![Screen Shot 2020-12-01 at 13 13 49](https://user-images.githubusercontent.com/14921356/100739319-34b20800-33d7-11eb-8764-e00af1e1df90.png)

This is for configuring the bootorder for VMs. 

As you can see the checkboxes get completely misaligned.

This is the issue on the PF4 docs site.
![Screen Shot 2020-12-01 at 13 17 38](https://user-images.githubusercontent.com/14921356/100739610-9bcfbc80-33d7-11eb-8ed3-ce742a9346ca.png)

Should the checkboxes get aligned in the middle? we use them in order to enable/disable the dragging ability of the data list items.

If you feel that too specific request and we should just created a CSS fix locally feel free to close.

**Comment by mcoker** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@KKoukiou @mcoker We currently have an open design issue here around draggable rows: https://github.com/patternfly/patternfly-design/issues/937 I've linked this so we can consider better what to do in this case.

**Comment by KKoukiou** [comment]
This is still problematic for some of our lists.

**Comment by mcarrano** [comment]
@mcoker what do you feel is the best way to address this? Would it be a quick fix to just align the drag handle vertically with the checkbox?

**Comment by mcoker** [comment]
@KKoukiou this looks OK to me, the draggable button has since been top aligned to the row

https://codesandbox.io/s/peaceful-kirch-qygnb?file=/index.js

<img width="207" alt="Screen Shot 2021-06-03 at 7 05 57 PM" src="https://user-images.githubusercontent.com/35148959/120726859-bf66e300-c49e-11eb-8ae8-21c4f0141b19.png">

**Comment by KKoukiou** [comment]
Thanks @mcoker - I did not realize it got fixed in the meantime.
