### ISSUE TITLE
Ability to "scroll to top" on a table

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly#3715]
In Insights Drift, we have a very long tree table that can potentially show 100s of rows on a single page.
It would be great to have the ability to have a single click "scroll to top".

We are planning to implement sticky headers, but if the user needs to access the toolbar they have to scroll *a lot*.

**Comment by mcoker** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@jschuler @tlabaj What would be required to support this?

**Comment by katierik** [comment]
This is still needed!

**Comment by mcarrano** [comment]
@katierik We currently have this issue on the roadmap to support a "Back to top" component: https://github.com/patternfly/patternfly-design/issues/970 This would be a floating button that could be added to long scrolling pages like this to scroll you back to the top of the page in a single click. I think that would be the bast way to solve this problem. This is currently scheduled for release during Q4.
