### ISSUE TITLE
Radio: add support for nested controls

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly#3717]
The Radio component renders a `div.pf-c-radio` which is a `display: grid` container. Currently the only way to render some content under the radio label, but indented at the same level as that label, is to pass the `description` prop which renders something inside a `div.pf-c-radio__description` within that grid container.

The problem is, that `.pf-c-radio__description` class darkens the text color and limits its width, it is designed only for a small text description. I want to implement something like the nested controls example from here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/data-input
![Screenshot 2020-06-10 17 17 51](https://user-images.githubusercontent.com/811963/84319639-5922db00-ab3e-11ea-95f0-245b7960676e.png)

If I place those nested controls inside the `description` prop, the size and color gets messed up, so instead I have to render them outside the Radio, but then I have to indent them separately and they aren't properly aligned within the Radio's grid.

It would be nice for the Radio component to accept arbitrary `children` and just render them inside its `div.pf-c-radio` after the description, making sure they are lined up underneath the label and indented by the same amount.

**Comment by mcarrano** [comment]
@mturley I've transferred this to Core to begin with creating the appropriate structure. This will be a good enhancement. Do you have any particular timeline for needing this? I will need to get it on our roadmap.

**Comment by mturley** [comment]
@mcarrano I don't think this needs a core change. I think it's just an issue with the React component not being flexible enough, I think if you can just put the nested contents inside the existing `div.pf-c-radio` it will work fine, but I'm not sure. I can write up an example of the resulting HTML to make sure it satisfies core folks.

I don't have any timeline for this, I have a sufficient workaround.

**Comment by mcarrano** [comment]
I'll defer to @mcoker on this. ^^^

**Comment by mcoker** [comment]
The radio (and checkbox) components only support the form element, label, and description as elements. We would need to add support for a new section in order to be able to nest content in the radio component and have it be aligned with the label.

**Comment by mturley** [comment]
Ah, got it. Ok yeah that would require a core change then.

**Comment by mcoker** [comment]
@mturley I have a PR up here - https://github.com/patternfly/patternfly/pull/3884. This serves as a general body container, not necessarily tied to being shown/hidden when the input is checked or not. Technically you could have more than 1 of those if you want, too, though I'm not sure if we want to support that. Do you think that works as a means to support a feature where that element hides/shows as you check the radio/checkbox? Or do you think we should have something more specific to the hide/show feature?

**Comment by mturley** [comment]
@mcoker I think that's perfect! The show/hide logic can be left to the consumer, that sounds more flexible anyway. Thanks!
