### ISSUE TITLE
clipboard copy element does not have a thin variant

### ISSUE THREAD

**Issue by ssbarnea** [patternfly/patternfly#3725]
One of the most common use cases for [clipboard-copy](https://www.patternfly.org/v4/components/clipboard-copy/react
) element is to provide an easy way to copy content that is likely needed for pasting in another place, while also reducing the cluttering the UI with generated text (GUID) that has no visual value for humans.

A classic use case would be to provide ability to copy a long GUID or checksum while displaying only a placeholder or abridged version of it in the UI.

The current issue is that if if you want to switch from a verbose text display to a friendly copy/paste variant you endup with a similar amount of extra "UI" complexity that cancels the entire UI improvement.

I will try to explain with few screenshots:

# before adopting clipboard

![](https://sbarnea.com/ss/Screen-Shot-2020-11-18-18-45-10.78.png)

This takes too much screen space as the value by itself does not have any human value. We want to minimize the UI presence while allowing user to easily copy the value as that is almost always the only use-case. In order not to make the feature too hard to discover we may want to keep the first 4 characters visible and to display the copy icon.

# after adopting clipboard

![](https://sbarnea.com/ss/Screen-Shot-2020-11-18-18-44-07.png)

Because the element is also an input we get a lot of extra boarders that are cluttering the UI and also increasing the final height. Another side effect is that this being a div instead of a span it does produce another break after the "UUID" label that describes the field name.

# desired visibility (optimal)

If possible the text should look like below, where the button is only the icon. Ideally it should also not be colored like a link.

![](https://sbarnea.com/ss/Screen-Shot-2020-11-19-09-59-07.90.png)

If we would have a variant that renders only the clipboard icon without anything else, we could easily obtain this behavior.

Related: https://github.com/patternfly/patternfly-react/issues/2044

**Comment by coreyvickery** [comment]
@mcarrano

Is this the correct issue where we can discuss the version for that was made for marketing?

https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/3b793334-4bd3-4208-9366-bba9b8deca8c

cc @ajacobs21e @mceledonia

**Comment by mcarrano** [comment]
@coreyvickery I don't really think these are the same thing. The Clipboard Copy component is designed to integrate the copy action with a text field that holds the content that you want to copy to the clipboard. This issue is not really changing that functionality but just requesting a lighter weight version of that without the border treatments. There is a similar request here: https://github.com/patternfly/patternfly-design/issues/1009

In looking again at your design proposal, I'm not sure that this needs to use the Clipboard Copy component at all since it doesn't include a text edit field. Can't what you want you be accomplished using a link style button with an icon and the label "Copy URL?" The function to copy the URL of the current page to the clipboard can just be tied to the button.

**Comment by mcarrano** [comment]
@ssbarnea please take a look at the inline option proposed here: https://github.com/patternfly/patternfly-design/issues/1009#issuecomment-783588428 Will that meet your needs?

**Comment by coreyvickery** [comment]
@mcarrano Makes sense, what I'm proposing is essentially a Button. I found an example that's similar which also fits into the Button category.

https://lightningdesignsystem.com/components/buttons/#Stateful

**Comment by mcarrano** [comment]
@coreyvickery I like the idea of adding a stateful button like this that would be useful for this and other use cases. Would you mind opening a new issue for this and attaching your designs? I can see about getting it on the feature roadmap as an enhancement to the Button component.

**Comment by coreyvickery** [comment]
@mcarrano Done.

https://github.com/patternfly/patternfly/issues/3889

**Comment by mcarrano** [comment]
Closing in favor of https://github.com/patternfly/patternfly/issues/3906 which is currently in progress.
