### ISSUE TITLE
Visited style for links

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly#3726]
Requesting a design exploration for a visited style for links. Possibly also for other elements (navigation, tabs, buttons, etc?)
@mceledonia

**Comment by coreyvickery** [comment]
@mcarrano @ajacobs21e 

Confirming that we're moving forward with #40199a ($pf-color-purple-600). Is there a dark theme variant?

I don't know about using the visited link style in other components like CTAs, but I'm happy to discuss in a future PF Design Share meeting.

**Comment by mcarrano** [comment]
@mceledonia ^^^

**Comment by mceledonia** [comment]
I think purple-600 looks good, we will definitely want a dark theme variant. What do you all think about purple-300? 

![image](https://user-images.githubusercontent.com/30935938/104049345-d4bb3800-51b2-11eb-90cf-a62a1baa84c0.png)

@ajacobs21e @coreyvickery @mcarrano

**Comment by ajacobs21e** [comment]
@mceledonia what background color do we have to test against for dark? #030303?
My non visual designer opinion is that purple-300 is a little light and I like purple-400 better, which does pass on #030303. But I support whatever you pick :)

**Comment by mceledonia** [comment]
@ajacobs21e I used a color from our in progress dark theme work. We have a few new background colors, and the lightest one it would need to pass on is currently #26292D which unfortunately 400 doesn't make the cut on!

**Comment by ajacobs21e** [comment]
@mceledonia this is why you're the expert! But you asked for my opinion so I had to shove it in there haha

**Comment by coreyvickery** [comment]
@mceledonia When you determine the correct values, can you please post them here?

**Comment by mceledonia** [comment]
@coreyvickery @ajacobs21e Sure thing!

Regular/light theme visited link - `$pf-color-purple-600:            #40199a `
Dark theme visited link - `$pf-color-purple-300:            #a18fff`

**Comment by coreyvickery** [comment]
@ajacobs21e @mceledonia

<img width="1466" alt="Screen Shot 2021-01-31 at 11 20 15 PM" src="https://user-images.githubusercontent.com/45767595/106426961-5f423080-641b-11eb-80a5-d3b4a460a3a7.png">

Are we liking how the purple looks on white? Not too dark?

cc @mcarrano

**Comment by ajacobs21e** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/e74b9f2f-be55-40a7-9df5-87ba61910d68-43372900-a50d-4a62-9369-a4673f0a30c2-v1.png?transparent=1&palette=1&width=246)
I like!

**Comment by mcarrano** [comment]
Per a meeting today with @mattnolting @ajacobs21e @mceledonia @mcoker and @abigaeljamie we will implement this style as part of the PatternFly [content/text component](https://www.patternfly.org/v4/components/text/html) so that users will see the specified styling whenever text is wrapped in that component.  Other instances where links are used will remain unchanged.
