### ISSUE TITLE
Add editable Label Group

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3741]
Add a new variant of the Label Group component to allow for creating new labels and adding them to the group. Here is an example of how this should work:

![image.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/9852f749-c38a-4445-9760-b3caf5a279b5)

**Comment by gdoyle1** [comment]
Having this capability for OpenShift and OCM would be very useful! Today we are able to do the following actions through one modal:

1. edit labels - the way we are doing this today is overwriting key/value pairs by setting key=[value] where [value] is different than the original value key was = to. 
2. add labels
3. delete labels

I'm proposing to be able to edit a label, similarly to how inline editing works, by clicking on a label and having it transform into standard text. That way the user can edit the key/value pair quickly. (see screens 4-6 here https://marvelapp.com/prototype/7iiccdg/screen/75944924)

Here's a recording of the implementation as it exists today on OpenShift

https://user-images.githubusercontent.com/30870144/109845438-24e6d180-7c1b-11eb-82ad-9377994da7b6.mov
