### ISSUE TITLE
Add new List variants

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3743]
Add new variants of the List component to include horizontal separators and icons.

Designs: https://marvelapp.com/prototype/7gc36d1

**Comment by mcoker** [comment]
Just to clarify the text should wrap beside the icon, not underneath it. Like this:

<img width="315" alt="Screen Shot 2021-01-05 at 1 26 43 PM" src="https://user-images.githubusercontent.com/35148959/103689996-ab539f80-4f59-11eb-8d99-257125c1dd2b.png">
