### ISSUE TITLE
Card updates

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3766]
- support for nested cards. that would default to no x-padding and a pf layout would be the expected method to control layout
- support for responsive borders (I have an idear there)
- support for pf-m-plain which strips borders and shadows (edited)

**Comment by bitwiseor** [comment]
Issue #4188 created to address the plain variant

**Comment by mattnolting** [comment]
addressed in https://www.patternfly.org/v4/components/card/html#plain and https://www.patternfly.org/v4/components/card#modifiers
