### ISSUE TITLE
CodeEditor: Needs an error state when an uploaded file fails to upload

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#3777]

**Comment by nicolethoen** [comment]
@mcoker @mcarrano Not sure who should take this issue and run with it, but it is blocking for Code Editor

**Comment by mcarrano** [comment]
Let's just mimic the error state styling in the File Upload component here: https://www.patternfly.org/v4/components/file-upload/html#file-upload-in-form-with-error. It's the same use case, I think.

**Comment by mcarrano** [comment]
@nicolethoen do you still think this is needed? If so, I will add to the roadmap.
