### ISSUE TITLE
Button text should be selectable

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly#3828]
The QE team on Insights (cloud.redhat.com) recently went to select the text of button links in order to copy and paste. However, they were unable to which was unexpected. This is related to the CSS prop `user-select` that was added [here](https://github.com/patternfly/patternfly/commit/80b3e891a38eea069352420343b97c82343653f7). 

I was talking to @mcoker and we agreed that this does seem arguably unexpected. I believe that the original case for this interaction was in [this issue](https://github.com/patternfly/patternfly/issues/802), but I think it's just as easy to argue the opposite. If they select the button, I would expect it to be copied like how alt text on an image is copied. Coker put together two code pens exemplifying this: [this one](https://codepen.io/mcoker/pen/mdOJJdQ) shows the difference between a button that has text that can be selected compared to one that can't, and [this one](https://codepen.io/mcoker/pen/eYBNNZg) shows how you can copy the alt text of an image. 

The current workaround would be to add a custom style in their application `.pf-c-button { user-select: auto; }` but even if this is changed, the original issue still affects anyone who uses the PF4 button component and other parts of the platform would still have the old way. There are also arguments to be made that using `user-select` can be bad UX like [this discussion post](https://ux.stackexchange.com/questions/83184/is-user-select-none-bad-ux) goes through. 

If there is an image or icon or something in a link, maybe you want to right click on the icon and download it. Or copy/paste the text from it. And if we stay with this pattern here where you can't select the text in a button, should we also disable it in places like navigation links? I think overriding the default browser behavior is unexpected here and we should enable users to select text. Or perhaps we can make the argument to not disable it globally but in places where inadvertently selecting the button text interferes with the function of the button. I think this is definitely a discussion that should be had though. 

@cdcabrera

**Comment by cdcabrera** [comment]
This is something we're experiencing in Subscription Watch, https://github.com/RedHatInsights/curiosity-frontend 

The behavior happens through the use of the PF(4)-React "button" component in this scenario, which also applies towards our use of anchor tags, since that option is available through the use of said component.

Disabling default browser behavior is generally unexpected behavior.

@ntkathole
