### ISSUE TITLE
Table Toolbar - Reduce L&R spacing to match T&B

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly#3834]
Currently, toolbars have 24px L&R padding (XL breakpoint), which looks odd as the T&B padding is 16px:
![Xnip2021-01-18_12-00-22](https://user-images.githubusercontent.com/23172038/104946589-5156cf00-5988-11eb-9f72-999354ac3aef.jpg)

Proposal is to adjust this padding to 16px all around for all breakpoints:
![image](https://user-images.githubusercontent.com/23172038/104946535-37b58780-5988-11eb-99e8-00ed4457c1ea.png)

**Comment by mcarrano** [comment]
Alternatively, maybe we should consider making all margins 24px to reduce risk of misalignment? May have dependency on PF5 theming work.

**Comment by kuklas** [comment]
hey, @mcarrano is this considered in PF5? w

**Comment by mcarrano** [comment]
@mceledonia @mcoker can you answer @katierik 's question?

**Comment by mcoker** [comment]
@mcarrano @kuklas it will, but a bit different from the request in the title/description. Currently the L&R padding/spacing seen is shared with the page chrome as a global gutter that changes dynamically/responsively based on veiwport size between 16px ("md" spacer) on small screens and 24px ("lg" spacer) on large screens. For v5 we're using a single spacer for all viewports (24px), so the T&B padding will also change to 24px to better align with everything around it.
