### ISSUE TITLE
Textarea Autosize/Autoexpand

### ISSUE THREAD

**Issue by andrewballantyne** [patternfly/patternfly#3837]
Would like to request that we could get the Textarea component (https://www.patternfly.org/v4/components/text-area) to get an auto-size ability when the user hits enter, it expands to contain all the text. Ideally we'd want it to shrink again if the user removes lines.

This is an ask for React PF, but was suggested to log here first and see where the logic needs to go first. 

cc @mcarrano 

Thoughts on design:

* starts at the default size
    * would be useful if this was configurable (ie `rows` or `min-height`?) 
* when the user reaches the end of the height of the area, the next 'enter' grows the box to support the new line
* when the user removes a line, it shrinks back down (until it hits the "default" size)

**Comment by mcarrano** [comment]
@mcoker @tlabaj can you take a look at this request? It came up in the OpenShift meeting today. I wasn't sure what would be required to enable this behavior since I know that we are currently using a browser native control for the text area.

cc @evwilkin

**Comment by mcoker** [comment]
From the core side, I think we would just want to add variable support for manipulating the textarea height since there are no vars in place currently. That would support defining initial size/min-height (and optionally a max-height), and a var the react component can set inline that manipulates the textarea element height.

**Comment by mcarrano** [comment]
Thanks @mcoker . I will get this on the PF roadmap then, starting in Core. Are you needing this in any specific timeframe @andrewballantyne ?

**Comment by andrewballantyne** [comment]
@mcarrano 4.8 of OCP. April 9th is Feature Freeze, so ideally before that.

**Comment by mcarrano** [comment]
Thanks @andrewballantyne . I will try to get this into the queue for our 2020.04 (end of March) release.

**Comment by andrewballantyne** [comment]
Is this going to make its way as a configurable Prop in the React component? @mcoker / @mcarrano
