### ISSUE TITLE
Drawer: box shadow and splitter are losing css when the panel is thin 

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly#3840]
For resizable drawers, the box shadow is lost when the drawer panel is very thin (the width of the splitter only), and the splitter itself sometimes loses one of its borders (I believe because it is resizing to be thinner than the splitter's width). Is it possible to impose a minimum width for the splitter, and keep the shadow at any width?

**Comment by mcoker** [comment]
Looks like a dupe of https://github.com/patternfly/patternfly/issues/3795

**Comment by kmcfaul** [comment]
You are correct! I will close this one then.
