### ISSUE TITLE
Update menu section header styling

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3844]
Want to update the visual styling of section headers that appear in all dropdown menu components including Dropdown, Select, Menu, Application launcher, and Options menu.

New header designs:

![image.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/30439048-5451-45a3-89a7-64712cbec15d)

Specs:

Text - Size $pf-global--FontSize--xs -- Color $pf-global--Color--200
Spacing - All the same

**Comment by nicolethoen** [comment]
@mcarrano can this be added to an upcoming milestone?

**Comment by blfetche** [comment]
@mcarrano @mcoker @srambach 
Applied only to dropdown menu for now, please review. Thanks

https://patternfly-pr-4917.surge.sh/

![Screen Shot 2022-06-21 at 11 26 21 AM](https://user-images.githubusercontent.com/96086344/174886582-71bb7325-9e6f-4405-a69c-e4440865e784.png)
