### ISSUE TITLE
Resizable drawer is unresponsive on Firefox

### ISSUE THREAD

**Issue by rottencandy** [patternfly/patternfly#3851]
**Describe the issue. What is the expected and unexpected behavior?**
The resizable drawer does not respond to mouse drag or keyboard controls on Firefox 72.0 and below,
but works as expected on other browsers _including_ Firefox 85.
I'm unsure of which exact Firefox version fixes the issue.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Reproducible in Firefox 72 on PatternFly release 2021.01, on the examples page: https://www.patternfly.org/v4/components/drawer/#resizable-on-right

https://user-images.githubusercontent.com/20013884/107532113-8e0e9280-6be3-11eb-8971-33d67cedd801.mp4

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug, haven't found a workaround.

**What is your product and what release version are you targeting?**
OCP 4.8

**Comment by evwilkin** [comment]
@rottencandy After initial investigation it requires bigger changes than we initially suspected - can you clarify the time frame you're looking to have this fix by in order to fit it into OCP 4.8?

**Comment by rottencandy** [comment]
> @rottencandy After investigation this requires bigger changes than we initially suspected - officially we support the latest version of Firefox, and it looks like the styles used here (and in some other places) are supported from Firefox 75+. Can you confirm which browsers OCP 4.8 supports - is this page current?
> 
>     * https://access.redhat.com/articles/4763741

@evwilkin yes, going by the page OCP 4.8 won't support Firefox < 75. I believe this bug won't be a blocker for us.
cc: @christianvogt @rohitkrai03

**Comment by evwilkin** [comment]
@rottencandy Thanks - it looks like the issue is caused by the use of `clamp`, `min`, and `max` which are supported in FF 75+.

However, it looks like `clamp` is supported in all OCP-listed browsers except Safari - it is [supported in Safari 13.1](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()#browser_compatibility) but OCP supports back to version 13 (per the chart linked above, for OCP 4.6).

Do you know which Safari version OCP 4.8 will officially support?  If it remains at Safari 13, we may still want to look at replacing `clamp` with a mix of `min` and `max`.

**Comment by christianvogt** [comment]
@evwilkin that's a good question on safari since the page doesn't mention anything about the safari minor versions. 
If you have a fix that works across everything with the same behavior, I'd say it's worth using it.
We can look into specifically what version of safari is supported.

**Comment by rottencandy** [comment]
Thanks @evwilkin. Is it possible to know when this fix would land in the `@patternfly/react-core` package?

**Comment by redallen** [comment]
It's already in what we're planning to release today or tomorrow:
```
@patternfly/react-catalog-view-extension@4.10.0
@patternfly/react-charts@6.14.0
@patternfly/react-code-editor@4.1.23
@patternfly/react-core@4.97.0
@patternfly/react-icons@4.9.0
@patternfly/react-inline-edit-extension@4.6.34
@patternfly/react-styles@4.8.0
@patternfly/react-table@4.23.0
@patternfly/react-tokens@4.10.0
@patternfly/react-topology@4.7.32
@patternfly/react-virtualized-extension@4.6.33
```

**Comment by evwilkin** [comment]
Hi @rottencandy just confirming that this release is now live - release notes on the Drawer change [here](https://www.patternfly.org/v4/developer-resources/release-notes/html) and final version numbers for react-core on that link under the `React` tab.  Thanks!
