### ISSUE TITLE
Search input: add auto-complete variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3863]
Add optional auto-complete to the Search input component.

Designs here: https://docs.google.com/document/d/1mFOuhoAJNBSWKHZKwz8T6OVk71OWNPhfAuVF1Jw3BAk/edit?usp=sharing

**Comment by mcarrano** [comment]
@mcoker I've opened this issue so we can pull it into the 2021.03 milestone. We are still reviewing this design, but expect to finalize this week.

**Comment by mcoker** [comment]
@mcarrano checking to see if this is OK to begin working on? Also I'm assuming the advanced search box can be open at the same time, and the auto-complete box would open on top?

**Comment by mcarrano** [comment]
Yes, that's correct.
