### ISSUE TITLE
form: vertical alignment issues

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#3868]
1. There are issues with the checkboxes and radio buttons not being properly aligned with their textual labels. This is slightly different per browser.
2. Labels for form elements are down too low (or are elements too high?)

Included are screenshots that show these issues, from Firefox:

In Cockpit:

![Screenshot from 2021-02-17 13-00-25](https://user-images.githubusercontent.com/10246/108204183-c5b99500-7123-11eb-9149-55748376adea.png)

![Screenshot from 2021-02-17 13-00-16](https://user-images.githubusercontent.com/10246/108204185-c5b99500-7123-11eb-961e-26cbe5d1544e.png)

On the PatternFly website:

![Screenshot from 2021-02-17 13-08-19](https://user-images.githubusercontent.com/10246/108204176-c3efd180-7123-11eb-9f8b-29ea0fe20c61.png)

![Screenshot from 2021-02-17 13-07-27](https://user-images.githubusercontent.com/10246/108204180-c520fe80-7123-11eb-800c-e18e004be543.png)

Expect results would be:
- Checkbox and radio buttons should look vertically centered to the first line of text
- Labels and form elements should be aligned to baseline

**Comment by garrett** [comment]
For checkboxes, this seems like an appropriate solution:

.pf-c-check > .pf-c-check__input {
    // Set the height of the input widget to be the same as its label
    --pf-c-check__input--Height: var(--pf-c-check__label--FontSize);
    // Offset by the top half of the difference between the height and the line height
    --pf-c-check__input--MarginTop: calc((var(--pf-c-check__label--LineHeight) - 1) / 2 * var(--pf-c-check__input--Height));
}

...at least for checkboxes nested inside labels. I haven't checked checkboxes next to labels yet. Nor have I gotten to radio buttons (although I assume they're the same). 

The restuls of the above code was checked in Firefox, Chrome, and WebKit.

**Comment by mceledonia** [comment]
Nice catch @garrett I think this is something worth resolving. I wonder if it is related to the misalignment in #3880?
CC @mcarrano @mcoker
