### ISSUE TITLE
validated="error" styles for Select component 

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#3874]
PF currently does not support a `validated='success' | 'warning' | 'error' | 'default'` on the Select component, whereas it does for the Form Select component, as shown below. Is it possible to add similar styles for the Select component that we have for the Form Select component?

<img width="824" alt="image" src="https://user-images.githubusercontent.com/21063328/108427843-c0377a00-720b-11eb-8c75-c222e5c4e6e8.png">

For my use case, I'm primarily interested in the error styles, but given that these are similar components, maybe all validated states would be useful.

cc @christiemolloy

**Comment by mcoker** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@jgiardino I don't see any reason we couldn't support that, do you @mcoker ? But I am curious if there's a reason to not use the Form Select. Does your use case involve data entry into a form? I believe we were expecting that you would use a form select there vs a Select more for things like filters. @mmenestr also wanted to see if making this addition would conflict with anything we say about select usage in our guidelines.

**Comment by mcoker** [comment]
Sounds good to me, seems well suited for the select and potentially the options menu, too.

**Comment by jgiardino** [comment]
Here are more details about our use case:
In our implementation of filters, we have a couple of cases the user could encounter that we need to inform the user about. We have a limit on how many filters can be applied at one time. We also validate on the free-form text input for "Name" which doesn't allow certain characters. I didn't see any examples explaining how to handle validation in the context of the PF filter design guideline. So our approach for now is to display a validation message in a tooltip, and use the validated prop on the input. But we don't have a validated prop on the select component (where we're using the checkbox variant of Select for multiselection). 

Let me know if there's another approach that you'd recommend for this use case, and if that approach is currently supported with the PF components.

**Comment by mcarrano** [comment]
Thanks for providing that additional detail @jgiardino . So I think we should get this on the roadmap then. Is there a particular time from you require this for? And remind me what the project is.

@mmenestr is this something we should also address in the filter guidelines or do you have other guidance regarding these error states? It's true that it's not something we really considered.

**Comment by jgiardino** [comment]
This would be for the app services bundle we're working on for clouddot. We're expecting to have an external eval available in April.

**Comment by mmenestr** [comment]
I think this would be fine to add! Had never considered this before either but I definitely see the value in it for those situations. It might be worth adding a short "validation" section to the filter guidelines to address this, but I would hold off until it's implemented!

**Comment by jgiardino** [comment]
I can demo what we have currently for filter validation, if that is helpful at all.

**Comment by mcarrano** [comment]
@jgiardino I can get this on the roadmap for our April 21 release. It will require both core styling and React follow-up, I believe to enable these styles. Can you confirm @mcoker and @tlabaj ?

**Comment by mcoker** [comment]
@mcarrano yep that's correct.
