### ISSUE TITLE
Search Input used in Toolbar will shift content to the right.

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly#3894]
If you use the search input component within a toolbar as shown in the following example.  It will push over the content when you type in it.  The team was expecting the content in the toolbar to not move to the right.

https://codesandbox.io/s/searchinputintoolbar-19538

CC: @srambach

**Comment by mcoker** [comment]
cc @mcarrano can we add this to a future milestone?

**Comment by mattnolting** [comment]
- [ ] Add width control to toolbar
- [ ] Add width control to search input
