### ISSUE TITLE
Add new Copy to Clipboard variants

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3906]
Want to enhance the Clipboard Copy component to add new variants for single line borderless and inline option. The goal is to provide light-weight, read-only versions of the components that can include additional actions per this design issue. https://github.com/patternfly/patternfly-design/issues/1009  

@lwigh can you attach a link to your final design mocks?

**Comment by lwrigh** [comment]
Here is the Marvel link to the inline and single line mocks: https://marvelapp.com/prototype/g39724e The first mock features the step by step interaction points that are out of context of the Quick Starts. Let me know if any other additional states need to be documented.

**Comment by mcarrano** [comment]
Thanks for posting @lwrigh 

@mcoker please take a look at this when you get a chance. I wasn't sure if the Inline and Single line were really different. Seems like the only difference in the design is the height of the gray background. Not sure what drives that height, but I think the idea is that when placed within a paragraph of text, this shouldn't need to change or increase the text spacing.

**Comment by mcoker** [comment]
@lwrigh I see a feature of the inline variation is the ability to click on the code and copy to clipboard.

<img width="274" alt="Screen Shot 2021-03-08 at 5 58 43 PM" src="https://user-images.githubusercontent.com/35148959/110397940-640c8c80-8038-11eb-875b-64cbe11b0b34.png">

But also if there is overflow text, clicking on the text shows a text cursor and allows the user to scroll/select the text in the input like a regular read-only text input (like the read-only inputs here - https://pf4.patternfly.org/components/clipboard-copy#expandable)

<img width="612" alt="Screen Shot 2021-03-08 at 5 58 52 PM" src="https://user-images.githubusercontent.com/35148959/110398024-91593a80-8038-11eb-9db8-334c63ce2e19.png">

How would you differentiate those two features? When would clicking on one copy the text, and clicking on the other focuses the text and lets you scroll in the text input?

Also @mcarrano it seems like for consistency, we might want to support that basic feature (clicking the text to copy it) in the current clipboard copy component?

**Comment by mcarrano** [comment]
@mcoker That's a good point about enabling a mouse event on the field. @lwrigh do you feel that's an important part of the design? Would it be OK to require the user to click the copy button, only, to initiate the action?

**Comment by lwrigh** [comment]
> @lwrigh I see a feature of the inline variation is the ability to click on the code and copy to clipboard.
> 
> <img alt="Screen Shot 2021-03-08 at 5 58 43 PM" width="274" src="https://user-images.githubusercontent.com/35148959/110397940-640c8c80-8038-11eb-875b-64cbe11b0b34.png">
> 
> But also if there is overflow text, clicking on the text shows a text cursor and allows the user to scroll/select the text in the input like a regular read-only text input (like the read-only inputs here - https://pf4.patternfly.org/components/clipboard-copy#expandable)
> 
> <img alt="Screen Shot 2021-03-08 at 5 58 52 PM" width="612" src="https://user-images.githubusercontent.com/35148959/110398024-91593a80-8038-11eb-9db8-334c63ce2e19.png">
> 
> How would you differentiate those two features? When would clicking on one copy the text, and clicking on the other focuses the text and lets you scroll in the text input?
> 
> Also @mcarrano it seems like for consistency, we might want to support that basic feature (clicking the text to copy it) in the current clipboard copy component?

@mcoker Being able to click on the code snippet to complete the action is an ask from OpenShift so we'll need that functionality for the OpenShift use case of the component. 

For the truncated version, maybe we could increase the width of the border around the code snippet so if the user clicked on the wider border that would initiate the copy to clipboard action. To focus on the text, the user could click into the immediate content area around the code snippet. @mcarrano @mcoker What do you think of that option?

**Comment by mcoker** [comment]
@lwrigh are you suggesting something like this where the padding around the text initiates the copy action, and clicking on just the text itself focuses in the text? https://codepen.io/mcoker/pen/WNoYwQJ

**Comment by lwrigh** [comment]
@mcoker Yup that's exactly what I was thinking of! That looks good 👍

**Comment by mcarrano** [comment]
I like that, too, @mcoker . For the existing Clipboard Copy component, I'd leave that as is since it has a button that is separate from the field and therefore I think should keep standard input group behaviors.

**Comment by mcoker** [comment]
@lwrigh @mcarrano Would the cursor change to a text cursor when hovering apply to any inline copy clipboard, or would that only happen when there is overflow text?

**Comment by lwrigh** [comment]
@mcoker I'm assuming the text cursor would only appear when there's overflow text.

**Comment by mcoker** [comment]
@lwrigh I don't believe there is a way to do that using CSS. I believe what will need to happen is the react component will detect whether there is overflow text or not, and would need to make a modification to the component to say that the text is focusable if there is overflow, otherwise it is not. 

Also that would imply that as the clipboard copy changes size and goes between having overflow text and not, the way you interact with the text changes. Also that if 2 clipboard copies are on the same page, and one has overflow text, and the other doesn't, the interaction for those 2 would be different, too. Just want to make sure that's expected? I've updated the [codepen](https://codepen.io/mcoker/pen/WNoYwQJ?editors=1100) with an example of that.

**Comment by lwrigh** [comment]
@mcoker That sounds good to me if the React is able to do that. 

That prototype matches up with what I would expect for the most part. I think the only thing that's missing is the focus state that should appear around the content area when the user clicks on the overflow text. Between the truncation ellipses and the inner content area focused state, I think that should provide enough feedback to the user so they can easily differentiate between the two copy to clipboards if they're on the same page.

**Comment by mcarrano** [comment]
@lwrigh @mcoker I'm uncomfortable with the difference in behavior of one instance that overflows and the other one that doesn't. I'd like to propose a different approach. The standard way we are addressing this case in PatternFly today is to just truncate the text and provide a tooltip on hover. Seems like that's the best approach here. There doesn't seem like another reason for the text to be focusable since the field is always read-only, right? Clicking anywhere on the component should take a mouse event and copy the contents to the clipboard, changing the contents of the tooltip message to confirm the copy. This will continue to satisfy the requirement to let the user click directly on the text to initiate the copy without burdening the React component of implementing the complex logic described above. Does this work?

**Comment by lwrigh** [comment]
@mcarrano @mcoker After some further discussion with the OpenShift team, I think we'll be going away from having the user click the code snippet to copy it to clipboard. It was getting too confusing with use cases that came up with wanting to copy parts of the code snippet so we'll be sticking to having the user click the clipboard icon to execute the action. Let me know if you have any questions about that decision.

**Comment by mcarrano** [comment]
I actually like that a lot better @lwrigh . It avoids a possibly unexpected interaction. @mcoker hate to shift gears on you, but any problem with just going back to simply a text input plus a plain button?

**Comment by lwrigh** [comment]
Here's the latest design document with updated designs: https://docs.google.com/document/d/1wahjAyDNbWomtqk8Zuz_7NrTmD1oKT1DonBjaWuzUos/edit?usp=sharing

**Comment by lwrigh** [comment]
![Design notes for PF](https://user-images.githubusercontent.com/20227374/111368752-a2bfc980-866c-11eb-843f-13907af9991b.png)
Here is a breakdown of the updated interactions that's featured in the design document above. Let me know if you need clarification on anything.

**Comment by mcoker** [comment]
@lwrigh I've put up a PR with this new variant here - https://github.com/patternfly/patternfly/pull/3933

**Comment by lwrigh** [comment]
That looks good to me @mcoker !

**Comment by christianvogt** [comment]
If you put two code block immediately adjacent they end up looking like this. Can you tell what is being copied by each?

![image](https://user-images.githubusercontent.com/14068621/111499857-c3922880-8719-11eb-9a36-e3d1d92e7076.png)
