### ISSUE TITLE
Introduce Code Block component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3907]
Code Block is a new component for presenting a snippet of read-only code. It is lighter weight than the Code Editor in both appearance and code footprint. It supports optional actions but not editing. 

Design issue. patternfly/patternfly-design#1009

@lwigh can you attach a link to your final design mocks?

**Comment by lwrigh** [comment]
Here is the Marvel link to the code block mocks: https://marvelapp.com/prototype/c2i36cd The first mock features the step by step interaction points that are out of context of the Quick Starts. Let me know if any other additional states need to be documented.

**Comment by mceledonia** [comment]
@christianvogt @mcarrano @lwrigh I do like the float-right solution christian has there. It scales well for large/small whereas the proposed horizontal layout ends up using more space than it needs to in certain circumstances. I don't think we considered this as an option before, it could be a good evolution of the proposal.

**Comment by mceledonia** [comment]
Could we potentially have the layout shift to float-right when there's ample room for it, looking at this from a responsive perspective? So a larger breakpoint could shift to float-right to not add the additional horizontal space when it's not needed.

**Comment by christianvogt** [comment]
While quick starts in a resizable drawer may begin with a smaller available width, it is just the first use case driving this component. We need to consider this could be used by others in main content areas where there is ample space available.

After all this is going to be a generic component.

**Comment by mcoker** [comment]
@lwrigh I have a PR for the component up here. I've gone with what's in the marvel designs for now. https://github.com/patternfly/patternfly/pull/3937

**Comment by lwrigh** [comment]
@mcoker That's looking good to me! Upon hover there should be a tooltip that tells the user what the action does, should that just be noted in the design documentation? I can see that being an optional part of the component depending on what the user needs from the component.
