### ISSUE TITLE
Close button in modal does not have a unique identifier

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#3913]
I'm not sure if this is an issue for core or react.

The issue we currently have is we'd like to be able to identify the Close button for testing, metrics, etc... The close button currently uses PF classes for buttons that could be used by other buttons in the modal, rather than a BEM class identifying it as an element in the modal. The react component says that it has a [className prop for the close button](https://www.patternfly.org/v4/components/modal#modalboxclosebutton), but none of the Modal react examples currently have a ModalBoxCloseButton component where this prop would be used.

With the current implementation, we can't uniquely target a close button in the modal if there are other buttons that also include the classes `pf-c-button pf-m-plain`, because we can't pass any custom html attributes to the Close button for this purpose. 

This isn't super critical at the moment, since we don't have buttons with these classes. But it's a very possible scenario in a future modal implementation.

**Comment by mcoker** [comment]
@jgiardino @tlabaj unless the `id` has a role for a11y (maybe for use with `aria-labelledby` along with the `id` of the modal title?) this seems like a react-only change.

**Comment by jgiardino** [comment]
Closing this and moving it to https://github.com/patternfly/patternfly-react/issues/5856 instead.
