### ISSUE TITLE
Page demo screenshot not showing

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3916]
From https://www.patternfly.org/v4/components/page/html-demos/

<img width="1277" alt="Screen Shot 2021-03-08 at 10 19 53 AM" src="https://user-images.githubusercontent.com/35148959/110348977-d741de80-7ff7-11eb-8837-c9fda1e39e9d.png">

cc @srambach

**Comment by redallen** [comment]
If core fixes the title this release we can update the screenshot in org.

**Comment by mcoker** [comment]
@redallen should I update the release notes with this PR to get it in the 2021.03 release?

**Comment by redallen** [comment]
If you'd like to put this PR in the release notes, sure! If you don't want to it's not a big deal.

**Comment by mcoker** [comment]
@redallen cool! As long as we can fix it on org, I'm fine with it going into the next release.

**Comment by redallen** [comment]
I don't think we can't fix it in org without the edits to `src/patternfly/demos/Page/examples/Page.md` :(

**Comment by mcoker** [comment]
@redallen oh sorry, I misunderstood. Updated the release notes.
