### ISSUE TITLE
Tab content/content - add padding variant

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3918]
In some instances, the tab content or regular content needs padding. We can either use `utility` classes or build `padding` modifiers into the component. 

This is an example of `tabs` and `tab-content` inside `pf-c-sidebar`. One could either use `pf-c-card__body` inside `pf-c-sidebar__content`, use a `utility` class, or we could add `padding` mods to `pf-c-tab-content`.
<img width="824" alt="Screen Shot 2021-03-08 at 12 15 28 PM" src="https://user-images.githubusercontent.com/5385435/110356343-22fc8400-8008-11eb-921a-7f116136173e.png">

**Comment by mcoker** [comment]
Resolved in https://github.com/patternfly/patternfly/pull/3914/
