### ISSUE TITLE
Add actions footer to Standard Menu

### ISSUE THREAD

**Issue by cntlsn** [patternfly/patternfly#3921]
At Red Hat 3scale API Management we have a use case where an actions footer is displayed at the bottom of a dropdown menu, please see the screenshot below:
![image](https://user-images.githubusercontent.com/2865173/110454564-ae891a00-80c7-11eb-8ca9-2f8a0371ff76.png)

The actions footer was added to the context selector component in https://github.com/patternfly/patternfly/issues/3475, but adding it to a standard menu is also a valid enough use case?

Thank you!

**Comment by mcoker** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@cntlsn we do currently have an open design issue with a similar request. See https://github.com/patternfly/patternfly-design/issues/928 That is currently being worked on by @mmenestr .  Do you agree that these are duplicates? If so I will close this in favor of the existing request. But let me know if you have specific schedule requirements. This is currently on the roadmap for our May release.

**Comment by cntlsn** [comment]
@mcarrano it does look like a duplicate, we can close. I actually looked for existing issues before posting this one, I guess we just used different terms to refer to the same components ;)
