### ISSUE TITLE
Card actions element margin

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3924]
Looks like the header toggle margin vars were applied to the card actions element - https://github.com/patternfly/patternfly/pull/3586/files#diff-f77b58a7cf3d9657d084dec7fcc8ac27020c93e9dedea7d718cc122ccf48cd83R135

Card actions should have its own vars. Also the negative top/bottom margin only works with card actions if there is a plain button/dropdown. If there is only a checkbox or regular/primary button, for example, the alignment of the actions element is off. And it does not need a margin-right.

**Comment by mcarrano** [comment]
Related to #4958
