### ISSUE TITLE
Add disclosure panel variant for Expandable section

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3952]
Add a new Disclosure panel variant for expandable sections. This will be optimized for use to display marketing oriented content. See designs here: https://www.sketch.com/s/f6a52c25-8657-4680-9d3e-4c09131e6ed0/p/disclosure

**Comment by mcoker** [comment]
@mcarrano the sketch link isn't working - can you provide another reference for the design?

**Comment by mcarrano** [comment]
Here is another link: https://marvelapp.com/prototype/657ed82

**Comment by mcoker** [comment]
@mcarrano great, thanks. Is the shadow around the component part of the component design or just something that's in the mockups?

**Comment by mcarrano** [comment]
I think that is an intended part of the design. @ajacobs21e can you confirm? I believe these were your mocks.

**Comment by ajacobs21e** [comment]
https://www.sketch.com/s/00432cc6-fd0c-454f-bdd6-c9720ceebbdc/p/3808A315-C566-4A2F-8BD1-94D092C61D8E

I can't remember why that shadow was used. It's not one of the standard PF shadows. @coreyvickery do you remember?
I think this should follow the accordion, which doesn't have a box shadow anymore. 
@mceledonia wdyt?

**Comment by mceledonia** [comment]
@ajacobs21e That sounds good to me, we have been shifting towards a new rule for when to use shadows - only when the element is higher in the Z plane, or overlapping other elements. So a flyout side panel would use a shadow, but an inline side panel would not. Removing the shadow here would be consistent with that as well.

**Comment by coreyvickery** [comment]
@ajacobs21e I don't remember, but this is what our Disclosure looks like currently.

https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/e5f80536-7da1-421e-813a-1cb974cfcd02

**Comment by ajacobs21e** [comment]
@mceledonia does this look good? it's bordercolor-100
https://www.sketch.com/s/00432cc6-fd0c-454f-bdd6-c9720ceebbdc/v/rMn8jD/a/0D2ZYy/r/WoxlPn

@coreyvickery do you know if your designs are using one of the PF drop shadow options?
https://www.patternfly.org/v4/guidelines/colors#shadows
small 
![image](https://user-images.githubusercontent.com/6415742/120817721-f3361d00-c51f-11eb-801f-558179603e19.png)

med
![image](https://user-images.githubusercontent.com/6415742/120817794-ffba7580-c51f-11eb-92eb-9ab502bf41d8.png)

large
![image](https://user-images.githubusercontent.com/6415742/120817818-0648ed00-c520-11eb-829c-55479727240a.png)

**Comment by mceledonia** [comment]
@ajacobs21e Looks great!

**Comment by srambach** [comment]
Would this be the same sort of "marketing"-type component as the card, accordion, tile, and button that we use the `pf-m-display-lg` modifier for?
Also, are the title and call to action an integral part of the component, or simply content that might appear in it?
@mceledonia @mcarrano @ajacobs21e

**Comment by mcarrano** [comment]
> Would this be the same sort of "marketing"-type component as the card, accordion, tile, and button that we use the pf-m-display-lg modifier for?

Yes, this is basically a variant that can be used for marketing-type content although it could be used anyplace where you want to place content inside of a closable panel.

**Comment by srambach** [comment]
@ajacobs21e Can you give me font sizes? I can't see them here so I'd be guessing. https://www.sketch.com/s/00432cc6-fd0c-454f-bdd6-c9720ceebbdc/v/rMn8jD/a/0D2ZYy
Also, I wanted to verify the max width of the text. I see the 750px + 2(24px padding) = 798. However, we have a breakpoint at 768 and I wanted to make sure it wasn't your intention to map to that in some way. It would be great to use some combination of breakpoint and spacer settings, but 750 and 798 don't map to anything easily.

**Comment by ajacobs21e** [comment]
@srambach the text is regular body copy in both the disclosure and the content panel. 
I will leave it up to your expertise to define the breakpoints. The intention was to make it so the text wraps at some easy to read point even if the component was the full page width. A 768 breakpoint with text max width of 720 (with 2 24px spacers) makes sense to me. @coreyvickery does that work for you?

**Comment by coreyvickery** [comment]
@ajacobs21e Works for me, thanks.
