### ISSUE TITLE
Select - when using a scrollable list, search filter and footer should remain fixed

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3975]
This is what the menu looks like when using `maxHeight` with the select component. The whole box scrolls instead of just the list of items.

<img width="822" alt="Screen Shot 2021-04-05 at 7 22 43 PM" src="https://user-images.githubusercontent.com/35148959/113641991-5bfa3980-9644-11eb-80b4-e6b17db68395.png">

The search filter should probably remain static. And with the upcoming footer enhancement from https://github.com/patternfly/patternfly/pull/3968, the list should scroll between the filter and footer, like the context selector (below)

<img width="279" alt="Screen Shot 2021-04-05 at 7 24 02 PM" src="https://user-images.githubusercontent.com/35148959/113642043-821fd980-9644-11eb-90ba-4b4d416663a7.png">

wdty @mcarrano?

**Comment by mcarrano** [comment]
Yes, I totally agree @mcoker . Is this something we can just fix or do you want me to add it to the next sprint?

**Comment by mcoker** [comment]
@mcarrano the next sprint sounds great.

**Comment by mattnolting** [comment]
The fix for this inside the select component would be a significant breaking change, as the search element is a child of the `menu`, where `pf-c-list` is not present, and `footer` is a sibling of `list`.

It looks like this when footer isn't present.
```
.pf-c-select__menu
  li 
    .pf-c-select__menu-item
  li
    .pf-c-select__menu-item
  li
    .pf-c-select__menu-item
```

And this when footer is present.
```
.pf-c-select__menu
  .pf-c-select__menu-list
    li.pf-c-select__menu-wrapper 
      .pf-c-select__menu-item
    li.pf-c-select__menu-wrapper
      .pf-c-select__menu-item
  .pf-c-select__menu-footer
```

Also, there's no `maxHeight` support in the `select`. I think the best solution to this issue, is to close it and open an issue to menu component to `dropdown/select`, when it's promoted.

**Comment by mcoker** [comment]
re: `maxHeight`, sorry I should have been more specific - it's a react prop https://patternfly-react.surge.sh/components/select#props

I was thinking we could introduce a scrollable variation that would opt in to the new markup and wrap whatever the items are in `__menu-list` and that's the element that would scroll. Or we could just leave it as it is and address using the menu component when it's promoted.

**Comment by mcarrano** [comment]
@mcoker what did we decide about this? Should I get it on the roadmap?

**Comment by mcoker** [comment]
@mcarrano I think the fix is implementing a scrollable variation for the select menu that opts in to different markup for the select list. I think it's just a matter of whether we want to support that now or encourage using the menu component, which has this ability built in already. I'm fine either way, I don't think it's a heavy lift to create the scrollable variation.

**Comment by mcarrano** [comment]
Hmmm... Maybe we don't fix this and encourage use of the Menu component in that case. What do you think @nicolethoen @tlabaj ?

**Comment by nicolethoen** [comment]
I'd support that
