### ISSUE TITLE
Feature: width limiter component

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3976]
```
$pf-c-width-limiter--breakpoint-map: build-breakpoint-map();

// width limiter
.pf-c-width-limiter {
    --pf-c-width-limiter--MaxWidth: auto;
    --pf-c-width-limiter--MinWidth: 0;

    @include pf-build-css-variable-stack(
        "max-width",
        "--pf-c-width-limiter--MaxWidth",
        $pf-c-width-limiter--breakpoint-map
    );
    @include pf-build-css-variable-stack(
        "min-width",
        "--pf-c-width-limiter--MinWidth",
        $pf-c-width-limiter--breakpoint-map
    );
}
```

**Comment by mcoker** [comment]
@mattnolting can you explain the use cases for adding this as a new component? cc @mcarrano

**Comment by mattnolting** [comment]
In many cases, layout for brochure style page is dictated by line length. Instead of using flex layout width modifiers, which can be unpredictable, a width limiter component will allow sentence length to define layout.

<img width="856" alt="Screen Shot 2021-04-19 at 12 57 57 PM" src="https://user-images.githubusercontent.com/5385435/115274766-037c6f00-a10f-11eb-90dd-8a6900aedf18.png">

I've been using a width limiter in each of my [CRC](cloud.redhat.com) integrations and it's extremely useful. Without it, matching design specs is challenging.
