### ISSUE TITLE
Bug: mobile view of filter panel

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#3983]
In the primary-detail example — https://www.patternfly.org/v4/demos/primary-detail/react-demos/primary-detail-full-page/ — a css issue exists when the viewport is resized to show the filter icon that displays a panel with filter options, where the data list contents behind the filter panel become visible when hovering the data list item.

Steps to reproduce:
1. Navigate to https://www.patternfly.org/v4/demos/primary-detail/react-demos/primary-detail-full-page/
2. Resize the window until the fillter toolbar components are replaced with a filter icon
3. Click the icon to display the filter components
4. Move the mouse cursor to hover over the first data list item

Result: The filter panel is still open, but the data list item displays on top of the panel on hover. 
![image](https://user-images.githubusercontent.com/21063328/113951529-b67ccc80-97e1-11eb-9556-f2f54fd25c98.png)

Expected behavior: the filter panel should remain visible until I click to dismiss the panel.
![image](https://user-images.githubusercontent.com/21063328/113951501-ad8bfb00-97e1-11eb-8e28-2b8240fb96b4.png)

**Comment by mcoker** [comment]
@jgiardino nice catch! The expanded content should be using a higher z-index, `--pf-global--ZIndex--sm`, which is what we use for menus that pop out from a toggle.
