### ISSUE TITLE
Card - expandable card icon doesn't rotate when expanded

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly#4002]
As [seen in the docs](https://www.patternfly.org/v4/components/card/#expandable), the expandable card doesn't rotate the carrot icon when expanded - it appears that this rule evaluates to `transform: none`:

```
.pf-c-card.pf-m-expanded .pf-c-card__header-toggle-icon {
    transform: rotate(var(--pf-c-card--m-expanded__header-toggle-icon--Rotate));
}
```

<img width="986" alt="Screen Shot 2021-04-13 at 5 21 28 PM" src="https://user-images.githubusercontent.com/8651509/114623299-11e50980-9c7d-11eb-8bf9-c93abbd6d1bb.png">

**Comment by mcoker** [comment]
@evwilkin this should be fixed in https://github.com/patternfly/patternfly/pull/3981
