### ISSUE TITLE
Request: Component Status List

### ISSUE THREAD

**Issue by mindreeper2420** [patternfly/patternfly#401]
In order to keep track of the components that are set for PatternFly 4, it would be great to have a list that details the status of the components. Ideally, this would be a list of all components that are currently being considered for PatternFly 4, what state they are in (design, documentation, code, examples, etc.), their version, and if they are available in the various frameworks that PatternFly offers (jQuery, Angular, React).

There is a basic list currently on http://www.patternfly.org/pattern-library/, but something similar to either how GitHub's Primer system displays statuses or a table that lists out the statuses would be preferable.

**Comment by mcarrano** [comment]
@mindreeper2420 We do have some of this information in a spreadsheet here: https://docs.google.com/spreadsheets/d/1L6CSV-kxGGiUHiG8fQ6aMSizGR2WQp6pXwjCBiaf8w0/edit?usp=sharing

**Comment by mindreeper2420** [comment]
@mcarrano what do you think about creating a page on the PatternFly 4 site that people can reference? The spreadsheet is behind the Red Hat wall, so not available to those that may want to see what is coming (or not).

**Comment by mcarrano** [comment]
This is a topic we discussed at length for PF 3 @mindreeper2420 . In principle I am fine with the idea of having a public facing roadmap. But at the moment, I'm curious what problem that's solving. Do you think think is unclear to the team? If so, let's address as part of our retrospective to discuss how we can do better.

**Comment by mindreeper2420** [comment]
I see this as a benefit to those both inside and outside of the internal Red Hat UXD Team.

If the idea is to gather large support from the community, then we need to be transparent and open with that community as to the roadmap and not keep things internal (even as an internal contributor, I did not know that excel sheet existed).

Take the upgrade from PatternFly 3 to PatternFly 4. As more teams want to (or need to) upgrade, there will be the inevitable questions of "when will this component be available?" or "will this component be moved over to PatternFly 4?". Having a clear answer for those (even if it is just as part of a release timeline, or generic "second half of 2019") will not only give a clear view into what is being done, but may in turn bring forth additional contributions. If a user sees that the component they need/want isn't going to be ported soon, they may be inclined to contribute said component. The majority of internal users of PatternFly are outside of the UXD Team, so this will benefit them as well.

In addition to a roadmap of moving components from PatternFly 3 to PatternFly 4, a Status List would also be a good idea (https://styleguide.github.com/primer/whats_new/status-key/). The more information that can be shared, the better (IMO).

**Comment by mcarrano** [comment]
@mindreeper2420 I am going to close this issue out as we try to clean up old issues. But as a general goal, I am interested in making our component roadmap more visible and predictable. Welcome any ideas you have, and feel free to reach out to me directly.
