### ISSUE TITLE
Login page - password strength meter demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4018]
Create a new Login page demo that shows show to implement a password strength meter according to the designs here: https://marvelapp.com/prototype/6jehce7/screen/78511266

**Comment by ajacobs21e** [comment]
@mcarrano is this for both pieces of the component?
the strength meter 
![image](https://user-images.githubusercontent.com/6415742/117199264-fcfd2100-adb7-11eb-94df-e2dede4e6b01.png)
and the requirements validation checklist?
![image](https://user-images.githubusercontent.com/6415742/117199314-0dad9700-adb8-11eb-8ada-9cb743470208.png)

FYI @gdoyle1

**Comment by mcarrano** [comment]
@ajacobs21e we've broken this up into two pieces. There is another issue here for creating what's we've decided to call "rich helper text" https://github.com/patternfly/patternfly/issues/4017 This will allow us to build the requirements validation checklist that can be used in a login screen or really with any text input field (you could use this to validate object names, for example). This issue would then use that new component to build a new variant of the login form that includes this and the strength meter as part of the password field. Does the help?

**Comment by ajacobs21e** [comment]
Yes, thank you!

**Comment by mcarrano** [comment]
@srambach Yes, this should be a new demo under Login Page. We don't need all of those different variants. The one on the first page called, "Interactions." is the one to implement. Sorry, I know that is a bit confusing.

As to how many states to show, that's a good question. We will want to follow up with a React demo to show the dynamic behavior so I'm not sure what we should typically provide from core. What are your thoughts @mcoker ?

**Comment by srambach** [comment]
@mcarrano OK, so not the ones with the progress bar at all then?

**Comment by mcarrano** [comment]
> @mcarrano OK, so not the ones with the progress bar at all then?

Right
