### ISSUE TITLE
Upgrade Red Hat Font

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#4021]
There has been a new release of the Red Hat Font. It includes a bunch of useful things for everyone using PatternFly:

1. Monospace version
2. Tabular figures (fixed width numbers in the proportional version; great for UIs)
3. Variable fonts
4. Light weights
5. Lots of little fixes

Changelog: https://github.com/RedHatOfficial/RedHatFont/blob/master/CHANGELOG.md
GitHub repo: https://github.com/RedHatOfficial/RedHatFont
Demo website: https://redhatofficial.github.io/RedHatFont/

**Comment by mcoker** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
We will put this on the roadmap for further investigation. In general, I agree this is something we should do.
