### ISSUE TITLE
Tabs: disable select content border on click

### ISSUE THREAD

**Issue by altwarg** [patternfly/patternfly#4034]
Issue on patternfly-react: https://github.com/patternfly/patternfly-react/issues/5721

I want to disable the display of the borders of the tab content when clicking on an empty tab content space.

Image:
![image](https://user-images.githubusercontent.com/34391398/116658013-02153700-a998-11eb-8bca-8a027c2f217a.png)

Video:

https://user-images.githubusercontent.com/34391398/116658080-19542480-a998-11eb-9f80-11531238608c.mp4

Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.
1. Open documentation: https://www.patternfly.org/v4/components/tabs
2. Move the mouse pointer over the contents of the tab and click on it
3. Click on free tab content.

**Comment by mcoker** [comment]
cc @jessiehuff
