### ISSUE TITLE
Update select to add a search filter in the menu

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly#4047]
Proposing to enhance the select component to be able to add a search input to filter down the menu options. Attached the design! I believe this has already been added to the context selector
![image](https://user-images.githubusercontent.com/30870144/117320186-fa530800-ae59-11eb-912a-e22e514ffa5e.png)

**Comment by mcarrano** [comment]
@tlabaj sounds like this would be a React fix. Please confirm and I can transfer it over. Any reason we shouldn't support adding the search box to any menu?

@gdoyle1 what's the priority on this?

**Comment by gdoyle1** [comment]
@mcarrano We'd also need this for OpenShift Console in the near future. Ideally by July BUT not a huge deal if it doesn't make it then
