### ISSUE TITLE
Add expandable inline alert

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4056]
Add a new Alert variation for an expandable inline alert.

Designs: https://marvelapp.com/prototype/9ihajjd

**Comment by gunishmatta** [comment]
I want to work on this issue.

**Comment by mcoker** [comment]
Hi @gunishmatta, thanks for offering to contribute! I've assigned it to you and am here if you have any questions. You can find development instructions in the README - https://github.com/patternfly/patternfly#development

Let me know if you'd like an introduction to how the repo is structured, the dev process, etc. You can reach out to me on the [PatternFly slack](https://slack.patternfly.org/) at @mcoker.

**Comment by mcoker** [comment]
@gunishmatta just wanted to check in and see if you still have time to work on this issue, and if so, do you have an ETA? We are hoping to get this feature into a release soon if possible. Thanks!

**Comment by gunishmatta** [comment]
I will try to finish by this weekend

**Comment by mcoker** [comment]
@gunishmatta sounds great, thank you!
