### ISSUE TITLE
Menu component positioned with popper transitions unexpectedly

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4062]
Re: https://github.com/patternfly/patternfly-react/pull/5722

https://patternfly-react-pr-5722.surge.sh/demos/composable-menu/#drilldown-menu-with-toggle

Popper is being used to position the menu relative to the toggle, and it uses `translate()` for positioning. We have a `transition` for `transform` that is being applied and causing the menu to transition the first time it is loaded.

Let's review that implementation and see if we need to transition `transform`, and if so, make sure popper's positioning via `transform` isn't interfering with our use of of that property in the CSS. We may also see if it's better for popper to use a wrapping element for positioning so it doesn't interfere with our component transitions.

Also as an aside, we're transitioning `height`, too https://github.com/patternfly/patternfly/blob/722442b2f6f76fba82df89c92362264515c9a31e/src/patternfly/components/Menu/menu.scss#L111

Does that need to move to `__content` since that element's height is being animated?

**Comment by mattnolting** [comment]
blocked by #4033
