### ISSUE TITLE
Table: add draggable variant

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly#4065]
**Describe the issue. What is the expected and unexpected behavior?**
Currently the data list component does not support a header like the table component does. If using a separate `DataListItem` as a header, the draggable variant of the data table causes the data cell move around if the user selects an item to drag. In this use case, the first cell should always remain static/unmovable when dragging around items. See below.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/32821331/117015256-867cf800-acbf-11eb-8f68-09ce72123bd5.gif)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
feature request

**What is your product and what release version are you targeting?**
Keycloak - new admin console

**Comment by jenny-s51** [comment]
Thank you @mcarrano and @mcoker - I plan to complete this section within the next couple of sprints and am hoping to use this new composable/draggable table variant . It would be great if you could help the Keycloak team get the work started in Core and get it on the roadmap as soon as possible.

**Comment by mcarrano** [comment]
@jenny-s51 I've pulled this into the current core sprint and will prioritize this. Once the core changes are done it will need to be handed off to React. We should be able to target React updates for our June 23 (2021.08) release. Hope that will work.
