### ISSUE TITLE
Drilldown menu has scrollbar while drilling down

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly#4073]
The scrollbar in this example causes the menu to change height rapidly: https://www.patternfly.org/v4/components/menu/#with-drilldown

![drilldown-scroll](https://user-images.githubusercontent.com/47335686/118510062-9bfe1300-b6fe-11eb-95a8-f04924aa3d0f.gif)

**Comment by mcoker** [comment]
cc @mattnolting
