### ISSUE TITLE
TreeTable actions disappear in responsive view

### ISSUE THREAD

**Issue by KevinFCormier** [patternfly/patternfly#4075]
Actions are available in normal table view:
![image](https://user-images.githubusercontent.com/42188127/118537921-877c4380-b71b-11eb-845a-28e479cebb42.png)

But when the responsive view is used, only the "Show row details" button is available:
![image](https://user-images.githubusercontent.com/42188127/118538092-bdb9c300-b71b-11eb-89c3-b349cf5a35fa.png)

Here is an example on codesandbox.io:
https://codesandbox.io/s/floral-shadow-fvii3?file=/index.js

Is this the intended behaviour?

**Comment by mcoker** [comment]
cc @mattnolting @mcarrano

**Comment by nicolethoen** [comment]
note to whoever works on this - combining the tree table with table actions will likely present some extra issues with keyboard navigation/accessibility. It will be something to be sure is tested and probably addressed at the same time.

**Comment by mcarrano** [comment]
Yeah, this was definitely an oversight. I can think of a couple of potential design solutions for this. I will put this on the roadmap and perhaps we can collaborate on the fix @mattnolting .

@KevinFCormier do you have a timeline for needing a fix?

**Comment by KevinFCormier** [comment]
@mcarrano To make use of it in our current release, we'd need it by mid June. But there is another somewhat similar problem that we'd probably need a fix for as well. (Otherwise we may need to disable responsive views for some of our tables and look at picking fixes for these up in a later release.) The other problem relates to having a nested table as the expandable row content, but I haven't opened an issue for it yet.

![image](https://user-images.githubusercontent.com/42188127/119569561-e4f83c00-bd7c-11eb-9f6d-ea8a47e47893.png)
- First column header is repeated
- No padding around content (for a non-table case, this happens for any cells after the first)
- Breakpoint from parent table applies to expandable row table

I can open an issue for that and try to provide a standalone example for you. Would this repo also be the right spot for that one?

**Comment by mcoker** [comment]
> Would this repo also be the right spot for that one?

@KevinFCormier yep, thanks!

**Comment by mcarrano** [comment]
@KevinFCormier we will definitely look at these, but I think getting these fixes to you by mid-June will be difficult. We are currently wrapping up a milestone due to release next week. Our next release following that would be June 23. Would that be too late? That will probably be the best case to get these fixes in unless that solution is easier than I think. What is your best guess @mcoker ?

**Comment by mcoker** [comment]
@mcarrano we should be able to make that date if we prioritize these issues. I can have a better idea once we have a design for the actions element in the responsive tree table, and a demo reproducing the issues in the [nested table comment](https://github.com/patternfly/patternfly/issues/4075#issuecomment-848277399).

**Comment by KevinFCormier** [comment]
June 23 is the final day of our final dev sprint for our current release, so we won't be able to pick it up. But we would like to pick it up for our next release, wrapping up development in September.

**Comment by mcarrano** [comment]
OK. We will definitely get this on our roadmap to deliver before then.
