### ISSUE TITLE
Label with isOverflowLabel does not support color variants

### ISSUE THREAD

**Issue by jerolimov** [patternfly/patternfly#4092]
## Describe the issue. What is the expected and unexpected behavior?

The [Label](https://www.patternfly.org/v4/components/label) supports a button variant with the prop `isOverflowLabel`. But when enable it, it breaks the `color` prop.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

tl;dr: https://codesandbox.io/s/patternfly-isoverflow-color-label-issue-iqej8

(The Label looks fine on CodeSandbox, but the color issue could be checked here as well.)

**When using the label in different variants with a color the label looks like expected:**

Code:
```tsx
import { Label } from '@patternfly/react-core';

export default function LabelIssue() {
  let i = 1;
  return (
    <div>
      <Label>Label {i++}</Label>
      <Label variant="filled">Label {i++}</Label>
      <Label variant="outline">Label {i++}</Label>

      <Label color="purple">Label {i++}</Label>
      <Label color="purple" variant="filled">Label {i++}</Label>
      <Label color="purple" variant="outline">Label {i++}</Label>
    </div>
  );
}
```

Visual result:
![image](https://user-images.githubusercontent.com/139310/119141376-77c76c80-ba45-11eb-84dd-8ca8058a6564.png)

No hover effect (as expected):
![Peek 2021-05-21 15-11](https://user-images.githubusercontent.com/139310/119142445-cb868580-ba46-11eb-8544-1a078fc7b66f.gif)

**But when adding `isOverflowLabel` and `onClick` prop (only the first one changes the UI, it also switches the internal component from a `span` to a `button`) the colors are missed:**

Code:
```tsx
import { Label } from '@patternfly/react-core';

export default function LabelIssue() {
  const onClick = (event: React.MouseEvent<HTMLButtonElement>) => console.log('onClick', event);
  let i = 1;
  return (
    <div>
      <Label isOverflowLabel onClick={onClick}>Label {i++}</Label>
      <Label isOverflowLabel onClick={onClick} variant="filled">Label {i++}</Label>
      <Label isOverflowLabel onClick={onClick} variant="outline">Label {i++}</Label>

      <Label isOverflowLabel onClick={onClick} color="purple">Label {i++}</Label>
      <Label isOverflowLabel onClick={onClick} color="purple" variant="filled">Label {i++}</Label>
      <Label isOverflowLabel onClick={onClick} color="purple" variant="outline">Label {i++}</Label>
    </div>
  );
}
```

Visual result (where the background is missing on all filled / colored buttons):
![image](https://user-images.githubusercontent.com/139310/119141997-40a58b00-ba46-11eb-83f5-b1049a44142c.png)

But it looks like the `isOverflowLabel` is required to have a button with a hover effect which shows a bigger border and `cursor: pointer` to indicate that the label is clickable.
![Peek 2021-05-21 15-13](https://user-images.githubusercontent.com/139310/119142782-29b36880-ba47-11eb-848c-de228f7755dd.gif)

## Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?
Bug

We workaround in OpenShift Console by not adding the `isOverflowLabel` prop, adding a `cursor: pointer` manually and live at the moment without the bigger border when the user hovers our button.

Workaround:
```tsx
import { Label } from '@patternfly/react-core';

export const WorkaroundLabel: React.FC = () => {
  return (
    <Label
      color="purple"
      onClick={() => {
        // ...
      }}
      onClose={(event) => {
        event.preventDefault();
        event.stopPropagation();
        // ...
      }}
      style={{ cursor: 'pointer' }}
    >
      Example label
    </Label>
  );
};
```

Looks like this:
![Peek 2021-05-21 15-20](https://user-images.githubusercontent.com/139310/119143626-19e85400-ba48-11eb-84b5-66bb0c93cf22.gif)

**What is your product and what release version are you targeting?**
OpenShift Console 4.8 (we can remove our workaround also with a later release)

**Comment by jerolimov** [comment]
It looks like that the `pf-m-overflow` overrides the `pf-m-purple` styles. Maybe it's required that the color needs a higher css specificity. 

![image](https://user-images.githubusercontent.com/139310/119145260-c1b25180-ba49-11eb-9cfc-c368b5acc185.png)

**Comment by redallen** [comment]
Looks like a CSS problem with:
```html
<span class="pf-c-label pf-m-purple">
  <span class="pf-c-label__content">Label 5</span>
</span>
```
vs
```html
<button class="pf-c-label pf-m-purple pf-m-outline pf-m-overflow">
  <span class="pf-c-label__content">Label 12</span>
</button>
```

**Comment by mcarrano** [comment]
@mcoker can you take a look?

**Comment by mcoker** [comment]
@mcarrano the overflow label was built to have consistent styling, mimicking the overflow chip.

https://www.patternfly.org/v4/components/chip-group
https://www.patternfly.org/v4/components/label-group#overflow

Do we want to extend the color variations to the overflow label? Also the ability to use filled or outline?

**Comment by mcoker** [comment]
> Is the overflow label then just the thing at the end here that says "3 more"?

Yep! The overflow label is just the label at the end of a label group that will show hidden labels.

> But I'm a bit confused when I look at the React label examples here: https://www.patternfly.org/v4/components/label They have "labels that overflow" that is only introducing truncation. 

@mcarrano that is confusing. All that's demonstrating is what happens when you have a lot of text in the label, as the text part of the label has a `max-width`, and any "overflow" text is truncated. That's where overflow comes into play in those examples. We could rename the text in those examples to "[description] label with icon that truncates" instead of "overflows" to be more clear.

**Comment by mcarrano** [comment]
>  We could rename the text in those examples to "[description] label with icon that truncates" instead of "overflows" to be more clear.

I like that idea.  Can we make that change @tlabaj ? 

@jerolimov back to your original issue - sounds like the `isOverFlow` prop is not the right thing to use here, but what you are really looking for is the label with truncated text using the `isTruncated` prop, correct?
