### ISSUE TITLE
Toolbar: provide a way to make it sticky

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#4113]
In cockpit we use toolbars to filter really long lists, of hundreds of items. When the user scrolls down the list, they might still want to edit the filter options.

Could we consider making the toolbars optionally sticky? 

https://www.patternfly.org/v4/components/toolbar/

**Comment by mcoker** [comment]
Hey @KKoukiou yeah, I think that's a common enough use case. We do this currently with pagination, which shares a similar layout in relation to lists of things. WDYT @mcarrano?

**Comment by mcarrano** [comment]
Yes, I think this makes sense. Don't we have the ability to do that now using sticky sections @mcoker ?

**Comment by mcoker** [comment]
@mcarrano you can use the toolbar in a sticky page section currently, though I imagine there are use cases where the toolbar isn't use in its own page section so having it be sticky on its own would be helpful. Is that your use case @KKoukiou?

**Comment by KKoukiou** [comment]
@mcarrano @mcoker the use case when this emerged on our side was a card which contains a table with a toolbar. That table are a few hundreds of items, and therefore scrolling down and keeping the toolbar sticky is desired. But that toolbar is not on it's own page section.

The page looks like this:
![Screen Shot 2021-06-04 at 09 16 58](https://user-images.githubusercontent.com/14921356/120603558-771ed500-c44c-11eb-9458-28ad0638b334.png)

**Comment by mcarrano** [comment]
Thanks @KKoukiou . Yes, it sounds like a sticky toolbar option makes sense. Do you need this in a specific timeframe? Is this something you would be willing to help contribute?

**Comment by KKoukiou** [comment]
@mcarrano we actually we have a local customizatoin for this. I can try to upstream it :)

**Comment by KKoukiou** [comment]
That said feel free to assign me the issue.
