### ISSUE TITLE
Focused text inputs, :focus-visible vs :focus

### ISSUE THREAD

**Issue by mvollmer** [patternfly/patternfly#4121]
I am confused by how a focused text input is supposed to look. We have seen these variants:

![image](https://user-images.githubusercontent.com/3228183/120600775-d3d0be80-c451-11eb-8486-0802f8c5dd3b.png) (Firefox 88)
![image](https://user-images.githubusercontent.com/3228183/120601136-3e81fa00-c452-11eb-92bf-4ec42f55a461.png) (Chrome 91)
![image](https://user-images.githubusercontent.com/3228183/120605288-90c51a00-c456-11eb-8598-8a7621612dda.png) (Chrome some time ago)
![image](https://user-images.githubusercontent.com/3228183/120620229-70e92280-c465-11eb-96cd-4cc3f8c4c75d.png) (GNOME Web)

This looks a bit random and unintended to me.

Patternfly seems to have styles for a text input with the `:focus`pseudo class, but not for the `:focus-visible` pseudo class. A text input seems to get both `:focus` and `:focus-visible` when focused by a mouse click. This means that a text input is always rendered with the browser defaults for `:focus-visible`.

Naively, I would expect a focused text input to look like this:

![image](https://user-images.githubusercontent.com/3228183/120600607-a126c600-c451-11eb-9972-8857bf41fdf0.png)

This is how it would look with just `:focus` and without `:focus-visible`.

So, right now I am thinking that Patternfly should provide appropriate styles also for the `:focus-visible` pseudo class. (Or is it maybe a bug in browsers that focusing a text input with the mouse gives it the `:focus-visible` pseudo class?)

**Comment by garrett** [comment]
> Naively, I would expect a focused text input to look like this

That doesn't look focused to me; it looks way too close to a default text entry.

(Of the "before" ones, I prefer Firefox's. It has a typical blue ring to show it is focused. The heavy black outline in your Chrome screenshot is super heavy. It's odd that you have a orange outline for Chrome; I never saw that; it was blue from what I've seen before. Using orange like that makes it look like an error.)

**Comment by garrett** [comment]
There was discussion about a universal focus state @ https://github.com/patternfly/patternfly/issues/790 in 2019.

The discussion eventually led to a decision about states, which @jgiardino summarized in https://github.com/patternfly/patternfly/issues/790#issuecomment-492819453:

> I chatted with @mcoker and @mceledonia today about how to address this in PF4, and ultimately we're leaning toward a minimal approach to handling focus styles, at least initially.  This is a summary of what we discussed.
> 
> - We are not implementing universal focus styles, and are taking the approach that @mceledonia [mentioned above](https://github.com/patternfly/patternfly-next/issues/790#issuecomment-489648230), and therefore can close this issue and open new issues for specific components that do require custom styles
>   - Currently, this is only needed for the Switch: https://github.com/patternfly/patternfly-next/issues/1824
>   - But in the future, we should revisit the Typeahead variant of the Select once we finalize keyboard interaction: https://github.com/patternfly/patternfly-react/issues/1842
> - We discussed what the visual style should be, and if we should emulate browser styles or not. The general assumption is that users become familiar with the native styles for focus state in the browser they use the most, which is a compelling reason to do something that is consistent with the browser the user is using. That might be the approach we end up taking in a future release, but for now, to keep the initial implementation simple, we will use one style for all browsers. And we will choose a style that clearly indicates focus, matches the default theme, and doesn't necessarily try to emulate any one browser. 
> - Everyone agreed that showing focus styles only on keyboard interaction and not with mouse interaction is a preferable user experience. But we also didn't discuss if this is something we should try to do where the browser applies focus styles. I'm inclined to let browsers decide how to handle this for native interactive elements. For the switch, I'll defer to others on what should happen here. 
> - There are styles that only display on focus (e.g. the focus ring), but additionally there are styles that display on hover. Moving forward, styles that display on hover should also display on focus, in addition to the focus ring.

However, this was back in 2019, before:
- [Microsoft proposed new widgets for Chromium browsers](https://blogs.windows.com/msedgedev/2019/10/15/form-controls-microsoft-edge-chromium/)
- Chrome changed its widgets (it seems that Microsoft's work has heavily influenced current Chrome, but isn't 1:1)
- [Firefox changed its default widgets](https://bugzilla.mozilla.org/show_bug.cgi?id=1640195)
- PatternFly talked about revving up its look and feel (currently in process; mentioned in the latest PF Community call on 25 May)

So it's probably worth revisiting again? But we should consider the previous discussion too.

**Comment by mcoker** [comment]
cc @mcarrano @mceledonia @jessiehuff 

Hey @garrett and @mvollmer. We haven't used `:focus-visible` in any of our components yet. We usually try and leave the browser defaults in place for focus styles, though there are exceptions where we try to enhance the focus state for a better experience, and we aim to have our designs work with the browser defaults. 

That said, as `:focus-visible` has gained [browser support](https://caniuse.com/css-focus-visible), I think there are valid uses in our components as a progressive enhancement. I think this is something we may be able to do a design/a11y audit for to see if there are areas for improvement.

> is it maybe a bug in browsers that focusing a text input with the mouse gives it the :focus-visible pseudo class?

Per the [`:focus-visible` draft spec](https://drafts.csswg.org/selectors-4/#the-focus-visible-pseudo)...

> If the element which supports keyboard input (such as an input element, or any other element that would triggers a virtual keyboard to be shown on focus if a physical keyboard were not present), indicate focus.

Which means elements like a text input will always trigger `:focus-visible`. Here's a quick demo of text inputs versus buttons and the difference in how they trigger `:focus-visible`.

https://codepen.io/mcoker/pen/oNZrdOj
