### ISSUE TITLE
Request for truncation component

### ISSUE THREAD

**Issue by bgliwa01** [patternfly/patternfly#4129]
We have come across the need for truncation in the middle of a string in OpenShift to fit in a given amount of space. It would be helpful to have a component that truncates in the middle of the string, but only when there isn’t enough space. If truncated, it should automatically add a tooltip. The number of chars can vary to ensure it fills as much available space as possible.

**Comment by christianvogt** [comment]
I'd say it's more of a nice to have. So there is no hard timeline. IIRC this came up because a title needed to be truncated and ideally a tooltip would be shown only when the title became truncated. The workaround is to always have a tooltip available which isn't ideal.
