### ISSUE TITLE
Horizontal card grid demo updates

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4160]
* The card title/toggle alignment changes between the collapsed/expanded state because the labels are added/removed between the states. Let's see if we can keep that alignment consistent between the two states.
<img width="414" alt="Screen Shot 2021-06-17 at 11 16 11 AM" src="https://user-images.githubusercontent.com/35148959/122435277-7bbfaf00-cf5d-11eb-8a81-794878e34c3f.png">
<img width="405" alt="Screen Shot 2021-06-17 at 11 16 14 AM" src="https://user-images.githubusercontent.com/35148959/122435273-7b271880-cf5d-11eb-85c1-a0d72abb3303.png">

**Comment by mcoker** [comment]
cc @mcarrano can we add this to an upcoming milestone?

**Comment by mcarrano** [comment]
We do have an open design issue that's being worked on for a compact label: https://github.com/patternfly/patternfly-design/issues/1048 Would that be a better approach here?

**Comment by mcoker** [comment]
@mcarrano if we can update the demo to use compact labels, yep that would solve this issue.
