### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly#4176]
When using `(dart-)sass` to compile CSS we get a deprecation warning about using the division operator.

Example:
```bash
$: DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
$: Recommendation: math.div(pf-strip-unit($pxval), $base)
$: More info and automated migrator: https://sass-lang.com/d/slash-div
$:    ╷
$: 11 │   @return pf-strip-unit($pxval) / $base * 1rem;
$:    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
$:    ╵
$:     ../../node_modules/@patternfly/patternfly/sass-utilities/functions.scss 11:11       pf-size-prem()
$:     ../../node_modules/@patternfly/patternfly/sass-utilities/scss-variables.scss 94:30  @import
$:     ../../node_modules/@patternfly/patternfly/sass-utilities/_all.scss 4:9              @import
$:     src/Pagination/pagination.scss 1:9                                                  @import
$:     src/index.scss 18:9   
```
The solution is pretty self-explanatory. Use the `math.div` function instead.

https://sass-lang.com/documentation/breaking-changes/slash-div

There is even a sass-migrator package which will do the work for you.

**Comment by mcoker** [comment]
Hey @Hyperkid123 thanks for the issue! We have [upgraded PF to use dart sass](https://github.com/patternfly/patternfly/pull/4164) and fixed those warnings in our current release scheduled to go out later this week.

**Comment by KKoukiou** [comment]
This is already fixed :) I think you can close it.
