### ISSUE TITLE
bug(NumberInput): button icons are misaligned on firefox

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#4189]
This screenshot is from the PF docs page.

![Screen Shot 2021-06-24 at 18 06 42](https://user-images.githubusercontent.com/14921356/123296558-07fe4300-d517-11eb-8074-02b841be37a6.png)

Tested on Mozilla Firefox 89.0

**Comment by mcoker** [comment]
@mcarrano can we add this to a future milestone?
