### ISSUE TITLE
Select component with overflow: auto and max-height has issues with loadingVariant spinner option

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly#4207]
**Describe the issue. What is the expected and unexpected behavior?**
When using Select component with a custom CSS to limit its height it creates an overflow scroll bar if a spinner is in the list, even if the height does not exceed the `max-height`. The overflow scroll does not appear all the time, but in Firefox (for me), it appears when moving the mouse around

CSS used
```
.pf-c-select__menu {
  max-height: 300px;
  overflow: auto;
}
```

We need a height limitation since we have +30 items for some Select components.

Gif of the issue here
![patternfly-select-spinner-scrollbar](https://user-images.githubusercontent.com/6598829/124298239-54233600-db5c-11eb-8a0c-71204faf4679.gif)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/sleepy-hoover-j8qy0?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement

**What is your product and what release version are you targeting?**
Telltale

**Comment by mcoker** [comment]
cc @mcarrano can we add this to an upcoming milestone?
