### ISSUE TITLE
Table scrolling and sticky column

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly#4218]
As a user, I want to horizontally scroll through a table with daily data. 

In Cost Management, we're implementing a new "Historical Cost Explorer" feature. This charts multiple months worth of daily data. However, we also have the requirement to show a more detailed view of the data in a table (below). To view daily data in a table, we need the ability to scroll horizontally.

We could place the entire table in a scrollable window; however, the Drift app (another Insights application), has created their own custom table to support scrolling. In the screenshot below, the first column is sticky, while the other columns are allowed to scroll horizontally. This is the basic functionality we need from the PatternFly table.

**Drift**
![chrome-capture](https://user-images.githubusercontent.com/17481322/105381922-8871ee00-5bdd-11eb-9998-c20df8994c75.gif)

**Historical Cost Explorer**
<img width="1498" alt="Screen Shot 2021-01-21 at 11 32 18 AM" src="https://user-images.githubusercontent.com/17481322/105381968-96277380-5bdd-11eb-87b2-81eae6fc4655.png">

**Comment by mcarrano** [comment]
@mcoker I've moved this to the core repo so we can begin the work there.

**Comment by jamestalton** [comment]
Designers mentioned that shadows would be nicer than single line borders when scrolling.
Here is an example of that:

https://user-images.githubusercontent.com/6277895/125456909-4df3626e-f3c5-4737-a36c-9d2b6a5d201e.mov

**Comment by mattnolting** [comment]
> Designers mentioned that shadows would be nicer than single line borders when scrolling.
> Here is an example of that:
> 
>  Horizontal.Scrolling.Table.with.Scrolling.Shadows.mov

@jamestalton How are you adding borders/shadows to scrolled tables?
