### ISSUE TITLE
Alert: add "plain" variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4220]
Add a plain variant of the Alert component. This is designed as a light-weight inline alert that can be placed any where in the page. Unlike the full inline alert, it would not have other actions associated with it. See https://marvelapp.com/prototype/852jaj9/screen/75866265 for an example of what appearance and placement might look like.

**Comment by ajacobs21e** [comment]
@srambach will this have a dismissible variant?

**Comment by srambach** [comment]
> @srambach will this have a dismissible variant?

That wasn't included in this issue. @mcarrano wdyt? I think it would take some design thought, because otherwise the X would potentially be floating over to the right by itself without the bounding box to tie it together.

**Comment by ajacobs21e** [comment]
thanks, just checking to make sure I add the right symbols to the library!
