### ISSUE TITLE
Remove up and down arrows for pagination direct input box

### ISSUE THREAD

**Issue by vjwilson** [patternfly/patternfly#4224]
In reference to this component, https://www.patternfly.org/v4/components/pagination

<img width="767" alt="Screen Shot 2021-07-15 at 11 19 29 AM" src="https://user-images.githubusercontent.com/715729/125813306-9698ef50-3754-4a86-b2b9-38e51adfa670.png">

Those up/down arrow buttons in the <input type="number"...> type are hard to see, hard to click, less accessible, and cause more confusion than they are worth.

I think we should remove them from design, docs, and implementations like partternfly-react.

For an example of why those arrows should be removed, see this article from the Gov.UK team:
https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

**Comment by mcoker** [comment]
cc @mcarrano @jessiehuff wdyt?

**Comment by mcarrano** [comment]
My understanding is that those spin buttons are imposed by the browser because this is a number input. Is that right? @jessiehuff is there an a11y reason to have them there? I don't feel like they really add value from a usability perspective since the user can always use the "<" or ">" to go forward or back a page. I'd be OK to remove them as long as it doesn't have other bad side effects to do so.

**Comment by mcoker** [comment]
> My understanding is that those spin buttons are imposed by the browser because this is a number input. Is that right?

@mcarrano yep. We removed them in the [number input](https://www.patternfly.org/v4/components/number-input) because we added our own increment buttons. You could make the same argument to remove them in pagination since we have the  "<" and ">" buttons like you mentioned.

**Comment by mcarrano** [comment]
@jessiehuff any reason not to remove these?

**Comment by mcarrano** [comment]
@jessiehuff ^^^

**Comment by jessiehuff** [comment]
I think it'd be fine to just remove the visual arrows similar to the [Number Input component](https://www.patternfly.org/v4/components/number-input/). I can't think of any downsides to doing so. 👍

**Comment by vjwilson** [comment]
@mcoker @evwilkin Would one of your remove the bot's *wontfix* label and keep this issue open?

**Comment by mcarrano** [comment]
Sorry this got lost in the shuffle. Just added to our roadmap for 2022.
