### ISSUE TITLE
Navigation: add new vertical nav variants

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4225]
Want to extend our existing vertical nav to be more scalable and composable by adding three new patterns that include a flyout, a drill-down, and an additional level of accordion expansion. The idea would be to make our navigation more flexible by allowing these elements to be combined with existing patterns to meet product needs.

@beccaglass can you please post final designs here when ready?

**Comment by mattnolting** [comment]
https://www.figma.com/proto/AJi4XmCkrdGEK532YmbAqH/tertiary-nav?node-id=102%3A3678&scaling=min-zoom&page-id=0%3A1

**Comment by mattnolting** [comment]
@mcarrano splitting this issue for [flyout](https://github.com/patternfly/patternfly/issues/4244) and [drilldown](https://github.com/patternfly/patternfly/issues/4244)

**Comment by mcarrano** [comment]
@mattnolting that's fine to break into smaller deliverables. There was also a third variant for an L3 expansion (https://www.figma.com/proto/4HNu06gFjfAXs6tOroQ1QZ/composable_nav?node-id=0%3A649&scaling=min-zoom&page-id=0%3A344). Wanted to make sure you didn't miss that.

**Comment by mattnolting** [comment]
@mcarrano closing in favor of https://github.com/patternfly/patternfly/issues/4253

**Comment by beccaglass** [comment]
https://docs.google.com/document/d/17jhcgkUgpw7f9Ixf9ew8RfcivSck9mdv_Yw6fIZhlAs/edit?ts=60cb76dd#heading=h.ea3lujnv46vp

**Comment by mcoker** [comment]
@beccaglass there is a PR up for the flyout nav. Would you mind leaving a review on the PR?

https://github.com/patternfly/patternfly/pull/4301

Demo is at https://patternfly-pr-4301.surge.sh/components/navigation#flyout
