### ISSUE TITLE
Wizard in a page - Add support for a sticky footer

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#4228]
@srambach helped our team customize the wizard to have a sticky footer in a wizard that displays in a page (see example below). We would like to reuse that in other related UIs that we're working on, so having support for this in PF would be helpful.

A question was also recently raised about support for a responsive layout.  

Is it possible to add support for making the wizard footer sticky in the context of a page, but also have that stickiness adjust per breakpoint (because too many sticky regions in a small viewport doesn't leave much room for viewing the content region on the page)?

![image](https://user-images.githubusercontent.com/21063328/126328011-ef9f215d-a588-4e1c-8d07-e08eb31a9476.png)

**Comment by mcoker** [comment]
Hey @jgiardino! The wizard's footer should be sticky by default anywhere it's used. In the page, it requires being wrapped in a unique page section. Here is the react example showing the wizard in a page - https://patternfly-react.surge.sh/components/wizard/react-demos#in-page

Re: adjusting per breakpoint, @garrett has opened an issue around supporting height media queries and the work is scheduled to begin in an August/September sprint - https://github.com/patternfly/patternfly/issues/3660. Will that work for you?

**Comment by jgiardino** [comment]
Oh, thanks for sharing that! So maybe we're just missing the `type={PageSectionTypes.wizard}` on the `<PageSection>` component. As for the responsive issue, sure, that timeline works. Thanks for the info! I'm good with closing this.
