### ISSUE TITLE
Enhancements for advanced search input component

### ISSUE THREAD

**Issue by agagancarczyk** [patternfly/patternfly#4231]
Hi @mcoker , we're trying to use the advanced search input component (https://www.patternfly.org/v4/components/search-input#advanced) for the following search functionality in a new keylock UI, but the PF component is not supporting: 
**dropdowns, input fields with icons e.g calendar, and making "Has words" field optional**. 

Could you please advise if this enhancement can be implemented by your team and how long would it take? Many thanks!

![Screenshot 2021-07-22 at 09 24 29](https://user-images.githubusercontent.com/4890675/126610325-ff7327cd-b4e8-4450-82c9-c02c9ae590f1.png)

cc @mcarrano

**Comment by nicolethoen** [comment]
Hi @agagancarczyk!
So excited that keycloak is interested in the SearchInput component!
We are currently working on a number of enhancements and some refactoring for the component, so we could definitely discuss each of those features as part of that effort. The updates will not be available in the next upcoming release, but are on the roadmap. We will keep you posted.

**Comment by agagancarczyk** [comment]
Many thanks for your reply @nicolethoen. We have found an alternative solution but you may still wish to enhance this component for future users.

**Comment by mcarrano** [comment]
@agagancarczyk We recently introduced this demo for a composable search that I believe should address this.  Please take a look at: https://www.patternfly.org/v4/components/search-input/react-demos#composable-advanced-search
