### ISSUE TITLE
Add badge to notification drawer tab

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#4234]
After #4233 implements a badge option for the tab label, the badge should be added to the notification drawer alert tab as shown in this mockup https://marvelapp.com/prototype/g8idd54/screen/79182156

**Comment by srambach** [comment]
@mcarrano is this still part of the design for the enhanced notification drawer?

**Comment by mcarrano** [comment]
@srambach Let's hold on this. I'm still trying to get some direction from the OpenShift team on this one.

**Comment by mcarrano** [comment]
Looks like this is no longer an ask from OpenShift so I am closing.
