### ISSUE TITLE
CodeEditor copy action only copies the currently selected line of text

### ISSUE THREAD

**Issue by starpit** [patternfly/patternfly#4247]
I am using `@patternfly/react-code-editor@4.2.92`. When I click the copy button, only the current line of text is copied to the clipboard. I have to manually do a select-all in the content area, and then click the copy button in order to copy all of the text. Was this the intention?

**Comment by mcoker** [comment]
cc @tlabaj

**Comment by nicolethoen** [comment]
@starpit I believe that the code editor works where it copies all the text if you have it all highlighted OR if you have none of it highlighted. If the user has taken the time to highlight some text, it assumes that you are trying to copy the highlighted text.

You could also use the custom control to build your own version of a copy button that behaves differently.
