### ISSUE TITLE
Navigation variants: flyout, drilldown, third level expansion

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#4253]
- [ ]  Create flyout, drilldown and third level expansion navigation variants. 
- [ ]  Ensure they all work together

[Flyout](https://www.figma.com/proto/AJi4XmCkrdGEK532YmbAqH/tertiary-nav?node-id=0%3A2&scaling=min-zoom&page-id=0%3A1)
[Drilldown](https://www.figma.com/proto/AJi4XmCkrdGEK532YmbAqH/tertiary-nav?node-id=54%3A2191&scaling=min-zoom&page-id=53%3A2106)
[Third level](https://www.figma.com/proto/4HNu06gFjfAXs6tOroQ1QZ/composable_nav?node-id=0%3A649&scaling=min-zoom&page-id=0%3A344)

**Comment by beccaglass** [comment]
specs: https://docs.google.com/document/d/17jhcgkUgpw7f9Ixf9ew8RfcivSck9mdv_Yw6fIZhlAs/edit?ts=60cb76dd#heading=h.ea3lujnv46vp

**Comment by mcoker** [comment]
@mattnolting can this be closed?

**Comment by mattnolting** [comment]
Yep
