### ISSUE TITLE
CodeEditor does not respond to browser font zooming

### ISSUE THREAD

**Issue by starpit** [patternfly/patternfly#4254]
E.g. hitting cmd+/cmd- on macOS does not result in the expected change of font size in CodeEditor.

Related: there is no way to pass in a preferred initial font size. And with monaco this is not possible to override with css alone.

**Comment by mcoker** [comment]
cc @tlabaj 

@starpit fwiw, the font size on [our code editor example page](https://patternfly-react.surge.sh/components/code-editor/react/basic/) seems to scale OK for me on Mac in chrome, firefox, safari, and edge (our supported browsers). Or are you testing a different way?

### Chrome
<img width="1552" alt="Screen Shot 2021-07-30 at 1 02 45 PM" src="https://user-images.githubusercontent.com/35148959/127694037-d2058b5b-6d4e-41a3-9893-1718534a6395.png">


### Firefox
<img width="1715" alt="Screen Shot 2021-07-30 at 1 03 09 PM" src="https://user-images.githubusercontent.com/35148959/127694044-e7b994b5-7226-459d-942c-4163ea6c4c19.png">


### Safari
<img width="1715" alt="Screen Shot 2021-07-30 at 1 03 47 PM" src="https://user-images.githubusercontent.com/35148959/127694054-2fc9aef8-78a9-4605-973c-50315ea52a33.png">


### Edge
<img width="1591" alt="Screen Shot 2021-07-30 at 1 04 20 PM" src="https://user-images.githubusercontent.com/35148959/127694063-b8991b3a-e1f7-4e88-ba1a-3e492b5d2e96.png">

**Comment by starpit** [comment]
Hey! Thanks, to clarify: if i adjust the font-size say of the `root` element, CodeEditor neither adjusts to this, nor does it allow me to specify the font-size i want to use.

**Comment by mcoker** [comment]
@starpit gotcha! Looks like the editor API supports setting a `fontSize` - https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html. I'll wait for one of the react devs to reply.

**Comment by nicolethoen** [comment]
@starpit @mcoker 
To adjust the fontSize of the CodeEditor, you can pass a `fontSize` property via the CodeEditor's `options` prop like this: 
`<CodeEditor options={{fontSize: 300}}/>`
