### ISSUE TITLE
Add Disabled variant for tabs

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4257]
Want to add a disabled tab variant. Design spec here: 

![image](https://user-images.githubusercontent.com/6619860/127696632-a2bb6240-4399-4e5a-bfe5-92b8c18d854f.png)

Want the ability to display tooltips on the disabled tabs as we do for buttons. See original design request here: https://github.com/patternfly/patternfly-design/issues/1066

**Comment by lclay2** [comment]
@jessiehuff, Hi I'm working on the usage guidelines for this feature. Are there any a11y considerations related to this that would be helpful for designers to know about - things they can do in the design to make this feature more accessible? Thanks!
