### ISSUE TITLE
Select with variant={SelectVariant.typeaheadMulti} and validated="error" shows two error icons

### ISSUE THREAD

**Issue by jjmerri** [patternfly/patternfly#4263]
I created this codesandbox which was copied from the patternfly docs and added `validated="error"`
https://codesandbox.io/s/relaxed-smoke-0dr2t?file=/index.js

![image](https://user-images.githubusercontent.com/17522082/128233390-c01bb6e9-aca9-44fd-8dbd-eb0418cc27cb.png)

Minimal reproduction:
```
<Select variant={SelectVariant.typeaheadMulti} validated="error"></Select>
```

**Comment by mcoker** [comment]
@jessiehuff can you confirm whether `aria-invalid` belongs on the text input in an invalid typeahead select, or if it would go on the toggle button like the other select examples?

**Comment by jjmerri** [comment]
@jessiehuff bump

**Comment by mcoker** [comment]
@mcarrano can we add this to an upcoming sprint? It's currently causing the bug above where 2 error icons show up in the typeahead multi-select when it is in the invalid state.
