### ISSUE TITLE
Dropdown options should be displayed in a fixed position

### ISSUE THREAD

**Issue by jonkoops** [patternfly/patternfly#4265]
We're displaying a Dropdown in our application that is inside of a modal. Because the list of options is positioned absolutely it will create scroll bars in the modal and the options will slip below the fold.

**Before selecting**
![image](https://user-images.githubusercontent.com/695720/128348065-762206cc-3aaa-46da-93fb-09de0b8922c9.png)

**Dropdown clicked**
![image](https://user-images.githubusercontent.com/695720/128348107-6b847a09-7d18-40f2-8bfb-c6f0c319c153.png)

As you can see the options fall under the fold of the modal, causing confusion for the user. Ideally we'd like to see the Dropdown work the same as the native dropdown would. Which is to have a position above all the other elements of the page, whilst also not affecting the scroll-able area when inside a container with overflow scroll. Sort of like this (but without the scroll bar):

![image](https://user-images.githubusercontent.com/695720/128348424-22cc8c2b-9984-41b6-a5ff-d29f3b40b955.png)

For more information see the related issue in our project https://github.com/keycloak/keycloak-admin-ui/issues/538#issuecomment-893099974

**Comment by jonkoops** [comment]
This can be fixed by positioning the element in the document by passing `menuAppendTo={() => document.body}` to the `Select`. However this does come with the downside that there are no ARIA attributes to associate the elements, creating a possible A11Y issue.

**Comment by mcoker** [comment]
cc @jessiehuff are there any extra a11y considerations needed for when the select menu is detached from the select component/toggle?

**Comment by jessiehuff** [comment]
When I tested our example of this with our[ select menu document body example](https://www.patternfly.org/v4/components/select/#select-menu-document-body), I noticed that I was unable to navigate into the menu by screen reader, so there likely are a11y considerations that we need to add. I'm not entirely sure what those considerations would be though as I don't think I've seen this exact pattern before, but I created [this issue ](https://github.com/patternfly/patternfly-react/issues/6150)to investigate.
