### ISSUE TITLE
Description List: provide an option to fill columns not rows first

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#4281]
The provided DescriptionListGroup items, will fill the page horizontally first, by filling the rows and then rows.

Would it be possible to provide a property to make them first fill in the columns?

In cockpit we use Description List in the following scenario:
![Screen Shot 2020-09-10 at 16 10 48](https://user-images.githubusercontent.com/14921356/92742738-36dc6b80-f380-11ea-8205-3e0cc8e2c8cf.png)

As you can see some of the data are more related to each other, IOW there are groups.

Let's visualize the above data as two groups, group1 for CPU info and group2 for BIOS info.

Our React code of course has the groups in order,
```
<DescriptionListGroup>
item1-group1
item2-group1
item3-group1
</DescriptionListGroup>
<DescriptionListGroup>
item1-group2
item2-group2
item3-group2
</DescriptionListGroup>
```

Now the groups fill horizontal space. I feel like the users would expect to find the groups vertically listed though. I can achieve this effect by setting `grid-auto-flow: column` and also the `grid-template-rows` rule.

Resulting in:
![Screen Shot 2020-09-10 at 16 15 50](https://user-images.githubusercontent.com/14921356/92743662-0943f200-f381-11ea-9f46-839bcd453dd2.png)

I am just raising the point here, feel free to close the issue if you think the current implementation does not need this flexibility.

**Comment by garrett** [comment]
not stale
