### ISSUE TITLE
Toolbar hides labels in collapsed state

### ISSUE THREAD

**Issue by marusak** [patternfly/patternfly#4284]
Using example: https://www.patternfly.org/v4/components/toolbar/react/stacked-example/
Changing browser size so toolbar is collapsed it looks like this:
![Screenshot from 2021-08-11 14-40-10](https://user-images.githubusercontent.com/12330670/129030666-15516cb2-b8cc-4c3c-b02c-b646162958cd.png)

Labels for all selects are not displayed. This seems odd, as for someone who only sees this collapsed state (like mobile users) would have hard time understanding what these selects do.

Removing [THIS](https://github.com/patternfly/patternfly/blob/main/src/patternfly/components/Toolbar/toolbar.scss#L338) rule makes it look like this, which seems much more user friendly:
![Screenshot from 2021-08-11 14-40-30](https://user-images.githubusercontent.com/12330670/129030905-e8b1f90e-c0f3-44c6-8810-5ad4a3b4c78a.png)

I would even send PR with removal of this one rule, but I feel like I am not understanding why it was introduced in the first place.

**Comment by mcoker** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
I think what you are suggesting makes sense @marusak .

@mattnolting @nicolethoen can you take a look at this? I can't remember what the context was here for this example. Typically we don't include labels like this in the toolbar for space considerations, but I think we wanted to show that this is possible. Do the labels need to be hidden when we collapse the filter group?

**Comment by nicolethoen** [comment]
I dont have any memory of a need to hide the labels. Should be simple enough
