### ISSUE TITLE
Toolbar demos overlapping & duplicated

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly#4287]
The [toolbar HTML demos](https://www.patternfly.org/v4/components/toolbar/html-demos/#toolbar-attribute-value-single-select-filter-desktop) overlap each other as the select items seem to overflow the example container.

Additionally, the '[Toolbar attribute value checkbox select filter on mobile](https://www.patternfly.org/v4/components/toolbar/html-demos/#toolbar-attribute-value-checkbox-select-filter-on-mobile)' demo looks to be listed twice.

**Comment by mcoker** [comment]
@mcarrano can we add this to an upcoming milestone?
