### ISSUE TITLE
Form demo - bug?

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly#4288]
Was looking at helper text [HTML examples](https://www.patternfly.org/v4/components/form/html#help-text) and noticed inconsistencies in spacing. 

The bottom helper text example is inconsistent with the rest in two ways:
1. The spacing between the input field and the helper text is bigger than in the others (and in my mind, wrong)
2. The last example has an icon in front of the helper text, while the other examples do not.

Wondering if this is a bug, or an intentional thing? 

<img width="830" alt="Screen Shot 2021-08-11 at 4 09 18 PM" src="https://user-images.githubusercontent.com/51165119/129096243-10d39b84-af4c-407e-aec3-01b032171dbf.png">

I also noticed the added icon in the helper text in these examples... is this a new thing? How come some of the examples have it and some don't? Seems redundant when it's already present in the input field itself.

![image](https://user-images.githubusercontent.com/51165119/129096575-e3d3a835-a0e7-4ad7-a3ad-cb23c41b2cce.png)

cc: @arburka

**Comment by mcoker** [comment]
> The spacing between the input field and the helper text is bigger than in the others (and in my mind, wrong)

@mmenestr that is a bug, @mcarrano can we add this issue to an upcoming milestone?

> I also noticed the added icon in the helper text in these examples... is this a new thing? How come some of the examples have it and some don't? Seems redundant when it's already present in the input field itself.

That's been a feature of the helper text element for a while. It was originally added to support use of helper text in the [login component](https://www.patternfly.org/v4/components/login-page/html/invalid/). This example on the form page is just demonstrating the ability to add an icon - I'm not sure about the redundancy of the icon also in the form field. It's visible in the react examples, too - https://www.patternfly.org/v4/components/form. @mcarrano do you think we should change the examples?

**Comment by mcarrano** [comment]
@mcoker adding this issue to the next sprint. Regarding the helper text icon. Yeah, it seem redundant and contrary to our guidance. Can we just remove that from the examples and then we can follow up with a React issue?

**Comment by mcoker** [comment]
> Can we just remove that from the examples and then we can follow up with a React issue?

@mcarrano yep. Though do you want to remove the icon or the status in the input fields? I'd like to keep an icon in one of the examples if we can so it's visible and not just referenced in the docs. Maybe we could add an icon to regular (black text) helper text that doesn't have a state associated with it?
