### ISSUE TITLE
Revisit semantics of the card component

### ISSUE THREAD

**Issue by thomasmaas** [patternfly/patternfly#430]
Given that the card component represents a piece of individual content it's almost always defendable and very often preferable to use an `<article>` element. And given that the `<article>` element is a sectioning element, using it would make it possible to also use the `<header>` and `<footer>` elements inside of it. The idea is to reflect this most common use case in the examples to stimulate optimal HTML semantics. 

So instead of 

```
<div class=".pf-c-card">
  <div class="pf-c-card__header></div>
  <div class="pf-c-card__body></div>
  <div class="pf-c-card__body></div>
</div>
```  
we would have:

```
<article class=".pf-c-card">
  <header class="pf-c-card__header></header>
  <div class="pf-c-card__body></div>
  <footer class="pf-c-card__body></footer>
</article>
```  

cc: @jgiardino

**Comment by jgiardino** [comment]
Thanks for adding this issue, @thomasmaas!

I'm adding a few details here for reference and background info...

There are a couple of examples out there regarding html for cards:

- [Card example on inclusive-components.design](https://inclusive-components.design/cards/), uses `<li>` for the card
- [Card example from Jen Simmons](https://www.youtube.com/watch?v=dQHtT47eH0M), uses `<article>`

Both approaches are valid, plus variations on those approaches. The html someone would use really depends on the context. If the context was a card view with pagination, then there's additional benefit to the user by using `<li>`, which could also have a child `<article>`. In the context of a dashboard, using `<article>` is definitely appropriate, and the more generic `<section>` might be better for other cases too (like cards nested inside a parent card that already has `<article>`.

I do agree with the original issue description to update the examples from `<div>` elements to the ones recommended. Additionally, I'd like to see these updates made:

1. A note adjacent to the example that calls attention to the fact that the html elements being used are the most common, but to refer to the Accessibility section for examples of other elements that could be used depending on context. 
2. A test example (doesn't need to be merged in the final update, but just tested to make sure it displays as expected) to check that the following additional elements are supported for the `.pf-c-card` element:
    - `<section class="pf-c-card">`
    - `<li class="pf-c-card"><article>`
    - `<li class="pf-c-card"><section>`
3. Details added to the Accessibility section on when the elements listed above would be used.

@andresgalante @dgutride For # 1. above, is this doable? Are you ok with adding something like this? I'm guessing this would be a separate issue to be able to add that note somewhere to the component page.

**Comment by jgiardino** [comment]
Just wanted to include some notes for a quick [test](https://rawgit.com/andresgalante/jenn/master/cards.html) I did with JAWS of different combinations of elements related to the Card component.

- Article: 
  - announces article beginning and end
- Section:
  - doesn’t announce section as a section
  - would require a label to identify it as something that is announced
- Lists
  - for unordered list items when `list-style-type` is `disc`, list items are announced with “bullet”
  - for ordered list items when list-style-type is `decimal`, list items are announced with their number
  - for both types of list items, when `list-style-type` is `none`, JAWS doesn't announce anything to indicate the beginning or end of a list item
- Article nested inside list item
  - when `list-style-type` is the default for `ul`, list item is ignored, and article is announced instead

I still think it's worth supporting different elements for Card. But it would be good to do additional testing to see if aria attributes can be used to supplement the semantics that seem to be tied to the `list-style-type` style. And it would be great to get some user testing on this too, once we have a demo page for cards, to verify that this information is relevant and helpful.

**Comment by mcoker** [comment]
cc @jessiehuff do you want to leave this open?
