### ISSUE TITLE
Examine flyout menu parent element

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4306]
re: https://github.com/patternfly/patternfly/pull/4301#discussion_r691216222

We're using a button for the flyout menu parent element, and looks like we should be using an anchor - https://www.w3.org/WAI/tutorials/menus/flyout/#use-parent-as-toggle

**Comment by mcoker** [comment]
@mcarrano can we add this to an upcoming milestone?

**Comment by mcarrano** [comment]
@mattnolting @mcoker I think we can close this out for now. Upon discussion in the Leads meeting today, this doesn't feel like something we should support from a design perspective unless or until it's requested from project. Right now, the way our product navs are designed, there does not seem to be an expectation that an item that has children is also a link to a page.
