### ISSUE TITLE
Launcher menu obscured sticky page section header

### ISSUE THREAD

**Issue by vjwilson** [patternfly/patternfly#4321]
I think my team has found a bug with the interaction between a couple of CSS vars for z-index values.

`--pf-c-app-launcher__menu--ZIndex` has a value of 200.
--pf-c-page--section--m-sticky-top--ZIndex has a value of 300

This leads to an open launcher menu being partial covered by a sticky main section header.

We can override in our app for now, but I think this should work out-of-the-box. 

PF version: 
`"@patternfly/react-core": "^4.147.0",`

Example screenshot:
![Screen Shot 2021-08-23 at 9 43 17 AM](https://user-images.githubusercontent.com/715729/130463800-53242f47-cfb2-47d4-b050-43603af6252b.png)

**Comment by mcoker** [comment]
Hey @vjwilson! It looks like your menu is coming from the page header. The page header has a higher `z-index` than the main section, so elements from the header should appear on top of the main section, regardless their `z-index`. Here is an example where I've set the app launcher menu's `z-index` to `auto` - https://codesandbox.io/s/sweet-kalam-ezogw?file=/style.css

I'm curious if you are using the page component for the overall page chrome with the page component's `.pf-c-page__header` and `pf-c-page__main` elements for the header and main content area? Also are you able to share a URL with the problem, or fork my codesandbox and reproduce the issue so I can see it in the browser?

**Comment by vjwilson** [comment]
@mcoker Thanks for helping troubleshoot this. I discovered that we had added those z-index overrides in our very first PR to start our migration to PatternFly, when we still didn't really understand how things fit together.

I was able to remove those overrides, and my later overrides, and everything seems hunky-dory. Sorry for the false alarm.
