### ISSUE TITLE
Unstyled "0" when no results in SearchInput

### ISSUE THREAD

**Issue by ianw** [patternfly/patternfly#4330]
You can see below there is a "0" in the search results when nothing is found and `resultsCount=0`.  It's not styled like the counter number (in a grey label)

![Screenshot 2021-08-25 at 14-04-06 Zuul Projects](https://user-images.githubusercontent.com/108448/130724780-0d7ee43c-0846-481a-8d6c-5b9809ee5683.png)

It isn't really documented what should happen, but I think this possibly looks a bit odd?  I'd just expect a "0" in the grey label like when >0

This is implemented in 

https://review.opendev.org/c/zuul/zuul/+/805581

Another way to see it it is to edit the "results count" example on https://www.patternfly.org/v4/components/search-input/ and instead of `resultsCount: 3` set it to `0`

**Comment by mcoker** [comment]
cc @tlabaj
