### ISSUE TITLE
SearchInput advanced search in PageSection doesn't expand height

### ISSUE THREAD

**Issue by ianw** [patternfly/patternfly#4331]
I have implemented an advanced search that looks like

![Screenshot_2021-08-25_14-20-20](https://user-images.githubusercontent.com/108448/130726076-2f288b43-89c4-4d63-b6ab-4228ba895e9c.png)

however, if the results are short, then the search box gets cut off

![Screenshot_2021-08-25_14-20-54](https://user-images.githubusercontent.com/108448/130726112-0506486d-8557-44f2-b3ec-81c2d1024153.png)

I fully expect the answer is that it is user error.  I guess something needs a `min-height`?  Is it possible for the SearchInput to just handle this and make sure if it is in a PageSection it expands to show the full search menu?  If there is some sort of answer, I'll be happy to help add it to the documentation.

**Comment by mcoker** [comment]
Hi @ianw,  from https://www.patternfly.org/v4/components/page/react-demos/, can you verify this is in place?

> To make the page take up the full height, it is recommended to set the height of all ancestor elements up to the page component to `100%`

**Comment by mcoker** [comment]
@ianw sorry for the delayed response! It means all parent elements of `.pf-c-page` need `height: 100%;`. If you're also importing our global styles (they're included by default unless specifically excluded), `html` and `body` already have `height: 100%;`, so you only need to specify the height for elements between `<body>` and `.pf-c-page`.

We have a utility class `.pf-u-h-100` you can use, but you'll need to import the entire sizing utility to get that class. Unless you're already using that utility, or prefer using utilities over writing custom CSS, I would just recommend writing a few CSS rules. Assuming your page has the structure of:

```
<html>
<body>
  <div id="root">
    <div id="router">
      <div class="my-app">
        <div class="pf-c-page">
          ...
```

The CSS would look like

```
#root, #router, .my-app {
  height: 100%;
}
```
