### ISSUE TITLE
Password generator demo

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly#4340]
In addition to the password strength indicator, this would be an enhancement to the input field that allows for a menu to appear once selecting the field (similar to typeahead) that presents a randomly generated value. We are going with a different way of approaching this for the time being in OCM, but it'd greatly improve the feature if we were able to do what I have below! My guess is that this would be best to add to the password strength component that was recently designed. No real rush on the timeline here - the sooner it's released, the sooner we can update our feature to use it!

<img width="649" alt="Screen Shot 2021-06-07 at 10 15 47 AM" src="https://user-images.githubusercontent.com/30870144/121032511-566ebc00-c779-11eb-945e-800b5763b0f5.png">

<img width="573" alt="Screen Shot 2021-06-07 at 10 16 02 AM" src="https://user-images.githubusercontent.com/30870144/121032569-5ff82400-c779-11eb-82cf-178c2ebf70bf.png">

**Comment by mcarrano** [comment]
@mcoker I'm looking this over again and thinking that maybe this can be created using the new composable panel. Let me know if you have further questions about implementation. There are some additional mocks here: https://marvelapp.com/prototype/c7j2b6b/screen/80220689 They are essentially the same as what's included in the issue description.
