### ISSUE TITLE
Progress button completion state

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly#4354]
I have a use case that is either an extension of the progress button or a new component. 
I would like to use the progress button to show that an action is happening in the background, and then change the button state to show that the action has completed. This could possibly also show that the action has failed, although that's not needed for my use case.

My example:
![progress button](https://user-images.githubusercontent.com/6415742/131010562-31781e00-0c50-479c-a58d-f00e1c13b4fe.png)
User goes to log in to their Red Hat account and is prompted to link their company IdP to their Red Hat account. During this process, change the button to a progress button to show the linking is happening (and also disable the button so the user can't submit multiple times), then show that the link is complete for a few seconds before redirecting to the user's destination.
In this use case I'm using the Brand primary button color.
I can't use a toast on the next step because at that point the user has left the SSO app. It would require adding code to every system that uses Red Hat SSO which isn't viable. Another option would be to show an interstitial page or a toast on this page before it redirects. 

Is this something that can be achieved with existing components + js?

**Comment by ajacobs21e** [comment]
@mcarrano sorry I missed this. I don't have a specific deadline. Is this something that can still be made into a demo please? Thanks!

**Comment by mcarrano** [comment]
Yes. This is currently on our roadmap for January.
