### ISSUE TITLE
Table demo: move expand all control from toolbar to table header

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4366]
Per [this design issue](https://github.com/patternfly/patternfly-design/issues/1071) want to update the demo here to locate the "expand all" control to the table header. https://www.patternfly.org/v4/components/table/html-demos#expandable.

Design proposal looks like this:

![image](https://user-images.githubusercontent.com/6619860/132701911-26fd3134-0057-477b-9569-46a1a643708e.png)

Want to implement Proposal 2.

**Comment by srambach** [comment]
Will also remove the demos https://www.patternfly.org/v4/components/toolbar/html-demos#toolbar-expand-all-collapsed and https://www.patternfly.org/v4/components/toolbar/html-demos#toolbar-expand-all-expanded that are showing the expand/collapse all in the toolbar above a table. Per @mcarrano in the future, we might want to add a demo to the expandable datalist to show this.
