### ISSUE TITLE
Support key-value filtering

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4374]
some sort of input with menu that can be used to support key-value filter use cases for selecting multiple search terms. See the proposed design here: https://marvelapp.com/prototype/15dbe4c9/screen/81845426 

@nicolethoen @kmcfaul @tlabaj please review and let me if you see any issues and how best to proceed.

@jessiehuff would also love your input from a a11y perspective.

**Comment by nicolethoen** [comment]
This likely should be a composable input - to be paired with a menu to build an attr-value advanced search. The core implementation does not need to include the menu. It could build upon a preexisting input component? like form control?
