### ISSUE TITLE
Implement styles for DragDrop component

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#4376]
Follow up work for https://github.com/patternfly/patternfly-react/pull/6258

**Comment by redallen** [comment]
There are 2 components, `<div className="draggable">` and `<div className="droppable">`. Interactions and DOM structure can be found [here.](http://patternfly-react.surge.sh/components/drag-and-drop)

Droppables have 2 states with box shadows, valid and invalid.

Draggables also have 2 states with box shadows, valid and invalid. Invalid should have `cursor: 'not-allowed'`. There is an additional 3rd state of being dragged. Non-dragging items have animations for moving as the user drags over them. The dragging item has another animation for returning home after an invalid drop.

You can see the various [`setStyle` tags implemented in React](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/DragDrop/Draggable.tsx#L130) to see what exactly is being used now. Some things like draggable's `transform: translate(mouseX, mouseY)` and `background: getDefaultBackground()` will have to stay, but the rest should be classes!

**Comment by mcarrano** [comment]
Here are the designs for reference: https://marvelapp.com/prototype/h198be4/screen/81623894
