### ISSUE TITLE
certain "diagonal" tooltip positionings result in no caret/pointer

### ISSUE THREAD

**Issue by starpit** [patternfly/patternfly#4382]
When using bottom-start or bottom-end or top-start or top-end, the "pointer" part of the tooltip is not visible.

See #3930 for a related feature.

CodeSandbox: https://codesandbox.io/s/cranky-chaum-obqn8?file=/index.js

bottom-start (buggy):
<img width="332" alt="Screen Shot 2021-09-20 at 2 27 57 PM" src="https://user-images.githubusercontent.com/4741620/134054917-ad65bc25-d3b4-4e2e-82d8-c2d3d568f975.png">

bottom (correct):
<img width="320" alt="Screen Shot 2021-09-20 at 2 28 18 PM" src="https://user-images.githubusercontent.com/4741620/134054950-9715dc77-0b61-46c5-8cad-160a01f34a14.png">

**Comment by mcoker** [comment]
@mcarrano we only added this to the popover - can we create an issue to add to the tooltip, too?

**Comment by starpit** [comment]
Thanks!

Oh, maybe my pointer to #3930 was misleading. I can't to be honest remember if Tooltips had that positioning behavior prior to #3930... In any case, the diagonal positions are [documented](https://www.patternfly.org/v4/components/tooltip) and seem to have some visual effect (the tooltip body indeed moves), and typescript doesn't complain about the property value.

**Comment by mcoker** [comment]
@starpit thanks!
