### ISSUE TITLE
"form select" padding is not consistent with PatternFly "select"

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#4387]
When set to auto width, the dropdown icon is too close to the text:
![Screenshot 2021-09-21 at 10-31-29 PatternFly 4 • Form select](https://user-images.githubusercontent.com/10246/134143208-603178d0-d87e-4547-9964-4c67cf0f1474.png)

It looks like it's set to 24 pixels padding to the right, which _includes_ the icon, padding to the right, and padding to the left:
![Screenshot from 2021-09-21 10-31-33](https://user-images.githubusercontent.com/10246/134143570-c84a089d-2ade-4315-81d2-62b7675b29a6.png)

Here's the non-form PatternFly select, also set to auto width:
![Screenshot 2021-09-21 at 10-31-07 PatternFly 4 • Select](https://user-images.githubusercontent.com/10246/134143361-82463ffc-5bbb-4210-b9a5-ee6c27ac25be.png)

Meanwhile, the same icon in the PF select is 24px + 8px to the right + 16px to the left. That's 48px total, twice of what the form select.
![Screenshot from 2021-09-21 10-31-12](https://user-images.githubusercontent.com/10246/134143546-d2948ca2-b316-4eae-8f04-1e8303028d1d.png)

---

Here's a comparison, with PF select on top and the PF's styled form select (multiple times, under the first one) aligned to different locations:

![Screenshot from 2021-09-21 11-13-21](https://user-images.githubusercontent.com/10246/134144848-66958b6c-721f-4586-81bd-5df3b2123d76.png)

Here's a difference with the form select being at 25%:

![select-comparison](https://user-images.githubusercontent.com/10246/134145142-c3fdd7eb-fb50-4cbd-af02-175383fa8b38.png)

We can see that vertical padding is fine, text is fine, and even the dropmarker to the right side is fine.

The problems:

- calculation of the padding on the right to change the width between the text and dropdown icon (a little too much)
- padding on the left between the border and the text (noticeably not enough)

---

For context: We encountered this issue in Cockpit-Podman @ https://github.com/cockpit-project/cockpit-podman/issues/755. There are additional screenshots on that issue, but hopefully the ones here communicate the issue enough.

**Comment by garrett** [comment]
Here's a fix:

```scss
select.pf-c-form-control {
    --pf-c-form-control--PaddingRight: 41px;
    --pf-c-form-control--PaddingLeft: 6px;

    // Firefox's select text has additional padding of 2px on left & right
    @-moz-document url-prefix() {
        --pf-c-form-control--PaddingRight: 37px;
        --pf-c-form-control--PaddingLeft: 2px;
    }
}
```

This has been confirmed to work in the following browsers:

- Firefox Linux
- Chrome (Chromium) Linux
- GNOME Web (WebKit) Linux
- Firefox Windows
- Edge (Chromium) Windows

The above snippet makes "form select"s look similar to PF's non-form "select" in all browsers on Windows and Linux. I'm unsure of any macOS browsers yet.

I don't like that it's using magic numbers and has a hack to target Firefox (which has a padding around the text other browsers do not have). Ideally, we would:

- Make it not use magic numbers, but based on some already existing multiple of PF's spacing unit (probably based on icon's width plus padding on the sides of it for the rightmost padding)
- Target the text in Firefox to remove the redundant padding instead of using a `@-moz-document` targeting hack

I dug into https://searchfox.org/mozilla-central/source/layout/style/res/forms.css (Firefox's form CSS source) to see where the text box padding is coming from and if we could override it somehow. I didn't see an obvious solution.

**Comment by garrett** [comment]
For the non-Firefox values, the left padding looks like it's 0.5 of spacer, the right seems like 2.5 of spacer might be about right (I'd have to re-check with both in-page). For Firefox, we could use the same values in a calc() and remove 4px to make it pixel perfect with the rest.

**Comment by mcarrano** [comment]
@mcoker thoughts?
