### ISSUE TITLE
Create a Rich Text Editor component

### ISSUE THREAD

**Issue by gautamkrishnar** [patternfly/patternfly#4388]
We need to have a standard rich text editor for all of our apps. Currently, most of our Drupal apps use CKEditor (https://ckeditor.com/) for this purpose. SPAs use some libraries depending on their availability and framework support. 

We need to make it a part of the Patternfly library in order to standardize it.

**Comment by mcarrano** [comment]
@gautamkrishnar can you give me more information about the project you are working on and your requirements? We could potentially provide a PatternFly wrapper to a third party editor like we do for the Code Editor component, but we will need more information before we can commit to that.

**Comment by gautamkrishnar** [comment]
@mcarrano We are working on certified technology apps for Red Hat partners. Our React SPAs are deployed under https://connect.redhat.com. 

We currently created a wrapper on top of CKEditor to serve our purpose. The Rich text editor component looks like the following:

![Screenshot 2021-09-22 at 9 07 22 PM](https://user-images.githubusercontent.com/8397274/134701454-0dc80118-e056-4084-bb9e-37597949f11d.png)

In the above example, we made a wrapper that uses Patternfly React's [FormGroup](https://www.patternfly.org/v4/components/form) react component and CKEditor to get the desired result we need. The output of the component is HTML code generated from the provided text and formatting applied.

**Comment by mcarrano** [comment]
@guatamkrishnar Sorry to take so long to get back to you about this. We've had a chance to review this within the PatternFly team, and while we can see the potential benefits of standardizing on an approach, we try to limit bundling 3rd party libraries like this with PatternFly as much as possible. Another approach we could take is to expose your current solution as a community extension. You can read more about Community extensions here: https://www.patternfly.org/v4/extensions/community-extensions. This will make your approach sharable to a wider audience and hopefully promote some consistency among users of PatternFly.

Is this something you would be interested in contributing? If so, we can help walk you through the process. Let me know.

**Comment by mcarrano** [comment]
I am going to close this out per my note above. @guatamkrishnar the offer still stands to include this as a community extension if that's still of interest.
