### ISSUE TITLE
Reduce spacing for popover and tooltip

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4422]
~~Want to reduce outer padding around content for Popover and Tooltip to 16px.~~

Talked to @mceledonia and he clarified that we need to update the tooltip to have 8px padding all around. The popover is OK as it is.

He would also like to decrease the size of the tooltip's arrow by 50%.

See https://github.com/patternfly/patternfly-design/issues/1081 for discussion.

**Comment by nicolethoen** [comment]
closed by https://github.com/patternfly/patternfly/pull/4462
