### ISSUE TITLE
Request for sticky footer and header for modal

### ISSUE THREAD

**Issue by thile01** [patternfly/patternfly#4430]
I would like to add the sticky header/footer pattern to modal please.

Default state:
![default](https://user-images.githubusercontent.com/89646477/136569648-cc264ef7-1661-4dc6-a5a8-d4f07ca3d95d.png)

Scroll state:
![scroll](https://user-images.githubusercontent.com/89646477/136569674-d6dc2655-7548-4882-819a-80bf2d7ad71c.png)

**Comment by mceledonia** [comment]
@thile01 It seems like this is actually the default behavior for the modal once it reaches the max height of the viewport. The header and footer become sticky and the content area is scrollable. Does this solve for your use case, or is something additional required?

**Comment by thile01** [comment]
@mceledonia Yes, this works perfectly! Thanks so much!

**Comment by mcarrano** [comment]
Great to hear that this solution works @thile01 . I am going to close this issue in that case.
