### ISSUE TITLE
Aggressive styling on header tags

### ISSUE THREAD

**Issue by zwitter1** [patternfly/patternfly#4515]
By default Patternfly asserts that all header html tags are to have a font-size of 100%. This seems rather strong and potentially confusing given that we are effectively nullifying several default html tags. Should this maybe be included as part of pf-c-title if that is the primary purpose of this styling decision?

![Screen Shot 2021-11-12 at 10 15 28 AM](https://user-images.githubusercontent.com/1789250/141491907-e4fe143a-5c01-4f7d-80cb-fa4bcea6258d.png)

**Comment by mcoker** [comment]
Hey @zwitter1, this is part of the global reset CSS to reset the heading `font-size` and `font-weight` to a common baseline, so their usage in all components is consistent with the PF design. https://github.com/patternfly/patternfly/blob/d3de31d993b01a1340bb6826c4dcb2b1ddfdf468/src/patternfly/base/_globals.scss#L39-L47

If using a heading in PF, you can use the title component as mentioned, or if you just prefer write HTML and/or don't want to use the title component and get the default PF typography styles for each heading, you can use the `<Text>` react component https://www.patternfly.org/v4/components/text and/or the HTML equivalent, the "content" (`.pf-c-content`) component https://www.patternfly.org/v4/components/text/html.
