### ISSUE TITLE
npm run build give different visual to the Select component

### ISSUE THREAD

**Issue by mchenier** [patternfly/patternfly#4517]
When we launch our react application with npm start everything looks like we intended. But when we do a build for production release with "npm run build" we encounter styles that have changed in the Select component. The border of the select box becomes invisible even tough the isPlain props is set to false. 

Versions:
"@patternfly/patternfly": "^4.151.4",
"@patternfly/react-charts": "^6.21.8",
"@patternfly/react-core": "^4.168.8",
"@patternfly/react-icons": "^4.19.8",
"@patternfly/react-styles": "^4.18.8",
"@patternfly/react-table": "^4.37.8",
"react": "^17.0.2",

Please let me know if you need other informations or details.

**Comment by mchenier** [comment]
I tried the simplest Select box in the patternfly-react-seed project and now the build works. There must be something in my project conflicting with the Select CSS but I can't put my finger on it. If you have any suggestion of where to look at that would be appreciated.

**Comment by mcoker** [comment]
Hey @mchenier, looks like you're probably running into a bug with cssnano and how it tries to optimize CSS variables. There is a fix mentioned in this issue - https://github.com/patternfly/patternfly-react/issues/5650#issuecomment-822667560

Let me know if that doesn't work for you.

**Comment by mchenier** [comment]
I see that my version for cssnano is this. So it can indeed be the problem.
react-scripts@4.0.3
  └─┬ optimize-css-assets-webpack-plugin@5.0.4
    └── cssnano@4.1.11 

I then tried to add the "patched" css in a Test.css file like so.
.pf-c-select__toggle:before {
  border-top: var(--pf-c-select__toggle--before--BorderTopWidth) solid
    var(--pf-c-select__toggle--before--BorderTopColor);
  border-right: var(--pf-c-select__toggle--before--BorderRightWidth) solid
    var(--pf-c-select__toggle--before--BorderRightColor);
  border-bottom: var(--pf-c-select__toggle--before--BorderBottomWidth) solid
    var(--pf-c-select__toggle--before--BorderBottomColor);
  border-left: var(--pf-c-select__toggle--before--BorderLeftWidth) solid
    var(--pf-c-select__toggle--before--BorderLeftColor);
}

I imported that css file in my component that used the Select component. Im not sure that's the way to do it since I never played with css customization so maybe you can correct me there.

But after doing that I still have the same problem.

**Comment by mcoker** [comment]
@mchenier my best guess is the problem is either that you're using `:before` in the selector instead of `::before`, and/or your custom CSS is being loaded before the PF CSS instead of after - it needs to come after the PF CSS so it can override the original rules.

The code you pasted works in this demo I've put together here - https://codepen.io/mcoker/pen/GRvzGPZ?editors=0110

**Comment by mchenier** [comment]
That maybe a stupid question but how I assure the custom CSS is loaded after PF CSS ? 
Here is my test component I load at the app start.

Test.tsx
```
import { useState } from 'react';
import {
  Select,
  SelectOption,
  SelectOptionObject,
  SelectVariant,
} from '@patternfly/react-core';
import './Test.css';

const Test = (): JSX.Element => {
  const [isOpen, setIsOpen] = useState(true);

  const options = [
    <SelectOption key={0} value="Select a title" isPlaceholder />,
    <SelectOption key={1} value="Mr" />,
    <SelectOption key={2} value="Miss" />,
    <SelectOption key={3} value="Mrs" />,
    <SelectOption key={4} value="Ms" />,
    <SelectOption key={6} value="Dr" />,
    <SelectOption key={7} value="Other" />,
  ];

  const onToggle = (isOpenParam: boolean) => {
    setIsOpen(isOpenParam);
  };

  const clearSelection = () => {
    setIsOpen(false);
  };

  const onSelect = (
    _event: React.MouseEvent<Element, MouseEvent> | React.ChangeEvent<Element>,
    _selection: string | SelectOptionObject,
    isPlaceholder?: boolean | undefined
  ) => {
    if (isPlaceholder) clearSelection();
    else {
      setIsOpen(false);
    }
  };

  return (
    <>
      <Select
        variant={SelectVariant.single}
        onSelect={onSelect}
        onToggle={onToggle}
        isPlain={false}
        isOpen={isOpen}
        width="120px"
      >
        {options}
      </Select>
    </>
  );
};

export default Test;
```

And the Test.css
```
.pf-c-select__toggle::before {
  border-color: var(--pf-c-select__toggle--before--BorderTopColor)
    var(--pf-c-select__toggle--before--BorderRightColor)
    var(--pf-c-select__toggle--before--BorderBottomColor)
    var(--pf-c-select__toggle--before--BorderLeftColor);
  border-style: solid;
  border-width: var(--pf-c-select__toggle--before--BorderTopWidth)
    var(--pf-c-select__toggle--before--BorderRightWidth)
    var(--pf-c-select__toggle--before--BorderBottomWidth)
    var(--pf-c-select__toggle--before--BorderLeftWidth);
}
```

**Comment by mcoker** [comment]
@mchenier my guess is that should work, though I work more on the CSS side and am not as familiar with how a react app would import the CSS. @nicolethoen or @tlabaj can you provide some insight? They are trying to ensure some custom CSS is loaded after the default component CSS from PF.

**Comment by mcoker** [comment]
@mchenier just wanted to check in and see if this was still an issue?

**Comment by mchenier** [comment]
Yes we didn't find a workaround yet. I was hoping @nicolethoen or @tlabaj would respond. But we have move on for now since it's not a huge problem. I understand that this problem will be fix on the cssnano dependency will be update. Is that right?

**Comment by mcoker** [comment]
@mchenier one of our developers attempted to fix this in the core repo with this PR - https://github.com/patternfly/patternfly/pull/4442/files

That change was included in `@patternfly/patternfly": "4.145.0"`, although it looks like you're on `"@patternfly/patternfly": "^4.151.4"` and still experiencing the issue. Can you confirm you're on `4.145.0` or greater?

As for the CSS override, if you're still having issues with that, let me know and I'll try and get another react developer to help out and make sure the override CSS is being included and in the right spot so it can override the default patternfly CSS.

**Comment by mchenier** [comment]
@mcoker 
Our package-lock.json now shows this.
"@patternfly/patternfly": "^4.159.1",
"@patternfly/react-charts": "^6.28.4",
"@patternfly/react-core": "^4.175.4",
"@patternfly/react-icons": "^4.26.4",
"@patternfly/react-styles": "^4.25.4",
"@patternfly/react-table": "^4.44.4",

So we did update but still have the problem. I tried a vanilla patternfly-react-seed and the problem was not present.  Maybe there is a conflict with my current project. I tried to strip it down of all CSS customization or anything I could think would interfere but still had the problem.

Yes if someone can confirm I was using the workaround the right way it will probably help.

If you need more information about my project let me know thanks for your help.

**Comment by mcoker** [comment]
Are you able to replicate the issue in an environment I can access? Or could we hop on a video call? Feel free to contact me on google chat or the patternfly slack at patternfly.slack.com

**Comment by mchenier** [comment]
I have created https://github.com/mchenier/patternfly-select-problem
I removed all unnecessary files. I recommend using the internal devcontainer with vscode remote container.
After that "npm start" to see the working Select and npm run build to get the static build with the broken Select.

Let me know if you find interesting.

**Comment by mcoker** [comment]
@mchenier thanks for that! I ran the static build and started a server from that dir and I got a mostly unstyled select, but looks like it's because the base PatternFly CSS isn't included. I added this tag to `index.html` (just to test) - `<link href="https://unpkg.com/@patternfly/patternfly@4.159.1/patternfly-base.css" rel="stylesheet">` and everything is looking great. The order of the `2.[...].css` and `main.[...].css` files are correct with the former being the select component CSS and the latter being the local CSS overrides.

Maybe we could do a screen share and try to troubleshoot more?

**Comment by mchenier** [comment]
Yes we could set a meeting but first do you see the same problem I have. Here is the screenshot I took today with the build. On the left is the site with "npm start" and on the right "npm run build" 
![image](https://user-images.githubusercontent.com/34419414/145578978-30ba4758-a64d-4cae-9650-99d114386a99.png)

**Comment by mcoker** [comment]
Yep, I'm seeing that initially, but it's because this build doesn't include the patternfly base CSS that contains global variables that the components use to implement styles for colors, shadows, etc. 

In that `index.html` you've loaded, you can add `<link href="https://unpkg.com/@patternfly/patternfly@4.159.1/patternfly-base.css" rel="stylesheet">` to the `<head>` of the document, or visit the URL in the `href` attr of that `<link>` and copy all of the CSS it loads, then paste that between `<style>[paste it here]</style>` tags in that page (you can do it in dev tools) and you should see that the borders look OK.

**Comment by mchenier** [comment]
Ok my bad I didn't understand that fully in the first place. That means my test project was not correct to test the bug I will try to reproduce our problem in that environnement and get back to you.

**Comment by mchenier** [comment]
I can confirm that the workaround of including the Test.css works in that case. If you comment the "import './Test.css';" line in Test.tsx you will get that select with no border. I will dig a little more to why that workaround doesn't work in the production code.

**Comment by mchenier** [comment]
I was able to correct the problem in the code in production using the patch css. I don't know what happen before when it didn't work but the conclusion to this issue is to use the "patch" css (see Test.css in that issue). Let me know what is the ETA for the real fix on this.

Thanks for all your time.
