### ISSUE TITLE
address alignment issue with input group text

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#453]
There is a slight height issue with text with the input group. `pf-c-input-group__text` is off by 1px. I'm not sure if this is caused by the padding calc on the input or the font itself.

When referencing Bootstrap's input group I've noticed they have the same issue. 

This is related to this #444

**Comment by rachael-phillips** [comment]
@matthewcarleton are we ready to close this one out based on #455?

**Comment by mcoker** [comment]
bump
