### ISSUE TITLE
Login dialog footer doesn't stay at the bottom when the right hand side is bigger

### ISSUE THREAD

**Issue by ctron** [patternfly/patternfly#4540]
Having more text on the right hand side of a login dialog, doesn't keep the "footer" in inside the login dialog at the bottom of the component:

![image](https://user-images.githubusercontent.com/202474/143558606-75273fcc-3027-43ea-8a0e-66c463afa018.png)

I would expect that the "main" section expands in this case, and the footer (and band) is still aligned with the bottom.

**Comment by mcoker** [comment]
@mceledonia @mcarrano wdyt?

Here are a couple of approaches.
Footer/band stuck to the bottom as @ctron mentioned
<img width="1276" alt="Screen Shot 2021-11-29 at 5 29 32 PM" src="https://user-images.githubusercontent.com/35148959/143959036-69cc4e42-4299-4444-9e65-a0c7020e4303.png">

The login box doesn't expand to match the height of the stuff on the right
<img width="1316" alt="Screen Shot 2021-11-29 at 5 30 01 PM" src="https://user-images.githubusercontent.com/35148959/143959032-07211be7-dc11-4c6d-803e-e53e6e5fee35.png">

Same ^ but centered vertically
<img width="1354" alt="Screen Shot 2021-11-29 at 5 35 27 PM" src="https://user-images.githubusercontent.com/35148959/143959484-770ee120-1d78-4329-a88d-efcca64fc259.png">

**Comment by evwilkin** [comment]
@mceledonia @mcarrano did we identify a preference from these options, & if so can we add it to the issue here?

**Comment by mcoker** [comment]
IIRC, we chose the 2nd one - continue to have the login box on the left and the content on the right to be top-aligned with one another, but don't stretch the login box on the left's height beyond what it is naturally based on its content
