### ISSUE TITLE
table: Action layout is broken in both the compact variant and mobile breakpoint sizes

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#4547]
Two related issues with the tables, regarding actions and layout:

1. When `isCompact` / `pf-m-compact` is added to the table, the padding is incorrect, especially on desktop.
2. When actions are more than just the ⋮ (kebab menu) is used in the actions area, the layout is broken in mobile. (It's arguably still problematic with just the kebab menu.)

### Normal, desktop (for reference; the bugs are not visible here)

![normal table](https://user-images.githubusercontent.com/10246/144247282-094a1775-623e-4654-955b-48313b5d4a81.png)

### When compact is applied

There's not enough space above and below the buttons.

![Screenshot 2021-12-01 at 14-35-19 PatternFly 4 • Table](https://user-images.githubusercontent.com/10246/144247170-ac3a1c02-30bf-47cc-b45a-03f35c443453.png)

### Mobile mode

![Screenshot from 2021-12-01 14-35-47](https://user-images.githubusercontent.com/10246/144247111-bee272b1-4c99-4945-940b-bf762d343358.png)

### Mobile size with grid view on, to see the layout

![Screenshot from 2021-12-01 14-36-51](https://user-images.githubusercontent.com/10246/144247387-a786a43a-3dd9-4b2d-be75-af7b45e93302.png)

### Mobile mode with other text and grid view

Sometimes actions need to be a bit longer. Even still, imagine longer text, like if you changed the language to German.

![Screenshot from 2021-12-01 14-47-55](https://user-images.githubusercontent.com/10246/144247532-3bf3589d-ebc6-4ae1-aa6b-d790680f5299.png)

I did not show compact applied in mobile mode; the same issues show up regardless.

---

This affects us in Cockpit quite a bit, as we're using this pattern (table with action button + action menu) in several places. 

Our current workaround is to not set the last class for actions (that is: treat it as a normal row) and then add a `data-label=""`. This makes the actions show up as its own row on the bottom instead of being on the top and stealing horizontal space from all the content. It also makes compact mode work with proper spacing around the actions.

---

Suggested actions (somewhere between some to all):

- Re-evaluate if the mobile layout is what we want
- Adjust the PF CSS to better handle compact mode
- Perhaps adjust the layout for mobile mode (or handle it differently)
- Fix the demo to not have these issues (as a developer could copy it as-is and inherit these two bugs)

**Comment by mvollmer** [comment]
I like this approach best right now: https://github.com/cockpit-project/cockpit/pull/16681

Buttons are shown when the table is in "row mode", but they move into the menu in "card mode".

**Comment by mattnolting** [comment]
Issue moved to [patternfly/patternfly-react #6799](https://github.com/patternfly/patternfly-react/issues/6799) via [**ZenHub**](https://www.zenhub.com/)
