### ISSUE TITLE
Better align card actions with title

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4553]
re: https://github.com/patternfly/patternfly-react/pull/6639#pullrequestreview-819106228

See if we can better align actions in cards with different title font sizes

**Comment by mcoker** [comment]
@mcarrano @mmenestr @mceledonia can I get your opinion on our ideal card title and action alignment from the conversation in https://github.com/patternfly/patternfly-react/pull/6639#pullrequestreview-819106228? 

By default, actions are top-aligned with the card title. Since we expect most actions to be "plain", we move (offset) the action position up by 6px (the amount of the action's top padding), so that the top of the title text aligns with the top of the button text/icon. This is what's seen in the demos currently. It works better with the default card title size, but looks odd with large text.

<img width="554" alt="Screen Shot 2022-01-17 at 5 35 53 PM" src="https://user-images.githubusercontent.com/35148959/149847780-86611a09-412d-46a7-8b34-02266f335df3.png">

In cases where the user isn't using a plain action, we have a variation for the action that removes the offset, so that the top of the action itself (ie, a primary button) aligns with the top of the title text.

<img width="441" alt="Screen Shot 2022-01-17 at 5 34 37 PM" src="https://user-images.githubusercontent.com/35148959/149847716-b8fa7871-9383-41b0-9f3d-156b83da0185.png">

Based off of knowing the default behavior, what do you think is the ideal alignment here? And is that alignment an option/default we want to make in the PF card component, or just something to demonstrate here in the demos?

**Comment by mmenestr** [comment]
@mcoker I think what you have in those examples makes sense. I wonder if we could just say "horizontally center align" header and button every time, which would basically go along with what you have there.

So if the header text height is smaller than the button height, you'll have parts of the button "stick out" equally above and below. And if the header text height is the same as the entire button height, then there's perfect alignment. Hopefully that makes sense?

I also think it would make sense to make it some sort of default in the card component + something to show in the demo. Though we'd also want to keep in mind which buttons we'd want to encourage people to use in cards vs. not, and decide which buttons we'd want to show in a demo based on that.

**Comment by mcarrano** [comment]
@mcoker @mceledonia and I had a long discussion about this in Slack. We concluded that these dashboard card demos should use a custom layout using Flex. We will not change the default layout for card headers as we are concerned with unwanted side effects if we apply this to all cards. Developers building custom dashboard cards could be advised and replicate the demo to achieve the desired result. This approach will require minor updates to the React demo to pick up this change. I have opened https://github.com/patternfly/patternfly-react/issues/6823 to track that work.

@mcoker let me know if I missed anything. I've assigned the React issue to you, also, as discussed.

@mmenestr While your suggestion to horizontally center the text makes sense in theory, it does not seem like we have what's needed to get there. Do you think we need to talk about the expected alignment in the design documentation at all?

**Comment by mmenestr** [comment]
@mcarrano I personally don't think it's necessary no, especially if the demos will reflect the correct alignment which is what developers will use, in theory.
