### ISSUE TITLE
Notification Badge: add open state, dark background

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#4563]
Work needed for https://github.com/patternfly/patternfly-react/issues/6142
For consistency, put Notification Badge examples on a black background.
Add open state to match design guidelines.

**Comment by srambach** [comment]
To clarify details:
The "open" state (aka selected state) should be used whenever the badge has been clicked and the notification drawer is open. Currently, the notification badge is using the selected state styling of a header tools item from within the page component. So, for this issue we will leave that as is and document it.
