### ISSUE TITLE
Expandable section - provide an option to indent contents

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#4566]
With some layouts, having the contents of an expandable section left-aligned with the arrow and not the text makes it hard to convey visual hierarchy and grouping of elements. 

For example, we want to replace section headers with an expandable section component. But our previous layout presents these section headers with a bigger/bolder font than the expandable section. When we replace the section headers with the expandable section, we lose the visual prominence that our previous section headers had. 

If there were an option to indent contents inside an expandable section, this would help to convey the visual hierarchy of the contents on the screen. 

cc @lboehling

**Comment by lclay2** [comment]
Thanks for creating this @jgiardino
