### ISSUE TITLE
Radio 

### ISSUE THREAD

**Issue by wtrocki** [patternfly/patternfly#4572]
**Describe the issue. What is the expected and unexpected behavior?**

When radio on table is selected. View column gets 8% of the entire screen from CSS that makes it extremely long.
```
 <Table
      selectVariant={RowSelectVariant.radio}   
 >
```

I have hacked it by changing style but that doesn't render properly for firefox that doesn't like setting the width to columns:
https://github.com/openshift/console/blob/master/frontend/packages/rhoas-plugin/src/components/service-table/ServiceInstanceTable.scss#L1-L3

![image](https://user-images.githubusercontent.com/981838/119631098-7ad8a900-be07-11eb-836a-562684d6e62d.png)

**What is your product and what release version are you targeting?**
OpenShift 4.8

**Comment by mcoker** [comment]
@wtrocki I took a stab at trying to reproduce this in a codesandbox here, testing in Firefox - https://codesandbox.io/s/gallant-smoke-bwtyi?file=/index.js

The only custom CSS I can find in the console repo that would appear on this table (from the `className` in the component file you linked) is in https://github.com/openshift/console/blob/master/frontend/packages/rhoas-plugin/src/components/service-table/ServiceInstanceTable.scss, and I added that to the codesandbox.

Just wanted to confirm if this is still an issue, and if so, can you work with that codesanbox and tell me if you're able to reproduce the issue?

**Comment by wtrocki** [comment]
@mcoker Thank you so much for going extra mile to reproduce it. I can confirm that problem is resolved.
I originally missed previous commit. We are good to close that issue
