### ISSUE TITLE
Review invalid SCSS @import position in stylesheets

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4573]
re: https://github.com/patternfly/patternfly/pull/4567

Look for any instance of the `no-invalid-position-at-import-rule` stylelint rule in our stylesheets and see if we can fix the `@import` location and remove the `// stylelint-disable` line without introducing a breaking change.

**Comment by nicolethoen** [comment]
@mcoker should this issue have closed when that PR was merged?

**Comment by mcoker** [comment]
@nicolethoen nope, that PR required us disable some linter rules we have in place - this issue is to review the code where the linter was disabled so we can re-enable the linter rules. I've added the breaking change label as it doesn't need to be addressed now and is probably best addressed in a breaking change if we do update the code.

**Comment by mcoker** [comment]
This should be resolved via https://github.com/patternfly/patternfly/issues/4519, and if it isn't, I think it's fine to leave as sass will import it the way it needs to, and sometimes it's good to have the import in a logical order in the code depending on what it does.
