### ISSUE TITLE
Text Input Group: Placeholder text 

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly#4577]
Cannot add place holder text.

@dlabrecq opened react issue[#6697]( https://github.com/patternfly/patternfly-react/issues/6697).  Part of it has to do with placeholder text.  Somme core work will most likely need to be done to support this.

**Comment by mcoker** [comment]
Looks like we just need to add some styles for the text color when there is placeholder text. That can mimic the text input (form control component in core) and share a var @evwilkin recently created for the autocomplete/hint text https://github.com/patternfly/patternfly/blob/main/src/patternfly/components/TextInputGroup/text-input-group.scss#L26

Probably makes sense to have a base placeholder text color, and use that as the value for both the placeholder color and the hint text color.
