### ISSUE TITLE
Broken GitHub link on Modifiers page 

### ISSUE THREAD

**Issue by jeffpuzzo** [patternfly/patternfly#4581]
Navigating here:
https://pf4.patternfly.org/modifiers

at the bottom of the page there is a link `View source on GitHub` which navigates to a 404 page in GitHub.

**Other considerations:** Is this page outdated? Do we want to add more modifiers here? Maybe it should be removed altogether since it seems modifiers are outlined for individual components now.

**Comment by mcoker** [comment]
@jeffpuzzo nice find! This file hasn't had a meaningful update in a very long time. Do you want to remove it? 

This is the source for that page: https://github.com/patternfly/patternfly/blob/main/src/site/pages/modifiers.md

And we have a script that generates modifiers on that page that can be removed: https://github.com/patternfly/patternfly/blob/main/scripts/extractModifiers.sh

Then you might grep/poke around on the [core workspace](https://pf4.patternfly.org/), [react workspace](https://patternfly-react.surge.sh/), and [org site](https://www.patternfly.org/v4/) for a link to that page.

cc @srambach @mattnolting any objections to removing this from the docs?

**Comment by jeffpuzzo** [comment]
@mcoker Yeah, I'll remove it. Thanks for the extra info. If I don't hear back about objections, I'll proceed with a PR, thank you!

**Comment by srambach** [comment]
The purpose of that page was to help us keep modifier names consistent - so we didn't end up with pf-m-fill and pf-m-filled for example.  I'll admit I haven't used it for a long time.
