### ISSUE TITLE
PatternFly table's default baseline vertical alignment causes awkward alignment for a tables that contain an images.

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly#4606]
**Describe the issue. What is the unexpected and expected behavior?**
The PatternFly table's default vertical alignment is set via `.pf-c-table tbody > tr > * {vertical-align: baseline;}` which causes awkward alignment for table's that contain an image.

The OpenShift console displays a table of installed Operators and associated logo within each row. So by default the row content is aligned to the baseline of the logo image. Note `<img` are set at 40 x 40 px. So we have to override the PatternFly rule and set it to `vertical-align: top` so the content aligns. Ideally their would be an additional `pf-c-table` class that would allow for custom alignment (top, middle, baseline).

**Demo**
https://codesandbox.io/s/hungry-http-gstml?file=/index.tsx

**Baseline aligned**
<img width="1089" alt="Screen Shot 2022-01-12 at 5 25 41 PM" src="https://user-images.githubusercontent.com/1874151/149232745-de313d7c-1e0a-4f69-9e8b-11f2d860cc3b.png">

---
**Top aligned**
<img width="1078" alt="Screen Shot 2022-01-12 at 4 46 57 PM" src="https://user-images.githubusercontent.com/1874151/149232628-1bd9747a-5f58-4620-951d-c10af0c9a6c2.png">

**Comment by mcarrano** [comment]
@mattnolting I agree, it would be good to have a demo of this for future reference.

**Comment by mcoker** [comment]
@mattnolting yep, great idea to call this out in a demo.
