### ISSUE TITLE
Dropdown - primary button toggle issues

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4631]
The split button toggle is getting the normal toggle's bottom border treatment. That shouldn't happen, the toggle should behave like a primary button - only the background changes on hover/focus/active/expanded. A good example is the [primary menu toggle component variation](https://www.patternfly.org/v4/components/menu-toggle#primary).

<img width="254" alt="Screen Shot 2022-01-20 at 10 08 48 AM" src="https://user-images.githubusercontent.com/35148959/150376796-883c7621-5abd-40c8-93fb-5d43dd57f4d8.png">

Also I noticed the main primary dropdown toggle hover/focus/active/expanded states aren't working - https://www.patternfly.org/v4/components/dropdown/html/#primary-toggle. Those should also mimic the primary menu toggle link referenced above.

cc @mcarrano @mmenestr LMK if you see any issues with this.

**Comment by nicolethoen** [comment]
Sounds like this is related to: https://github.com/patternfly/patternfly/issues/4612

**Comment by mmenestr** [comment]
I agree that the whole background should change on hover/click - there shouldn't be that "lighter blue underline" on the button.

**Comment by mcarrano** [comment]
Should we pull this into the upcoming milestone?

**Comment by mcoker** [comment]
@mcarrano sounds great!
