### ISSUE TITLE
Select toggle focus/expanded state issue

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4632]
The select toggle has a 1px bottom border on hover/focus/active/expanded, while the rest of our menu toggles have 1px hover, 2px focus/active/expanded. The select toggle should be updated to match the other toggles.

Select:
<img width="837" alt="Screen Shot 2022-01-20 at 10 47 14 AM" src="https://user-images.githubusercontent.com/35148959/150383954-baa84939-ca90-4b7b-99fa-d9b8d116a936.png">

Options menu (for comparison):

<img width="400" alt="Screen Shot 2022-01-20 at 10 49 30 AM" src="https://user-images.githubusercontent.com/35148959/150384147-3d7426e9-e2e3-442a-9309-51c80db5f5de.png">

cc @mcarrano @mmenestr seems like this might be a regression. Can you confirm the toggle treatment should match?

**Comment by mcarrano** [comment]
Yes, I agree. @mceledonia can you also confirm?
