### ISSUE TITLE
compact labels have wrong height inside a label group

### ISSUE THREAD

**Issue by eliranmal** [patternfly/patternfly#4638]
### description

when putting `Label` components inside a `LabelGroup`, and marking only some of them - **but not all** - with the compact modifier, their layout is not affected by the compact state, and the label's box remains at full height.

this issue is opened to handle a higher-level issue ([patternfly/react #6815][1]), which originates in the underlying CSS rules.

### steps to reproduce

1. create a label group, and put some labels inside
1. assign the `pf-m-compact` modifier to one of the labels

### expected result

the modified label should have a compact layout, with lower height.

### actual result

the label remains at its full height (but its text does get smaller).

[1]: https://github.com/patternfly/patternfly-react/issues/6815

**Comment by eliranmal** [comment]
@nicolethoen / @evwilkin - can you please assign me to this issue?

i opened it following another issue on the react repo, thinking it should be handled here.
i already have a working fix, just want to tie it to this issue and open a PR.

**Comment by eliranmal** [comment]
thanx!

**Comment by eliranmal** [comment]
#### discovery

- any label group item is a flexbox, and has default alignment for its items.
- as result, nested labels are aligned with the initial rule: `align-items: normal`, which [behaves like `stretch` for flex items][1].

#### suggested solution

apply `align-items: center` to label group items as a sensible default, and declare it as a new component-level property, to allow overrides (e.g. `--pf-c-label-group__list-item--AlignItems`).


[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/align-items

**Comment by mcarrano** [comment]
@eliranmal see my comment on https://github.com/patternfly/patternfly-react/issues/6815. I think this was based on a misunderstanding of how the label group was intended to work and should be closed, I think. Do you agree>

**Comment by eliranmal** [comment]
@mcarrano, yes, indeed the original issue was based on a misunderstanding (or misuse).  
i think it may still be a good idea to fix this (for fool-proofing?), but i understand that i can't anticipate many of the breaking changes this change may introduce, and there are other concerns that are not met by it.

i can simply omit the CSS changes, and the mixed-labels example from the docs, and leave in just the new compact label examples.

**Comment by eliranmal** [comment]
*note:* this issue was not actually fixed (but resolved by updating the docs), so maybe it should be labeled with a `wontfix` (?)
