### ISSUE TITLE
investigate options for adjusting target size and layout of interactive elements

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#464]
The minimum size for target area defined by PF visual design is 32x32px. The AAA recommendation from [WCAG](https://www.w3.org/WAI/WCAG21/quickref/#target-size) is 44px.

Some concerns that were expressed related to the 32 size minimum:

- Users using a touch device may have trouble targeting specific interactive elements, especially when interactive elements are immediately adjacent.
- Users with any motor control impairments using a mouse could have difficulty targeting interactive elements, especially when adjacent.

As part of this issue:
- Investigate what methods might be available for detecting whether the user is using touch or a mobile device. 
- For each method, identify what our options are for adjusting the css to accommodate the users mentioned above.
- Provide recommendations for button layout - what's the minimum space that should display between buttons (whether in a toolbar layout that's fullscreen, a toolbar layout that's wrapping, or stacked like in a list view)

**Comment by jgiardino** [comment]
Notes about this issue with links to additional resources on this topic are included in the [a11y review agenda document](https://docs.google.com/document/d/1tyfNd32YIG5JIkqh4d9vT0_qPmBzyBCa9PY3V1SkapE/edit?usp=sharing)

**Comment by mcoker** [comment]
cc @jessiehuff do you want to leave this one open?
