### ISSUE TITLE
The jump links don't appear in mobile on 2 HTML demo examples

### ISSUE THREAD

**Issue by wesleymiles** [patternfly/patternfly#4645]
The jump link HTML demos “[Vertical jump links toggle text on mobile](https://www.patternfly.org/v4/components/jump-links/html-demos#vertical-jump-links-toggle-text-on-mobile)” and “[Vertical jump links collapsed on mobile](https://www.patternfly.org/v4/components/jump-links/html-demos#vertical-jump-links-collapsed-on-mobile)” don’t show any jumplinks on mobile. 
![image](https://user-images.githubusercontent.com/613815/151567004-f71df581-e5b6-411a-bc7b-e35815480620.png)

**Comment by mcoker** [comment]
Thanks @wesleymiles! https://github.com/patternfly/patternfly/pull/4703
