### ISSUE TITLE
Add layout style for functional button in the CodeEditor header

### ISSUE THREAD

**Issue by DaoDaoNoCode** [patternfly/patternfly#4658]
Based on the design here https://marvelapp.com/prototype/15bb10j4/screen/81521392, we are going to add a demo to support the 'View shortcuts' feature, and it would be nice if the layout style of the button could be supported here.

**Comment by mcoker** [comment]
cc @mmenestr @mcarrano

**Comment by mcarrano** [comment]
@DaoDaoNoCode We currently have an open React issue for this that's been in our backlog for a while: https://github.com/patternfly/patternfly-react/issues/6663 If you wanted to pick that up, it would be great! But I'm not sure what you need from core. What do you mean by "layout style of the button?" I was hoping we could just place a link button in the code editor toolbar. Do you need something from core to make that work?

**Comment by mcoker** [comment]
@mcarrano yeah the code editor toolbar is only setup for the actions on the left and the tab on the right. We'll need to add some kind of element to support that new action, or other actions you think may go there.

**Comment by DaoDaoNoCode** [comment]
@mcarrano Hi! Yes I am currently looking into this issue, and I noticed that there are only 2 classnames in the header: `pf-c-code-editor__controls` on the left for the controls and `pf-c-code-editor__tab` on the right for the code type. And it's currently unable to add another button that aligns right without the support of the core side because we don't have classname for that component.

**Comment by mcarrano** [comment]
OK. In that case I will pull this issue into a core milestone. @mcoker do you think this is something easily addressed in the current milestone or should I just queue it up for milestone 03?

**Comment by mcoker** [comment]
@mattnolting would you have time to work on this in this milestone?

**Comment by mattnolting** [comment]
@mcoker On it
