### ISSUE TITLE
Dashboard demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4659]
Create a dashboard demo page that shows how to use cards to create responsive dashboard layouts. Should include layouts for a full page dashboard and for a dashbar as defined in the design mocks here: https://marvelapp.com/prototype/d642i6g/screen/84550919  Can use placeholder images for charts where applicable as we do for card demos. These should be replaced with actual charts as we move to React.

**Comment by jgiardino** [comment]
For the dashbar examples shown in the design, is it possible to use similar semantics as the DescriptionList component, or even implement this as a new variant of the DescriptionList component? The semantics are identical, but the presentation is different. 

I posted a similar question here: https://github.com/patternfly/patternfly/issues/4699
