### ISSUE TITLE
Spinner - enhancement to support icon replacement

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4665]
Replacing an icon with a spinner can cause layout shifts since icons are often different sizes.

Let's create a way to support showing an icon and replacing it with a spinner as part of the spinner component. Ideally you could display multiple icons before/after showing the spinner. Like for some sort of progress thing - `default/start icon -> some other icon -> spinner -> some other icon -> finish icon`.

We can look at the plain progress button for an example on how that might be done.

**Comment by srambach** [comment]
I think that a good approach for this would be something similar to what bulma does - a container that holds any icon (or the spinner) and maintains consistent sizing and alignment. https://bulma.io/documentation/elements/icon/
@mcarrano @mmenestr @mceledonia @mcoker WDYT? And does calling the component "icon" seem ok?

**Comment by mmenestr** [comment]
Agree @srambach thats the first thing that came to mind when I read the description

**Comment by mcoker** [comment]
+1 - seems like this would be really useful in general.

**Comment by mcarrano** [comment]
Yes, I agree, also.
