### ISSUE TITLE
`Spinner` - Inconsistent spinning direction between normal and `isSVG`

### ISSUE THREAD

**Issue by gbraad** [patternfly/patternfly#4679]
![image](https://user-images.githubusercontent.com/1894/153164010-3770df11-ca36-4b1b-82d2-7a6c43a2bd0b.png)

The left `Spinner` spins anti-clockwise, while the right one using the `isSVG` property spins clockwise.

```javascript
import React from "react";
import ReactDOM from "react-dom";
import "@patternfly/react-core/dist/styles/base.css";
import { Button, Spinner } from "@patternfly/react-core";

class SpinnerDemo extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return (
      <div style={{ margin: "20px" }}>
        <Button variant="secondary">
          <Spinner size="md" /> Running
        </Button>{" "}
        <Button variant="secondary">
          <Spinner size="md" isSVG /> Running
        </Button>
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<SpinnerDemo />, rootElement);

```

Ref: https://codesandbox.io/s/goofy-banach-lnouw?file=/index.js

**Comment by mcoker** [comment]
cc @mceledonia @mmenestr @mcarrano

**Comment by gbraad** [comment]
I wouldn't mind if the spinning direction can be set by a property, but clockwise spinning seems to receive less 'negative' reactions.

**Comment by mmenestr** [comment]
I would agree that clockwise would make the most sense to me!

**Comment by mcoker** [comment]
@mcarrano technically we still support the old spinner so it may be good to keep to keep the example/docs around, just label them legacy like we've done with other components?
