### ISSUE TITLE
Bug - Tooltip - bottom-end and other diagonal positions lack arrow UI

### ISSUE THREAD

**Issue by starpit** [patternfly/patternfly#4682]
**Describe the problem**
When using any of the "diagonal" positions (bottom-end, for example), the Tooltip UI lacks the arrow UI element.

**How do you reproduce the problem?**
https://codesandbox.io/s/heuristic-wescoff-x04u2

**Expected behavior**
Tooltips should always have an arrow UI element.

**Is this issue blocking you?**
No workarounds known.

**Screenshots**
<img width="393" alt="Screen Shot 2022-02-09 at 7 39 11 PM" src="https://user-images.githubusercontent.com/4741620/153314782-dc91e7e0-c4ed-4af9-b861-91838171e317.png">

**What is your environment?**
 - OS: any
 - Browser: any
 - Version: latest, including 4.192.15

**What is your product and what release date are you targeting?**

[Kui](https://github.com/kubernetes-sigs/kui)

**Any other information?**

It is there in the DOM, so this is probably a CSS bug. I thought this used to work correctly?

**Comment by mcarrano** [comment]
@starpit we are about to release full React implementation of this feature in the 2022.02 release. Can you retest this with that release (should be available by tomorrow) and let us know if you still see this?

**Comment by starpit** [comment]
Sure thing.

**Comment by starpit** [comment]
4.198.5 seems to have resolved this. thanks!
