### ISSUE TITLE
Update masthead help icon used in all full page demos

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4686]
For consistency with design guidance and current product usage, our full page demos should be using the filled question-circle `fas fa-question-circle` in the masthead.

Result should look like this:
![masthead](https://user-images.githubusercontent.com/6619860/153488358-66845dc4-cfdd-49ca-bd39-0c2d8f890a94.png)

**Comment by mcoker** [comment]
cc @mattnolting can this go in the template you created?

**Comment by mcarrano** [comment]
@mcoker This definitely partially addresses the problem-at least in the two sets of demos it applies to. What about other full page demos like Navigation? Any way to update them all globally or does each one need to be updated individually?

**Comment by mcoker** [comment]
They need to be updated individually. It's probably not a big deal to update them all, a find/replace should take care of it. wdyt @mattnolting?

**Comment by mcoker** [comment]
@mcarrano updated - you should see it reflected in https://patternfly-pr-4683.surge.sh/ once the build finishes on https://github.com/patternfly/patternfly/pull/4683
