### ISSUE TITLE
DescriptionList - alternate font styles

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#4699]
**Is this a new component or an extension of an existing one?**
Description list

**Describe the feature**
We'd like to use the semantics provided by the description list component to surface the contents shown in the following example, but using a font treatment similar to the styles shown below. The request is to provide modifier of the description list that provides styles similar to what's shown below. 

![image](https://user-images.githubusercontent.com/21063328/155367769-f67e6b55-ecea-4f30-ac2f-55a285c201fb.png)

cc'ing @lboehling

**Comment by jgiardino** [comment]
Chatting with @lboehling offlist, she shared [this example of a recent PF design](https://marvelapp.com/prototype/d642i6g/screen/84549152). This visual presentation would also work for our use case, but would it make sense to implement this design as a variant of the description list component? Semantically these seem the same, it's just a different visual treatment.

**Comment by mcarrano** [comment]
@jgiardino sorry that it's taken so long to follow up on this. Yes, the dashbar could be thought of as a variant of a description list. However it's a more general construct as I can see wanting to use those cards to contain more dynamic content like charts and/or actions. But it does beg the question of whether we should have a more card-like presentation of a description list as you are suggesting. @mcoker @mattnolting can you weigh in on this? Do you agree that this presentation belongs as a variant of the description list component?

**Comment by mcoker** [comment]
@jgiardino for the screenshot in the description, is there a reason you wouldn't just match whatever the element/styling is for the "Chloetest" text above it and use that in the `<dd>`? https://codesandbox.io/s/festive-turing-ec400y?file=/index.js

**Comment by jgiardino** [comment]
I don't have a strong opinion regarding the visual presentation for this type of info, which I guess is the reason for opening this issue. 😄 We _could_ use custom styles as @mcoker notes, but if this is a common design pattern that we use throughout all of our products, then providing this variant in PF would result in a more consistent presentation of this pattern between apps. 

The only thing I have a strong opinion about is that we're able to use the semantics available with a description list, but with visual styling that is more prominent than the default styling. 

The issue I see with using the Title component to get this presentation is that the Title component doesn't provide a presentation-only variant (i.e. just a `<span>`) which would be preferred to avoid altering the heading outline of the page.

**Comment by mcarrano** [comment]
@jgiardino I've put this on our feature roadmap for Q3. Will that work? Sorry that's it's taken so long to work through the details.

**Comment by jgiardino** [comment]
No worries, we're not blocked by this. Q3 sounds good. Thanks!

**Comment by mcoker** [comment]
@jgiardino they will be as soon as our current release goes live. We're still testing, but I'm guessing it will be live some time tomorrow.

**Comment by jgiardino** [comment]
Ah, that makes sense. Thanks, @mcoker!
