### ISSUE TITLE
Bug - Dark Theme - themes directory isn't included in PatternFly package.

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#4700]
**Describe the problem**

Users who want to @import `.scss` encounter a compilation error, as the themes directory is missing in package.

**Comment by evwilkin** [comment]
Confirmed - [contents of @patternfly/patternfly npm package](https://unpkg.com/browse/@patternfly/patternfly@4.179.1/)

Additionally, it looks like some of the dark theme CSS files that are included are empty such as [those shipping with each component](https://unpkg.com/browse/@patternfly/patternfly@4.179.1/components/Alert/themes/dark/).

Step 1 is to update the [`sassFiles` array within the `gulpfile`](https://github.com/patternfly/patternfly/blob/main/gulpfile.js#L16) to ensure the `patternfly/src/patternfly/themes` directory is included, then additional testing & updates to ensure all correct files are included & CSS files are compiled correctly.
