### ISSUE TITLE
Search input - add dark and masthead variants

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4705]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any? Search Input

**Describe the feature**
Want to add new variants of the Search input to be used either in the masthead or above the primary nav.

The first variant is just a dark version of the existing search input that can be used above the navigation or anywhere else a search input is required on a dark background.

The second variant is intended for use in the masthead and includes both dark styling and the ability to collapse the input to an icon. This behavior can be found on the PatternFly website.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
See https://marvelapp.com/prototype/hgh0dj1/screen/85392551 for final design.

**Any other information?**

**Comment by nicolethoen** [comment]
If the search input is being refactored to use the Text input group under the hood - the styling updates may need to be made to the text input group
