### ISSUE TITLE
Bug - Table - action cells in thead and tbody should be right aligned

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#4716]
**Describe the problem**
`.pf-c-table__action` cells in thead and tbody should be right aligned. 

**How do you reproduce the problem?**
Provide steps to reproduce. A [codepen](http://codepen.io) or [codesandbox](https://codesandbox.io/) demonstrating the problem is appreciated.

**Expected behavior**
A clear and concise description of the expected behavior.

**Screenshots**

Before: 

![Screen Shot 2022-03-03 at 9 42 46 AM](https://user-images.githubusercontent.com/5385435/156587572-b70029e5-05a3-4f3f-aa0f-38c14a3b5ce1.png)

![Screen Shot 2022-03-03 at 9 42 57 AM](https://user-images.githubusercontent.com/5385435/156587600-42096394-432a-4243-a430-48f968e9f239.png)

After: 

![Screen Shot 2022-03-03 at 9 43 14 AM](https://user-images.githubusercontent.com/5385435/156587625-cf441526-2f5c-40a4-84cb-42d5b0748908.png)

![Screen Shot 2022-03-03 at 9 43 35 AM](https://user-images.githubusercontent.com/5385435/156587643-009baa22-efe1-47f8-bd27-33a3ab4f7db1.png)

**Comment by nicolethoen** [comment]
closed by #4717
