### ISSUE TITLE
TreeView - Ability to select parent nodes without changing expand state

### ISSUE THREAD

**Issue by daggmano** [patternfly/patternfly#4724]
For our use case, we need to be able to trigger onSelect for any node (leaf or parent) without changing the expand state. A parent node can then be expanded using the caret to the left of the item. Is this possible, or can this be requested as an improvement?

**Comment by mcarrano** [comment]
@daggmano Thanks for raising this issue. This has been raised before and we are planning to address. It's on our roadmap for Q2. Let us know if you have any specific dates when this is needed.

**Comment by daggmano** [comment]
@mcarrano As with most things, we needed it yesterday ;) For now I've managed to get around it using jQuery and a custom `onSelect` method, and also added the option to have 'disabled' items (specific format of the `id` field and CSS matching to attribute substrings), but it's a hack. Would be great to have this baked in, so very glad it's on the roadmap.
