### ISSUE TITLE
[Label Group] - editable label group

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4756]
Want to introduce the ability for users to add new labels to a label group component.

Design issue: https://github.com/patternfly/patternfly-design/issues/1108
Final designs: [Marvel ](https://marvelapp.com/prototype/2d90c04g/screen/85343000)and [Design doc](https://docs.google.com/document/d/1XfP0mgrIrTSUTTClCMl3hvU_CVE14jJmVv-LEOXdfuY/edit#)

**Comment by pankajshivpuje** [comment]
Link to the marvel: [https://marvelapp.com/prototype/2d90c04g/screen/85343000](url)
Document:[https://docs.google.com/document/d/1XfP0mgrIrTSUTTClCMl3hvU_CVE14jJmVv-LEOXdfuY/edit#](url)
