### ISSUE TITLE
Add support Tab close and new Tab buttons

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly#4757]
**Describe the issue. What is the expected and unexpected behavior?**
OpenShift Console is creating a terminal view with the ability to add and remove tabs. It uses the `Tab` component along with `TabTitleIcon` in the title.

There is no clean way to support the addition of a button in the title. We can easily add our own `Button`, minus the padding. However I feel like the addition of a close button should be part of the react component framework.

Additionally, support for a button to the right of the tabs that is always visible in order to `add new tab` should be provided. Today we can get around this by adding an additional tab and make it function as a button and not a content tab. However if many tabs are present, this tab can scroll off screen. Ideally such a button would become sticky on the right side and not get hidden.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
enhancement

**What is your product and what release version are you targeting?**
OpenShift 4.11

**Comment by mcarrano** [comment]
@christianvogt @abhinandan13jan what is your expectation for naming the new tab when it is added? Should the new tab name just be set by the consumer? I would expect so, but want to make sure there's no expectation that the user can edit the tab names.

**Comment by christianvogt** [comment]
@mcarrano The new tab action should signal the parent component to render a new tab. Therefore tab name will be controlled by the parent component.

Editing of tab names via an inline editor may be requested in future but is unnecessary atm. I believe the rendering component has control over the display of the title and can render a customized editable tab title if they choose to right now.

**Comment by mcoker** [comment]
@christianvogt I have a PR here if you'd like to leave a review - https://github.com/patternfly/patternfly/pull/4787
