### ISSUE TITLE
Tooltip - dark mode tooltip background is hard to see and on some backgrounds and invisible on others

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#4771]
**Is this a new component or an extension of an existing one?**
Tooltip

**Describe the feature**
It seems that the tooltip either needs a background color update and/or box-shadow to distinguish it from potentially matching background color.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
https://codepen.io/bobcatTaco/pen/WNdzNWm

**Comment by doruskova** [comment]
@mcarrano I remember I created this mock a while ago for a tooltip https://marvelapp.com/prototype/963bhhh/screen/75172511

Here's the example in a context https://marvelapp.com/prototype/963bhhh/screen/75172512
