### ISSUE TITLE
Make the CSS `cursor` property configurable for form labels

### ISSUE THREAD

**Issue by dgdavid** [patternfly/patternfly#4777]
Hi there!

I'd like to know if it's possible to use a CSS variable for defining the `cursor` CSS property for the forms labels. Currently, it is set to `pointer` but the idea is to _revert_ it to [default](https://browserdefaultstyles.com#label) because using `pointer` looks a bit confusing IMHO. We even got a user confused thinking they were links, see https://github.com/yast/d-installer/issues/115#issuecomment-1090205696

https://github.com/patternfly/patternfly/blob/6e04cbd09b4e9bc7f09fc9a39831ca9d64f773d7/src/patternfly/components/Form/form.scss#L262-L273

I'd like also to kindly ask you for the motivation of using a `cursor: pointer` on labels, since as far as I could check it is not so common. I saw it was introduced at https://github.com/patternfly/patternfly/pull/224, but I didn't find a reference about why.

Of course, I can overwrite it by overriding the rule as we are already doing with others rules, but

* for this particular case, [we have to use `!important`](https://github.com/yast/d-installer/commit/c3bbf801b0c4c6ccae516042afe7e1f465bd3bf0) or override it after every `import { FormGroup } from "@patternfly/react-core"`. None of them are ideal.

* today, I realize that I overlooked an interesting recommendation given at https://www.patternfly.org/v4/get-started/develop#install 
  
  > If you need to overwrite any elements, we recommend extending the variables found in the .scss files, rather than manually overwriting the CSS. 
  
  But there is neither, Sass nor CSS variable.

Thanks in advance!

**Comment by mcoker** [comment]
@dgdavid thanks for the issue! You raise an interesting point. I believe the idea is that these labels are interactive - clicking on them will do something (focus the associated form field). We do this for other elements/components, too - buttons, switch, selectable cards, etc. There is definitely an argument to be made for form labels to use a default cursor, as well as reserving the pointer cursor for links only. This would better match default user agent styling, as well as match the CSS3 UI w3c recommendation for use of a pointer cursor - https://www.w3.org/TR/css-ui-3/#cursor

@mceledonia @mcarrano @mmenestr do you have any thoughts here?

**Comment by dgdavid** [comment]
> I believe the idea is that these labels are interactive - clicking on them will do something (focus the associated form field)

That was what I guessed, but actually giving the focus to the associated element when clicking on them has been the _default_ behavior of labels on HTML forms. Unless I'm wrong.

> There is definitely an argument to be made for form labels to use a default cursor, as well as reserving the pointer cursor for links only. This would better match default user agent styling, as well as match the CSS3 UI w3c recommendation for use of a pointer cursor - https://www.w3.org/TR/css-ui-3/#cursor

I think so, thank you.

**Comment by mmenestr** [comment]
I guess it is a little weird/misleading that hovering on the label uses a pointer cursor... even though clicking on the label does technically lead to an action (focuses on its field). All in all, I wouldn't be against switching to a default cursor for this though! 

I'm also thinking that most people aren't going to be clicking on the label to focus on a field - they'd just click into the field directly, so hopefully it won't make too much of an impact if we do switch to a default cursor.

**Comment by dgdavid** [comment]
> I'm also thinking that most people aren't going to be clicking on the label to focus on a field - they'd just click into the field directly, so hopefully it won't make too much of an impact if we do switch to a default cursor.

I agree, but if the change can help a few users and not make things worse for the rest, it is worth it :)

Anyway, the contribution for [making it configurable](https://github.com/patternfly/patternfly/pull/4779) is merged :smiley: So, now the question is whether to keep it configurable but using the _default_ values or to remove those rules. I'd choose the latter. In any case, I can take care. Or maybe you folks prefer to mark it as a [good first issue](https://github.com/patternfly/patternfly/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/4779
