### ISSUE TITLE
Consider aligning the popover close with the end of content

### ISSUE THREAD

**Issue by chloenayon** [patternfly/patternfly#4781]
We've noticed that the close button on a popover does not align with the end of the popover content.
This is consistent with the examples of popovers in the [documentation](https://www.patternfly.org/v4/components/popover/):

![Screenshot from 2022-04-04 18-06-25](https://user-images.githubusercontent.com/11710246/161585769-1553c222-e899-42b3-982c-f6e2628d84fa.png)

How about aligning the button with the end of the content?

![popover-align](https://user-images.githubusercontent.com/11710246/161585458-8b0cb30d-e8fc-444d-a806-05cf23323889.png)

**Comment by mcarrano** [comment]
We will get this onto our roadmap. Currently scheduling into Q3.
