### ISSUE TITLE
Bug - Label - Labels break out of container with long strings of text

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#4795]
**Describe the problem**
Labels exceed their container with long strings of text.

**How do you reproduce the problem?**
https://codesandbox.io/s/musing-villani-wtq9p3?file=/index.js

**Expected behavior**
Labels should truncate by default. The truncate variant should be updated to limit the default width of 100%. 

**Is this issue blocking you?**
Yes, but can work around

**Comment by mcoker** [comment]
We have a breaking change issue to truncate labels by default - https://github.com/patternfly/patternfly/issues/3409
