### ISSUE TITLE
Split Action Button - Add secondary button styling

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly#4798]
Can we add in a variation of the split action button that uses our secondary button styling?  We support primary styling for the split action, but not secondary. Support for secondary styling would be great to differentiate from other primary buttons on the page, while also differentiating/emphasizing the split action button from the basic dropdown/select styling. https://www.patternfly.org/v4/components/dropdown#split-button-primary-action

**Comment by mcarrano** [comment]
Thanks @lboehling . We will get this on our roadmap.
