### ISSUE TITLE
Timestamp component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4801]
**Is this a new component or an extension of an existing one?**
New

**Describe the feature**
Introduce a Timestamp component. The Timestamp would provide consistent formats for displaying date and time values per the designs here: https://marvelapp.com/prototype/2cf6171g

**Comment by thatblindgeye** [comment]
cc: @mcarrano 

Regarding the text wrapping on overflow, would there be a preference for the alignment when text does wrap between either left or center aligned? Here are a couple of screenshots showing the differences between them with a couple of different widths (first screenshot is center aligned, second screenshot is left aligned)

![timestamp overflow center aligned](https://user-images.githubusercontent.com/70952936/179518188-2126c5bd-d4ce-4895-8799-33613b44dcaf.png)

![timestamp overflow left aligned](https://user-images.githubusercontent.com/70952936/179518306-f8889f38-2f70-4bf5-b0ab-b612c77f0630.png)

**Comment by mmenestr** [comment]
I agree, i'd probably just left align
