### ISSUE TITLE
Label - investigate moving "add" label outside of group list structure

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4831]
follow-up re: https://github.com/patternfly/patternfly/pull/4828

The "add" label should exist outside of the label group list, though ideally the add button should flow inline with other labels. Specifically, when labels wrap to a new line, the add button should wrap inline with the rest of the labels. 

cc @thatblindgeye

**Comment by mcarrano** [comment]
This change is needed before implementing React feature.
