### ISSUE TITLE
Checkbox - Add the ability to indicate that a checkbox is required

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4845]
**Is this a new component or an extension of an existing one?**
Checkbox

**Describe the feature**
The may be cases where you want to indicate that a checkbox must be set to proceed, e.g. when the user must acknowledge terms and conditions to open an account. In this case, just as for labeled form fields, it should be possible to place a red asterisk to the right of a checkbox label.

**Comment by mcarrano** [comment]
@blfetche we did not create design mocks for this, but if you need advise on spacing or related visuals, I'd suggest checking with @mceledonia . This would mainly be for the case of a standalone checkout that must be checked to move forward with a process. Otherwise checkboxes are naturally optional by definition.

**Comment by blfetche** [comment]
> @blfetche we did not create design mocks for this, but if you need advise on spacing or related visuals, I'd suggest checking with @mceledonia . This would mainly be for the case of a standalone checkout that must be checked to move forward with a process. Otherwise checkboxes are naturally optional by definition.

Ok thank you.
