### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#4854]
when crawling through the workspace in the a11y report, the following broken links were discovered:

- [Checkout our upgrade guide for a list of breaking changes!](https://www.patternfly.org/v4/developer-resources/release-notes/#2020.07-release-notes-2020-06-05) should point to '/developer-resources/upgrade-guide'
- [This component is designed to be used within a dark component such as the masthead.](https://www.patternfly.org/v4/components/notification-badge/html#overview) should point to 'components/masthead'
- [Note: The page component currently handles the selected state styling...](https://www.patternfly.org/v4/components/notification-badge/html#overview) should point to '/components/page'

**Comment by mcoker** [comment]
cc @bfletche
