### ISSUE TITLE
Bug - Patternfly components specify Red Hat Text font-weight: 700, but that webfont is not available

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly#4859]
**Describe the problem**
https://www.patternfly.org/v4/components/form
Inspect "Full name"
To figure out what web font is loaded in chrome you can go to the "Computed Tab" under elements
Scroll all the way to the bottom, and you'll see this:
![image](https://user-images.githubusercontent.com/5607236/168379508-018dd0c5-5ddd-4c9c-bf4d-615432a5134d.png)

Medium is `font-weight: 500`, but since there isn't a font-face declaration that provides `700`, it's using what it can.

**Expected behavior**
I'd either like to get 700 on that page, or if that isn't what's expected (700 is a bit chonky for that size text) update the CSS to specify 500.

Adding variable fonts could help this, we are pushing that update to the portal on Monday, which is how we found this bug.

**Comment by mcoker** [comment]
Hey @wesruv! If I understand the issue, this was something we did intentionally when these fonts were introduced. We wanted to have normal (to support either `normal` or `400` in CSS) and bold (support `bold` or `700`) text in PF, but the bold font was way too chonky indeed, so we mapped the `RedHatText-Medium` font to `font-weight: 700` in the `@font-face` rule. 

https://github.com/patternfly/patternfly/blob/50c8990653214df3ea2edf0b343fd34d053b1b30/src/patternfly/base/_fonts.scss#L47-L55

and a newer version of the font users can opt-in to:

https://github.com/patternfly/patternfly/blob/50c8990653214df3ea2edf0b343fd34d053b1b30/src/patternfly/base/_fonts.scss#L90-L96

It is indeed confusing. To further confuse things:
* RHD light/300 is RedHatDisplay-Regular
* RHD normal/400 is RedHatDisplay-Medium
* RHD bold/700 is RedHatDisplay-Bold
* RHT normal/400 is RedHatDisplay-Regular
* RHT normal/700 is RedHatDisplay-Medium

I want to say these were the recommendations to use when the RHT/RHD fonts were created. We gave feedback about the naming inconsistencies, but just ended up using it this way. Variable fonts FTW!
