### ISSUE TITLE
Accessibility - class similar to `pf-screen-reader` 

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#4886]
Followup for https://github.com/patternfly/patternfly-react/pull/7474

https://github.com/patternfly/patternfly-react/pull/7474#pullrequestreview-992177438

![image](https://user-images.githubusercontent.com/5385435/171475336-754c50a2-de84-472a-a741-8392baed0f16.png)

We need a class to use that, instead of `position: fixed` and no width or height, is positioned `absolute` and full width and height to be used in things like a selectable `data-list` with a checkbox or radio.

**Comment by wise-king-sullyman** [comment]
I believe that this may resolve #4835 as well
