### ISSUE TITLE
Bug - Card component - Cards presented on the same background color in dark theme mode loose their edge contrast

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly#4889]
**Describe the problem**
Cards presented on the same background color, which happens within `<PageSection variant={PageSectionVariants.light}>`, have the same background `--pf-global--BackgroundColor--100`, which is fine on light theme, but in dark theme mode they loose their edge contrast because the box shadow is barely perceptible.

OpenShift console presents cards within `<PageSection variant={PageSectionVariants.light}>` in several locations.

**How do you reproduce the problem?**
https://codesandbox.io/s/whie-worker-hzvqws-hzvqws

**Expected behavior**
It would help to have increase edge contrast between the card and its page section in dark theme.

_Option 1_ 
Set card background to a slightly different color than the current `--pf-global--BackgroundColor--100`
eg. `:where(.pf-theme-dark) .pf-c-card {--pf-c-card--BackgroundColor: var(--pf-global--BackgroundColor--dark-300)`

_Option 2_
Add a 1px border to `.pf-c-card` 
eg. `:where(.pf-theme-dark) .pf-c-card {border: 1px solid var(--pf-global--palette--black-1000)}`

_Option 3_
Increase the card boxshadow size to `--pf-global--BoxShadow--md`

**Screenshots**
Provided APIs are presented using the card component
<img width="1252" alt="os-dark-card" src="https://user-images.githubusercontent.com/1874151/171700795-b57d12d4-e089-4427-a739-102b20372318.png">

<img width="1397" alt="os-dark-card2" src="https://user-images.githubusercontent.com/1874151/171700810-79cc587c-c0e9-4058-ba2d-31b13f89acba.png">

**What is your product and what release date are you targeting?**
OpenShift 4.11

**Any other information?**

**Comment by nicolethoen** [comment]
@mceledonia and @mcoker could you take a look at this?
