### ISSUE TITLE
Update @font-face

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#490]
I've been reading about webfonts and came across this:
```you’ll soon be able to start dropping support for older webfont formats. EOT is only necessary for Internet Explorer 8 and below, and raw OpenType files are only necessary for Android versions prior to 4.4.```
Most modern browsers support woff and woff2 formats. Since we are no longer supporting IE11 and below I think we can remove support for EOT.  
Currently we include the following: 
```
@font-face {
    font-family: "overpass";
    font-style: normal;
    font-weight: 200;
    src: url("#{$pf-global--font-path}/overpass-webfont/overpass-thin.eot"); /* IE9 Compat Modes */
    src: url("#{$pf-global--font-path}/overpass-webfont/overpass-thin.eot?#iefix") format("embedded-opentype"),
      url("#{$pf-global--font-path}/overpass-webfont/overpass-thin.woff2") format("woff2"),
      url("#{$pf-global--font-path}/overpass-webfont/overpass-thin.woff") format("woff"),
      url("#{$pf-global--font-path}/overpass-webfont/overpass-thin.ttf")  format("truetype"); /* Safari, Android, iOS */
  }
```

I'm not sure what our level of support is for Android so we may need to keep ```ttf```

Android has supported WOFF for four major versions now, and half of 4 (4.4.3 and on had stable WOFF support, 4.4.2 and below did not).

We should also consider adding

```font-display: fallback;```

Which will Show the webfont if it is available within 100ms. If it is not available, show the fallback font. If the webfont takes longer than three seconds to load, continue showing the fallback font.

The support for this decent and if the browser doesn't know it will just ignore it.

**Comment by mcoker** [comment]
bump
