### ISSUE TITLE
Bug - Form and Form control - Error states + colors need changing

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly#4900]
**Describe the problem**
The Form and Form control documentation have 2 issues with them:
1. The error states should not include an icon at the helper text level. 
2. The color of the exclamation circle, and success icons seems off -they should both match the color of the input underline, but they look brighter than that to me.

**How do you reproduce the problem?**
1. Icon issue: https://www.patternfly.org/v4/components/form/html#help-text

2. Color issue:
https://www.patternfly.org/v4/components/form-control#input
https://www.patternfly.org/v4/components/form-control#select
https://www.patternfly.org/v4/components/form-control#textarea

**Expected behavior**
1. A form input with an error should look like this:  
<img width="318" alt="image" src="https://user-images.githubusercontent.com/51165119/172932118-9cfc448d-f838-4cba-8dd5-55edb67e7e03.png">

2. The colors should match the ones in this example: https://www.patternfly.org/v4/components/form-control#icon-sprite

**What is your environment?**
 - Browser: Chrome
 - Version 102.0.5005.61

**Comment by mcoker** [comment]
This will be fixed via https://github.com/patternfly/patternfly/issues/5469
