### ISSUE TITLE
Bug - [ProgressStepper] - [interactive popovers should be buttons and not spans with onTriggerEnter]

### ISSUE THREAD

**Issue by andyyvo** [patternfly/patternfly#4907]
**Describe the problem**
ProgressStepper component was originally not opening popovers via the keyboard. After solving the issue in [#7532](https://github.com/patternfly/patternfly-react/pull/7532) of the react repo, it was found that a better alternative solution would be to make the `span` using the `onTriggerEnter` prop into a `button` to better simulate the native experience of opening a popover.

**How do you reproduce the problem?**
https://patternfly-react-main.surge.sh/components/progress-stepper

**Expected behavior**
For the ProgressStepper component with Popovers, the keyboard should be able to open a popover using the space/enter key. This was accomplished in [#7532](https://github.com/patternfly/patternfly-react/pull/7532) of the react repo.

**Comment by thatblindgeye** [comment]
@andyyvo Nicole has #4898 opened for this same issue, so I'm going to close this as a duplicate. Thanks for wanting to mention the issue, though! 🙂
