### ISSUE TITLE
Wizard with drawer cleanup

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4918]
Couple of follow ups to the demo

https://github.com/patternfly/patternfly/pull/4896#issuecomment-1162389578

in https://patternfly-pr-4896.surge.sh/components/wizard/html-demos/with-drawer-in-page/, the "open drawer" link should only be present when the drawer is closed.

I also noticed we limit the page width of the wizard section when it's in the page. This is what our current demos look like:

<img width="2331" alt="Screen Shot 2022-06-21 at 4 45 40 PM" src="https://user-images.githubusercontent.com/35148959/174902639-462d104f-6731-46b0-ab13-72a91573ffb9.png">

One solution could be to allow the wizard section to be full width, then limit the width of the form itself

<img width="2331" alt="Screen Shot 2022-06-21 at 4 46 30 PM" src="https://user-images.githubusercontent.com/35148959/174902729-c0d911c4-56f7-4081-a71c-72b3183918bf.png">

wdyt @mmenestr @mcarrano @mceledonia?

**Comment by mmenestr** [comment]
I think that makes sense @mcoker (to allow the wizard section to be full width, but limit the width of the form itself )! And I would imagine that if there was a drawer in the wizard, the drawer would still be aligned with the right part of the window, and the drawer itself would stay the same width no matter how the window is resized. So as you resize the window, the form would be more covered or less covered by the drawer depending on the width of the window.
