### ISSUE TITLE
Bug - FormControl - icons not passing color contrast a11y rules

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#4922]
The `pf-m-calendar`, `pf-m-clock`, and `pf-m-search` all render light grey icons are too light to pass axe color contrast checks.
![Screen Shot 2022-06-22 at 11 41 32 AM](https://user-images.githubusercontent.com/26305082/175074034-4aecc01d-ab97-45ac-9448-9259dc5b6be0.png)
![Screen Shot 2022-06-22 at 11 41 24 AM](https://user-images.githubusercontent.com/26305082/175074035-3846f900-7d87-453d-a39f-b6aaacfc2011.png)
![Screen Shot 2022-06-22 at 11 41 18 AM](https://user-images.githubusercontent.com/26305082/175074038-6960e4db-310d-48b1-877c-0c0f2b9816d9.png)

**Comment by nicolethoen** [comment]
Possibly related to https://github.com/patternfly/patternfly/issues/4900

**Comment by mcoker** [comment]
Fixed in v5, these were updated to use our secondary text color.
