### ISSUE TITLE
Bulk Selection - Enhancement for loading state

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly#4926]
**Is this a new component or an extension of an existing one?**
This is an extension of the existing Bulk Selection component

**Describe the feature**
We have found that in some cases, the back-end can be slow to respond when the user is selecting a large number of items at the same time. This leaves a delay between the user clicking the "select" action, and seeing results.
This proposes to add a loading state using the existing spinner.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
![bulk loading](https://user-images.githubusercontent.com/23172038/175625862-c84f09cd-27d4-4612-abf1-ef3b8f78446c.jpg)

This is currently being built as a reusable component by a member of the Insights Frontend team for console.redhat.com

**Comment by nicolethoen** [comment]
[I did create a codesandbox](https://codesandbox.io/s/youthful-volhard-808re3) to demonstrate that it should be feasible - but it would need some style updates to format the spinner correctly.

this should also be something enabled in the MenuToggle component.

**Comment by nicolethoen** [comment]
@mmenestr @mcarrano are there any design guidelines or recommendations related to this?
