### ISSUE TITLE
Form inputs - Provide styles for read-only inputs that are visually similar to description list

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#4935]
**Is this a new component or an extension of an existing one?**
Form and form inputs

**Describe the feature**
We'd like to have a different style for read-only inputs that are visually similar to how property values display in a [description list](https://www.patternfly.org/v4/components/description-list) instead of being similar to how disabled inputs display. 

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
For Kafka topics, we worked with @lboehling and @srambach to create [custom css](https://github.com/bf2fc6cc711aee1a0c2a/kafka-ui/blob/481894163351cddd41487ef7f0c75aa71c69e6b4/src/components/TextWithLabelPopover/TextWithLabelPopover.css) to create the UI shown in the following example. For this use case, most properties are read-only but a few are editable. We created custom css for read-only inputs for the following reasons:
- The original design used similar styles as the description list. But when the user is in the context of a form, providing the values in a read-only input is more accessible (e.g. the 3rd property is read-only, but is still focusable).
- There was concern that inputs that appeared visually disabled would imply there was some action a user could take to enable them. In this scenario, the properties are always read-only.
 
![image](https://user-images.githubusercontent.com/21063328/176474033-e206c8bc-dd48-4669-ab97-fefaa42cf3cf.png)

**Any other information?**
There are other projects that would like to reuse this variation. One of the projects would use this style in a view-mode of a page where the user can click Edit to switch to edit-mode. We still want the visual presentation that is shown above for the Kafka topic, but there are a few additional use cases for this project:
- The form is generated dynamically from a schema. Being able to apply a modifier at the Form level would be preferred. But also note for the use case described above, we need also need to be able to apply this modifier at the input level. 
- In our original implementation of these styles, we only had to deal with text inputs. But the other project that has forms generated dynamically could have other input types. These other types include the PF Select component and boolean/checkbox values.

**Comment by mmenestr** [comment]
@nicolethoen talked to other designers around this and we all agreed that the solution proposed here is better than what we have today for a read-only field. So the proposal is to **replace** the current read-only styling, in favor of the more "detail list" styling. Thinking it should still have a border and classic input styling but it not be visible if that makes sense.

I just want to bring this up at design share in 2 weeks for a sanity check before we move forward, but after that it should be good to be added to a milestone.

**Comment by nicolethoen** [comment]
@mcarrano could we add this to an upcoming milestone?

**Comment by mcarrano** [comment]
Yes, but first I also wanted to get input from @mcoker . The proposal from design is that we just strip the border and background styling from the existing read-only input so it essentially just appears as a plain text element. Will this cause any unwanted side effects? I'm aware that we use these read-only fields in other components like Clipboard copy so want to be wary of affecting things other than standard form elements.

**Comment by mcoker** [comment]
@mcarrano @mmenestr a couple of thoughts come to mind.

There is padding around the form control elements - would we keep that so that switching between readonly and non won't shift anything around? Or let the content shift?

No shift
![noshift](https://user-images.githubusercontent.com/35148959/179607702-b4b5d64a-07ee-47cc-9cc0-ea94a5f1d790.gif)

Shift
![shift](https://user-images.githubusercontent.com/35148959/179607646-27f51058-0b79-4ac1-be3c-dfb83a52f558.gif)

Also I'm not sure how likely/valid the use case is, but you can have success/warning/error statuses with readonly inputs - assuming that's a valid use case, would the icon positioning change at all?

I'm assuming this would also apply to textarea elements. By default our textareas are taller than a single line of content, and with multiple lines of content, there is a scrollbar. Removing the border and background without adjusting the height and scrollbar might make for an odd experience, so something to consider.

I've put up a PR here with this basic change - https://github.com/patternfly/patternfly/pull/4984

The top form demo has the toggle to go between readonly and non - https://patternfly-pr-4984.surge.sh/components/form/html-demos

You can also see the default text input and textareas on the form control examples page - https://patternfly-pr-4984.surge.sh/components/form-control

**Comment by mcarrano** [comment]
> There is padding around the form control elements - would we keep that so that switching between readonly and non won't shift anything around? Or let the content shift?

I don't feel like the shift is a problem.

> Also I'm not sure how likely/valid the use case is, but you can have success/warning/error statuses with readonly inputs - assuming that's a valid use case, would the icon positioning change at all?

I can't think of a use case for that. What would it mean to report status of a read-only value?

> I'm assuming this would also apply to textarea elements. By default our textareas are taller than a single line of content, and with multiple lines of content, there is a scrollbar. Removing the border and background without adjusting the height and scrollbar might make for an odd experience, so something to consider.

I agree that this change does not work well for textarea elements. I don't think we intend to apply different styling there but I see where that makes us inconsistent. @mmenestr @mceledonia what do you think? Is it possible to just localize this change to the single line text input and not the text area @mcoker ?

**Comment by mcoker** [comment]
> Is it possible to just localize this change to the single line text input and not the text area @mcoker ?

Yep. Also you mentioned the clipboard copy component - that and the file upload components currently rely on the readonly styles for their layout - background to create the box, padding for spacing.

https://patternfly-pr-4984.surge.sh/components/clipboard-copy

https://patternfly-pr-4984.surge.sh/components/file-upload

**Comment by mcoker** [comment]
IMO this new style seems more like a variation - we have a "plain" variation that we use in other components that applies this basic styling. The other variation could be to update the default to plain, but retain a "box" variation, or something like that.  We have a "box" tabs variation that behaves this way.

Just looking at our styling in other components, I think we should change the text color of a disabled text input. Disabled buttons (including a control button, which mimics form control/text[input/area] elements), tabs, toggles all have grey text. That would be one way to differentiate readonly and disabled text inputs. We could also use a different background color for readonly.

**Breaking news** - looking into it, we do have a different font color for disabled inputs, but looks like a bug that it isn't being applied. Here's what it looks like with the disabled color properly applied:

#### Text input:
<img width="1417" alt="Screen Shot 2022-07-19 at 12 23 41 PM" src="https://user-images.githubusercontent.com/35148959/179812005-809fe38b-a8b9-4066-8dbd-1d8437bbc307.png">
<img width="1417" alt="Screen Shot 2022-07-19 at 12 23 47 PM" src="https://user-images.githubusercontent.com/35148959/179812014-3ea3f652-f4ae-495e-b328-5f51ab78901d.png">

#### Text area:
<img width="1417" alt="Screen Shot 2022-07-19 at 12 24 20 PM" src="https://user-images.githubusercontent.com/35148959/179812044-fbe7b8dd-cc31-4b4b-b635-fce2072f28f0.png">
<img width="1417" alt="Screen Shot 2022-07-19 at 12 24 23 PM" src="https://user-images.githubusercontent.com/35148959/179812052-1b58974a-c75b-41ec-9742-a9c279fd3d1e.png">

#### Select (there seems to be a dark theme icon issue):
<img width="1417" alt="Screen Shot 2022-07-19 at 12 34 08 PM" src="https://user-images.githubusercontent.com/35148959/179813710-28e6cccb-9d5d-4ab1-b2c5-342637529ba7.png">
<img width="1417" alt="Screen Shot 2022-07-19 at 12 34 16 PM" src="https://user-images.githubusercontent.com/35148959/179813716-c8c65171-f345-4979-87b5-147e98984126.png">

**Comment by mcarrano** [comment]
Per discussion during today's triage meeting, we will add a new variant of the text input as a "plain" read-only input that removes border and background treatments and leave the existing read-only input untouched.  @jgiardino will this address your needs? Do you still require a modifier that can be applied at the form level? Also, let me know if you have any target dates in mind. I am currently scheduling new feature work into Q4.

As for the disabled text color, we should definitely fix that separately. @mcoker I believe you were going to open a new issue for that?

**Comment by mcoker** [comment]
@mcarrano https://github.com/patternfly/patternfly/issues/4987

**Comment by jgiardino** [comment]
Thanks for the update, @mcarrano

I chatted with the product team, and the Q4 timeframe works for us. As for the form-level modifier, the UI dev lead identified this as a nice-to-have, stating that it would make it easier to apply this style at the form level.

**Comment by thatblindgeye** [comment]
@mcarrano @jgiardino  In regards to the new plain readonly variant:

1. Wanted to confirm whether the padding should remain intact or not. Looking at the clip @mcoker posted above things look good, but if only one input has the plain readonly variant it might look a little off (though this is kind of subjective):

    ![plain readonly without padding](https://user-images.githubusercontent.com/70952936/186750426-248a729a-3889-4077-a1b6-54f16f28a218.png)

    And the focus border ends up right up against that first character:

    ![plain readonly without padding focused](https://user-images.githubusercontent.com/70952936/186755010-6f4ecf8a-1555-4b1d-b0f8-8210e7635391.png)

2. Should a plain, readonly variant have any hover styles, such as a bottom border appearing on hover? Or should it visually behave more similarly to our plain dropdown variant (hovering over that does not cause any visual styling to occur). With a hover style for context:

    https://user-images.githubusercontent.com/70952936/186757200-8cb9e9a9-3180-484a-a6ac-d42d6654d340.mov

**Comment by mcarrano** [comment]
Since the read-only field is not interactive I would not expect it to have hover styles.

**Comment by jgiardino** [comment]
Thanks for sharing that example, @thatblindgeye.

I agree with @mcarrano on not expecting hover styles.
And the spacing as shown in your example also matches what I expect to see. I think that's the best layout/spacing considering the possible mix of inputs that are or are not editable within a single form. 

I also don't see the proximity of the focus ring with the text as an issue. Maybe a tiny nudge of padding could help and still retain the overall layout/spacing that you show in your example, but maybe this tiny nudge is just noticeable enough to make the layout seem off. I don't have a strong feeling on that one, though.
