### ISSUE TITLE
Dark theme - Update visited text link color to purple-300

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly#4955]
We overlooked this one, thanks to Ethan Kim for finding it. Currently the visited link color is the same as in default theme which is too dark and has poor contrast. Updating this to the purple-300 variable is the fix. 

CC @mcoker @mcarrano @mmenestr

**Comment by mceledonia** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/30935938/178009184-8d368199-9dfa-49b6-bd1c-7a99f0d6c0c2.png">

**Comment by mcoker** [comment]
@mceledonia just to confirm, in @srambach's dark theme utility PR, this was updated to purple-200

https://github.com/patternfly/patternfly/pull/4933/

Here is current light theme:
<img width="276" alt="Screen Shot 2022-07-08 at 9 45 07 AM" src="https://user-images.githubusercontent.com/35148959/178015629-d4f21945-4456-473c-b9c7-f462144b1b5a.png">

purple-200
<img width="325" alt="Screen Shot 2022-07-08 at 9 45 36 AM" src="https://user-images.githubusercontent.com/35148959/178015662-55814731-60bf-4767-a787-f999a734802f.png">

purple-300
<img width="294" alt="Screen Shot 2022-07-08 at 9 45 59 AM" src="https://user-images.githubusercontent.com/35148959/178015702-e2973b64-70cf-4edf-9522-e39d0010f890.png">

**Comment by mcarrano** [comment]
Adding to the upcoming milestone for tracking. We should try to address in the next release.
