### ISSUE TITLE
Skip to content and button style conflict

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4972]
`.pf-c-skip-to-content` is applied directly to `.pf-c-button`, and both have `position` set to different values (absolute vs relative), so if button styles are loaded after the skip to content styles, the skip to content button is set to `position: relative`

Generally speaking we try and avoid sharing component styles on a single element. The skip to content component should probably just be a container that positions itself and can use `:focus-within` to manage the `left` position to bring it into view.

**Comment by nicolethoen** [comment]
Closed by #5153
