### ISSUE TITLE
Banner - add a new icon variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#5013]
**Is this a new component or an extension of an existing one?**
Banner

**Describe the feature**
Want to add a new variant of the banner that allows for an icon in front of the text. This is an a11y enhancement that will provide an additional affordance besides color to allow color blind users to detect status. We should support the usual standard status icons along with the ability to provide a custom icon. 

Designs: https://marvelapp.com/prototype/17i95gf4/screens

**Comment by mcoker** [comment]
@mcarrano we don't currently format the text in the banner in any way aside from adjust the text color based on the variant. We could support an icon in the layout, but then we would need to be a bit more opinionated about the layout than we are currently. This could also be a demo where we put the icon and text in a flex layout and use the flex layout to manage the spacing/alignment.
