### ISSUE TITLE
Table - add min/max height to OuterScrollContainer

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#5019]
**Is this a new component or an extension of an existing one?**
Composable table

**Describe the feature**
https://github.com/patternfly/patternfly-react/issues/7425#issuecomment-1198249738

**Comment by mcoker** [comment]
@mattnolting is this a dupe of https://github.com/patternfly/patternfly/issues/5038?

**Comment by mattnolting** [comment]
@mcoker yep, closing
