### ISSUE TITLE
Enhance utility classes documentation

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#502]
Several areas in utility classes need better documentation.

@jgiardino's comments
* I wonder if this one should be split out into separate rows: .pf-u-text-left{-on-[breakpoint]}
```
For example
.pf-u-text-left
then
.pf-u-text-left-on-[breakpoint]
```

* It would be good to reference the Flex examples from the Display > Display Flex example, so that consumers realize there are more classes related to flex.

* In the Margin and Padding examples, it's hard for me to pinpoint what's going on. I think splitting these out into more granular examples might help. Like give me the just the simplest example first, then progress into the more complex examples. I wonder if the text strings used in those examples could be updated to provide more clarity, too.

**Comment by mcoker** [comment]
@mattnolting do you want to keep this open?

**Comment by mattnolting** [comment]
@mcoker I don't think so
