### ISSUE TITLE
Progress stepper - long strings in title/description don't wrap

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5024]
These blocks should allow long strings to break, so the layout doesn't break. It would also be great if the layout didn't break this way if this does happen, too.

<img width="878" alt="Screen Shot 2022-08-05 at 4 32 53 PM" src="https://user-images.githubusercontent.com/35148959/183210420-90aa108e-ec11-445c-b19d-5ce6f64f7f98.png">

<img width="876" alt="Screen Shot 2022-08-05 at 4 36 49 PM" src="https://user-images.githubusercontent.com/35148959/183211715-ac92004f-7e56-4f3d-8a8e-d51b3ea64617.png">

----

@mmenestr @mcarrano should the steps always be the same width/distance apart in a horizontal layout? I looked through the design issue (https://github.com/patternfly/patternfly-design/issues/879) and didn't see any mention of that, and didn't see any text wrapping/long text in the mockups. 

Here's an example:

<img width="888" alt="Screen Shot 2022-08-05 at 4 49 30 PM" src="https://user-images.githubusercontent.com/35148959/183215442-6530ac0f-5b67-41ba-9ff4-745f497e2653.png">

Or would we want it to look like this:

<img width="887" alt="Screen Shot 2022-08-05 at 4 51 23 PM" src="https://user-images.githubusercontent.com/35148959/183215819-9968b604-4336-429c-aef2-598bd528deab.png">

**Comment by mmenestr** [comment]
I feel like ideally, yes, each part should be the same width/distance apart so that visually it looks better, but that's just me! So we'd want it to look like the bottom pic.
