### ISSUE TITLE
Make sure we're presenting inline vs overlay menus properly

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5027]
Looking at the react components for time picker and advanced search, they both have the ability to show their popup menu "inline," which places it in the flow of the document as a block element and pushes content below it down.

However, in these cases we shouldn't be showing the menu with a drop shadow as the menu isn't overlaying the content below it. Per @mceledonia 

> I will stick with my rule of
> Inline = border
> Overlay = shadow
> if possible

There is also a question of the default behavior for these menus. I'm not sure if there needs to be a change in core for this, but I noticed that the react time picker component is "inline" by default - should it be? The [`menuAppendTo` prop documentation](https://www.patternfly.org/v4/components/time-picker#timepicker) reads:

> The container to append the menu to. Defaults to 'inline'. If your menu is being cut off you can append it to an element higher up the DOM tree. Some examples: menuAppendTo="parent" menuAppendTo={() => document.body} menuAppendTo={document.getElementById('target')}

Just reading that, it reads like "inline" will still position it on top of other stuff, but _"If your menu is being cut off"_ (by a containing element's overflow, I'm assuming), you can change the element it's appended to.

I guess my goal here is to figure out how they should be presented by default, then create follow up react issues to match where we can.

--

## Time picker
![Aug-08-2022 09-18-38](https://user-images.githubusercontent.com/35148959/183439683-0754d578-ab5c-419f-afd5-f0db4a6436e2.gif)

## Advanced search
![Aug-08-2022 09-21-56](https://user-images.githubusercontent.com/35148959/183440687-62ce99f6-c79e-47a7-ab11-74d66d41aa4a.gif)

**Comment by blfetche** [comment]
Was informed this issue was corrected in React, and looked through PF to identify other similar issues, but no other similar issues were found.
