### ISSUE TITLE
Toolbar - explore alignment; error validation throws off alignment

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#5030]
**Is this a new component or an extension of an existing one?**
Toolbar

**Describe the feature**
Explore adding a modifier for this alignment issue. 

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**

![image](https://user-images.githubusercontent.com/5385435/184016693-87d06aa4-550c-4e8a-b91a-4a5c990a132c.png)

![image](https://user-images.githubusercontent.com/5385435/184016714-7e3efd2e-90fe-4655-8424-71a776f7558b.png)

**Comment by mcarrano** [comment]
@mattnolting do you have a specific product use case where this is coming up? Seems like there are some design considerations here and wonder if we can avoid the need for this text.

**Comment by mattnolting** [comment]
@mcarrano The toolbar items are vertically aligned center by default. The fix for this is to align items baseline or top and add a modifier to align items center, to support that behavior. Baseline alignment seems ideal to me (what we use in table, data lists, etc) in that, all the components that I see used in toolbars (buttons, form inputs, pagination, etc) are the same height. This is a breaking change in that the default behavior of the toolbar would change, although all of our examples would remain unaffected. 

Here's an example: https://codesandbox.io/s/vibrant-lalande-37zypb?file=/index.html

**Comment by mcoker** [comment]
@mattnolting looks good to me!

**Comment by nicolethoen** [comment]
Closed by https://github.com/patternfly/patternfly/pull/5201
