### ISSUE TITLE
Notification badge icon contrast issue in dark theme

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5049]
Noticed this looks a bit off in dark theme. Should we change that to black?

Here is the button and notification badge side-by-side

<img width="1090" alt="Screen Shot 2022-08-19 at 4 37 55 PM" src="https://user-images.githubusercontent.com/35148959/185710822-dd5ce63f-aef3-44e2-b61c-9ac561556bc3.png">

The existing hover/expanded states
<img width="552" alt="Screen Shot 2022-08-19 at 4 38 20 PM" src="https://user-images.githubusercontent.com/35148959/185710820-77d33645-ef07-4705-a7f2-1b668b0f5c46.png">

With a black icon
<img width="473" alt="Screen Shot 2022-08-19 at 4 38 40 PM" src="https://user-images.githubusercontent.com/35148959/185710815-5fe88ff0-ddd9-4b40-a687-19a804e4f944.png">

What it looks like in the masthead

expanded
<img width="640" alt="Screen Shot 2022-08-19 at 4 41 06 PM" src="https://user-images.githubusercontent.com/35148959/185711120-3c8c7ddd-69a9-4968-adb8-3f7856c5a98e.png">

not-expanded (ignore the expanded drawer 😅)
<img width="655" alt="Screen Shot 2022-08-19 at 4 41 35 PM" src="https://user-images.githubusercontent.com/35148959/185711105-9527b464-319e-435a-a336-fdbd3c453a6a.png">

cc @mceledonia @mcarrano

**Comment by mcarrano** [comment]
@mceledonia can you take a look at this. The concern is whether there is enough contrast between the icon and the hover background for the attention (red) state. One idea is to just make the icon white on hover, but unclear if that will pass a11y contrast check.

**Comment by mcarrano** [comment]
Per discussion on Aug 30, lets make this change.

**Comment by mcoker** [comment]
@mceledonia @mcarrano some screenshots for review:

### Current light theme

<img width="1840" alt="Screen Shot 2022-08-30 at 4 28 19 PM" src="https://user-images.githubusercontent.com/35148959/187548593-88ff56da-9875-4898-a164-8793a5255680.png">

### Current dark theme

<img width="1840" alt="Screen Shot 2022-08-30 at 4 28 45 PM" src="https://user-images.githubusercontent.com/35148959/187548590-2504e9d1-de85-4465-b6b5-3523eda7f2a8.png">

### Black attention icon

<img width="1840" alt="Screen Shot 2022-08-30 at 4 28 53 PM" src="https://user-images.githubusercontent.com/35148959/187548587-b9cfd35e-dc62-49c8-bb35-8cf62b9cf675.png">

### Icon color indicates status instead of background. Expanded icon color doesn't change.

**Note:** expanded icon color doesn't change

<img width="1840" alt="Screen Shot 2022-08-30 at 4 38 28 PM" src="https://user-images.githubusercontent.com/35148959/187548586-b9136536-2959-47f7-b7d2-1116ecd2673a.png">

### Icon color indicates status. Expanded icon color changes.

<img width="1840" alt="Screen Shot 2022-08-30 at 4 38 42 PM" src="https://user-images.githubusercontent.com/35148959/187548584-613e0d55-36ee-4481-a423-63d2d8179aac.png">

#### Only the read notification badge has a background when expanded

<img width="1840" alt="Screen Shot 2022-08-30 at 4 39 39 PM" src="https://user-images.githubusercontent.com/35148959/187548579-2f6c1897-603c-48eb-a8b5-dd44ca052f6b.png">

**Comment by mcarrano** [comment]
This is a tough one. But I'm thinking this version: Black attention icon  But could also argue for: Icon color indicates status. Expanded icon color changes.  My only concern is that creates inconsistency with light theme. What do you think @mceledonia ?

**Comment by mceledonia** [comment]
Yeah this is a tough one. Just dumping my thoughts for both:

- Black attention icon + background colors — It is a little odd seeing the icon color flip between unread+attention states. Important to note though that the user will never see this side-by-side view, only one of these states at a time. Because of that, I feel like the weirdness of the switch is ok, if not beneficial in terms of communicating urgency.

- Colored icons + no background — These are nice but run into some weirdness with the active states needing to be different due to the color contrast of the lighter background. I also am not a huge fan of these being a different approach than light theme.

I think I'm with @mcarrano here, leaning towards black attention icon with colored background fills as they are in the screenshot.

**Comment by mcoker** [comment]
@mceledonia @mcarrano perfect, and agreed. Thanks for looking!
