### ISSUE TITLE
Bug - word-break can break words unexpectedly

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5053]
Reported in slack, nesting absolutely positioned elements will break every character using `word-break: break-word;`

https://codesandbox.io/s/muddy-wave-1gy49s?file=/index.html

Looks like `break-word` has been deprecated, too. https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

**Comment by mcarrano** [comment]
In the short term, lets try to fix this for Slider specifically.
