### ISSUE TITLE
chart.js - Simple yet flexible JavaScript charting for designers & developers

### ISSUE THREAD

**Issue by ericpritchett** [patternfly/patternfly#5054]
**Is this a new component or an extension of an existing one?**
Implement [chart.js](https://www.chartjs.org/) for the html/css version of Patternfly so users of the html/css version can leverage charts. This project is under the MIT License.

**Describe the feature**
It appears that the react version of PatteryFly has many more charts available than the html/css version. Utilizing chart.js would offer the html/css version to use charts.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Examples can be found at https://www.chartjs.org/docs/latest/samples

**Comment by mcarrano** [comment]
@ericpritchett while we can understand the potential use for this, we don't feel there is enough demand to justify an investment in officially supporting chart.js at this time. That said, this could be a great community project if you are inclined to work on it and/or recruit others to help. Let me know if that's of interest to you. I will keep this as an open request for now, but it will not be added to our feature roadmap.
