### ISSUE TITLE
Menu - Add a danger state for menu items

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#5057]
Want to add the option to apply danger state styling for items in a menu. See https://github.com/patternfly/patternfly-design/issues/1168 for details.

**Comment by blfetche** [comment]
Coming off closed issue [#1168](https://github.com/patternfly/patternfly-design/issues/1168). I could not clearly gauge the direction for design but went ahead and implemented changes in line with @mceledonia recommendation for option 1. Please see below:

**Light Theme**
![image](https://user-images.githubusercontent.com/96086344/190942554-01e212cf-01d5-4f35-a8dd-2d1c544ca03c.png)

![image](https://user-images.githubusercontent.com/96086344/190942594-c6c8775c-5cc1-47a7-aca6-8041df35d527.png)

**Dark Theme**
![image](https://user-images.githubusercontent.com/96086344/190942679-07e88105-1d36-4b4e-9826-86d7ccab84ca.png)

![image](https://user-images.githubusercontent.com/96086344/190942711-e48a19d2-8e88-4355-a8cd-5dddce7b3052.png)

**Comment by mcarrano** [comment]
This looks good to me. @mceledonia can you check?

**Comment by mceledonia** [comment]
Looks good to me as well!
