### ISSUE TITLE
Banner - add sticky bottom variation

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5081]
Per the design guidelines, a banner should be sticky to wherever it is used, and we currently only offer a sticky (top) variation. You can achieve faux-sticky bottom banner a handful of ways, but we should probably offer a simple sticky bottom modifier for general use.

**Comment by blfetche** [comment]
@mcoker I have a working solution locally but before committing my changes, had a question on the header names under the demo section. 

It sounds as if we want to add a bottom banner that appears toward the bottom of the content area? With that in mind and referring to the demo tabs, should we rename "Basic" to "Default" and explicitly call out the bottom option? In the example below I also renamed the "Top/bottom" header to Top/bottom of page" as it isn't clear now as to which top or bottom we are referring to.

![image](https://user-images.githubusercontent.com/96086344/190704493-24a7078b-b5c9-4a54-8547-c59258fe7a26.png)

**Comment by mcoker** [comment]
@blfetche I'm not sure... the "basic" wording is just a generic title we give to usually the most simple (and sometimes default) version of a component/demo. In the case of the banner, "default" also refers to a banner variation. So that could be a little confusing. We may even be able to avoid either word and label the demos by their banner placement. And if we refer to "default," then it's clear we're referring to the banner variation, not the placement.

Per the design recommendations, either top and/or bottom are valid for either in the page content or around the page. But I'm not sure if we're showing the recommended way of using a banner or not - ie, if  sticky top in page content is most recommended if in the page content, and both sticky top and sticky bottom are recommended if displayed outside of the page - or if we're just showing the ways to place the banner.

If we're showing our recommendation, I think what you have is good, though I wonder if we need a sticky bottom demo at all. Or if maybe that should be updated to show both sticky top and bottom if our recommendation is to have both if you're showing a bottom banner.

If we're just showing a demo of how to place banners, I think we could just have 2 demos. 
  1. Top and bottom of page content - just replace the current default/top demo with a demo that shows both top and bottom in page content
  2. Top and bottom of page, which already exists.

What are your thoughts @mcarrano?

**Comment by mcarrano** [comment]
@mcoker @blfetche I'm unclear what we mean by bottom of the page content. The default placement is at the top of the content area (what we currently call "Basic"). The other option is at the top and bottom of the viewport (above and below the page) This was an explicit requirement from Gov't Systems for denoting classification of content.

**Comment by mcoker** [comment]
@mcarrano you can see it at the top and bottom of the page content in a few screenshots on the design guidelines page - https://www.patternfly.org/v4/components/banner/design-guidelines

FWIW here are the design guidelines before I updated the screenshots and updated the verbiage - https://www.patternfly.org/2022.11/components/banner/design-guidelines

When I saw it there I assumed we were missing a variation for a bottom banner in the page content. Is that a valid use case?

FWIW this is how it would look - https://codesandbox.io/s/admiring-tree-l4pnh5?file=/index.html

**Comment by blfetche** [comment]
Perhaps this helps

![image](https://user-images.githubusercontent.com/96086344/190793491-233a78d6-3d55-4d70-a245-19695ca318db.png)

**Comment by mcarrano** [comment]
Ah, learn something new everyday! I wasn't aware we recommended that. But I'm OK with it. @mmenestr can you confirm this is what we want?

**Comment by mmenestr** [comment]
To be honest, I never thought twice about that, and I'm wondering if it is really what we want.... I want to say that if it's inside the body of the page, having it just at the top is enough, and if it's outside the body of the page, then having it top and bottom makes sense. I honestly could go either way but we'd definitely need to update our guideline images to match that

**Comment by blfetche** [comment]
@mcarrano @mmenestr Thank you for your feedback, do we have use cases where we would need a banner to appear in the proposed location within the body?

**Comment by blfetche** [comment]
Closing this issue as it was determined that a bottom banner is not needed within the body.

**Comment by mmenestr** [comment]
Org issue: https://github.com/patternfly/patternfly-org/issues/3208
