### ISSUE TITLE
Search Input - client side validation

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#5089]
In the App Services Kafka service, Some of the properties that a user can filter on have requirements on what characters can be used, specifically the Name property. When the user tries to filter by Name and specifies an invalid character in the search input, we display an error icon in the search input on submit and provide a reason why the value was not applied as a filter via tooltip text, as shown in the example below. 

![image](https://user-images.githubusercontent.com/21063328/187932400-c7dca390-d35c-4493-8b20-adca0c9c7e40.png)

We're starting to look at updating our filter components to use the [PF design guidelines for text entry filters with a button](https://www.patternfly.org/v4/guidelines/filters#text-entry-filters) for this property, and are interested in switching out the Input Group we have today with the Search Input component. But the Search Input component does not currently support these options:
- displaying a tooltip for the text input
- display icons on validation
- displaying the search ➡️ button as disabled

Before opening a pf react issue to request these enhancements, I wanted to raise this question to the PF design team to determine if it makes sense to support this pattern in the search input, or if there is another recommendation for handling this use case.

**Comment by jgiardino** [comment]
Thanks for pulling this one in! I'm not sure about timeline for this. @riccardo-forina is currently working on a refactor of our table view, with the goal of making something that we can reuse across more pages. As part of this he was revisiting the current implementation we have for the filter toolbar and making updates to align with the latest design guidelines. This is when we realized that some aspects of our current implementation are not supported with the Search Input component. Our preference is to use both what's supported by PF components and also what's recommended by PF design guidelines, which is why I raised this issue. But for now we still have our current implementation that we can use until these updates are made. 

@riccardo-forina is out this week, but might have more thoughts on timing of this when he gets back.

**Comment by riccardo-forina** [comment]
I'm late to reply, but we indeed ended up recreating the L&F of the Search Input [on our side](https://redhat-developer.github.io/app-services-ui-components/?path=/story/shared-tabletoolbar-searchinput--type-error-for-invalid), with the extra validation Jenn mentioned.

**Comment by mcarrano** [comment]
So is this needed any longer from PatternFly?

**Comment by jgiardino** [comment]
@mcarrano - I can't speak for @riccardo-forina on this. In my opinion, I think that depends on how PF recommends handling errors for inputs that display in a toolbar, and if the search input component is the recommended component for surfacing filtering in the toolbar. 

I know there is this other layout issue that has a different approach to what I show above: https://github.com/patternfly/patternfly/issues/5030

When working on designs for this, I opted for a tooltip instead of inline helper text partly due to the layout issues, but also due to the fact that my messages were too long to display inline. I don't think it's realistic to expect the approach shown in #5030 to work for everyone's use case.

Ultimately, we want to follow design guidelines that PF recommends for use cases like handling errors (and hopefully the PF components we need would support the design guidelines 😄 )

**Comment by riccardo-forina** [comment]
To add on what Jenn wrote, from an engineering PoV the less custom code er have, the happier we are. We'd love to see our use case supported officially by PF, it would mean we are doing things by the book!

**Comment by mcarrano** [comment]
@riccardo-forina @jgiardino Yes, as you note there is a related issue about making it possible to have validation below the field for items in a toolbar. I think we should address that first and then revisit this topic. I will keep this open in our backlog for now.

**Comment by mcoker** [comment]
@mcarrano @jgiardino @riccardo-forina there is a PR up for #5030 if you want to have a look and provide any feedback taking this issue into consideration - https://github.com/patternfly/patternfly/pull/5201

**Comment by jgiardino** [comment]
Thanks for sharing this, @mcoker. I took a look at the preview, but didn't find any examples that illustrate how error handling is supported with these updates to the toolbar. Do you have any guidance on what examples I should look at to see how this use case is handled with these updates? It might be nice to add some HTML demos that illustrate this use case so that they're easy to find/share with other team members.

**Comment by mcoker** [comment]
@jgiardino sorry about that, agree we should have a demo with some guidance for how/when error text should show up like this. I just mocked this up in dev tools with the use case from this issue:

<img width="1651" alt="Screenshot 2022-12-14 at 1 59 00 PM" src="https://user-images.githubusercontent.com/35148959/207702191-65abd629-cae7-4112-9062-0c67477e1a9f.png">
<img width="1651" alt="Screenshot 2022-12-14 at 1 58 19 PM" src="https://user-images.githubusercontent.com/35148959/207702194-dfda52ce-01e7-4b43-a952-38e4118e495d.png">

cc @mattnolting

**Comment by jgiardino** [comment]
Thanks for sharing these examples, @mcoker! I have a couple more questions 😄 

- @mcarrano For the use case where handling error validation for toolbar form inputs, is displaying the message inline vs in a tooltip the recommended approach from the PF design team? Do you know if there will be any design guidelines that further describe this behavior (e.g. when does the message display, does the input become disabled, etc...)
- The original description for this issue describes updates to the Search input component, which I don't think is shown in your example above. So I just want to check whether this issue will remain open for adding support to the items requested (or at least the items requested that would be inline with any PF recommendations).

**Comment by mcarrano** [comment]
Good questions @jgiardino We will give this more consideration and look at the pros and cons of different approaches from a design perspective.

**Comment by mmenestr** [comment]
@jgiardino have you considered other solutions that would avoid having to have some sort of error text around this?

Some ideas could be putting a message in the empty state that comes up when the search yields no result (ie: User searches, no results match the criteria because the input is invalid, so the empty state says "no matches found, ensure that your input only includes lower cases letters from a to z etc")?

Another consideration would be having a list of items to select from, rather than having it be a free form text input that could result in input errors?

**Comment by jgiardino** [comment]
Thanks, @mcarrano and @mmenestr.
@mmenestr regarding some of your suggestions, here are some initial thoughts: 

> Some ideas could be putting a message in the empty state that comes up when the search yields no result (ie: User searches, no results match the criteria because the input is invalid, so the empty state says "no matches found, ensure that your input only includes lower cases letters from a to z etc")?

This could be an option, but it's also not consistent with the design guidelines provided for [forms regarding error validation](https://www.patternfly.org/v4/components/form/design-guidelines#errors-and-validation). If we break from these guidelines for this use case, it would be good to update the guidelines if this is the direction that PF recommends. 

It would also be good to consider the use case where other filters have been applied and whether the invalid filter displays as a filter chip. For example, do we continue to make an api call with a filter that we know is invalid? How should we communicate to the user which input is invalid? How do they clear the empty state to see their previous set of results before they specified an invalid filter option? Our current implementation does not apply the invalid result as a filter, which means the items listed below the toolbar remain unchanged, and the user can either correct the form input or continue browsing the current results. With all of the additional considerations with handling the invalid filter after form submit, I feel like handling this on the form input immediately reduces complexity for this use case.

> Another consideration would be having a list of items to select from, rather than having it be a free form text input that could result in input errors?

I don't think that option works for our use case. We're using the text input for values that are user-specified.

**Comment by mmenestr** [comment]
@jgiardino I wouldn't necessarily look to the Form guidelines for this, since the input is not in a form form. I can add guidance around filter validation under the Filter guidelines though!

As for the empty state solution - yes, I think you'd continue to make an API call, which would lead to an empty state displaying the message that they input is invalid. From there, there usually is a "Clear filter" button as part of the empty state to go back to the original list. But I see what you mean - in this case, since it's an attribute filter, the empty state solution doesn't really work... it only works if there's only one filter attribute.

So I guess @mcarrano @mcoker we might have to go ahead and go with the originally proposed solution, unless you can think of anything else.

**Comment by mcarrano** [comment]
No, I think the idea of adding validation text below the field is consistent with what we've done elsewhere to report field level validation errors in forms and easily extends to filters and toolbars with the latest toolbar fixes.

**Comment by mcarrano** [comment]
Let's re-evaluate this following all of the v5 toolbar updates and see if further action is needed. I think we are still waiting on this issue to be resolved: https://github.com/patternfly/patternfly-react/issues/8604
