### ISSUE TITLE
[Component] - [short description]

### ISSUE THREAD

**Issue by arburka** [patternfly/patternfly#5113]
**Is this a new component or an extension of an existing one?**
Extension of documentation of acronyms
https://www.patternfly.org/v4/ux-writing/terminology/#abbreviations-and-acronyms

**Describe the feature**
Add additional information related to what Josh describes in Slack
Josh
  [5 hours ago](https://rhux.slack.com/archives/CQVFVCN2G/p1663858105877969?thread_ts=1663600577.207609&cid=CQVFVCN2G)
Stepping into this late, but I think it also should depend on how the company refers to itself in its own marketing materials. E.g. If you go to [Amazon's AWS website](https://aws.amazon.com/), the acronym AWS is everywhere, whereas if you go to the [Google Cloud website](https://cloud.google.com/), GCP is nowhere to be found. Looking at the Google website, it seems they primarily call their product "Google Cloud"

https://rhux.slack.com/archives/D0237NQLZ71/p1663876512688479

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Nope!

**Any other information?**
@wolfeallison @kaedward

**Comment by mmenestr** [comment]
Closing bc it was created in the wrong repo
