### ISSUE TITLE
All - review use of transitions/animations for prefers-reduced-motion alternatives

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5120]
**Is this a new component or an extension of an existing one?**
All existing (and future) components using transition effects or animation should be reviewed for possible seizure or vestibular triggers that should be addressed by removing or altering the effect when `prefers-reduced-motion` is true.

**Describe the feature**
The media query `prefers-reduced-motion` should be used to remove or change effects that are problematic. Of most concern are things that flash and things that slide. [A working doc](https://docs.google.com/document/d/1SkWJFajTFzySXwzrbjF0_gwLJos4fy6SU8-_Cla2uNo/edit?usp=sharing) contains notes about specifics as well as techniques.
Note: just removing every transition is not necessarily the best solution, as not all effects are equally problematic and in some cases are helpful for populations that intersect with those sensitive to motion. However, we could consider implementing a "kill switch" variable that does remove all; this could then be exposed to the user with a custom setting.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
There may need to be design issues to create the alternatives to existing effects.

**Any other information?**
List of components currently using transition or animation is in [the working doc](https://docs.google.com/document/d/1SkWJFajTFzySXwzrbjF0_gwLJos4fy6SU8-_Cla2uNo/edit)

**Comment by mcarrano** [comment]
Coordinate with @mceledonia on the design side

**Comment by srambach** [comment]
I've put all the components with transitions currently, and all the components on the list to add animations to, into a [sheet](https://docs.google.com/spreadsheets/d/1jjm2nXvqLsObuhSZ-cbII7d22WQ98W5r1ycC9BwJCIk/edit#gid=0). The column on the right indicates whether design is needed for prefers-reduced-motion or if it's probably ok to leave it - e.g. the caret rotation that we have many places should be ok because it's small, a rotation, and doesn't flash.

@mceledonia
