### ISSUE TITLE
Empty state - clean up CSS

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5138]
* Looks like we can comb through the CSS and make general updates around variable usage and general maintenance of specificity - like creating a var for the body font-size that can be manipulated at the size variation selector specificity https://github.com/patternfly/patternfly/blob/02bda75f8f22a9e230be216ed2e6e8ffd5b48cc3/src/patternfly/components/EmptyState/empty-state.scss#L79-L81
* We're styling the title font-size - we should remove that and see if there is still a need to manage the font-size there - https://github.com/patternfly/patternfly/blob/02bda75f8f22a9e230be216ed2e6e8ffd5b48cc3/src/patternfly/components/EmptyState/empty-state.scss#L92-L94
  * We may consider adding a title element to the empty state for the title, and/or for a place to use the title component, instead of styling the title component when it's a direct descendent.
* Similar to ^, we're styling `.pf-c-button.pf-m-primary` when it's a direct descendent and that can be problematic. We should probably remove that, and just use the `__primary` empty state element for the primary action (which may not always be a primary button)
* Consider using the small button modifier in the xs empty state if we want to have small actions, instead of styling all buttons, which could be problematic and potentially break if we add button variations that set font-size with a higher specificity than this rule - https://github.com/patternfly/patternfly/blob/02bda75f8f22a9e230be216ed2e6e8ffd5b48cc3/src/patternfly/components/EmptyState/empty-state.scss#L60-L62
* Use gap here - https://github.com/patternfly/patternfly/blob/02bda75f8f22a9e230be216ed2e6e8ffd5b48cc3/src/patternfly/components/EmptyState/empty-state.scss#L117-L129
* Update the icon so that we're always using a container for the icon, and the icon is placed as a child of the icon container. This will keep the empty state class on the container instead of needing to manipulate a class on the icon itself. Currently the react empty statue component needs an icon passed as a component by default, and the empty state class is applied to the icon directly which we would like to avoid.
  * related - https://github.com/patternfly/patternfly-design/issues/1198

**Comment by nicolethoen** [comment]
@mcoker when the follow up issue is opened in react, can we make a note that there are empty states used in the Dual list selector examples (and I think Table examples/demos) that will also need to be updated?

**Comment by nicolethoen** [comment]
Closed by #5307
