### ISSUE TITLE
Wizard - support for step status

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5142]
React has custom styles for an invalid step that we should bring back to core.

Here's the example https://patternfly-react-v6.surge.sh/components/wizard/#step-error-status.

**Comment by mcarrano** [comment]
@mcoker I'm not clear if we need other statuses. Seems like a step either succeeded or it did not. Are there other options we should consider?

**Comment by mcoker** [comment]
@mcarrano we can always add them later if we don't have use cases for other statuses.

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6447
