### ISSUE TITLE
Wizard - clean up CSS

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5143]
A couple of things I spotted, but there may be other improvements, too

* Wizard close button class is on the plain button component - we should have a separate wizard element for the close button that the plain button component is placed inside.
* The wizard title class is on the title component - same as above. We may also consider not using the title component there, which ties the title markup to the presentation. For example, if we want to update the font size of the wizard title, that's a markup change - it maybe be better if we could handle that in CSS.

(check for other instances in the wizard as well)

**Comment by nicolethoen** [comment]
This solution will be similar to recent modal/popover/empty state solutions
