### ISSUE TITLE
Bug - [Table] - [weird borders in Safari]

### ISSUE THREAD

**Issue by idryzhov** [patternfly/patternfly#5173]
**Describe the problem**
Table borders are displayed weirdly in Safari. There are multiple borders in middle cells.

**How do you reproduce the problem?**
Open https://www.patternfly.org/v4/components/table#composable-actions in Safari and look at the table.

**Expected behavior**
The borders should be displayed only once.

**Is this issue blocking you?**
I can manually disable `vertical-align: baseline` in browser inspector, but I can't do that programmatically (I'm using patternfly-react).

**Screenshots**
Default behavior:
<img width="1680" alt="Screenshot 2022-10-14 at 14 16 19" src="https://user-images.githubusercontent.com/1313087/195835346-ef0ac675-a91b-4369-8f13-6aecdd898463.png">

With `vertical-align: baseline` disabled:
<img width="1680" alt="Screenshot 2022-10-14 at 14 16 44" src="https://user-images.githubusercontent.com/1313087/195835406-f95c37ce-0b77-44c2-b567-0d6c30a3ee55.png">

**What is your environment?**
 - OS: macOS
 - Browser Safari
 - Version 16

**Comment by mcoker** [comment]
Hey @idryzhov, this issue outlines the issue - https://github.com/patternfly/patternfly/issues/5016

I just checked Safari TP and it still has the issue. Hopefully it's resolved quickly. In the meantime, changing this will likely fix the double border for most tables - https://github.com/patternfly/patternfly/blob/2e3c6ae53034cfa9a42dcdaf73a34b3841f5f320/src/patternfly/components/Table/table.scss#L554

If you can provide an override in your CSS, it would look like:

```
.pf-c-table tbody > tr > * {
  vertical-align: revert; /* or whatever value is most suitable */
}
```

**Comment by idryzhov** [comment]
Thanks @mcoker, this is really helpful.
I am closing this issue as a duplicate.
