### ISSUE TITLE
Potential namespace conflict with "default" in status prop enums

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5175]
Technically "default" is a status indicated by `.pf-m-default` (cyan), but "default" is also a special word in many of our enums that applies whatever the prop's default is (as if the prop were undefined). It seems like we usually (though not always) have a way to provide a value to set the prop to undefined?

We have status props that are optional (meaning you should be able to set the prop to it's default as if it were undefined), but also need "default" as a status value (to apply `.pf-m-default`), and they can't use the same name. Some examples

### Popover
https://github.com/patternfly/patternfly-react/blob/b44f6c31e0ab822af9626fd16912d4eb6ba01f3e/packages/react-core/src/components/Popover/Popover.tsx#L49

### Notification drawer list item
https://github.com/patternfly/patternfly-react/blob/b44f6c31e0ab822af9626fd16912d4eb6ba01f3e/packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx#L19

### Modal/Modal content
https://github.com/patternfly/patternfly-react/blob/b44f6c31e0ab822af9626fd16912d4eb6ba01f3e/packages/react-core/src/components/Modal/Modal.tsx#L68

https://github.com/patternfly/patternfly-react/blob/b44f6c31e0ab822af9626fd16912d4eb6ba01f3e/packages/react-core/src/components/Modal/ModalContent.tsx#L75

### Icon
https://github.com/patternfly/patternfly-react/blob/b44f6c31e0ab822af9626fd16912d4eb6ba01f3e/packages/react-core/src/components/Icon/Icon.tsx#L20

### Alert

This one is a little more tricky, and kind of. `<Alert>` on its own without a status modifier class provides _default status_ styling (cyan). However, there is no `.pf-m-default` class to specify default status styling. It's implied that if you want to convey "default" status, don't use a modifier. This is because there is no non-status alert (just regular/black text/icons). I don't know if there should be? That said, it's a bit inconsistent with some of our other components where we offer optional size variations where whatever the default size is (no size variation) is also offered as a specific variation. I think that's useful from a general theming perspective. It also lets us update the default size while still offering whatever the previous default was as an option.

So `variant="default"` undoes any status variation/class, but also provides default status styling since that's the default from the core CSS.

I guess we could
* leave this as is
* add `.pf-m-default` as a variation. That would allow us to update the non-status default for the component in the CSS to be black text/icon or something, while still offering `default` as a status variation via `.pf-m-default`. This is probably inline with how other components work.
* make `.pf-c-alert` require a status modifier class, since we currently don't support a non-status alert in presentation. So add `.pf-m-default` in the CSS and apply that class with `variant="default"` in the react component. Buttons are like this and require a variation since we don't have a generic/unstyled button.

cc @tlabaj

**Comment by mcoker** [comment]
cc @mceledonia @mmenestr - do you think there is a more appropriate/meaningful name for the current "default" status? Examples of where it's used now:

Notification drawer - cyan
* https://www.patternfly.org/v4/components/notification-drawer/html#basic

Modal
* https://www.patternfly.org/v4/components/modal/html#default-alert

Popover
* https://www.patternfly.org/v4/components/popover/html#default-alert-popover

Icon - cyan
* https://www.patternfly.org/v4/components/icon/html#status-colors

**Comment by mcarrano** [comment]
@mmenestr @mceledonia and I discussed this today. What about something more like "no status" or "null status?" This makes sense because the default here was really introduced for use cases where none of the standard status or severity settings made sense. Thoughts @mcoker ?

**Comment by mcoker** [comment]
I guess "no/null status" seems like there is no status, I'd wonder about cases like the popover/modal where you can have just an icon in the title (matches the text color), or a "no/null status" cyan icon - what the difference would be?

And could no status be a case for using the "info" status? Or is there a differentiation of an "info" status alert and a default/null/no status alert?

Assuming we want to keep it, maybe "none", "neutral", or "generic"?

**Comment by mcoker** [comment]
@mcarrano sounds good to me! Also, if we decide this is the best name for the variant, we should be able to handle the issue in the core/react code. We'll just need to have the same naming conversation around the word "default" and its use in our component props.

**Comment by nicolethoen** [comment]
the shortest path to addressing this is likely to just rename 'default' to 'custom'
Does that sound right, @mceledonia ?
