### ISSUE TITLE
Slider - input group above thumb looks odd

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5176]
This is what it looks like now. There is a white background applied to the `%`, which is part of the input group - a "plain" input group "text" element

![www patternfly org_v4_ (1)](https://user-images.githubusercontent.com/35148959/195633798-63b99fe3-de4a-41b4-a76b-eef0ede23934.png)

Without the background

![www patternfly org_v4_ (2)](https://user-images.githubusercontent.com/35148959/195634010-2dda57bb-1169-4e56-b0e2-5bfcee0b481f.png)

With a regular input group text element

![www patternfly org_v4_](https://user-images.githubusercontent.com/35148959/195636874-5b56d9ce-89b1-457d-8c9e-635c177d21d5.png)

With the border removed

![www patternfly org_v4_ (1)](https://user-images.githubusercontent.com/35148959/195909717-373eba18-5995-4d37-bc1e-064b0c4ffa1a.png)

Why there is so much space there

![www patternfly org_v4_](https://user-images.githubusercontent.com/35148959/195909756-32da60d3-5e72-4212-a6f6-b5c92115cb48.png)

wdyt @mcarrano @mceledonia @mmenestr

**Comment by mmenestr** [comment]
I like "With a regular input group text element"

**Comment by thatblindgeye** [comment]
Just want to clarify: should the regular text input group only be used when the input is above the thumb, or would we want it to be used for any input on a Slider as shown below? Screenshot is from my local React workspace for a followup to this issue.

![Slider input with regular text input group](https://user-images.githubusercontent.com/70952936/203070138-fa1a01b8-a9c3-4c05-ab0a-2bffe1909bff.png)

**Comment by mcarrano** [comment]
That's a good question @thatblindgeye . I would expect these to be consistent. @mmenestr @mceledonia do you agree? For reference, here's what it looks like now: https://www.patternfly.org/v4/components/slider#value-input

**Comment by mceledonia** [comment]
Agreed, they should all be the same!

**Comment by thatblindgeye** [comment]
Sounds good!

One other thing is, how would we want this input group text to look when the input itself is disabled @mceledonia @mmenestr ? Currently I don't believe there's disabled styling for the input group text, and when the slider input is disabled it looks odd with the update:

![Updated slider input without disabled text](https://user-images.githubusercontent.com/70952936/203131281-0651757a-3e10-4dfb-8e5b-1484235c7d03.png)

There's a couple of options I thought of, one of which is just using the `pf-m-plain` styles as disabled styling:

![Updated slider with plain styling for disabled text](https://user-images.githubusercontent.com/70952936/203131480-9149dea4-d5ae-4acb-96e4-77082d4c65a5.png)

Or matching the disabled styling of the form control (update background color and remove the bottom border):

![Updated slider with text matching disabled input styles](https://user-images.githubusercontent.com/70952936/203132032-63ad8a41-8848-4bdb-9743-0ba0b8b8d515.png)

**Comment by mceledonia** [comment]
I prefer the last option given that it's consistent, I think keeping it all within a single shape helps visually as well.
