### ISSUE TITLE
Audit component global variable usage

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5185]
Towards https://github.com/patternfly/patternfly/issues/5105 and https://github.com/patternfly/patternfly/issues/5117

The goal for this is to identify gaps and other issues with our current global vars as a starting point for refactoring the global vars to move towards tokens and better support theming.

In this issue, let's audit the existing use of global vars, including CSS (`--pf-global-`)  and SCSS (`$pf-global-`) global vars, including the color vars (`--pf-global--palette` and `$pf-color-`).

Something along the lines of:

* List of vars 
* What their primary purpose is
* Where they're used

What we're looking for is probably along the lines of:
* Misuse that is just a basic bug - we're using the wrong one (or no var at all) when there is a global var that suits the purpose. 
* Misuse due to a gap in global vars - we're using a border or disabled var for something that isn't a border/disabled thing simply because the var provides the value we want to use. This would also cover most uses of the color specific vars, which I'd say should either never be the case, or be a valid last resort/exception.
* Trends in use/misuse - where are we using them well, and where might we be using a var across concepts that's technically OK but would benefit from different/better vars (eg, disabled color for both use with text and backgrounds/surfaces, or the `-50` colors for light status backgrounds). 

As part of this effort, it would be great to take a look through the components and see where we are not using a global var where we should be. A good example is with transition/animation timing/easing. Here are some examples where we are hard coding values for that.

```
accordion.scss:  --pf-c-accordion__toggle-icon--Transition: .2s ease-in 0s;
card.scss:  --pf-c-card--m-selectable-raised--m-selected-raised--Transition: transform .25s linear, box-shadow .25s linear;
card.scss:  --pf-c-card--m-selectable-raised--m-selected-raised--before--Transition: transform .25s linear;
clipboard-copy.scss:  --pf-c-clipboard-copy__toggle-icon--Transition: .2s ease-in 0s;
data-list.scss:  --pf-c-data-list__toggle-icon--Transition: .2s ease-in 0s;
expandable-section.scss:  --pf-c-expandable-section__toggle-icon--Transition: .2s ease-in 0s;
nav.scss:  --pf-c-nav__scroll-button--Transition: margin .125s, transform .125s, opacity .125s;
notification-drawer.scss:  --pf-c-notification-drawer__group-toggle-icon--Transition: .2s ease-in 0s;
switch.scss:  --pf-c-switch__toggle--before--Transition: transform .25s ease 0s;
table-grid.scss:  --pf-c-table__toggle__icon--Transition: .2s ease-in 0s;
table.scss:  --pf-c-table__toggle--c-button__toggle-icon--Transition: .2s ease-in 0s;
tabs.scss:  --pf-c-tabs__scroll-button--TransitionDuration--margin: .125s;
tabs.scss:  --pf-c-tabs__scroll-button--TransitionDuration--transform: .125s;
tabs.scss:  --pf-c-tabs__scroll-button--TransitionDuration--opacity: .125s;
tabs.scss:  --pf-c-tabs__link-toggle-icon--Transition: .2s ease-in 0s;
```

**Comment by srambach** [comment]
This spreadsheet pulls all uses of globals in PatternFly, then extracts the variable name into 2 columns (set vs used) for sorting and filtering. 
A second sheet autofills a de-duplicated list that should have intended usage of variables added by hand.
A pivot table adds counts for possible interest 🤷 
Some queries for candidates for globals, like anything manually setting transition, box shadow, using palette colors, using pixel values are in separate sheets.
https://docs.google.com/spreadsheets/d/1_ZfLYbGVdoQRMUrROm4GDFQ_RoYDJd6peUksGSGdgJo/edit?usp=sharing

**Comment by srambach** [comment]
@mcoker @mattnolting @mceledonia 
WDYT? Are there any other ways of viewing that would be useful? What other searches can you think of to find candidates for globals?
