### ISSUE TITLE
Remove search input classes/component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5212]
In core, the search input component is still beta, and is used in these places. I'm assuming these should be updated to use the text input group, and the search input group component can be removed?

* Menu
* Application launcher
* Log viewer - [we have CSS support for it](https://github.com/patternfly/patternfly/blob/e12e8d5cf82cbb9e0d49a619974d07565dcf68e3/src/patternfly/components/LogViewer/log-viewer.scss#L136-L138)
* Select
* Dual list selector
* Page and masthead demos - masthead drilldown
* Context selector
* Tree view
* Toolbar - [toolbar-item-context-selector.hbs](https://github.com/patternfly/patternfly/blob/e12e8d5cf82cbb9e0d49a619974d07565dcf68e3/src/patternfly/components/Toolbar/toolbar-item-context-selector.hbs#L11)
* Text input group - [text-input-group-clear.hbs](https://github.com/patternfly/patternfly/blob/e12e8d5cf82cbb9e0d49a619974d07565dcf68e3/src/patternfly/components/TextInputGroup/text-input-group-clear.hbs) - doesn't appear to be used anywhere

**Comment by nicolethoen** [comment]
https://github.com/patternfly/patternfly/blob/v5/src/patternfly/components/TextInputGroup/text-input-group--search-input.hbs
