### ISSUE TITLE
Bug - [Form Control Select] - [Icon is incorrect in dark mode]

### ISSUE THREAD

**Issue by jelly** [patternfly/patternfly#5215]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

**How do you reproduce the problem?**

1. Visit https://pf4.patternfly.org/components/form-control/#select
2. Switch to dark mode and see that the select icon changes into a checkmark

We observe this problem in cockpit with the following versions:

```
    "@patternfly/patternfly": "4.219.2",
    "@patternfly/react-core": "4.258.3",
    "@patternfly/react-icons": "4.92.10",
    "@patternfly/react-styles": "4.91.10",
    "@patternfly/react-table": "4.111.33",
```

**Expected behavior**

It should show a white triangle, such in other selects in dark mode

**Is this issue blocking you?**

We have a workaround in Cockpit.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**
 - Chrome 107.0.5304.87-1

**What is your product and what release date are you targeting?**

Cockpit

**Comment by garrett** [comment]
## Screenshots

### Light

![image](https://user-images.githubusercontent.com/10246/199776819-fee10bd0-c321-4060-b6a6-62ca8a2867bf.png)

### Dark

![image](https://user-images.githubusercontent.com/10246/199776878-9bb729e4-aed4-4cf6-9735-792d4ec54c12.png)
