### ISSUE TITLE
Bug - pf-svg classes not included in react-styles

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly#5218]
**Describe the problem**
The CI build is failing in https://github.com/patternfly/patternfly-react/pull/5275 due to [these missing css classes ](https://github.com/patternfly/patternfly/blob/main/src/patternfly/base/patternfly-icons.scss#L4-L30) which do not get pulled into `react-styles`.

This is because `patternfly-base.scss` doesn't include them, as they're not in the import chain.

**How do you reproduce the problem?**
https://patternfly-react-pr-5275.surge.sh/components/button#variant-examples
The button variants that include icons are oversized due to the missing styles.

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/5220
