### ISSUE TITLE
Bug - CalendarMonth - Fix spacing of year to not truncate

### ISSUE THREAD

**Issue by phill-85** [patternfly/patternfly#5222]
**Describe the problem**
The year input field for the CalendarMonth component appears to use a standard HTML input element with the type number. Using Brave on Ubuntu 22.10 & Windows 10 this gives the little up and down arrows to the right of the input. Using Brave on Android 13 this behaves like a line edit with the numeric keyboard.

**How do you reproduce the problem?**
View demo at https://www.patternfly.org/v4/components/calendar-month

**Expected behavior**
I think this would provide better design consistency, and usability, if the NumberInput component was used instead. The + & - controls will provide better usability, especially on mobile where to change to the next or previous year will require only 1 touch instead of 3.

**Comment by phill-85** [comment]
Alternatively / Additionally, |< & >| buttons could be added to the CalendarMonth component to change the year.

**Comment by mcarrano** [comment]
We looked at this. While we don't expect to use a Number input here, we do see the issue and will investigate other solutions.

**Comment by nicolethoen** [comment]
Our list of supported browsers at this time can be found here: https://www.patternfly.org/v4/get-started/about#supported-browsers

**Comment by phill-85** [comment]
Also the same in Chrome Version 107.0.5304.110 (Official Build) (64-bit), on mobile and desktop.

Screenshot from Chrome:
![image](https://user-images.githubusercontent.com/4619659/202048677-3f662c5a-5a9a-44d4-b8f7-1e2166c6208d.png)

**Comment by nicolethoen** [comment]
The arrows appearing in the input was something we left intentionally. But in some browsers it's causing the year to truncate, so that's not ideal.
