### ISSUE TITLE
Card - font weight for titles should be medium

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly#5234]
> @mmenestr @jenny-s51 The header font weight is a good catch. They should use medium font weight, we don't actually use bold for any of our font styles so we should be consistent there. 

https://www.patternfly.org/v4/guidelines/typography#usage-guidelines

_Originally posted by @mceledonia in https://github.com/patternfly/patternfly-react/issues/8286#issuecomment-1313998126_

**Comment by nicolethoen** [comment]
Likely we need to clarify with design what this font weight should be. @mceledonia

**Comment by nicolethoen** [comment]
We might also consider updating the Card Title to be structured similarly to the way that @srambach  updated the Empty State title
