### ISSUE TITLE
Dark theme and use of pf-t-dark/pf-t-light 

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5257]
https://github.com/patternfly/patternfly/blob/24957f7db1fdbd28d55ffa05eba4d4a68e16b793/src/patternfly/sass-utilities/placeholders.scss

The file linked above is the current light/dark theme support we have in core for creating light/dark sections and a basic set of overrides of global vars for light/dark theme. These light/dark sections can be applied to the whole page, or an individual element/block/component, and can apply to components in components. For example, you could have light theme with a dark theme card (all of its children will inherit dark theme global vars), and a light theme table within the card (meaning the table and all of its children are light theme). With the update to the official dark theme and keeping the visual refresh in mind, I think we want to consider:

* Do we want to continue to support dark theme on blocks this way - and particularly on blocks within blocks? For example - the masthead is a dark block. Its menu toggles should probably be dark. But should the dropdown menus that those toggles open be light theme or dark theme, assuming the rest of the page is light theme? If light themed, then we need to be able to inverse the theme at different levels of nesting, which can get tricky.
* Since we should have a full dark theme available with the visual refresh, will the visual refresh introduce a truly light theme (no "dark theme" blocks/sections), and the whole page toggles from light to dark? @mceledonia I believe this is what you have mentioned as part of the goals to deliver with the visual refresh.

cc @mceledonia @lboehling @mcarrano creating this to officially track this change. Feel free to add any additional notes.

related to https://github.com/patternfly/patternfly/issues/5105

**Comment by mcarrano** [comment]
@mcoker @mceledonia Just doing some housekeeping. Is this issue still relevant?

cc @andrew-ronaldson
