### ISSUE TITLE
Bug - Remove outdated styles in _common.scss

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly#5261]
**Describe the problem**

Follow up to #5218 
Towards https://github.com/patternfly/patternfly-react/pull/5275

**How do you reproduce the problem?**

Tested on a local branch with the changes in https://github.com/patternfly/patternfly-react/pull/5275. The icon sizes are correct now when we import the svg classes following the changes in #5218 . However some outdated styles in `_common.scss` are now causing the PF site to look like this when built:

<img width="1728" alt="Screen Shot 2022-11-16 at 3 47 32 PM" src="https://user-images.githubusercontent.com/32821331/204579100-43040cce-bfc3-4c57-9506-a51a807e0c74.png">

After investigating, removing these outdated styles seems to fix it. https://github.com/patternfly/patternfly/blob/main/src/patternfly/base/_common.scss#L2-L11

These are already expected to be removed in the breaking-change release based on the comments.

**Comment by nicolethoen** [comment]
Closed by #5339
