### ISSUE TITLE
Icons - Add "processor" icon

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#5263]
Adds a new icon for "Processor". Pending completion of https://github.com/patternfly/patternfly-design/issues/1210

**Comment by yichen1yu** [comment]
![data-processor](https://user-images.githubusercontent.com/108347329/208143913-465fd14a-31c2-47a5-a39e-10265e25e418.svg)

**Comment by yichen1yu** [comment]
Svg filed attached. Feel free to let me know if there's any question. Thanks!
