### ISSUE TITLE
Refactor click/select affordances for cards

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#5264]
Follow up to https://github.com/patternfly/patternfly-design/issues/1211

### Updates to the card behavior/interactions:

1. Selectable cards:
**Updates**: There is a hover on the entire body of the card via mouse and keyboard. We are introducing a background color for more visual affordance on the hover, focus, and selected state. Clicking anywhere on the card would select the card and there is now more visual affordance to the selected state of the card with the addition of the background color and blue border around the body of the card. This mirrors Carbon's interaction for tiles.
![Selectable Card@1x](https://user-images.githubusercontent.com/98424339/213583757-ae226d0d-f0c0-405f-9d8e-ea801f90928e.png)

2. Single-selectable cards (new):
There is a hover on the entire body of the card via mouse and keyboard. We are introducing a background color for more visual affordance on the hover, focus, and selected state. Clicking anywhere on the card would select the card and there is now more visual affordance to the selected state of the card with the addition of the background color and blue border around the body of the card.
![Single Selectable Card@1x](https://user-images.githubusercontent.com/98424339/213583777-c13fa034-bd9d-4b6a-b315-b305572a7a47.png)

3. Clickable cards:
There is a hover on the entire body of the card via mouse and keyboard. We are introducing a background color for more visual affordance on the hover, focus, and selected state. Clicking anywhere on the card would trigger the action: ex. opening the primary-detail drawer, navigating to a new page, etc. **Updates**: There is now more visual affordance to the "clicked" state of the card with the addition of the background color and blue border around the body of the card.
![Clickable Card@1x](https://user-images.githubusercontent.com/98424339/213583818-a319803f-e7ad-47e9-ad31-30d3ae1bc8aa.png)
![Clickable Card w primary detail](https://user-images.githubusercontent.com/98424339/211892745-243edd4b-1012-400d-aecc-d36363767ffa.png)

4. Selectable & clickable cards:
Moving away from nested interactions and requiring separate affordances when there are multiple actions within a card. The body of the card being a trigger to an action will be reserved for when there is a single action within the card, like the above examples. 
There is a hover on the card title and checkbox via mouse and keyboard. Clicking on the title will trigger the action of either opening a primary-detail drawer, navigating to a new page, etc. If opening a primary-detail drawer, the card will appear with a blue border to indicate that the card has been clicked. To select the card for a global action, the user would need to click the checkbox. Below are examples of the different states in a white and gray background.
![Selectable   Clickablev3 gray bg@1x](https://user-images.githubusercontent.com/98424339/213577281-d0d8c93d-9961-4cd4-82d9-eaff83d0d19e.png)
![Selectable   Clickablev3@1x](https://user-images.githubusercontent.com/98424339/213577285-2dd4dbd5-7bfc-4938-880e-4143ba032aaa.png)

### **Visual Specs:** (Selectable only & Clickable only cards)

1. Default card state uses default card component

2. Hover card state: 
- Fill: #FFFFFF
- Shadows: #000000, Alpha:18 X:0, Y:8, Blur:16; #000000, Alpha:8 X:0, Y:0, Blur:6
- Inner Shadows: #F5F5F5, Alpha:100, X:0, Y:-200, Blur:0

3. Focus card state uses PF Focus State layer

4. Select/Active card state:
- Fill: #FFFFFF
- Borders: 18. $pf-color-blue-400, Center, Width:1
- Shadows: #000000, Alpha:18 X:0, Y:8, Blur:16; #000000, Alpha:8 X:0, Y:0, Blur:6
- Inner Shadows: #F5F5F5, Alpha:100, X:0, Y:-200, Blur:0

5. Disabled card state:
- Fill: #FAFAFA
- Borders: 5. $pf-color-black-300, Center, Width:1

### **Visual Specs:** (Selectable & Clickable cards)
1. Default card state uses default card component

2. Hover card state uses the default card component with text: 08. Link (RHT rg 16) 2.pf-global--link--Color--hover.

3. Select card state uses default card component

4. Click (Active) card state:
- Fill: #FFFFFF
- Borders: 18. $pf-color-blue-400, Center, Width:1
- Shadows: #000000, Alpha:18 X:0, Y:8, Blur:16; #000000, Alpha:8 X:0, Y:0, Blur:6
- Inner Shadows: #F5F5F5, Alpha:100, X:0, Y:-200, Blur:0

5. Disabled card state:
- Fill: #FAFAFA
- Borders: 5. $pf-color-black-300, Center, Width:1

**Comment by nicolethoen** [comment]
Is this issue going to address this other card issue? https://github.com/patternfly/patternfly/issues/4956

**Comment by srambach** [comment]
> Is this issue going to address this other card issue? #4956 @mcoker @srambach

At the moment I have changed the legacy class names to be `X-deprecated` because we are reusing the modifier `pf-m-selectable` but I am in favor of removing the legacy variants completely. @mcoker wdyt?
