### ISSUE TITLE
Bug - [Table] - [Table background in modals does not use the same background with the modal]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#5278]
**Expected behavior**
Inherit the modal background maybe.

**Is this issue blocking you?**
Not blocked.

**Screenshots**
![dark-mode-table-in-modak](https://user-images.githubusercontent.com/14921356/206427392-d4e1a9ca-9e44-4031-a9ec-5188abb8e34a.png)

**What is your product and what release date are you targeting?**
cockpit

**Any other information?**
In not interested to fix it upstream, I am ok to add a local workaround in cockpit css.

**Comment by mcoker** [comment]
cc @mceledonia @lboehling this is because the table is set to use `pf-global--BackgroundColor--100` - is that something we want to consider updating?

**Comment by mcarrano** [comment]
@KKoukiou we see the issue. Will try to address as part of the global variable refactoring for PatternFly 5.

**Comment by mcarrano** [comment]
We acknowledge that this is a design anomaly with dark theme, but we don't have an easy fix at this time. It might make sense to change the background of the table to match the modal in this case, but that is not a solution that can work everywhere.

**Comment by Venefilyn** [comment]
@mcarrano @mcoker has there been any follow-up recommendations here since this was in PF5 or is it still something we should override ourselves?
