### ISSUE TITLE
Login and About modal - Update background image to use lightweight SVG

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#5282]
Want to update background images used in Login and About Modal components per the designs here: https://github.com/patternfly/patternfly-design/issues/1202#issuecomment-1349585686

The goal is to replace the bitmaps with lighter weight SVGs that can be easily replaced by projects. The default SVG images will be shipped as placeholders.

@mceledonia can you add the SVG file here to be used for this implementation?

**Comment by mceledonia** [comment]
@mattnolting Here's the SVG and screenshots showing position in both login + about modal.
- Background color is `#151515` or `--pf-global--BackgroundColor--dark-100`

![image](https://user-images.githubusercontent.com/30935938/213002057-0c2556a4-2160-4c65-9c78-3ffbd45b8966.png)
![image](https://user-images.githubusercontent.com/30935938/213002085-f02c218c-3477-408f-8a6c-31b528c8a8ec.png)
