### ISSUE TITLE
Alert - Combine documentation for Alert and Alert Group

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#5323]
Combine Alert and Alert Group into a single component called Alert. Alerts groups are just containers for alerts so it makes sense to reorganize these to include a coordinated set of examples.

**Comment by mcarrano** [comment]
@mcoker @srambach I started to look at this issue and had some questions about how to proceed with combining documentation in the core docs. I think whatever we decide would apply to this issue and also to combining Chip/ChipGroup and Label/LabelGroup.

I'm looking at the HTML pages on the website and looks like our general convention is to start with a section labeled "Examples" and then follow with a section labeled "Documentation." Is that right? I guess my main question is whether it makes sense to just append the two pages together and still keep Alert Group distinct or integrate the docs more. So the outline could be...

Option 1:

Alert
  Examples
  Documentation
Alert Group
  Examples
  Documentation 

Option 2:
Examples (combined set of examples)
Documenation (combined documentation)

For reference, here's the PR I've put put on the React side: https://patternfly-react-pr-8930.surge.sh/components/alert Let me know your thoughts.

**Comment by srambach** [comment]
I tend to fast scroll to the bottom if I'm looking for documentation, so option 2 would probably be my personal preference. I think it would be fair to split documentation though - could we do:

Alert examples (maybe link to documentation for alert at the end of this)
Alert group examples
Documentation for alert
Documentation for alert group
CSS Variables (combined)
