### ISSUE TITLE
Label Group - Add enhancements to use in place of Chip Groups

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#5344]
**Describe the feature**
We want to deprecate the chip group in favor of using label groups for current use cases. This will require some minor updates to the Label group as follows:

* Add a Compact label group variation. This is intended to use compact labels and adjusts the height of the group to the shorter label size.

* Update the border color/thickness to be more prominent. 

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**

![Screenshot 2023-01-20 at 3 36 37 PM](https://user-images.githubusercontent.com/6619860/213800866-7c972ddf-786b-4f71-aeb5-c85eb8dbe3df.png)

(https://www.sketch.com/s/d7e287f4-39e3-4c17-a302-2131d8f3ea87)

**Any other information?**

**Comment by kmcfaul** [comment]
Will be closed with #5346
