### ISSUE TITLE
Select - Update multi-select to use label group in place of chip group

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#5345]
**Describe the feature**
We are deprecating the chip group so want to use the new compact label group in applicable components when it is used to represent multiple selections.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**

![Screenshot 2023-01-20 at 3 33 41 PM](https://user-images.githubusercontent.com/6619860/213800414-8e30f20d-1da6-47b7-8228-aebdf341eb0a.png)

https://www.sketch.com/s/d7e287f4-39e3-4c17-a302-2131d8f3ea87/a/bg7PO7V

**Any other information?**

**Comment by kmcfaul** [comment]
Closed by #6532
