### ISSUE TITLE
Button - expand "inline" support to other variants

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5351]
The problem - we have super small buttons across components that are either
* not using the PF button component
* are using the PF button component but the padding/size is customized in each component

Some examples:
* [form help popover button](https://www.patternfly.org/v4/components/form#basic) - doesn't use PF button
* [label close button](https://www.patternfly.org/v4/components/label#filled) - uses a modified PF plain button
* [text input group close/utility button(s)](https://www.patternfly.org/v4/components/text-input-group/html#utilities-and-icon-with-placeholder-text) - uses a modified PF plain button
* [tabs help/close actions](https://www.patternfly.org/v4/components/tabs#help-and-close-actions) - uses a modified PF plain button

Looking at the [WCAG spec on target size](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html), there are cases for buttons that do not have minimum target sizes with a specific callout for help icons or icons that flow with sentences and could wrap with the text and throw off the size/spacing of the text around it.

Right now, `.pf-m-inline` only applies to "link" buttons, and it basically makes a link button look like a link/anchor. I don't know if we would try and expand that variation, or possibly create a new variant, I think at a minimum, there is a case for an inline plain button where the font-size is inherited and either padding is removed or minimal padding is added so that it doesn't exceed the line-height of adjacent text of the same size.

cc @srambach @mceledonia

**Comment by andrewballantyne** [comment]
bump @mcoker -- let us keep this ticket alive.

cc @nicolethoen we talked about this at the last PF Office Hours. I'd like to see something done here so we don't have to override PF. I really want to see PF as the source of truth to building our app and not have to write custom styles to make it do what we need.
