### ISSUE TITLE
Update script that finds modifier classes

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#538]
re: https://github.com/patternfly/patternfly-next/issues/398

* get classes from
   * compiled CSS instead of SCSS
   * code docs (code.md)
* update regex to include numbers, and things like `.pf-m-offset-#{$col-num}-col#{$suffix}` if possible.
* add modifiers to the website output from classes that are in CSS and docs.
* generate a warning for classes that are either in CSS but not docs, and vice versa.
* can we add this to the standard dev workflow, when you commit or submit a PR, so that the list of modifiers is updated and you're alerted of modifiers that are either in CSS and not docs, or vice versa?

We need to add a blurb about usage of modifier classes to the list on the website, too. The format should follow the table at the bottom of the [contribution page](https://pf-next.com/contribution).
* Would it be possible to create an file/object of some sort of known modifier classes and a blurb about it's use, and as the script runs that finds modifier classes, it references that object and builds a table for the website with the modifier class and the usage blurb?
   * Is there a better way to do that making the process as automatic as we can?
   * Could this spit out a warning if it finds valid modifier classes but there is no blurb about usage?

cc @andresgalante

**Comment by redallen** [comment]
Could this issue be updated @mcoker ? [The script](https://github.com/patternfly/patternfly-react/blob/master/packages/react-tokens/scripts/generateTokens.js) that grabs classes and CSS variable values has been updated multiple times.

**Comment by mcoker** [comment]
@redallen the original intent behind this was to populate `/modifiers` in the core docs with a list of all of the library's modifier classes, providing a reference to encourage consistency. Personally, I don't find that particularly helpful, so I'm in favor of removing the page unless others find it useful.

The [modifiers script](https://github.com/patternfly/patternfly/blob/master/scripts/extractModifiers.sh) also has to be run manually, and the [list of modifiers](https://github.com/patternfly/patternfly/commits/master/src/site/pages/modifiers.md) hasn't had a meaningful update in nearly 2 years. I guess the question is if we think it would be helpful if it were run regularly (as part of the build?), and maybe also if the list were more descriptive.

wdyt @christiemolloy @mattnolting @mceledonia @mcarrano? Also @srambach, I believe you were in favor of this at some point.
