### ISSUE TITLE
fa-check-circle (f058) won't render with color

### ISSUE THREAD

**Issue by Chr1st1anSears** [patternfly/patternfly#5415]
When I used the [fa-check-circle icon in this PR](https://github.com/redhat-appstudio/docs.stonesoup.io/pull/15/files#diff-6ad93ccb0d496c8be0ce27b202cabfd31dc6963e4ff60889f478653cf3f55264), it came in without the green coloring that it's supposed to have.

I tried using the SVG from patternfly.org and linked to it in [this asciidoc document](https://github.com/redhat-appstudio/docs.stonesoup.io/pull/15/files#diff-b4a6a456de3d2cd21bc7006d15dc9178ccf7474147d08d3c5eff661810d6998f). I wrote the doc in VS Code running on a RHEL CSB machine.

For now, this doesn't create a huge issue with the doc, but it'd be great to have the correct coloring as soon as possible.

Thank you.

**Comment by mcoker** [comment]
Hey @Chr1st1anSears! Looks like you have `fill="var(--pf-global--success-color--100)"` in place, which is great. https://github.com/redhat-appstudio/docs.stonesoup.io/blob/e9a822929341cc0fa661584a9a7033430692d510/docs/modules/ROOT/images/success_icon.svg#L2

However, that relies upon the custom property `--pf-global--success-color--100` being available in the scope you're using the icon. By default, our `--pf-global--*` custom properties are scoped to `:root` (the same as `<html>` on your page), so as long as you're importing the global properties the standard way, I would expect this variable to be available.  Can you tell me more about how you're using/importing the global vars in your app?

If you're unsure about the custom property being available on the page, you can always use the value of `--pf-global--success-color--100` as a fallback in your `var()` declaration, like `fill="var(--pf-global--success-color--100, #3e8635)"`. However, if you're using patternfly react, you can import the [token for success-color--100](https://unpkg.com/browse/@patternfly/react-tokens@4.94.6/dist/esm/global_success_color_100.js) and build that `var()` dynamically, which will ensure you're using the right fallback value (`#3e8635` above) in case we end up changing that for some reason.

Something like:

```
import iconSuccessColor from '@patternfly/react-tokens/dist/esm/global_success_color_100.js';

<svg fill="var({iconSuccessColor.name}, {iconSuccessColor.value})"
```

**Comment by Chr1st1anSears** [comment]
Hey @mcoker, thanks for your help! Adding #3e8635 like you suggested worked!
