### ISSUE TITLE
Accordion - variant with toggle on the left

### ISSUE THREAD

**Issue by mgrabovsky** [patternfly/patternfly#5426]
**Is this a new component or an extension of an existing one?**
An extension to the [accordion component](https://www.patternfly.org/v4/components/accordion).

**Describe the feature**
Add the possibility to display the accordion toggle on the left side of the header, as in the [expandable section component](https://www.patternfly.org/v4/components/expandable-section), rather than on the right as is the default now.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
My quick mockup:
![Screenshot 2023-01-30 at 18-19-26 🚧 New test results CI Dashboard](https://user-images.githubusercontent.com/134321/215548918-14022916-2b07-4e02-8d7b-69cbda0443fd.png)

**Comment by mcarrano** [comment]
@andrew-ronaldson @srambach this is one that we should look at getting on the roadmap to allow for an alternate variant of the Accordion.

**Comment by mcoker** [comment]
cc @thatblindgeye
