### ISSUE TITLE
Helper text - make status icon required for status variants

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5438]
Warning, success, and error should include the status icon by default. We'll want to:

* Update the helper text component examples and demos to add those icons.
* Update the docs to indicate the icon is required with a status variant.
* Update any other component examples/demos that use helper text to ensure they have an icon if a status is set
  * Looks like we already have params for `--Is[Status]` and also `--IsDynamic` (icons are also required for dynamic items), and icons are included with `--HasIcon`, so I'm thinking we can just test for `--Is[Status], --IsDynamic, --HasIcon`, and include the icon automatically if any are set. One way to do that is with the concat helper like `{{#if (concat --IsError --IsWarning --IsSuccess --IsDynamic --HasIcon) }} {{> icon}} {{/if}}`. Then we just need to review our uses of helper text in all of the component docs and make sure we're indicating status via those params.

**Comment by nicolethoen** [comment]
We are no longer requiring an icon on helper text
