### ISSUE TITLE
Remove status icons from form control components

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5439]
The problem with those icons, since they are background images to browser rendered form elements:
* https://github.com/patternfly/patternfly/issues/2702 - browsers stomp on custom background styles for these elements in ways we can't override
* https://github.com/patternfly/patternfly/issues/4652 - content security policies disallow data URIs as the source for images in markup
* https://github.com/patternfly/patternfly/issues/4900 - due to the way we import sass vars, the default/light theme form control icon is the wrong color currently.

Met with the team and we decided the icon in the form control component should be moved out of that element and into the helper text instead. This update should remove the use of background images from the form control component.
  * The exception here may be the form select arrow, since it is also created from a FA icon as a background image. I think we should remove it and get away from trying to style that directly on a browser rendered element until there is better support for customizing these elements, or we suggest the use of our select component.

Related:
Here's the core issue for updating the helper text component - https://github.com/patternfly/patternfly/issues/5438
And the related react issue - https://github.com/patternfly/patternfly-react/issues/8863

**Comment by srambach** [comment]
@mcarrano I think this is saying to also remove the caret from our **native form select**, because it has the same problem with the background image. Then there won't be an indication that it's a dropdown. I just want to verify that's ok. https://www.patternfly.org/v4/components/form-control#select (NOTE: this is **not** our React select component https://www.patternfly.org/v4/components/select)

**Comment by srambach** [comment]
The caret and custom icons are also background images and will cause the same problems that I understood to be causing a problem with the new work that @mcoker is doing. The caret will still be on the custom select component that we have created. We may need confirmation from @mcoker about whether we need to remove all background images on a input controls.

**Comment by mcarrano** [comment]
Thanks for the explanation @mcoker . I guess that the solution we have for removing the background images works for the case of field validation, but not sure we have a solution for other use cases. Sounds like we are talking about:

- Form selects
- Number inputs
- Fields that have a custom icon like a date or time picker field. 
- Anything else?

What does this mean for things like the [Time picker for example](https://www.patternfly.org/v4/components/time-picker#basic-12-hour) that places a clock icon in the field. Do we loose that? We can revisit the design for each of these components. But I'm concerned about adding scope at this point. Do you think this is a problem we could continue to live with in the short term?

**Comment by mcoker** [comment]
@mcarrano that should cover it, but as far as I can tell, it's just the form select caret, time text input, date text input, and the status/validation icons. How would number inputs change? As far as I can tell, we are not adding icons to number inputs.

I can't find anywhere that we're using the calendar text input in a component. The date picker component uses an input group to add the calendar icon as a button that triggers the calendar picker - https://www.patternfly.org/v4/components/date-picker

We are using the time text input in the [time picker component](https://www.patternfly.org/v4/components/time-picker).  A couple of things we could do there instead are use the [text input group](https://www.patternfly.org/v4/components/text-input-group#utilities-and-icon) or a menu toggle with typeahead and an icon, which is probably more appropriate since it is a dropdown/select. That would just use the text input group under the hood, here's a demo - https://codesandbox.io/s/flamboyant-galileo-y4ihss?file=/index.tsx

**Comment by mcarrano** [comment]
@mcoker I think that the solution you propose for the Time picker works. For the Number Input, we're talking about this example: https://www.patternfly.org/v4/components/number-input#with-status I suppose we could rework this to place the status in helper text vs an embedded icon like this?  What would the solution be for a form select?

I'm concerned about the need to make these changes as we approach a code freeze. Should I assume there would be some React follow-up? What is the impact of doing nothing? Will it be any worse than it is today with PF4? If not, I might vote to defer this.

cc @nicolethoen

**Comment by srambach** [comment]
> As far as I can tell, we are not adding icons to number inputs.

There are number inputs with status and it makes space and puts in an icon.
https://www.patternfly.org/v4/components/number-input#with-status

**Comment by nicolethoen** [comment]
Rewriting the TimePicker to use the TextInputGroup under the hood sounds preferable, and will take a _little_ bit of effort on the React side.
I think reworking the NumberInput might be even slightly more significant, though I am not as familiar with that components inner workings. @tlabaj would know more. 
I don't think the React team is a stretched for time as core right now, so it feels feasible. WDYT, @tlabaj

**Comment by mcoker** [comment]
Oh gotcha re: the number input. I was under the impression that anywhere a form control is used now, it will not convey status via the icon and helper text (or some equivalent) will need to be used. So that would apply to the number input as well, since it's basically a pre-built input group with a form control and buttons. If the number input is used within a form, helper text can be applied since it can apply to any control used in a form. If it's outside of a form, the helper text would need to be applied manually - but that applies to the other form control elements we're updating, too (text input, etc).

One solution to the number input could be to add a helper text element to it, and allow the helper text component to be passed if the number input has status and is used outside of the context of a form. This would mimic the progress and date picker components. 

If we end up keeping the icons in these form elements, we just need to work on how the icons' colors are assigned. It's currently broken in pf4, and theming them (for our internal themes and for users) will likely be a bit complicated and require a manual intervention since a PF var like "--pf-global--status--success/warning/etc" doesn't work with a background image.

**Comment by srambach** [comment]
So, to summarize, does this look like a good path forward @mcarrano @mcoker @nicolethoen @tlabaj ?
- Form inputs: remove status icons (this issue)
- Form inputs with custom icons: use input group (remove custom icons in this issue; add demo on the input group?)
- Number inputs: add a helper text element, same as progress and date picker (remove icons in this issue; needs core and React issues to add helper text element)
- Time picker: Change to use a text input group as the date picker does (React issue needed)

I think one question remains:
- * Form selects: leave the caret as a background image for now? Or can we remove the caret and recommend use of the select component for visual consistency?

**Comment by mcarrano** [comment]
@srambach I am good with this. I can work up an example of what the number input should look like with helper text instead of a warning icon inside the field.

As for the Form selects -- can we keep the caret as a background image? I'd also be OK to recommend use of our custom select and deprecate Form Select. Is there a reason we need to have Form Select as a unique component? It only causes confusion about what to use.

**Comment by mcarrano** [comment]
Here is what the revised Number input should look like with helper text instead of an embedded icon:

![Screenshot 2023-04-03 at 9 33 45 AM](https://user-images.githubusercontent.com/6619860/229599993-56023658-989c-41d6-980a-55e380859778.png)

@mceledonia @mmenestr @lboehling wanted to also make you aware of this issue. The summary is that we will no longer embed an icon inside of form fields or similar controls for validation for v5. We should also make updates to the Sketch Kit and design docs for consistency. Please review any places that might need updates and open issues as needed. See the list from @srambach above for affected components.

**Comment by lboehling** [comment]
added design kit issue here: https://github.com/patternfly/patternfly-design-kit/issues/614

**Comment by srambach** [comment]
Here's a thought - since we only are worried about the caret for the select, what if we add it as the :after with the trick of using the border?
https://codepen.io/srambach/pen/yLRBdQp
I _think_ the select has to be wrapped; I can't get it to work otherwise, but seems like it could be a possibility?
@mcoker @mcarrano @thatblindgeye @mattnolting

**Comment by mcarrano** [comment]
@srambach it's a bit odd that the caret is not clickable but the field is. But I suppose we could live with this as a compromise. Does this solve your dark theme issue @mcoker ? Also, can there be a cursor change when hovering over the interactive area? That would be helpful.

**Comment by mcoker** [comment]
Yep, that solves the dark theme issue since we're no longer using a background image that requires a color update for theming for the caret. Although FWIW if we can update the form control elements to have a wrapping element, that potentially allows us to include icons in these form control elements as we would with any other component - meaning we can include regular icons from pf-icons/react-icons/FA for status, the caret, etc. That's effectively what the text input group is - it's a wrapper around a text input that lets us put icons, navigation elements, etc in the component and it appears as if they're inside the text input element.

@mcarrano @srambach I updated the codepen. Namely I'm keeping all of the existing styles on the select, positioning the pseudo using our existing vars that position the background elements, and removed click events from the pseudo icon so you can click on it and the click event will happen on the select underneath. Also colored the pseudo icon red, to show its position relative to the existing icon in the select. It's also worth noting we aren't using an icon with this approach - we're creating an inverted triangle shape by manipulating borders.

**Comment by mcarrano** [comment]
This is great, @mcoker !
