### ISSUE TITLE
TreeView - Override MaxNesting

### ISSUE THREAD

**Issue by ctron** [patternfly/patternfly#5452]
**Is this a new component or an extension of an existing one?**

`TreeView`

**Describe the feature**

Currently the tree view maxes out at 10 levels. Yes, sometimes we need more.

In the .scss file, it is defined as:

```scss
$pf-c-tree-view--MaxNesting: 10;
```

See: https://github.com/patternfly/patternfly/blob/7ddc2de5cfb96f204e62730878a9e77bed64b998/src/patternfly/components/TreeView/tree-view.scss#LL1-L1C33

It would be great if this could be overridden. To my understanding, it should be possible with:

```scss
$pf-c-tree-view--MaxNesting: 10 !default;
```

**Comment by srambach** [comment]
This should be a non-breaking change. This variable is used to loop to make the nested styles and calculate indentation necessary for the tree levels. Increasing this variable will increase the size of the compiled css.

**Comment by mcarrano** [comment]
We can update to allow override. We will address after the PatternFly v5 release
