### ISSUE TITLE
Bug - Table stick column borders disappear

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly#5453]
Cost Management shows a skeleton while loading data, in addition to a composable table with sticky columns. After loading, the skeleton is replaced. Typically the table looks fine, except when the page is zoomed out. In this scenario, the table's sticky column borders disappear upon a page refresh.

**Demo:**
https://user-images.githubusercontent.com/17481322/227370670-172ac296-c864-497c-afd6-933c6956a520.mov

**Simple test to replace page content**
![Screenshot 2023-03-23 at 5 38 56 PM](https://user-images.githubusercontent.com/17481322/227370841-858a3189-0a8f-4c81-beeb-4d025662ec42.png)

**Composable table code**
https://github.com/project-koku/koku-ui/blob/main/src/routes/views/explorer/explorerTable.tsx#L336

**Comment by mcoker** [comment]
@dlabrecq can you confirm if this is still an issue? If so do you mind creating a codesandbox that reproduces the bug?
