### ISSUE TITLE
Menu with icons alignment off

### ISSUE THREAD

**Issue by Misjohns** [patternfly/patternfly#5545]
The space between the icon and menu item appears off when the user changes the width of their screen. Looks like the menu item is centered instead of flush left.

![image](https://user-images.githubusercontent.com/97301019/236931990-421a57ea-32b7-46f3-9fe6-763ff3ee5229.png)

![image](https://user-images.githubusercontent.com/97301019/236931943-872159f9-4a89-48f1-a27b-595aa7a67de5.png)

**Comment by mcoker** [comment]
@christianvogt @Misjohns if this is with the dropdown component, this has since been fixed and will be available in our upcoming major release:

https://github.com/patternfly/patternfly/issues/4894
https://github.com/patternfly/patternfly/pull/5425

**Comment by christianvogt** [comment]
@mcoker that does look to be the same issue. Feel free to close this.
