### ISSUE TITLE
Update - Content element styling

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#5548]
**Describe the problem**
Content elements should be assigned classes. 

- Elements with specificity of 11 must retain that value. 
  - `el.pf-c-content__{h1, h2, h3, h4, h5, h6, p, ul, dl, small, etc}`
  - Ensure content functionality is unchanged

**Comment by mcoker** [comment]
dupe of https://github.com/patternfly/patternfly/issues/5966
