### ISSUE TITLE
[all] - [RTL _ Use logical properties and values for controlling the layout]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#5555]
Physical dimensions and directions are described left to right and top to bottom, while their logical counterparts are described start to end and inline or block.

Using the latter has the advantage that UIs will be corrently auto-adjusted for RTL languages. Patternfly so far uses the physical properties.

https://www.w3.org/TR/css-logical-1/

This will be fix of a big percentage of problems that Patternfly has regarding RTL support. 

You can use the stylelint plugin [0] to autoconvert a big part of the fixes. 

I suggest that you first: 

* [ ] stop introducing properties the 'old' way
* [ ] convert the existing codebase little by little or how you feel confortable to use the logical properties

Note that this should haveno impact on LTR users, while massively improving the experience of RTL.

[0] https://www.npmjs.com/package/stylelint-use-logical-spec

**Comment by mcoker** [comment]
This is done and can be see on the main branch.
