### ISSUE TITLE
Select component empty state handling

### ISSUE THREAD

**Issue by heyethankim** [patternfly/patternfly#5574]
## Requesting new features, enhancements, or design changes to PatternFly

When the options in the [select component](https://www.patternfly.org/v4/components/select/react-next/) are already available, it is very straightforward.

But what if the options are generated by user? For example, in the ACM ApplicationSet creation wizard, “Argo Server” is empty at first. If we know it is empty at first, we should provide a different experience.

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/84546841/236473692-fbec44bf-8be9-4c00-98d7-a54c00a91a85.png">

**Comment by mcarrano** [comment]
Converting for more discussion...
