### ISSUE TITLE
Nav - group spacing is off

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5592]
Small bug left from https://github.com/patternfly/patternfly/pull/5507

<img width="322" alt="Screenshot 2023-05-17 at 8 40 11 PM" src="https://github.com/patternfly/patternfly/assets/35148959/323f14dd-2f5b-4632-baf8-afcda381fe44">

**Comment by mcoker** [comment]
Looks like this is causing the `margin-top` to extend outside of the parent, so the top "padding" isn't visible in the list. Isn't CSS fun?!?! 😂

<img width="291" alt="Screenshot 2023-05-26 at 12 28 48 AM" src="https://github.com/patternfly/patternfly/assets/35148959/d826986e-504f-4f9f-a3d3-f6158a07cf10">
<img width="357" alt="Screenshot 2023-05-26 at 12 28 53 AM" src="https://github.com/patternfly/patternfly/assets/35148959/ce7d9c54-791e-4411-976c-d338a8458a3b">

**Comment by thatblindgeye** [comment]
@mcoker do you recall if the spacing issue was only on the grouped nav without titles? If that's the case I can apply the alternative of updating the CSS within the `pf-m-no-title` selector instead per my comment in the PR, or revert the margin-top in the current PR back to padding-top and remove that padding from a nav list that has the `pf-m-no-title` and is a sibling of another nav list (to retain the first nav list spacing).
