### ISSUE TITLE
Input group - display flex on item can cause issues with multiple items in item

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5593]
https://github.com/patternfly/patternfly/blob/5f8e339a476f578c6d9fdb1fd809f178a9b94e75/src/patternfly/components/InputGroup/input-group.scss#L47

I think it's fair to allow someone to use some sort of _form element type of thing_ and have something like helper text underneath it (just as an example), and the flex layout is going to break that.

Unless we're using flex intentionally for some other reason, looks like this may only exist so we can use `align-items` on the `__text` element? https://github.com/patternfly/patternfly/blob/5f8e339a476f578c6d9fdb1fd809f178a9b94e75/src/patternfly/components/InputGroup/input-group.scss#L85

I think it would be best if the item is just a regular element, and we can center the text element some other way.

**Comment by thatblindgeye** [comment]
It looks like the display flex is also making all items in a group retain the same height (buttons with a text area):

![Input group with buttons and textarea](https://github.com/patternfly/patternfly/assets/70952936/d810ca25-141a-46d8-aa82-66cf1bf7f527)

(though maybe adding a `pf-m-full-height` class or some such to the button to alter the `height` could work? Things like a select/dropdown toggle using the MenuToggle component already has that ability)

At least in terms of adding helper text to an InputGroupItem, that may end up causing some cramped helper text depending on the width of the InputGroupItem. The inputs in the [Input Group examples](https://pf5.patternfly.org/components/input-group/) are typically wide enough, but if a helper text were to be placed on a Select for some reason it could be rather cramped. For something like that I'm wondering if it'd just be better to place helper text after the entire InputGroup rather than as a part of an individual InputGroupItem.

**Comment by mattnolting** [comment]
@mcoker I think @thatblindgeye's inclination makes most sense. Setting `display: flex` on `.pf-v5-c-input-group__item` allows its any children to adjust to full height of `.pf-c-input-group`. Without it, we would either need to add a modifier or set direct children to `height: 100%`. I'd vote for using a layout with helper text. 

<img width="1144" alt="Screenshot 2023-05-25 at 4 48 44 PM" src="https://github.com/patternfly/patternfly/assets/5385435/26af34f9-46a0-431c-82f0-5fa00e2431c1">

**Comment by mcoker** [comment]
Yeah that's a great point re: the height, though I wonder if we ever actually want buttons or dropdowns or whatever form elements are placed beside of a textarea element to grow that way. I know it's in our examples, but it seems like it could be a bit unpredictable. Tagging @mceledonia @mcarrano @andrew-ronaldson to see if that's a use case we want to support. It won't always work predictably, either - here's the select from another example moved beside a textarea. Though it would work with a menu toggle, I imagine there are other gotchas like this.

<img width="1083" alt="Screenshot 2023-05-25 at 11 21 33 PM" src="https://github.com/patternfly/patternfly/assets/35148959/f5b0ddf3-c4ba-4e31-a07c-a4d276fdebe4">

re: helper text, I agree, but we have a demo in the v5 workspace for a use case we support with helper text in the date picker, and that was the preferred way to handle error/status text for some form element in a toolbar (could be a text input or whatever), which is what made me think of the potential issue here.

<img width="1574" alt="Screenshot 2023-05-25 at 11 30 34 PM" src="https://github.com/patternfly/patternfly/assets/35148959/a85e4089-9c10-4275-9c9e-189316149524">

**Comment by mcarrano** [comment]
> I wonder if we ever actually want buttons or dropdowns or whatever form elements are placed beside of a textarea element to grow that way. I know it's in our examples, but it seems like it could be a bit unpredictable.

I don't see a case where we need to do that. Do you @andrew-ronaldson or @mceledonia ?  It's not something I've ever seen in a design.

**Comment by andrew-ronaldson** [comment]
Agreed @mcarrano I can't think of a case where that is needed.

**Comment by mattnolting** [comment]
From an a11y perspective, if a user were to zoom-in/increase font-size, it would result in this and layout breaks. Also present  

![Screenshot 2023-06-01 at 11 44 53 AM](https://github.com/patternfly/patternfly/assets/5385435/8818a136-14c3-469d-97f6-085b0c0d1f85)

![Screenshot 2023-06-01 at 11 50 13 AM](https://github.com/patternfly/patternfly/assets/5385435/31037f56-4544-4272-9d87-ee611540a686)

I think it's best to leave the items flexed and consider adding an element `(row, container, content)` to enable layout/placement of helper text. Additionally, we could add modifier to `un-flex` items. @mcoker @mcarrano @andrew-ronaldson WDYT?

![Screenshot 2023-06-01 at 12 10 48 PM](https://github.com/patternfly/patternfly/assets/5385435/65ca4297-d1ff-40ef-a13a-91e7903c7985)

**Comment by mattnolting** [comment]
Closing in favor of https://github.com/patternfly/patternfly/issues/5642
