### ISSUE TITLE
Spike - assess/reorganize variable documentation between core and org

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5601]
This issue is to track planning and possibly implementation of consolidating the global variable and other documentation that exists on core with what is on .org.

Link to slack thread in #pf-scrum https://patternfly.slack.com/archives/C03LQ25DDLN/p1684351754657699

https://pf4.patternfly.org/guidelines#variables
https://github.com/patternfly/patternfly-org/tree/main/packages/documentation-framework/pages

**Comment by srambach** [comment]
I matched up the various documentation pages that are on the workspaces to the new V5 documentation in [this spreadsheet](https://docs.google.com/spreadsheets/d/1A_RHUkfZkeFikO5FASquHjFe8kKlSSCDMg42alh5qoM/edit?usp=sharing).

My recommendations for the Core workspace are:
- Remove "Accessibility" from the top nav and remove https://github.com/patternfly/patternfly/blob/v5/patternfly-docs/site/pages/accessibility-guide.md because that information is newer and broken up into sections in .org
- Rename [Contribute](https://github.com/patternfly/patternfly/blob/v5/patternfly-docs/site/pages/contribution.md) to be a link from the readme called "Handlebars guidelines"
- Also in [Contribute](https://github.com/patternfly/patternfly/blob/v5/patternfly-docs/site/pages/contribution.md), separate the instructions for adding a custom icon to core into a new file also linked from the readme as "Add a custom icon"
- Move [Guidelines](https://github.com/patternfly/patternfly/blob/v5/patternfly-docs/site/pages/guidelines.md) to be a link from the readme called "CSS/Sass guidelines"
- Remove "Upgrade guide" from the top nav and remove outdated [Upgrade guide file](https://github.com/patternfly/patternfly/blob/v5/patternfly-docs/site/pages/upgrade-guide.md) **question, does this icon info exist elsewhere and/or is it still valid? **
-  Question: The icons pages are different between org, core workspace, and react workspace. Are all valid for their context or is there a disconnect?

Recommendation for React workspace:
- Move Release notes from the "Developer resources" section to a "Get started" section to remain consistent with .org

**Comment by mcarrano** [comment]
> Question: The icons pages are different between [org](https://dpu07u5c4ng26.cloudfront.net/v4/design-foundations/icons), [core workspace](https://pf5.patternfly.org/icons), and [react workspace](https://patternfly-react-main.surge.sh/icons). Are all valid for their context or is there a disconnect?

@srambach Yes, it is true that these are different and this is sometimes confusing. The React icons are really a superset of PatternFly icons as they include all of the PatternFly icons plus everything in Font Awesome. The core icons are all of the PatternFly unqiue (pf-icon) icons, and the Icons page on the website includes these plus a curated set of Font Awesome icons that we recommend for use. I'm not sure if there is a better way to expose this information, but essentially the Icons page on the website is our recommended icon set. Does that help?

Regarding the recommendations for linking to the core contribution guidelines from .org, we do have this page on the website: https://www.patternfly.org/v4/contribute/develop Is that page up to date and useful? If not, it would be simple to update.

**Comment by srambach** [comment]
> Regarding the recommendations for linking to the core contribution guidelines from .org, we do have this page on the website: https://www.patternfly.org/v4/contribute/develop Is that page up to date and useful? If not, it would be simple to update.

@mcarrano Yes - https://www.patternfly.org/v4/contribute/develop/ has a link to https://github.com/patternfly/patternfly#guidelines-for-css-development (which is the core readme.md file) which is where I am proposing to link those two files from.
