### ISSUE TITLE
Bug - [FormSelect] - [The caret of the FormSelect has different color than the caret of the Select component]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#5604]
See the form select caret being grey-ish https://patternfly-react-v5.surge.sh/components/forms/form-select#basic whilst the caret on menus is black.

This is problematic as in forms these two are used next to each other sometimes.

Also the position of the caret moved a bit to the right, causing the same issue of misalignment when selects and form-slects are used one after another.

See the two selects together here for comparison:
https://codesandbox.io/s/flamboyant-booth-qcbpge

Expected is that the carets align in position and color.

**Comment by thatblindgeye** [comment]
This looks like it's resolved from the Core side, possibly just React needing to take in the latest alphas. When running Core locally this is what it looks like using a FormControl `select` vs a PatternFly Select component:

![FormControl select vs Select component](https://github.com/patternfly/patternfly/assets/70952936/e070b07c-271a-4ebf-9e13-3faab4b14760)
