### ISSUE TITLE
Core - add ability to retrieve component css vars only 

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#5620]
https://github.com/patternfly/patternfly-react/issues/9182 reported that v5 page sections need to live in a v4 page and they don’t seem to be playing nicely.

The consensus was that in general, a sub-component of one version should not be nested inside the main component that is a different version.

However, page and page__section are somewhat of a special case and apps might not have influence over their surrounding chrome.

One solution is to move all component variables to :root.
@mattnolting said he could deliver an option sass mixin that would deliver css variables for all components without associated styling.
Class names for the other version could be added manually.

@mattnolting suggested [this codepen](https://codepen.io/bobcatTaco/pen/KKGEvXB)

**Comment by srambach** [comment]
Summary of conversation:
[This issue](https://github.com/patternfly/patternfly-react/issues/9182) reported that v5 page sections need to live in a v4 page and they don’t seem to be playing nicely.

The consensus was that in general, a sub-component of one version should not be nested inside the main component that is a different version.

However, page and page__section are somewhat of a special case and apps might not have influence over their surrounding chrome.

One solution is to move all component variables to :root.
@mattnolting said he could deliver an option sass mixin that would deliver css variables for all components without associated styling.

@mattnolting suggested [this codepen](https://codepen.io/bobcatTaco/pen/KKGEvXB)
