### ISSUE TITLE
Bug - Modal - Disabled button in footer has no margin-right

### ISSUE THREAD

**Issue by skobyda** [patternfly/patternfly#5684]
Normally, button in the modal footer have the following margin-right applied to them:
```
.pf-c-modal-box__footer > .pf-c-button:not(:last-child) {
    margin-right: var(--pf-c-modal-box__footer--c-button--MarginRight);
}
```

However, that is not applied when Button is disabled, because disabled button gets wrapped in another `<div>` element:

![Screenshot from 2023-06-23 13-07-31](https://github.com/patternfly/patternfly/assets/42733240/37e1417f-06bd-419e-af0f-5aa9db31b9c0)

rendering `.pf-c-modal-box__footer > .pf-c-button` css selector invalid, and resulting in the the button with no margin-right:
![Screenshot from 2023-06-23 13-03-52](https://github.com/patternfly/patternfly/assets/42733240/da54f584-3e6d-4b39-8d6a-23c03bd8ad63)

**Comment by mcoker** [comment]
@skobyda thanks for bringing this to our attention. Considering what all is allowed to go into the footer, I think the modal component styling buttons in this way is pretty problematic as you've found. We have an action list component that gives you this basic button/action spacing - can you use that component here instead? Here's a demo - https://codesandbox.io/s/competent-morse-l26n4f?file=/index.tsx
