### ISSUE TITLE
Bug - [ToolbarItem] - [ToolbarItem label is not centered]

### ISSUE THREAD

**Issue by jelly** [patternfly/patternfly#5688]
**Describe the problem**

After upgrading from an old PF5 alpha release to a new one the `<ToolbarItem variant="label">` is no longer centered.

```
-    "@patternfly/patternfly": "5.0.0-alpha.53",
-    "@patternfly/react-core": "5.0.0-alpha.98",
+    "@patternfly/patternfly": "5.0.0-alpha.69",
+    "@patternfly/react-core": "5.0.0-alpha.127",
```

**How do you reproduce the problem?**

The problem can be seen on the [pf5 demo website](https://pf5.patternfly.org/components/toolbar#stacked-on-desktop) the label [used to be centered](https://www.patternfly.org/v4/components/toolbar#stacked-example).

Our [pixel tests show](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18823-20230626-090824-316dfa91-fedora-38/pixeldiff.html#TestTerminal-testBasic-header) a clear difference:

**Expected behavior**

The label is centered.

**Is this issue blocking you?**

Applied a css workaround:

```
div.pf-v5-c-toolbar__group {
  align-items: center;
}
```

**Screenshots**

![image](https://github.com/patternfly/patternfly/assets/67428/35a53cce-f70d-4712-8302-f4cf122e7b7f)

**What is your product and what release date are you targeting?**

Cockpit.

**Any other information?**

This might be related, although I am not 100% sure https://github.com/patternfly/patternfly/pull/5565 what I can see is that it seems to have had `align-items: center` before.

**Comment by mattnolting** [comment]
What we want to avoid is this:

![Screenshot 2023-06-30 at 11 05 54 AM](https://github.com/patternfly/patternfly/assets/5385435/b2834da8-f603-4e0e-bd17-48b2b5832e47)

I think that the default setting for `content/group/item` can be updated to `align-items: baseline` and checkbx/radio can be set to align-self center. I think that would solve most of the issues. @mcoker wdty?
