### ISSUE TITLE
Consume tokens in: Modal and About Modal

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5707]
[Figma design for Modal](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A34&mode=design&t=doZDRUaxE4vsn5dD-1)

[Figma design for About modal](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A18&mode=design&t=doZDRUaxE4vsn5dD-1)

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6042
