### ISSUE TITLE
Consume tokens in: Masthead and Navigation

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5712]
[Figma design for Masthead](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A33&mode=design&t=doZDRUaxE4vsn5dD-1)

[Figma design for Navigation](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A35&mode=design&t=doZDRUaxE4vsn5dD-1)
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/issues/6000
- [ ] https://github.com/patternfly/patternfly/issues/5999
```

**Comment by evwilkin** [comment]
Closed by #6004 && #6033
