### ISSUE TITLE
Consume tokens: Tabs and Jump Links

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5726]
[Figma design for tabs](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A46&mode=design&t=doZDRUaxE4vsn5dD-1)

[Figma design for jump links](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A30&mode=design&t=doZDRUaxE4vsn5dD-1)
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/issues/6188
- [ ] https://github.com/patternfly/patternfly/issues/6189
```

**Comment by wise-king-sullyman** [comment]
Closing as all tasks are complete.
