### ISSUE TITLE
Consume tokens: Single file upload and Multiple file upload

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5727]
[Figma designs for file upload](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A25&mode=design&t=boxqVg1hn5hO0weV-1)

- [x] #6209
- [x] #6210

**Comment by wise-king-sullyman** [comment]
Completed by #6209 and #6210
