### ISSUE TITLE
Consume tokens: Accordion and Expandable section

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5729]
[Figma design for accordion](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A3&mode=design&t=doZDRUaxE4vsn5dD-1)

[Figma design for expandable section](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A24&mode=design&t=doZDRUaxE4vsn5dD-1)

**Comment by wise-king-sullyman** [comment]
Closed by #6058 and #6063
