### ISSUE TITLE
Consume tokens: Tooltip and Popover

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5732]
```[tasklist]
### Tasks
- [ ] Tooltip tokens
- [ ] Popover tokens
```

[Figma designs for tooltip and popover](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A40&mode=design&t=boxqVg1hn5hO0weV-1)

**Comment by wise-king-sullyman** [comment]
Closed by #6064 and #6065
