### ISSUE TITLE
Consume tokens: Inline edit

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5736]
[Figma link for inline edit](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A29&mode=design&t=boxqVg1hn5hO0weV-1)

**Comment by evwilkin** [comment]
@lboehling just seeing @andrew-ronaldson 's comment above isn't addressed to anyone, maybe meant for you?

**Comment by andrew-ronaldson** [comment]
> @lboehling just seeing @andrew-ronaldson 's comment above isn't addressed to anyone, maybe meant for you?

Good call @evwilkin 

oops!

**Comment by andrew-ronaldson** [comment]
Closed by https://github.com/patternfly/patternfly/pull/6176#issuecomment-1888145020
