### ISSUE TITLE
Consume tokens: Wizard

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5742]
[Figma design for wizard](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A51&mode=design&t=boxqVg1hn5hO0weV-1)

**Comment by nicolethoen** [comment]
most of the wizard CSS is the same in the deprecated (react) wizard, so most of the deprecated wizard will be able to be themed for free. I'd advocate that it is worth the extra effort to ensure the deprecated wizard is fully theme-able, as that will give products more time to migrate away from the deprecated implementation. Moving away from the deprecated implementation is widely used and a complex migration story.

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6251
