### ISSUE TITLE
Bug - Context selector/perspective switcher in page sidebar

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5776]
This is our demo of a context selector in a page sidebar. https://pf5.patternfly.org/components/menus/context-selector/html-demos/context-selector-in-sidebar/

There may be a better way to create that example using our existing components (and we just need to update our example), but as that example is written, it isn't ideal because:
* `page__sidebar-body` needs `.pf-m-menu`. There is no react prop for that, so at a minimum, we need to create a react follow up for that
* We style the context selector component there explicitly - that's a deprecated component, so those classes are going to go away. At a minimum, we need to update those classes to style the menu toggle and add any necessary variations.
* Just FWIW, the context selector uses `.pf-m-large` and `.pf-m-page-insets`, and neither are available on the context selector.

This story is just to support having a migration path for dropping the context selector since it's deprecated.

cc @mturley 
related: https://github.com/konveyor/tackle2-ui/pull/1185

**Comment by andrew-ronaldson** [comment]
Here's an example of the perspective switcher in OCP. 
<img width="1285" alt="Screenshot 2023-07-27 at 3 30 12 PM" src="https://github.com/patternfly/patternfly/assets/28658548/d20244b8-6ec7-4116-afef-c48c780b760e">
<img width="304" alt="Screenshot 2023-07-27 at 3 29 57 PM" src="https://github.com/patternfly/patternfly/assets/28658548/a73f49b3-1104-4505-9b08-df612f8a50f1">

**Comment by mcoker** [comment]
@andrew-ronaldson we will need to revisit this for v6. The context selector has been dropped and the styles we had in place were based off of the v5 look/feel. Is this something you think we'll want to ship with v6, or add support for later? Do you know if we have any v6 designs that include a perspective switcher in the sidebar?

**Comment by andrew-ronaldson** [comment]
I created a [design issue](https://github.com/patternfly/patternfly-design/issues/1305) for this. Will get this one in the next sprint

**Comment by andrew-ronaldson** [comment]
As an update @bekah-stephens has worked on a [Figma mock](https://www.figma.com/design/6BEkpvTaAinsLUulMDFbWm/PF-Edge-Cases---bstephens?node-id=23-3685&t=r8vw1tuR1Lzb3CV3-0) using the menu toggle.

**Comment by andrew-ronaldson** [comment]
Design issue  https://github.com/patternfly/patternfly-design/issues/1305 completed

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6839
