### ISSUE TITLE
[Form] - Eliminate layout shift in forms

### ISSUE THREAD

**Issue by Nefcanto** [patternfly/patternfly#5777]
Since I'm not using PatternFly directly, I couldn't answer your questions.

I'm using Keycloak and they are using PatternFly.

When I want to log in using Keycloak, each error that is shown would push the content below it downwards. This is a layout shift and it's a bad UX.

I opened [an issue](https://github.com/keycloak/keycloak/issues/21901#issuecomment-1647812801) for them, and they guided me here.

Please eliminate this layout shift. Thank you.

**Comment by mcoker** [comment]
cc @andrew-ronaldson @mmenestr

**Comment by Nefcanto** [comment]
@nicolethoen that might work for a form that is small enough to be shown above the fold without needing scrolling. Yet for long forms that's extremely bad UX. I had that experience with Microsoft ASP.NET tech stack for many years. You fill out a form and it does not submit and you end up with errors being on top and the form being lengthy and you have to scroll up and down to figure out what's wrong.

**Comment by Nefcanto** [comment]
@nicolethoen our solution for this in our company is that we have increased the fields' vertical margin to accommodate the error/help messages. And when we show the error, its place is already there. Thus we see no layout shift. Another option is to show the error horizontally in front of the page.

Another option is to turn the border of the field red, and show it's error on hover. This is not good though, as the user needs to do extra work to fix the form.

**Comment by nicolethoen** [comment]
@Nefcanto totally understand the scenario you're describing. Your original issue mentioned that this behavior was being seen in a log in form, so I was pointing out that this was previously addressed in the case of a log in by by using the error message at the top as done in the linked demo.

It is not out of the question to increase the field's vertical margin/space to accommodate the error/help messages. This would still need to be primarily configured by the product developer, since error messages can vary in length and the amount of space needed cannot be predicted unless it is rendered on page load and then hidden with `visibility: hidden` on the error message itself.

**Comment by Nefcanto** [comment]
@nicolethoen theoretically you are right. But based on my personal experience (more than 17 years of programming now) I have not seen long error messages. I think a good UX should be brief. The long message should be the tip or help of the field. The error should be either related to the required state of the field, to the data being invalid in format, or to duplicate data, or stuff like that. All of those errors can be less than 50 characters.

**Comment by nicolethoen** [comment]
@Nefcanto I believe your generalization would be correct most of the time. Bear in mind that all of the PF components are intended to not only accommodate the most common use case, but also account for internationalization and incredibly complex use cases. Some error message don't only include 50 characters, but also elements such as links and icons. Some error messages can even be made expandable to reveal more information. 

Right now, the type of the children of the HelperText component, which composes the error message, is `React.ReactNode` meaning we are not limiting people who use these components to 50 character strings.

Another conversation I've been a part of is about the concept of 'change blindness'. When something has changed on the page, especially to communicate an error or a required action on the part of the user, we need to make sure that this change does not go unnoticed. The shift in the layout when error message have appears is actually something which is supported by trying to mitigate this phenomenon. Albeit, it most certainly can be jarring, especially if the shift is dramatic.

All that being said, this is still something you can enable a few different ways. I very quickly demonstrated a simple way to do so [in this codesandbox](https://codesandbox.io/s/avoid-error-message-layout-shift-zdyz2h). I hope that's helpful.
