### ISSUE TITLE
Bug - [Radio] - [Inline Radio button in FormGroup is rendered verticially ]

### ISSUE THREAD

**Issue by jelly** [patternfly/patternfly#5787]
**Describe the problem**

After the update to PF5 final, [checkboxes in a FormGroup](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1162-20230731-105656-63a50068-fedora-38/pixeldiff.html#TestMachinesNICs-testNICAdd-vm-add-nic-modal) are now aligned vertically instead of next to each other. I'm pretty confident this is caused by this [commit](https://github.com/patternfly/patternfly/pull/5700/files#diff-601dac91bce44671e202bba80bb2f3654e8051ff8cc0b0f0aa93164449c74601R21).

**How do you reproduce the problem?**

```
      <Form isHorizontal>
        <FormGroup isInline hasNoPaddingTop label="connection">
          <Radio name="system" label="system" />
          <Radio name="connection" label="connection" />
        </FormGroup>
      </Form>
```

PF4 sandbox  https://codesandbox.io/s/happy-robinson-dd677s
PF5 sandbox: https://codesandbox.io/s/lucid-cdn-7hf2ky

**Expected behavior**

I expect the Radio buttons to appear next to each other when the FormGroup has `isInline`

**Is this issue blocking you?**

Dropping `width: 100%` should do the trick

**Screenshots**

Old:

![image](https://github.com/patternfly/patternfly/assets/67428/882a7656-b5ed-4cd8-a9b1-84d756594730)

New:

![image](https://github.com/patternfly/patternfly/assets/67428/232f5852-0ad0-4ab4-b36d-a1634f2a6df7)

**What is your product and what release date are you targeting?**

Cockpit

**Any other information?**

**Comment by mcoker** [comment]
cc @mattnolting
