### ISSUE TITLE
Bug - Checkbox and Radio - Vertical misalignment

### ISSUE THREAD

**Issue by martinpitt** [patternfly/patternfly#5802]
**Describe the problem**
Checkboxes and radio buttons are not properly vertically aligned. This even looks differently broken in firefox and chromium.

We see this in Cockpit, they've  been broken for a while throughout the 5.0.0-alpha and 5.0.0-prerelease series, and it still affects 5.0.0 final.

**How do you reproduce the problem?**

The rendering on https://www.patternfly.org/components/forms/checkbox itself looks good. Click on the codesandbox examples for [Controlled](https://codesandbox.io/s/frwy6w?file=/index.tsx) or [Uncontrolled](https://codesandbox.io/s/psj3tk) and you see the issue right away.

With Firefox 115 the labels are too high:

![image](https://github.com/patternfly/patternfly/assets/200109/34fa880f-ce6a-47c4-ba0d-9c8d70ef7a84)

With Chromium 115 the labels are slightly too low (but almost good):

![chromium](https://github.com/patternfly/patternfly/assets/200109/aae13c30-8cd6-4086-8f40-213851e5ce8e)

(Sorry for the frame noise, screenshotting elements in chromium is utterly broken..)

The effect is somehow more pronounced in Cockpit, where the Chromium screenshot looks like this:

![chromium](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230731-042548-fd1e607f-fedora-38-networking/TestBridge-testBasic-networking-bridge-settings-dialog-pixels.png)

Firefox looks similarly misaligned on codesandbox and Cockpit.

**Expected behavior**

Checkboxes and radio buttons are centrally vertically aligned in all browsers.

**Is this issue blocking you?**

No, we have a workaround.

**What is your environment?**
 - OS: Fedora 38
 - Browser: Firefox 115, Chromium 115, @garrett also tested with webkit
 - Version: PatternFly 5.0.0 final

**What is your product and what release date are you targeting?**

https://github.com/cockpit-project/cockpit ; we release continuously, but try to keep PF up to date.

**Any other information?**

@garrett has found a [PF CSS patch](https://github.com/cockpit-project/cockpit/commit/9f84d9ac98238b10ce9e17fdfb1737c116113c4e) that works in all three major browser engines, see https://github.com/cockpit-project/cockpit/pull/19138#issuecomment-1658327885 for detailed results. That also fixes the curious issue that checkboxes have a different height in different environments. With that, checkboxes and radios are good enough, and we will land the PF update to 5.0 final with this patch applied.

**Comment by mcoker** [comment]
cc @mattnolting
