### ISSUE TITLE
Bug - [BackgroundImage, AboutModal] - [Background image size compatibility]

### ISSUE THREAD

**Issue by dpanshug** [patternfly/patternfly#5806]
**Describe the problem**
How can the new `<BackgroundImage />` component accommodate varying image aspect ratios? Previously, the 'src' attribute accepted images of all dimensions. Additionally, the ability to apply filter props to the component was available earlier, and its removal now appears somewhat unconventional.

I've identified another concern as well. It pertains to the dimensions of the background image within the `<BackgroundImage/>` and `<AboutModal/>` components. Presently, the background image is confined to the lower-right corner of the page, rather than spanning the entire page width as it did before.

**Expected behavior**
- The Background Image component should ideally be compatible with all image aspect ratios. Alternatively, if there are limitations in this regard, the component's documentation should explicitly outline the supported capabilities.
- The image should span through the entire page, rather than lower right corner.

**Is this issue blocking you?**
- Blocking to upgrade new patternfly 5

**Screenshots**
<img src="https://github.com/patternfly/patternfly/assets/97534722/dad3f05d-6b22-4f32-af09-66b90d77dc11" width="700px" height="100%" />
<img src="https://github.com/patternfly/patternfly/assets/97534722/7fec5a46-24cb-4283-801f-5a60d313153a" width="700px" height="100%" />

**What is your environment?**
 - OS: Fedora
 - Browser: Chrome

**What is your product and what release date are you targeting?**
- Infinispan console, 1st week September

**Comment by dpanshug** [comment]
This bug may be relates to #5328

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by mcoker** [comment]
Hey @dpanshug! Tagging @mattnolting who worked on this initially. Also tagging @andrew-ronaldson @mmenestr @lboehling on the design side.
