### ISSUE TITLE
Implement RTL: chip, label, and badge

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5819]

**Comment by thatblindgeye** [comment]
cc @mcoker @andrew-ronaldson in case you could get any insights for the above

**Comment by mcoker** [comment]
I _think_ the way it is (truncating at the start) is what I would expect, it's only truncating at the start because it's english. That would be the end of the text in an RTL language. So it still reads this way from right to left
* chip text
* [...]
* [close button]

**Comment by thatblindgeye** [comment]
Gotcha, that sounds good. In that case there shouldn't be any other updates needed for these components.
