### ISSUE TITLE
Implement RTL: switch, slider, spinner, skeleton

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5835]

**Comment by mcoker** [comment]
@andrew-ronaldson @srambach @thatblindgeye do you think the skeleton animation should go in the opposite direction?

**Comment by thatblindgeye** [comment]
I kind of want to say _I_ wouldn't expect it to, at least based on us not mirroring the direction of a spinner (since both represent an indeterminate loading state).

**Comment by mcoker** [comment]
I wasn't sure if the skeleton gradient moved LTR/RTL to indicate the reading direction or the passage of time. I assumed the passage of time. Just to confirm, this is what I'm referring to. I updated the gradient color so it's more obvious.


https://github.com/patternfly/patternfly/assets/35148959/5af1f792-9318-4a50-bf7c-9b0f3daef80f


https://github.com/patternfly/patternfly/assets/35148959/a3a21e60-52d8-4e31-9d1a-f84c9249fa4d

**Comment by andrew-ronaldson** [comment]
I sent this to Tal to give us his expert opinion.

**Comment by tobiastal** [comment]
Hey guys, IMO the skeleton animation should go according to the text direction. i.e. for RTL languages, it should go from right to left.
Especially when a text is loaded, having the right direction feels much more fluid, and reduces jumps when looking at the screen. We tend to look at the beginning of the loader and expect the information to load from there.
For images and other components on the screen, it's not that important, but for consistency, I think that we should change the direction.
