### ISSUE TITLE
Bug - Button - Icons dont seem to have appropriate padding before button text

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#5944]
![Screenshot 2023-09-18 at 12 07 36 PM](https://github.com/patternfly/patternfly/assets/26305082/4e8b4834-5ae1-4d98-b2b2-10d36f9390f1)

[view in codesandbox](https://codesandbox.io/s/ancient-browser-9mhx4r)

The space between the icon and the button text appears too small.

reported by Ansible (James Talton)

**Comment by srambach** [comment]
Note: this appears to happen because of a missing space character between the text and icon. The plan is to wrap the text in a container and apply a flex layout to the button.
