### ISSUE TITLE
Consume tokens in: Charts

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#5949]
Design issue: https://github.com/patternfly/patternfly-design/issues/1275

Determine what changes are needed to consume tokens in Charts styles:

https://github.com/patternfly/patternfly/blob/v6/src/patternfly/patternfly-charts.scss
https://github.com/patternfly/patternfly/blob/v6/src/patternfly/patternfly-charts-theme-dark-unversioned.scss
https://github.com/patternfly/patternfly/blob/v6/src/patternfly/patternfly-charts-theme-dark.scss

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6644
