### ISSUE TITLE
Break Up Patternfly-addons into smaller units

### ISSUE THREAD

**Issue by paceaux** [patternfly/patternfly#5956]
### The problem: Patternfly-addons.scss is very large for being "addons"

patternfly-addons is approximately 200kb of compiled CSS and approximately 8300 lines (unminified).

The bulk of this weight comes from just two sass files:
1. `utilities/Sizing/sizing`
2. `utilities/Spacing/spacing`

When Patternfly is brought into our project, we are importing `patternfly-addons.scss`. It contributes 8000+ lines of CSS -- and we're only using 15% of the selectors it provides (50 selectors of the approximate 316). 

sizing and spacing alone contribute 68% of the overall weight of patternfly-addons. 

### Where this is a problem:
developers.redhat.com

* we're using patternfly 4.132. 
* This is not an urgent request. We noticed this during a routine audit of our  scss
* I've attached a zip file containing a json file showing which of these selectors we're using, and also a json file which just shows what our used/unused selectors are. 

### What would a solution look like
1. Each addon could be its own module
2. Ability to import the `pf-u-width-options` , `pf-u-height-options` maps 
3. exporting `pf-u-min-width` and friends as functions or includes
4. exporting the `pf-spacer-builder` as a function so that we can pass in breakpoints, spacer properties, and values

[developers-analysis.zip](https://github.com/patternfly/patternfly/files/12692029/developers-analysis.zip)

**Comment by mcoker** [comment]
@paceaux thanks for the issue! Great points, those stylesheets are really large, and could be optimized for sure. From the sounds of it, it looks like you're compiling our SCSS yourselves? FWIW, we do current compile each of the utilities as their own stylesheet to the path `@patternfly/patternfly/utilities/[Utility]/[utility].css`, for example [@patternfly/patternfly/utilities/Sizing/sizing.css](https://unpkg.com/browse/@patternfly/patternfly@4.132.2/utilities/Sizing/sizing.css).

If you're compiling our SCSS, we can also make `$pf-u-[width/height]-options` overridable by adding `!default` to their declarations, so all you should have to do is set those before you compile sizing.scss, and your values would be used instead. We could also just move those out to a global stylesheet that can be included.

Turning individual utility classes into functions/includes would be fine, too. With these kinds of classes and their size, I can definitely see the _utility_ of using individual classes available without having to import everything from that utility's stylesheet.

`pf-spacer-builder` could go into our global [mixins.scss](https://github.com/patternfly/patternfly/blob/main/src/patternfly/sass-utilities/mixins.scss) so it's available for import, too.

While none of this would be breaking or alter the compiled CSS in any way, active development is on v5.x. Are you able to update to 5.x or have a plan for updating? cc @mattnolting @nicolethoen

**Comment by paceaux** [comment]
Thanks @mcoker for getting back. 

We're currently importing the scss and compiling it ourselves. 
I didn't think to look for the individual stylesheet in utlities, but I'll see if that's something we could pull off. 

I think in the long run, we'd probably get the most benefit by being able to be selective about what we needed those utilities to do. 

We don't _yet_ have a plan for updating, but I can talk to the team and see when we can work on  a plan.

**Comment by mcoker** [comment]
@paceaux ok great, thanks. Let us know if you're able to update to v5 and we can see about getting this work onto the roadmap. And also if the individual utility stylesheets offer an improvement.
