### ISSUE TITLE
Content - create classes for relatively styled children elements

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#5966]
**Describe the problem**
We style children elements of `pf-v5-c-content` elements 
```
.pf-v5-c-content h1 {
  font-size: var(--pf-v5-c-content--h1);
}
```

We should use versioned css classes to these elements to apply these styles.
```
.pf-v5-c-content--h1 {
  font-size: var(--pf-v5-c-content--h1);
}
```

at a minimum, to prevent breaking changes, we could just extend the styles we apply to `.pf-v5-c-content h1 {...}` to also apply to `.pf-v5-c-content--h1 {...}`. New selectors should match specificity of existing selector to avoid any breaking/different behavior. Ensure content functionality is unchanged.

**What is your product and what release date are you targeting?**
This change would enable patternfly.org to use the PF classes rather than all these extra overrides on workspace classnames.
https://github.com/patternfly/patternfly-org/blob/979082df24c670350cecf057c916fb85ad37d714/packages/documentation-framework/templates/mdx.css#L80-L82

Ideally this will be addressed and org can be cleaned up before v6 is live.

**Comment by kmcfaul** [comment]
Closed by #6511
