### ISSUE TITLE
Modifier classes - consider full BEM naming

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5988]
Currently our format is
* `.pf-v5-c-button.pf-m-primary` // component
* `.pf-v5-m-tabular-nums` // global

Proposing
* `.pf-v5-c-button--m-primary`
* `.pf-v5--m-tabular-nums`
  * Or just as a nit, namespace these as "global", eg `.pf-v5-global--m-tabular-nums`

Pros
* Follows proper BEM notation
* Reduces specificity of selectors with modifiers
* Makes SCSS a bit more readable, relying less on the need for nesting - though you could go both ways, may come down to a writing preference.
* Ensures `.pf-m-something` used in more than 1 component in a nested situation don't somehow conflict
* Clears up any questions around why modifiers aren't versioned<sup>*</sup>
    <sup>&ast;</sup> _except for the ones at are_

Cons
* Longer classnames
* A large overhaul

wdyt @srambach @mattnolting

**Comment by srambach** [comment]
I can see some advantages. Would you want to get this into v6 or wait for the next breaking change? 🤔 Could we add the new modifiers and leave the old for a cycle?

**Comment by mcoker** [comment]
@srambach IMO too big of a lift for v6. We would need to rework a lot of components and resolve issues from the specificity changes. We could technically support both for a time period, though I'd probably want to think about it a little more to weigh the pros/cons.
