### ISSUE TITLE
Stalebot - update to stale github action

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6005]
We use stalebot but it's no longer maintained - https://github.com/apps/stale

It's recommended to use the stale action instead - https://github.com/actions/stale

We should also add a "stale" label and configure the action to set that label on issues identified as stale. The action also allows us to apply that label manually as another way to mark an issue as stale.

**Comment by wise-king-sullyman** [comment]
You can't save yourself stalebot!
