### ISSUE TITLE
Bug - DragDrop dragging background color missing

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly#6017]
It looks like the draggable.dragging background color variable (`--pf-v5-c-draggable--m-dragging--BackgroundColor`) isn't defined in `drag-drop.css`, or I'm missing where it's getting defined. It's currently rendering the background as transparent which isn't correct.

**Comment by mcoker** [comment]
@kmcfaul it's left empty intentionally so the component doesn't stomp on an existing background color, depending on what the `.pf-v5-c-draggable.pf-m-dragging` class is applied to. In the core examples, the background color is coming from a workspace style for those examples - https://github.com/patternfly/patternfly/blob/466a5e56d529b62ef78b510ec723a178e5ab7c84/src/patternfly/components/DragDrop/examples/DragDrop.css#L5-L6

**Comment by kmcfaul** [comment]
@mcoker Okay thanks for clarifying! That file looks like it was removed or moved on the new drag drop PR so that's why I'm having trouble finding it. 

An additional question I have is about the opacity that is set on the droppable.before (`--pf-v5-c-droppable--before--Opacity`) for the "ghost row" that shows where an item will be dropped. This works fine for plain text but when we are wrapping component structures like DataList/DualListSelector the opacity doesn't seem to work anymore (the component looks like it's getting its own background/opacity and lies on top of the droppable). Is there a specific place this needs to be applied to the DataList row for example? Or is there another class to use for the grey-text/lighter row styling.

**Comment by mcoker** [comment]
@kmcfaul do you have a PR or something where I can see? Taking a stab from what you described, I'm wondering if the droppable overlay just needs a `z-index` so it can sit on top of all the stuff inside of the droppable element. Added that to a codesandbox here to show (though "1" is not the ideal value) - https://codesandbox.io/s/great-hugle-vfmdff?file=/style.css

We didn't have clear uses cases and requirements when this component was created, so we may need to make some updates as we use it more.

**Comment by kmcfaul** [comment]
PR which are my updates to the original PR is here https://github.com/patternfly/patternfly-react/pull/9784. 

I'll re-ping you when I get a working build, there are some issues I'm wrangling that is preventing the surge from working right now.

**Comment by kmcfaul** [comment]
Still want to increase the z-index of the overlay for the ghost row (default and DataList and DualListSelector).
Add the default dragging background color (per component).

**Comment by mcoker** [comment]
closed in favor of https://github.com/patternfly/patternfly/issues/6074
