### ISSUE TITLE
Bug - [Password] - [Password strength breaks on horizontal forms]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#6032]
**Describe the problem**
The password strength does not wrap correctly on horizontal forms.

**Screenshots**
![Screen Shot 2023-11-03 at 16 03 25](https://github.com/patternfly/patternfly/assets/14921356/d8a62088-0c12-4f74-b096-30adddce1acc)

**What is your product and what release date are you targeting?**
Anaconda

**Comment by mcoker** [comment]
cc @mmenestr @andrew-ronaldson this is a result of the "additional label info" layout breaking in a horizontal form - it's only supported in the non-horizontal form currently. https://www.patternfly.org/components/forms/form#form-group-with-additional-label-info

FWIW if we just put the add'l info under the label in a horizontal form, this is what it would look like.

preview link - https://codesandbox.io/s/bold-mountain-9kygkq?file=/index.html

<img width="445" alt="Screenshot 2023-11-07 at 1 40 55 PM" src="https://github.com/patternfly/patternfly/assets/35148959/0391db6f-2bbc-4801-8aff-2f543bcbe67a">

**Comment by mcoker** [comment]
cc @andrew-ronaldson @lboehling WDYT about this issue?
