### ISSUE TITLE
Bug - Box shadow tokens typo

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly#6034]
It looks like a handful of box-shadow tokens are missing a dash `-` in the name.  Tokens are seen here:

- https://github.com/patternfly/patternfly/blob/v6/src/patternfly/base/tokens/_tokens-font.scss#L88-L91

Similar values are used just above in that same stylesheet but include a double dash between `sm` and the direction (ex: `  --pf-t--global--box-shadow--sm--top` vs `--pf-t--global--box-shadow--sm-top`

**Comment by mcoker** [comment]
closed via #6039
