### ISSUE TITLE
Bug - FormControl - input fields have incorrect width in Firefox

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly#6036]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

When opening the following components in Firefox, the `input`s in the `pf-v5-c-form-control` components do not have the correct widths. 

- Number input
- Calendar month
- Date and time picker
- Date picker
- Time picker

**How to test**
Open the [Number input examples](https://www.patternfly.org/components/number-input/html) in Firefox and see the `<input>` fields have incorrect widths.

<img width="283" alt="Screenshot 2023-11-07 at 9 50 25 AM" src="https://github.com/patternfly/patternfly/assets/32821331/83759a5f-1e0e-4c53-8f05-ae9ee55888fa">

Is this something that can be fixed by setting `min-width: 0` on those inputs?

Discovered via https://github.com/patternfly/patternfly-react/pull/9484

**Comment by mcoker** [comment]
Looks like this is from an older version of FF (v102.12)
