### ISSUE TITLE
Page - remove extra padding in sidebar (penta)

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6052]
> In pages, you can see that we've got a large spacer on the inline-start of the page sidebar AND on the navigation. I think the padding should be removed from the page sidebar, WDYT?

@srambach Yep, I agree 👍

_Originally posted by @mattnolting in https://github.com/patternfly/patternfly/issues/6033#issuecomment-1805771482_

**Comment by nicolethoen** [comment]
Closed by #6053
