### ISSUE TITLE
Create tokens and variables for all the valid combinations of text

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6066]
**Describe the enhancement or change**
Text specs are here: https://www.figma.com/file/iPks6qJfvvwGOTHgpoIvHm/Penta-Design-Tokens-%26-Styles-Library?type=design&node-id=1677%3A8119&mode=design&t=D43UHI0rxrQ9x7qZ-1

Create necessary tokens and also variables that can be used to set font with shorthand.

**Comment by wise-king-sullyman** [comment]
Closing in favor of #6046
