### ISSUE TITLE
Add "corner" css vars to Tooltip in Penta

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6080]
**Describe the enhancement or change**
Followup to https://github.com/patternfly/patternfly/pull/6064

We could add some CSS vars for the top and left properties for when the arrow is meant to be positioned in the "corner" of a tooltip. Right now we have vars like `--#{$tooltip}--m-top--Left`, `--#{$tooltip}--m-bottom--Left` etc, but for classes like `.pf-m-top-left` we're applying a hardcoded value like `0`. Possibly we could introduce new vars like `--#{$tooltip}--m-top-left--Left` instead.

**Is this request originating from a Red Hat product team? If so, which ones and is there any sort of deadline for this enhancement?**

**Any other information?**

**Comment by tejaskh3** [comment]
Hey @thatblindgeye, can i work upon this issue??

**Comment by mcoker** [comment]
@thatblindgeye do you remember the use case for needing to add those vars? I looked in https://github.com/patternfly/patternfly/pull/6064 but am not seeing where we said they would be useful. IIRC it was so we could potentially adjust the arrow like this popper/floating-ui example?


https://github.com/patternfly/patternfly/assets/35148959/9b03a965-fa58-427d-9878-6b545f805b88

**Comment by thatblindgeye** [comment]
@mcoker I think it was just a way to provide a little more customization for the consumer. It was probably a discussion had during one of the Penta meetings

**Comment by mcoker** [comment]
@thatblindgeye sounds good, yeah we can work on this. @tejaskh3 you're more than welcome to pick this up if you'd like, I think the TL;DR here is that if a user wants to customize the arrow position for one of the tooltip positions, they have a CSS var they can override for their customization that 1) positions the arrow where they want it and 2) doesn't impact arrows in other tooltip positions.
