### ISSUE TITLE
Global - update mixins to use tokens

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6093]
In particular, the spacers used in mixins need to be updated to use tokens.

https://github.com/patternfly/patternfly/blob/main/src/patternfly/base/_variables.scss
https://github.com/patternfly/patternfly/blob/main/src/patternfly/sass-utilities/scss-variables.scss

Question: do we still use these sass variables, or do we migrate away from maintaining these global variables in favor of the token variables?

**Comment by mcoker** [comment]
I'm definitely in favor of removing SCSS vars and just using CSS where we can, and even CSS functions in place of SCSS where possible (like math). A good example of SCSS vars we probably need are for breakpoints since you can't use a custom property in a media query currently.

**Comment by mattnolting** [comment]
Remove as many `scss` variables as possible 👍

**Comment by mcoker** [comment]
This has been completed
