### ISSUE TITLE
Breadcrumb penta updates

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly#6097]
Follow up to #6060

* Use gap instead of margin
* Add focus styles to items
* Investigate the inline padding - is that needed?
* There should be a spacer-sm betweent the > dividers so the hover state of menu toggle isn't touching the dividers. (https://github.com/patternfly/patternfly/pull/6430#issuecomment-2009568465) Can be part of ^ just to review the overall spacing

**Comment by andrew-ronaldson** [comment]
Closing. Updates done in another issue
