### ISSUE TITLE
Bug - [Tabs] - [Vertical Tabs show content below tablist instead of beside]

### ISSUE THREAD

**Issue by aDogCalledSpot** [patternfly/patternfly#6117]
**Describe the problem**
When using vertical tabs, the content is rendered below the tablist.
This looks a bit strange, especially when using boxed tabs.

**How do you reproduce the problem?**
This behavior is shown on the Patternfly website: https://www.patternfly.org/components/tabs#vertical-tabs:
![image](https://github.com/patternfly/patternfly/assets/22723953/536b0c86-003d-47a4-9b49-18848fece0a4)

Note that the tablist fills the entire width of the demo.

So you can use [the code from that example](https://codesandbox.io/p/sandbox/old-sky-js8c49)

**Expected behavior**
The content is displayed to the right of the tablist, as the design (especially if the tabs are boxed) indicates.

I could sort of replicate what I want by wrapping both the tablist and the content in a flexbox.

```html
<div class="pf-v5-c-tabs pf-m-vertical pf-m-box">
  <div style="display: flex;">
    <ul class="pf-v5-c-tabs__list">...</ul>
    <section class="pf-v5-c-tab-content">Users</section>
  </div>
</div>
```

yields:

![image](https://github.com/patternfly/patternfly/assets/22723953/b60707b4-729b-41ef-824f-a785343c2e3a)

**Is this issue blocking you?**
The current workaround is to use detached tabs and place the tabs and the content in a grid and manually specifying how large each side should be.

**What is your environment?**
 - OS: Arch Linux
 - Browser: Firefox

**Comment by wise-king-sullyman** [comment]
Thanks for making this issue!

In reviewing this issue the PF leads don't believe this is necessarily a _bug_, as the way we would probably recommend doing this is using a sidebar layout, though there might be some issues with that approach which we should investigate.

For the person that takes this issue: scope here should be trying to put vertical tabs and tab content in a sidebar layout and documenting what, if any, issues arise.
