### ISSUE TITLE
Consume tokens: Menu toggle

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6163]
**Is this a new component or an extension of an existing one?**
Menu toggle

[Figma design for menu toggles](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A16&mode=design&t=doZDRUaxE4vsn5dD-1)

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6177
