### ISSUE TITLE
Consume tokens: Select

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6165]
**Is this a new component or an extension of an existing one?**
Select

[Figma design for select](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A16&mode=design&t=doZDRUaxE4vsn5dD-1)

**Comment by wise-king-sullyman** [comment]
Closing as we now plan to deprecate old select entirely
