### ISSUE TITLE
Consume tokens: Overflow menu

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6166]
**Is this a new component or an extension of an existing one?**
Overflow menu

[Figma design for overflow menu](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A16&mode=design&t=doZDRUaxE4vsn5dD-1)

**Comment by mcoker** [comment]
@mattnolting looks like overflow menu was updated in https://github.com/patternfly/patternfly/pull/6057 - can we close this issue, or are there still updates you'd like to see for penta?

**Comment by srambach** [comment]
The only things I see are that 1) some of the examples have custom CSS with v5 in the name, but we'll be fixing that globally and 2) looks like the overflow menu uses a dropdown, so I think we'll want to update that to be a menu. 

Closing will followup https://github.com/patternfly/patternfly/issues/6408
