### ISSUE TITLE
Bug - Primary-detail demo -  in dark theme drawer bg is transparent

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6175]
**Describe the problem**
In the [Primary detail demo](https://pf6.patternfly.org/patterns/primary-detail/html-demos/primary-detail-expanded/) the drawer has a transparent background in dark theme (but shows a white background correctly in default theme)

**Comment by pragyamishra56** [comment]
@srambach Mam, could you elaborate on the issue that it would be helpful for resolving the issue

**Comment by wise-king-sullyman** [comment]
Closed by #6183
