### ISSUE TITLE
Replace uses of Dropdown (deprecated) with MenuToggle

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6207]
**Describe the enhancement or change**
We've deprecated Dropdown, but it's used many places in core. This issue should replace any uses of Dropdown with Menu instead

Known places:
- [x] Breadcrumb
- [x] Card
- [x] Dual list selector
- [x] Hint
- [x] Inline edit
- [x] Log viewer
- [x] Notification drawer
- [ ] Table
- [ ] Tree view
- [ ] some additional demos

Hint: search .md and .hbs for `{{> dropdown` to find instances

**Comment by kmcfaul** [comment]
DataList also uses dropdown-toggle

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6566
