### ISSUE TITLE
Card - update demos

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6232]
**Describe the enhancement or change**
A lot of the demos for card use custom styling that we no longer need to use that way. Review all the demos and update as needed to use newer components - e.g. status label, colors on the notification drawer item titles.

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/issues/6249
- [ ] (the rest of the card demos)...
```

**Comment by andrew-ronaldson** [comment]
Closed for separate issues
