### ISSUE TITLE
Button - use gap instead of left/right margin for icon button

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6245]
**Is this a new component or an extension of an existing one?**
On the icon button, we currently use `pf-m-start` and `pf-m-end` to apply a margin to the left or right of the icon to ensure proper space between the icon and text. If we use gap instead, the gap can collapse if there is no text. In addition, we can probably remove the two modifier classes since gap will work in both cases.

**Any other information?**
React is using an icon button for the notification badge and if there is no text, the icon is currently mis-aligned because of the extra space added. (React requires one of the modifiers)

@wise-king-sullyman

**Comment by mattnolting** [comment]
https://github.com/patternfly/patternfly/pull/6167/files/88dd1182d2456ddc1750a186db004e40759ce642#r1468135792
