### ISSUE TITLE
Bug - MultipleFileUpload - incorrect penta styling on the progress toggle icon

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly#6247]
Followup to patternfly/patternfly-react#10031

**Describe the problem**
MultipleFileUpload's `__status-progress-icon` styling should either be removed (allowing the `__toggle-text` styling to be inherited) or updated to reflect the new penta styling.

If we go the update route we should probably also add similar styling for the`__status-progress-text` class which is used in the HBS for the text within the progress toggle.

**Screenshots**
Figma (all of the toggle is blue):
<img width="628" alt="image" src="https://github.com/patternfly/patternfly/assets/7115053/4c2ed320-572d-4d7c-af36-c0659792d5bb">

On staging (icon is not blue):
![image](https://github.com/patternfly/patternfly/assets/7115053/4704f14a-7ccf-4041-a38f-b9d0c6f10aa3)

**Comment by andrew-ronaldson** [comment]
Closed by https://github.com/patternfly/patternfly/pull/6688
