### ISSUE TITLE
V6 Bug - [Nav] - remove `pf-m-expandable` from examples

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly#6248]
**Describe the problem**

`pf-m-expandable` no longer exists in Nav style sheet.  It should be removed form example code.

**How do you reproduce the problem?**
You can see the modifier in examples with expandable nav (https://pf6.patternfly.org/components/navigation/#expanded)

**Expected behavior**
A clear and concise description of the expected behavior.

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6727
