### ISSUE TITLE
Bug - Accordion, Button, Horizontal Nav Overflow - Mix blend modes dropped

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly#6250]
@thatblindgeye noticed in [this issue](https://github.com/patternfly/patternfly-react/pull/10033#pullrequestreview-1838876252) that the hover states on accordions weren't appearing as expected in dark mode. Manually applying the mix blend mode made the hover states appear normally. 

Looks like the mix blend mode tokens have fallen off a number of components that previously had them defined in the [v6 core staging site](https://pf6.patternfly.org/components/button). Noticing it missing on plain and link buttons, accordion toggles, and horizontal overflow buttons.

**Comment by srambach** [comment]
@lboehling @mcoker can this be closed now that we are using the opacity in the token rather than a separate mix blend mode?
