### ISSUE TITLE
Bug - Tabs - border inline start/end on boxed variant for Penta

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6254]
**Describe the problem**
The Penta Tabs updates has a visual bug where if the first or last Tab is the "current" tab when the variant is `pf-m-box`, it has an inline-start (if first Tab) or inline-end (last Tab) border:

![image](https://github.com/patternfly/patternfly/assets/70952936/1c404c0f-6150-4d89-8d32-082a856597ba)

This has to do with the selector `.pf-v5-c-tabs.pf-m-box .pf-v5-c-tabs__item.pf-m-current:last-child .pf-v5-c-tabs__link::before` applying the border-width on the `::before` pseudo

**Comment by andrew-ronaldson** [comment]
Closed by https://github.com/patternfly/patternfly/pull/6697
