### ISSUE TITLE
Consider chaining of tokens and the impact on breaking changes

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6255]
When we have vars that are (explicitly or implicitly) defined by another var, we run the risk of introducing breaking changes if we change any of the vars involved in providing a value for another var.

Examples:

In these cases, if a user themes either `--border-base` or `--blue-300`/`--brand`, we've established that those can ultimately theme `--border-top` and `--link` respectively.

Say a user has themed `--blue-300` as a means to theme their global brand and link colors. If we change, for example, `--brand: var(--blue-300);` to `--brand: var(--blue-400);`, then `--blue-300` no longer themes `--brand` and `--link`, and is a breaking change for that user.

```
--border-base: grey;
--border-top: var(--border-base); // defined by --border-base

// or at the global token level

--blue-300: #06c;
--brand: var(--blue-300);
--link: var(--brand); // defined by --blue-300 and --brand
```

As we define what a breaking change is with regards to tokens/vars being the API for component styles, we should consider this ^ so we can provide reliable, documented suggestions and techniques for customizing PF styles and establish authoring practices for core devs that can be documented and referenced to validate code.

----

A similar issue is the potential of writing CSS like this:

```
--border-base: var(--pf-t-global--border--token);

border: var(--border, var(--border-base)); // --border is not defined, only used for theming within PF or by users
// border: var(--border, var(--pf-t-global--border--token)); - another way of writing it
```

An additional issue is that this will not create a react token for `--border` currently, and react tokens is used to generate our variable documentation as well as giving react users a JS token to reference the value for the var.

Also it will not create a `--border` var that core devs and users can reference for this particular border.

**Comment by srambach** [comment]
Meeting scheduled for March 7

**Comment by mcoker** [comment]
Closing for now. We decided that semantic tokens are protected from breaking changes, but base/palette tokens are not
* Core/design will not change the relationship of semantic tokens once they're released, which should protect them from breaking changes
* We will only change the value of base/palette tokens if needed
