### ISSUE TITLE
Font weight utility class

### ISSUE THREAD

**Issue by ryelo** [patternfly/patternfly#626]
In a couple instances, there are cases that a heavier font weight would be needed to distinguish content.

For example: 

![image](https://user-images.githubusercontent.com/12520842/44406582-fbb53880-a529-11e8-96e4-1fe9e0b68492.png)

If you had a few cards that were lined up like the image above and you needed to signify the header of the card as the title, the titles get lost easily - especially when scrolling.

**Comment by matthewcarleton** [comment]
hey @ryelo could you use the content component here? https://pf-next.com/components/Content/examples/

**Comment by ryelo** [comment]
We could do that, but I think the overall goal is to not add more elements.

I think something like how [Bootstrap's card](https://getbootstrap.com/docs/4.0/components/card/) works with their title or even modifiers like  [Bulma's Typography](https://bulma.io/documentation/modifiers/typography-helpers/) and [Bootstrap's Text](https://getbootstrap.com/docs/4.0/utilities/text/)

We're using React, so having something like 
```JS
<CardHeader bold> Foo </CardHeader>
```
would be awesome too.

**Comment by tiffanynolan** [comment]
We're also running into a similar issue with the cards and the Integreatly project. I spoke with @mceledonia about this the other day. I believe the header is supposed to have a default size of 18px (vs the current 16px) which should help differentiate it. However, I'm not sure that will provide enough visual difference for the hierarchy.

Current implementation with the 16px header as specified in the card component.

![image](https://user-images.githubusercontent.com/15326290/53263179-a27bbc80-36a6-11e9-846f-51741d3485f2.png)

The Integreatly team is recommending that the H4 style (fourth level title) is used as the base style for the card header as this provides more weight and visual difference. 
![image](https://user-images.githubusercontent.com/15326290/53263225-c8a15c80-36a6-11e9-8a29-eee974397b2c.png)

**Comment by mceledonia** [comment]
I think that's a great recommendation, the semibold weight of the fourth level title should be just enough to push that hierarchy up to where it needs to be. Thanks again @tiffanynolan !

**Comment by ryelo** [comment]
Yeah, we are working around this project also using the fourth title level weight 😄

**Comment by mcoker** [comment]
@ryelo @tiffanynolan @mceledonia created https://github.com/patternfly/patternfly-next/issues/1465 for that request.

**Comment by mcoker** [comment]
We have a separate request currently being worked on that will add this under a new font/text utility https://github.com/patternfly/patternfly/issues/3246
