### ISSUE TITLE
Action list - update column-gap var for icon modifier

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6262]
**Is this a new component or an extension of an existing one?**
Action list

**Describe the feature**
We should update the column-gap var for action-list__group when action-list has the `pf-m-icon` modifier, that way we can update all groups in an action list at once rather than having to apply the modifier to each group

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

**Any other information?**

**Comment by srambach** [comment]
Closed by #6263
