### ISSUE TITLE
Utility classes - update to support RTL

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6273]
There are some utility classes that could be updated with logical values. We should look over all of them, but two that stand out are

https://github.com/patternfly/patternfly/blob/7bff19089077f5f61631735b5bc7b190257d90d2/src/patternfly/utilities/Alignment/alignment.scss#L2-L7

https://github.com/patternfly/patternfly/blob/7bff19089077f5f61631735b5bc7b190257d90d2/src/patternfly/utilities/Float/float.scss#L3-L6

**Comment by srambach** [comment]
Related issue: https://github.com/patternfly/patternfly/issues/6315

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6400
