### ISSUE TITLE
Bug - Tree Table - Children break on mobile view when borders are applied

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly#6283]
**Describe the problem**
Adding a left or right border to a tree table cell that winds up nested in mobile view results in some bad styling.

**How do you reproduce the problem?**
(I found this issue in PatternFly React, but when I asked, Nicole Thoen suggested I open the bug here instead.)

Add hasLeftBorder or hasRightBorder to a `<Td>` that winds up as a child. [Look at this example](https://codesandbox.io/p/sandbox/distracted-easley-jg795z?file=%2Findex.html) at a smaller breakpoint to see the issue.

Here's a screenshot:
<img width="465" alt="Screenshot 2024-02-07 at 1 51 44 PM" src="https://github.com/patternfly/patternfly/assets/7014965/09018d54-501b-4462-9544-f4537183fafe">

**Expected behavior**
Children should render properly on mobile when a border is applied.

**Is this issue blocking you?**
Yes!

**What is your environment?**
 - OS: macOS Sonoma version 14.3
 - Browser Chrome 
 - Version 121.0.6167.85

**Comment by mattnolting** [comment]
@rebeccaalpert Looks like the nested table is missing `table thead/tbody`. Can you update that and let us know if that ffixe

![Screenshot 2024-02-28 at 10 14 30 AM](https://github.com/patternfly/patternfly/assets/5385435/1bfddb74-0c9e-4f28-a6a0-5d09cb5584da)

**Comment by rebeccaalpert** [comment]
Hi @mattnolting - I don't have a lot of control over the generated HTML because I'm using PatternFly React for this. This is an example pulled directly from the PatternFly site, with borders added.

**Comment by rebeccaalpert** [comment]
Also happens in the HTML example if you add pf-m-border-right or left to any of the "Migration assessment" tds:
[
<img width="994" alt="Screenshot 2024-02-28 at 10 57 14 AM" src="https://github.com/patternfly/patternfly/assets/7014965/c86d97ff-cf5b-41bf-852b-6c1798b52f75">
](url)

**Comment by mattnolting** [comment]
closed via #6864
