### ISSUE TITLE
Use semantic spacer tokens

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6292]
These should go in controls and buttons/actions

https://github.com/patternfly/patternfly/blob/b18cc266d24d9ff894da48e705e5eb4e98b15b60/src/patternfly/base/tokens/_tokens-default.scss#L154-L159

**Comment by thatblindgeye** [comment]
Per conversation with @lboehling , we should use these semantic spacer tokens where our actual Button (button spacers) or form inputcontrols and Menu Toggles (control spacers) are used, or where they're implied to be those components (for example, the sort button in a Table is essentially/implied to be or look like one of our Button variants so we'd probably want to use the spacers there)

**Comment by thatblindgeye** [comment]
Closed by 6507
