### ISSUE TITLE
Page - ensure all the main-[breadcrumb, section, subnav, etc] section spacing is correct

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6300]
We can have a lot of types of sections and we should make sure that the spacing for all is correct, particularly the block spacing when you have all/some of them stacked. Eg, ensure all of the possible combos below look correct.

```
page-main
  page-main-subnav
  page-main-breadcrumbs
  page-main-tabs
  page-main-section
```

**Comment by srambach** [comment]
Closed by #6628
