### ISSUE TITLE
Wizard follow ups

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6314]
From https://github.com/patternfly/patternfly/pull/6251#pullrequestreview-1879050606

* in page wizards - only the wizard content (nav and main) should scroll. Has to do with `align-self: start` being added to `$page__main`.
* Use the action list in the footer - right now the actions in the footer have margins, including a margin-bottom, so the bottom padding of the footer takes into account the action margin, which we shouldn't need to do?

**Comment by thatblindgeye** [comment]
Closed by #6611
