### ISSUE TITLE
Bug - Nav - flyout menus are broken

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6327]
Looks like it was probably introduced with the penta menu PR
* https://github.com/patternfly/patternfly/pull/6167 
* https://patternfly-pr-6167.surge.sh/components/navigation#nav-with-flyout

The commit before that (menu toggle), flyout menu looks good
* https://github.com/patternfly/patternfly/pull/6177
* https://patternfly-pr-6177.surge.sh/components/navigation#nav-with-flyout

**Comment by thatblindgeye** [comment]
Closed by #6435
