### ISSUE TITLE
Bug - MenuToggle - spacing between content and controls is off when content is short

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6337]
**Describe the problem**
If MenuToggle content isn't long enough to fill its container, the content and controls are centered horizontally:

![Full width menu toggle with incorrect spacing, where content and toggle icon are centered](https://github.com/patternfly/patternfly/assets/70952936/65cc94dd-ef7a-45a0-b6d4-2d6ba69eb3ec)

**How do you reproduce the problem?**
Provide steps to reproduce. A [codepen](http://codepen.io) or [codesandbox](https://codesandbox.io/) demonstrating the problem is appreciated.

**Expected behavior**
A clear and concise description of the expected behavior.

**Is this issue blocking you?**
List the workaround if there is one.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6336
