### ISSUE TITLE
Persist A11y Audit Results

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly#635]
Now that we've support for a11y status reporters in CI, we can move onto the next phase of exposing this effort. We'd like to increase the visibility of the audit results for each release.

Done criteria:
- Audit results downloadable from [releases](https://github.com/patternfly/patternfly-next/releases) page

Requirements:
- Audit results can be kept/viewed over time

**Comment by seanforyou23** [comment]
Any chance we're still planning to do this work? Are there any questions about what's needed? This issue has been open for a while, might be good to follow through with it or maybe close it if it's not something we want to prioritize?

**Comment by jessiehuff** [comment]
I'm open to making any of our a11y more public, but I'm curious which part you're thinking of here? Are you thinking the a11y script results on our components, our documentation, or the monthly audit we've been doing? I think the last we talked, you were thinking something to do with the script? I have talked to others about making the monthly a11y audit more public. The idea at the moment would be to save it as a pdf maybe once a quarter to show a quarterly snapshot, but the cadence to that idea is still flexible at the moment.

**Comment by seanforyou23** [comment]
Yes exactly, the main thing was to have the ability to monitor/view the progress of the accessibility support over time. This could come in the form of some as fancy as a UI that displays the results in a PF chart over time, or as cheap as simply running the report and exporting the results to a text file that's supplied along with our downloadable release in some way.

**Comment by redallen** [comment]
We don't have this ability for any of our test results in any of our patternfly repos. We need some service or backend to store and display results. I haven't found any good solutions.
