### ISSUE TITLE
Bug - Card - Clickable not working

### ISSUE THREAD

**Issue by gitdallas** [patternfly/patternfly#6352]
**Describe the problem**
With the latest version of Chrome, clickable cards are not styled correctly or behaving correctly. This issue was originally filed under react, here https://github.com/patternfly/patternfly-react/issues/10104 but I believe it to be a core only fix.

**How do you reproduce the problem?**
this can be seen in the [HTML examples](https://www.patternfly.org/components/card/html#clickable). it will look fine in older versions (pre 122) of chrome or in other browsers. Styling is strange (as seen below) and there are no hover or cursor changes.
![image](https://github.com/patternfly/patternfly-react/assets/5322142/8aad66ed-4908-45e9-aa1f-53a87bcf9581)

**Comment by gitdallas** [comment]
christian found a [workaround](https://github.com/patternfly/patternfly-react/issues/10104#issuecomment-1967577024) which may also be helpful in finding a solution.

```
.pf-v5-c-card__selectable-actions .pf-v5-c-radio__label {
  width: 100%;
  height: 100%;
}
```

**Comment by evwilkin** [comment]
Summary of findings & resolution: https://github.com/orgs/patternfly/discussions/6381
