### ISSUE TITLE
Bug - Calendar month - rendering select menu

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6356]
**Describe the problem**
Calendar month is rendering a select menu.

<img width="375" alt="Screenshot 2024-02-26 at 3 54 15 PM" src="https://github.com/patternfly/patternfly/assets/5385435/43fcc332-d71a-4eae-9b46-6f8c75074d0a">

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6357
