### ISSUE TITLE
Bug - Modal v6 - Close button positioning

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6380]
**Describe the problem**
The close button is fixed top-left instead of top-right.
<img width="985" alt="Screenshot 2024-03-01 at 4 10 17 PM" src="https://github.com/patternfly/patternfly/assets/28658548/9c47de6c-05f9-4bdd-83ce-4368dd4d2113">

**Comment by wise-king-sullyman** [comment]
close #6382
