### ISSUE TITLE
Update var names used for logical properties

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6389]
In v5, we updated CSS properties with logical property equivalents for padding, margin, borders, insets, etc. To avoid that being a breaking change, we left the CSS var names unchanged, so we have a lot of places in the code where the CSS property and var names do not match. For example https://github.com/patternfly/patternfly/blob/7df2e174cc259386641610cf1dc5bec1364b3f92/src/patternfly/components/Button/button.scss#L213-L216

For v6, let's update these to match. We should consider doing it in a single effort and using screenshots to validate the changes, similar to the workflow used in v5 to switch to logical properties.

**Comment by srambach** [comment]
Closed by #6593
