### ISSUE TITLE
Page/masthead logo - should be the same size as the sidebar/vertical nav

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6420]
With a sidebar/vertical nav, the masthead logo area looks to take up the the width of the sidebar - notably any stuff that comes after the logo in the masthead (that isn't the right-aligned actions 'n such) should start at the same point that the page main content starts.

Some ideas:
* Now that we can use subgrid, the masthead logo could possibly be part of the page grid layout. This seems like the ideal solution?
* We have width vars for the sidebar that we could use with the masthead logo.
* ...

<img width="601" alt="Screenshot 2024-03-14 at 10 38 03 AM" src="https://github.com/patternfly/patternfly/assets/35148959/b35fcf91-ddf9-4ef9-b5e5-e3f1c50279c2">

<img width="586" alt="Screenshot 2024-03-14 at 10 48 42 AM" src="https://github.com/patternfly/patternfly/assets/35148959/f9881648-2252-4c8b-9306-cfcea07fcbca">

**Comment by mcoker** [comment]
@lboehling can you confirm the intent of the logo area in the masthead is to consume the same width as the sidebar? Or should that width be variable to match the size of the logo - and any menus or horizontal nav or whatever that comes after the logo in the masthead would just come after the logo and not be aligned with the left edge of the page content?

**Comment by lboehling** [comment]
@mcoker you're right! the design intent is to have the logo area span the width of the sidebar (if there is one), so that any controls that come after the logo in the masthead are aligned with the left edge of the page content.

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6870
