### ISSUE TITLE
Table - sort button

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6437]
**Is this a new component or an extension of an existing one?**
Table sort button 

**Describe the feature**
Needs a `pf-m-plain` variant that matches the button variant. The variant belongs to `pf-v6-c-table__button` (@mcoker) as they have yet to be updated to `menu-toggle`s.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**

<img width="904" alt="Screenshot 2024-03-19 at 11 08 48 AM" src="https://github.com/patternfly/patternfly/assets/5385435/2e4b0ea9-ba79-47d3-8df0-20fb0127d7b3">

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6461
