### ISSUE TITLE
Bug - Check - standalone variant height in menu-toggle is unhappy 

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6450]
**Describe the problem**
This is an issue with 
- [ ] Patternfly 6  

Standalone check height needs to be min-height

**How do you reproduce the problem?**

<img width="298" alt="Screenshot 2024-03-21 at 10 08 23 AM" src="https://github.com/patternfly/patternfly/assets/5385435/8e727ee5-0762-4faa-95ab-4976ba9e55a1">

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6451
