### ISSUE TITLE
Penta Badge/Menu Toggle - update styling when only badge is passed to Menu toggle

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6463]
**Describe the enhancement or change**
Followup to https://github.com/patternfly/patternfly/pull/6430, which contains followup change to be made/looked into

**Is this request originating from a Red Hat product team? If so, which ones and is there any sort of deadline for this enhancement?**

**Any other information?**

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6543
