### ISSUE TITLE
Icons - Adding severity icons to the PF library

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6467]
This is a follow up to https://github.com/patternfly/patternfly-design-kit/issues/718

Several products require severity icons to help prioritize actions from a user. These icons are separate from our standard alert statuses.

```[tasklist]
### Definition of done
- [ ] Add these new icons to our pf icon font
- [ ] Add examples on the PF [icons page](https://www.patternfly.org/components/icon)  
```
This issue requires docs followup to outline the difference between alert status and severity.

**Comment by mcoker** [comment]
@andrew-ronaldson is this ready to work on for v6 or does the issue for [branded icons](https://github.com/patternfly/patternfly/issues/6557) impact this issue?

**Comment by mcoker** [comment]
@andrew-ronaldson @smckinno can you point me to where I can find the SVGs? Usually this type of request will include the SVG(s) as an attachment and/or a zip if there are a bunch of files.

**Comment by andrew-ronaldson** [comment]
Can do. I'll dig them up and add to issue

**Comment by andrew-ronaldson** [comment]
![critical](https://github.com/patternfly/patternfly/assets/28658548/0c3d2f21-4b90-42ed-98d7-f8e06f422bb2)
![Important](https://github.com/patternfly/patternfly/assets/28658548/03b6f67a-8431-45fd-90fd-bf3da629cecb)
![Minor](https://github.com/patternfly/patternfly/assets/28658548/8b53dc0a-d328-419b-b741-8b4dc1a774fc)
![Moderate](https://github.com/patternfly/patternfly/assets/28658548/970f2941-4956-4d8a-b6cc-8729f98faef3)
![None](https://github.com/patternfly/patternfly/assets/28658548/b5ca0c59-f1eb-4c67-aff4-6c147f398ad7)
![Undefined](https://github.com/patternfly/patternfly/assets/28658548/e4c4a930-8f22-4b2c-909a-a89e36afc66e)

**Comment by andrew-ronaldson** [comment]
Here's a link to the folder https://drive.google.com/drive/folders/1L8VypEMTTpAvrUc1MiJY8Q8VHLJXXYI1?usp=sharing

**Comment by smckinno** [comment]
@mcoker I created these on Adobe Illustrator. Any suggestions on what I need to do to fix the svgs? Would flattening the icons be enough? I'm happy to try and play around with different ideas to figure this out.
I'm also in full support to go with naming the icons "Severity-critical" & etc. like you mentioned - and yes Undefined is named correctly so it would be "severity-undefined"

**Comment by andrew-ronaldson** [comment]
I managed to update these @smckinno 
Thanks for following up
