### ISSUE TITLE
Bug - Slider - step labels are positioned incorrectly

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6469]
**Describe the problem**
This is an issue with 
- [ ] Patternfly 5  
- [x ] Patternfly 6  
- [ ] other

On the slider, the step labels are all overlaying each other at the start of the slider

**How do you reproduce the problem?**
https://pf6.patternfly.org/components/slider

**Screenshots**
<img width="835" alt="image" src="https://github.com/patternfly/patternfly/assets/19825616/a201f1f8-b272-4808-9733-e38073564379">

**Comment by mcoker** [comment]
Looks like this may have since been resolved. Good to close @srambach?
