### ISSUE TITLE
Pull updated design tokens from Figma

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly#6472]
As discussed with @mcoker and @thatblindgeye, I've added semantic spacer tokens to support plain buttons and controls. They've been added to the Figma file and need to be brought into the tokens repo! 

**added** 

- global/spacer/control/horizontal/plain
- global/spacer/control/vertical/plain
- global/spacer/button/horizontal/plain
- global/spacer/button/vertical/plain
- "/default" to the existing global/spacer/control/horizontal and global/spacer/control/vertical tokens for better organization.

I also updated the disabled base token and semantic token values to improve contrast in light and dark themes (I didn't touch the names of the tokens, just the values).

FYI @srambach

**Comment by srambach** [comment]
New PR coming to add the compact spacers.

**Comment by srambach** [comment]
Closed by #6476
