### ISSUE TITLE
Wrong text colour of Search bar input in table of demo in Dark Mode

### ISSUE THREAD

**Issue by yamalameyooooo** [patternfly/patternfly#6512]
The text colour on the input field of the search bar in the demo is #f2f2f2 which kind-off mixes with #ffffff of the background and is unable to read the text input

<img width="517" alt="Screenshot 2024-04-04 at 1 43 20 PM" src="https://github.com/patternfly/patternfly/assets/52189801/95cd030a-5abc-493b-8329-d6b05485ca62">

Issue can be reproducible at https://pf-v6-seed-demo.surge.sh/inventory

**Comment by kmcfaul** [comment]
Should be resolved by updating the seed project to the latest alphas.

**Comment by evwilkin** [comment]
Confirmed that this is currently fixed but the V6 demo preview is outdated, working to update the demo link.

**Comment by evwilkin** [comment]
Our preview link tool Surge is not letting is update the code at that existing preview 👎  so for now here's a preview reflecting the current code:

- https://cut-scarecrow-pf-demo-v6.surge.sh/inventory

We are working towards a second Alpha release and may need to host a new preview link for the demo if we can't get around this Surge permissions issue.
