### ISSUE TITLE
Navigation - Add the ability to include icons in top level nav

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6527]
Follow up to https://github.com/patternfly/patternfly-design/issues/1287

Design would like the option to include icons on the top level navigation as a simple visual identifier for different Nav elements.  

Figma mocks can be found [here](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?type=design&node-id=21880-15917&mode=dev).

Icons should inherit the same size and colors as the text in the nav item. The Gap between the icon and text is an extra-small spacer.

Default state: Icon - (Icon/color/subtle)  |  Text - (text/color/subtle)
Hover state: Icon - (Icon/color/subtle)  |  Text - (text/color/subtle)
Selected state: Icon - (Icon/color/regular)  |  Text - (text/color/regular)

![Screenshot 2024-04-05 at 4 06 25 PM](https://github.com/patternfly/patternfly/assets/28658548/860f9658-a17b-4fa3-a5f4-59115012ab0c)

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6704
