### ISSUE TITLE
MenuToggle - add new modifier for split action toggle button text

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly#6534]
Part of https://github.com/patternfly/patternfly-react/pull/10256

If a split action toggle button has text, it will need a display:flex and some left-padding (inline styling in the react PR).

The hbs of MenuToggleCheckbox also needs to be updated to have a `span` nested inside the `label` (instead of a `label` in the `label`).

**Comment by mcoker** [comment]
@kmcfaul do we need follow-ups in react for this and the [same change for v6](https://github.com/patternfly/patternfly/issues/6778)?
