### ISSUE TITLE
Selected expanded accordion is cramped

### ISSUE THREAD

**Issue by Venefilyn** [patternfly/patternfly#6552]
**Please describe the issue**
Looking at the PF6 accordion when an item is selected it feels very cramped and closed together. Unselecting the item makes it look a lot better

**Are there visuals for this issue? Please provide screenshots**
Cramped if you just opened one
![image](https://github.com/patternfly/patternfly/assets/6598829/e78e50f6-f4ca-4d08-9758-c4d5402fedc9)

Deselecting the active element, which looks a lot better
![image](https://github.com/patternfly/patternfly/assets/6598829/b5de62a2-cddc-4cb1-b352-2c0ea1ed6d0c)

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**
https://staging-v6.patternfly.org/components/accordion

**Any other information?**

**Comment by mcoker** [comment]
cc @lboehling @andrew-ronaldson wdyt?

**Comment by kmcfaul** [comment]
The focus styling is intentional
