### ISSUE TITLE
Badge/Button - adjust colors of badge on disabled buttons

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6558]
**Please describe the issue**
@lboehling says: i updated the border--color--disabled semantic token to reference the disabled--200 base token. I also added the border color disabled to the disabled badge. so the disabled badge on disabled button should look like this!

![image](https://github.com/patternfly/patternfly/assets/19825616/1e24088c-644d-48a7-ab94-537c2e184aed)

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6616
