### ISSUE TITLE
Workspace. Configure handlebars to allow variable creation.

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#656]
```
var classes = '';

{{#> if component--size=="xxl"}}
  classes += ' pf-m-xxl'
{{/if}}

<div class="component-class {{classes}}">
  stuff
  {{> @partial-block}}
</div>
```
@matthewcarleton

**Comment by mcoker** [comment]
@mattnolting do you want to keep this open? It can be achieved on a basic level by nesting hbs blocks, and can `concat()` can `+=` strings?

**Comment by mattnolting** [comment]
@mcoker I think the ability to match conditional params is still valid and would allow us to write much more explicit and efficient handlebars examples. The attached snippet may not totally cover the request, but rather than creating an `--IsSomething` prop and checking if it's true, evaluating the `component--type` (as an example) value would allow us to create a single prop and just pass new values to it. So instead of `IsSomething="true"`, `component--type="primary"` or `component--type="[primary, display-large]"` would allow us to create a more versatile property that could add multiple settings to `.hbs` templates.

**Comment by mcoker** [comment]
@redallen @evwilkin wdyt, is this something we could consider adding to the workspace?

**Comment by redallen** [comment]
AFAIK, Handlebars doesn't allow defining variables in templates. That makes implementing something like this very difficult.

Something that could be done after shipping preview.patternfly.org and backporting the workspace here to Core is supporting multiple templating engines. For example, Pug and EJS allows defining variables in templates. There would be the extra cost of having two templating languages unless everything were to be converted, but if it improves readability/maintainability I think it's a worthwhile change.

**Comment by mattnolting** [comment]
Ignoring variable creation... Can we enhance handlebars to evaluate expressions as well as single values?

```
{{#if name == 'foo'}}
  <foo stuff>
{{else if name == 'bar'}}
  <bar stuff>
{{else}}
  <stuff>
{{/if}}
```

**Comment by redallen** [comment]
Yes, it's possible like this:
```js
Handlebars.registerHelper('equals', function (v1, v2) {
  return v1 === v2;
});
```

to have a syntax like this:
```hbs
{{#if (equals name "foo")}}
  <foo stuff>
{{else if (equals name "bar")}}
  <bar stuff>
{{else}}
  <stuff>
{{/if}}
```

I think this to be a misuse of Handlebars, though. It really prevents you from evaluating JS expressions.
