### ISSUE TITLE
Buttons - Animating transitions on all buttons variants.

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6589]
**Goal**
Adding subtle transition on buttons between default and hover states. 
[Link to Figma annotations](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/branch/YIxfglww1fRdQGclApv1nm/PatternFly-6%3A-Components?type=design&node-id=23613%3A1180&mode=design&t=zeOzDxjxoTCXWQLl-1).

Follow up work could include a Pressed state. Will create another issue when needed.

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6675 🥳
