### ISSUE TITLE
Menu toggle - Animating state transitions and menu panel

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6590]
**Goal**
Adding transitions between Default > Hover > Clicked states. This also includes the behaviour of the menu panel that is triggered by the menu toggle button.

Link to [Figma annotations](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/branch/J0HlG83xKgYoT2pMpCl4SY/PatternFly-6%3A-Components?type=design&node-id=22732%3A26347&mode=design&t=Mmwgp55YUkvDrHUz-1)

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6738
