### ISSUE TITLE
Alerts - Animating the toast alerts behaviours

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6592]
Goal
Follow up to design issue https://github.com/patternfly/patternfly-design/issues/1292

Adding a small jiggle on the menu toggle if it does not pass validation. If this animation is possible, we can create more issues for the other form elements that use validation.

Link to [Figma annotations](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/branch/ORqbrfhmIEkTwphXeX3Iq2/PatternFly-6%3A-Components?type=design&node-id=23637%3A4127&mode=design&t=YQ6fhYv6fAJLn8JT-1)

**Comment by srambach** [comment]
Closed by #6804 and will follow up with #6812
