### ISSUE TITLE
Log viewer updates

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6596]
Follow ups from https://github.com/patternfly/patternfly/pull/6578

* Once highlight text color tokens are added, we should update the highlighted text in log viewer to use them.

**Comment by lboehling** [comment]
https://github.com/patternfly/design-tokens/issues/43 made a follow-up tokens issue. This token has been added to the figma library ✅

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6656
