### ISSUE TITLE
Add CSS vars for breakpoints

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6613]
We removed the CSS vars for breakpoints since we can't use them in `@media` queries, and left only the scss vars. We need to add those back since the react repo uses the CSS vars as a means to get the breakpoint values to do fancy pants scripty things like resize observer, and I imagine products may, too.

https://github.com/patternfly/patternfly-react/blob/029351e0fa402c80a6199e2bd4b28e8c06f17562/packages/react-core/src/components/Page/Page.tsx#L4C8-L4C26

https://github.com/patternfly/patternfly-react/blob/029351e0fa402c80a6199e2bd4b28e8c06f17562/packages/react-core/src/components/Page/Page.tsx#L163-L197

**Comment by srambach** [comment]
Also - let's see if they can be added as a token coming from Figma so they span design-dev.

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/6636
