### ISSUE TITLE
Update utility class example borders

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6619]
https://pf6.patternfly.org/utility-classes/flex

Update border colors to use border tokens. Layouts have been updated so we can borrow that code:

https://github.com/patternfly/patternfly/blob/9a869f899f49ed375022e37fd13b6c20d0fb245e/src/patternfly/layouts/Flex/examples/Flex.css#L1-L6

**Comment by evwilkin** [comment]
Closed by #6621
