### ISSUE TITLE
[PageSection] - change padding for adjacent page sections with the same background color

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly#6631]
**Is this a new component or an extension of an existing one?**
`PageSection` is an existing component.

**Describe the feature**
`PageSection` has multiple variants with different colored backgrounds. The padding all around each section is currently `24px`. When adjacent sections have different color backgrounds, the spacing works well. But when adjacent sections have the same background, it looks like a lot of blank space. This has come up in discussions with our UX where the request was to reduce the spacing between adjacent sections.

While it is easy enough to remove the top padding with an override, us devs want to adhere to the PF prescribed layouts. Therefore this is a request to formally adopt such a layout change in the `PageSection` component.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
![image](https://github.com/patternfly/patternfly/assets/14068621/ee6ec8c2-b733-4ecf-972a-c4c557b19614)

![image](https://github.com/patternfly/patternfly/assets/14068621/81628ca3-b07b-4380-8253-1004a16b0eb8)
vs
![image](https://github.com/patternfly/patternfly/assets/14068621/81c95130-6b6c-4b42-a4d8-1e7c3a4b5440)

**Any other information?**

**Comment by mcoker** [comment]
cc @lboehling

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6766
