### ISSUE TITLE
Overflow menu, toolbar icons 

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6652]
From: [6566](https://github.com/patternfly/patternfly/pull/6566)

https://github.com/patternfly/patternfly/pull/6566#issuecomment-2110986659

* Overflow menu is missing kebab in mobile
* Toolbar icons disappeared

**Comment by srambach** [comment]
For more detail - here are screenshots from regression testing

<img width="1418" alt="image" src="https://github.com/patternfly/patternfly/assets/19825616/475b333a-8c29-447c-a82d-e8d1f610d40e">

<img width="1415" alt="image" src="https://github.com/patternfly/patternfly/assets/19825616/7dcfba50-b4d9-4e62-a90a-212db37b73c9">

**Comment by mattnolting** [comment]
After investigation, the icons above were in an `overflow-menu` where they should've been `pf-v6-c-toolbar__group.pf-m-icon-button-group`. [Toolbar group types example](https://pf6.patternfly.org/components/toolbar#group-types) remains as an example of `icon-button-group`.
