### ISSUE TITLE
Page - allow main container to fill

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6653]
**Describe the feature**
In V6, Page and PageSection components don't fill the page because pf-v6-c-page__main-container does not fill the available height (nor its child pf-v6-c-page__main).

Let's give the option with a `.pf-m-fill` on the main container to fill height and also look at whether any of the other possible components that can go there also need a modifier to fill vertical space.

@jeff-phillips-18 

(clarification: the page should not fill unless we add `.pf-m-fill`)

**Comment by evwilkin** [comment]
Closed by #6832
