### ISSUE TITLE
Bug - Tooltip - left and right positioning causes alignment issues with tooltip

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly#6662]
**Describe the problem**
This is an issue with 
- [ ] Patternfly 5  
- [x] Patternfly 6  
- [ ] other

Please give a clear and concise description of the problem. Which components are affected?

This is visible in PF topology with tooltips. Using the left positioned tooltip reveals gaps in between the tooltip body and arrow.

<img width="171" alt="Screenshot 2024-05-15 at 1 52 29 PM" src="https://github.com/patternfly/patternfly/assets/32821331/9b8c10b9-df39-4339-87ff-76473e718c58">

Examples when using position values that include "left" and "right" in the PF6 workspace (below is "left-start", "left", "left-end"):

<img width="253" alt="Screenshot 2024-05-15 at 3 52 31 PM" src="https://github.com/patternfly/patternfly/assets/32821331/5b5eec43-77ce-4131-9e90-e4054bd600a6">
<img width="250" alt="Screenshot 2024-05-15 at 3 52 36 PM" src="https://github.com/patternfly/patternfly/assets/32821331/45e9b33a-3238-450a-8fc7-65f552d7ab47">
<img width="250" alt="Screenshot 2024-05-15 at 3 52 57 PM" src="https://github.com/patternfly/patternfly/assets/32821331/c3e78168-c4e3-4759-ac60-917eaa58b7b3">

PF5 workspace renders the tooltip as expected for any instances of left or right positioning: 

<img width="251" alt="Screenshot 2024-05-15 at 4 01 16 PM" src="https://github.com/patternfly/patternfly/assets/32821331/0719ffce-0cda-4cb6-a856-34c3dd6f2d64">

<img width="258" alt="Screenshot 2024-05-15 at 4 01 26 PM" src="https://github.com/patternfly/patternfly/assets/32821331/1352102f-093d-4377-ac0f-84caf424a2e4">
<img width="254" alt="Screenshot 2024-05-15 at 4 01 20 PM" src="https://github.com/patternfly/patternfly/assets/32821331/4db6ffa5-454d-49bf-bd57-da352549125c">

**How do you reproduce the problem?**
Provide steps to reproduce. A [codepen](http://codepen.io) or [codesandbox](https://codesandbox.io/) demonstrating the problem is appreciated.

https://staging-v6.patternfly.org/components/tooltip#basic

Set "position" to any left or right type.

**Expected behavior**
A clear and concise description of the expected behavior.
No gaps - tooltip is aligned properly

**Is this issue blocking you?**
List the workaround if there is one.

**Screenshots**
If applicable, add screenshots to help explain the issue.
See above

**What is your product and what release date are you targeting?**
Topology v6 alpha upgrade

**Comment by jenny-s51** [comment]
Hi @mcoker - thank you for taking a look! 

I've noticed something interesting – while the issue seems to no longer exist on the staging site, it's still popping up in the Topology demo app with the latest alphas, but only on Chrome (currently rocking version 125.0.6422.61). Safari and Firefox render the tooltips as expected, though.

Sometimes my Chrome browser is a bit quirky and renders different styling/alignment relative to other browsers, so we might be able to just chalk it up to that and close out this issue if it cannot be reproduced. What are your thoughts?

Thanks for your help as always!

**Comment by mcoker** [comment]
Tracked this down to an issue with the default browser font size (1rem), likely due to use of a combo of pixels and rems in the tooltip styles not scaling properly when the doc font size is customized.

Not a huge problem, but this is something we should test at some point and see where we have bugs, which should be pretty easily fixed in most cases.

FWIW the browser default font size was modified in chrome -> preferences -> appearance 

<img width="742" alt="Screenshot 2024-05-17 at 3 27 46 PM" src="https://github.com/patternfly/patternfly/assets/35148959/cd9bd202-6be1-43d4-88de-272389a594ef">
