### ISSUE TITLE
Table - row double border on mobile

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6667]
Double bottom-border on non-expanded rows in expandable tables. Here's where the borders are coming from

https://github.com/patternfly/patternfly/blob/c11387c8b1dea7e573beb0a7f5c4c12a51c1080a/src/patternfly/components/Table/table.scss#L1060-L1062

https://github.com/patternfly/patternfly/blob/c11387c8b1dea7e573beb0a7f5c4c12a51c1080a/src/patternfly/components/Table/table-grid.scss#L185-L188

<img width="625" alt="Screenshot 2024-05-15 at 7 54 16 PM" src="https://github.com/patternfly/patternfly/assets/35148959/33cc8cc6-45d2-4824-9383-316c1c6b382a">

**Comment by evwilkin** [comment]
Closing in favor of #6556 - moving comments to that issue.
