### ISSUE TITLE
Rename the custom/local tokens stylesheet

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6682]
Right now this is called `tokens-font.scss` since it initially held font styles that were not defined in figma, but that file has grown to include a lot of custom/local tokens. Naming things is never fun - what about `tokens-local`? cc @srambach @lboehling 

https://github.com/patternfly/patternfly/blob/v6/src/patternfly/base/tokens/tokens-font.scss

**Comment by srambach** [comment]
I think I like local. The only other one I can see from [here](https://classnames.paulrobertlloyd.com/publishing/) is "[auxiliary](https://www.wordnik.com/words/auxiliary)" And I have a hard time spelling that ;-) 
From there I also see "helper" or "supplemental"
What resonates for you? @mcoker @lboehling

**Comment by mcoker** [comment]
+1 to local

**Comment by lboehling** [comment]
I also like local!

**Comment by srambach** [comment]
Closed by #6711
