### ISSUE TITLE
Page - main container should not fill viewport height

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6712]
Looks like there was a regression in https://github.com/patternfly/patternfly/pull/6611 that made the page container fill the available height by default, and we need to revert that back to the previous behavior. We'll just want to make sure that the wizard container scrolls properly as noted in https://github.com/patternfly/patternfly/issues/6314

FWIW, this his how it should look

<img width="1526" alt="Screenshot 2024-05-29 at 3 47 37 PM" src="https://github.com/patternfly/patternfly/assets/35148959/37b9cafa-f058-4da6-abc0-b3f721a25ad1">

And what it looks like now

<img width="1526" alt="Screenshot 2024-05-29 at 3 47 23 PM" src="https://github.com/patternfly/patternfly/assets/35148959/ec8a533b-a0f0-4daa-867c-4d1eb512d8e1">

related https://github.com/patternfly/patternfly/issues/6653

**Comment by evwilkin** [comment]
Closed by #6832
