### ISSUE TITLE
Page main container: make border optional

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#6714]
Without the 8 pixel border around the page main container, the scrollbar would sit flush against the edge of the page section.

It would however, make it so that the scrollbar handle could flow out of the page section container. It might require changing which element the scrollbar is attached to so that the border radius will also clip the scrollbar handle.

![Screenshot 2024-05-29 at 5 05 04 PM](https://github.com/patternfly/patternfly/assets/26305082/14743fa6-5cb5-468a-8872-cbe6ebd3689f)

If it's optional, then when someone has a fixed header or footer page section, then the scrollbar clipping wouldn't be an issue at all. Ansible requested this feature.

**Comment by mcoker** [comment]
@nicolethoen since there have been a bunch of changes to the scrollbar, do you know if this issue is still relevant? Feel free to close if it isn't.

**Comment by nicolethoen** [comment]
looking good to me :)
