### ISSUE TITLE
Bug - Timestamp - Font color & size don't use the default variables

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#6729]
**Describe the problem**
This is an issue with 
- [x] Patternfly 5  
- [x] Patternfly 6  
- [ ] other

Please give a clear and concise description of the problem. Which components are affected?

**How do you reproduce the problem?**
It looks like the example in the design document shows the contents using the default font color, but in the HTML and React components, the font color is gray. The font size is also small rather than the default medium.

**Expected behavior**
I would expect contents to use the default font color and size to be applied by default, and to allow consumers to decide if different styles are needed for their specific designs.

**Is this issue blocking you?**
The difference in presentation results in confusion within our team. Our designs are currently reflecting what's shown in the react/html examples. If this isn't expected from a PF design perspective, it's possible that the end result would not match what PF design would recommend. 

**Screenshots**
![image](https://github.com/patternfly/patternfly/assets/21063328/d692837c-78a4-4611-8b7f-52954d14c93a)

**What is your product and what release date are you targeting?**
RHOAI, June 17

**Comment by mcoker** [comment]
cc @andrew-ronaldson @lboehling

**Comment by andrew-ronaldson** [comment]
@mcoker want me to take a look at this in core?

**Comment by mcoker** [comment]
@andrew-ronaldson yes sir, thank you!

**Comment by mcoker** [comment]
Closed by https://github.com/patternfly/patternfly/pull/6953
