### ISSUE TITLE
Panel - Penta styling

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6732]
**Is this a new component or an extension of an existing one?**
Panel

**Describe the feature**
It doesn't look like Panel has any Penta-y looking styling applied to it on  both [V6 core staging](https://pf6.patternfly.org/components/panel) as well as React. cc @andrew-ronaldson @lboehling @kaylachumley want to check if this is intentional or if it got overlooked?

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

**Any other information?**

**Comment by kaylachumley** [comment]
I am not entirely sure - @lboehling Any more insight on panel?

**Comment by thatblindgeye** [comment]
Per @lboehling add a border radius md

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6741
