### ISSUE TITLE
Menu - search box padding

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6750]
Search left/right padding is 16px (md) and everything else in menu is 24px (lg). Seems like we should update the search box to match - @lboehling can you confirm?

**Comment by lboehling** [comment]
hey @mcoker! I reviewed this with the design team and we'd like to keep the [menu search box padding](https://staging-v6.patternfly.org/components/menus/menu/html#scrollable-menu-with-search-and-footer) as is! The search box gets really cramped at narrower menu widths with the 24px padding, and we like how the search icon optically aligns better with the menu item content with the 16px padding.

**Comment by mcoker** [comment]
@lboehling awesome, thanks!
