### ISSUE TITLE
Update text tokens across a few component titles

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly#6754]
See design issue -- (https://github.com/patternfly/patternfly-design-kit/issues/717). Some icon sizes may need to be adjust to match the updated title sizes. 

> **Update text tokens for alert titles, notification drawer item titles, hint title, default card title & popover titles.** 
> This is a result of a few design reviews and some direction from the DPO team.   Can we update the following text tokens? 
> 
> **Alert titles — inline, toast, and plain**
> 
> - update `font—family—heading` to `font—family—body`
> - update `Font —weight—heading` to `font—weight—body—bold` 
> - update `font—size—heading—xs` to `font—size—body—default` 
> 
> **Notification drawer item titles** 
> 
> - update `font—family—heading` to `font—family—body`
> - update `Font —weight—heading` to `font—weight—body—bold `
> - update `font—size—heading—xs` to `font—size—body—default` 
> 
> **Hint titles** 
> 
> - update `font—family—heading` to `font—family—body`
> - update `Font —weight—heading` to `font—weight—body—bold `
> - update `font—size—heading—xs` to `font—size—body—default` 
> 
> **Popover titles** 
> 
> - update `font—size—body—lg` to `font—size—body—default` 
> 
> **Card title — DEFAULT size** 
> 
> - update `font—size—heading—sm` to `font—size—heading—xs `

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6775
