### ISSUE TITLE
Hint: Update actions button position to match alert styling

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6763]
The close button on alerts has a special calc to reduce the padding by -8px to offset the plain button styling.

Can we please mimic this on the Actions button of the Hint component.

**Alert**
![Screenshot 2024-06-10 at 4 17 50 PM](https://github.com/patternfly/patternfly/assets/28658548/560747e6-6182-4f74-94e6-9e40011ea280)

**Comment by mcoker** [comment]
@andrew-ronaldson this should be fixed now via https://github.com/patternfly/patternfly/issues/6116 and https://github.com/patternfly/patternfly/pull/6708. It isn't on org/staging yet, but you can see it in the core workspace - https://pf6.patternfly.org/components/hint

**Comment by andrew-ronaldson** [comment]
Closed with [#6116](https://github.com/patternfly/patternfly/issues/6116) and [6708](https://github.com/patternfly/patternfly/pull/6708)
