### ISSUE TITLE
Navigation: Text-decoration: none on hover state

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6765]
The nav-items are assuming the global a:hover underline styling. I'd like to add a specific property to nav-item/link to remove that underline styling.

![Screenshot 2024-06-10 at 4 39 02 PM](https://github.com/patternfly/patternfly/assets/28658548/a7dc67ea-a351-40e3-87ea-5ab7f2875b34)

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6787
