### ISSUE TITLE
A Dropdown with many items expands outside the main-container

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly#6772]
`pf-v6-c-page__main-container` does not expand to contain `Menu`

**Are there visuals for this issue? Please provide screenshots**
![Screenshot 2024-06-11 at 12 20 25 PM](https://github.com/patternfly/patternfly/assets/1874151/f0c7608d-2814-4986-a707-8525be06e324)
**Sandbox test case**
https://codesandbox.io/p/sandbox/charming-fast-k6hc3d?file=%2Findex.tsx

 ----

_Double scrollbars_
![Screenshot 2024-06-11 at 3 39 26 PM](https://github.com/patternfly/patternfly/assets/1874151/821ed49e-bcdb-412d-8ff0-5a76f7133d05)
**Sandbox test case**
https://codesandbox.io/p/sandbox/eloquent-beaver-jvsx9j?file=%2Findex.tsx%3A254%2C44

**Video of issue**
https://github.com/patternfly/patternfly/assets/1874151/045b618e-8e35-4552-b306-31457298bc39

**Comment by mcoker** [comment]
@sg00dwin for this issue, I would suggest the same approach in https://github.com/patternfly/patternfly/issues/6773#issuecomment-2231190429 to use a scrollable menu. Would that solution work for you for this issue, too?

**Comment by sg00dwin** [comment]
@mcoker that option works as a solution... Something to possibly assess, since tall menus can cause breakage in a variety of layout use cases, should should Dropdowns and Selects default to having isScrollable with max-height to curtail those possibilities.
