### ISSUE TITLE
A Dropdown with many Menu items, within additionalGroupedContent that is set to sticky, is cut off and can cause sticky group to scroll.

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly#6773]
**Please describe the issue**
A Dropdown menu with many items (40) that is within `Page` `additionalGroupedContent` set to `sticky` does not display all items.

**Are there visuals for this issue? Please provide screenshots**

**_Multiple scenarios_**

1. Pages with full scrollable content, the menu is cut off below the page.
![Screenshot 2024-06-11 at 3 03 56 PM](https://github.com/patternfly/patternfly/assets/1874151/6f4ffd16-c54a-4d0f-b0b7-7513c9e8b639)

2. Pages with small amounts of content, the menu is cut off below the page and the sticky group scrolls.
![Screenshot 2024-06-11 at 3 05 44 PM](https://github.com/patternfly/patternfly/assets/1874151/a34ef6e1-ce73-4aea-b491-9fa5b52d4a36)

**Video of scenarios**
https://github.com/patternfly/patternfly/assets/1874151/5ed5c352-9ef1-4db7-9891-17766d81b1d3

https://github.com/patternfly/patternfly/assets/1874151/5ed5c352-9ef1-4db7-9891-17766d81b1d3

----

**Sandbox test case**
https://codesandbox.io/p/sandbox/hopeful-diffie-mwqv7x?file=%2Findex.tsx%3A469%2C34

**Comment by mcoker** [comment]
@sg00dwin for long menus like that, our recommendation would be to use `isScrollable` on `<Dropdown>`, which will limit the menu height to our default scrollable height (300px currently) and add a scrollbar. The default height can be modified by setting the `maxMenuHeight` prop. Will that work for your use case?

**Comment by sg00dwin** [comment]
> @sg00dwin for long menus like that, our recommendation would be to use `isScrollable` on `<Dropdown>`, which will limit the menu height to our default scrollable height (300px currently) and add a scrollbar. The default height can be modified by setting the `maxMenuHeight` prop. Will that work for your use case?

@mcoker that works in this case
