### ISSUE TITLE
Bug - MenuToggle - split toggle with checkbox has double label elements

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6776]
**Describe the problem**
This is an issue with 
- [x] Patternfly 5  
- [x] Patternfly 6  
- [ ] other

As noted in https://github.com/patternfly/patternfly/issues/6534, the handlebars for a MenuToggleCheck is rendering a `label` element inside of a `label` element when the menu toggle text is part of the checkbox. 

Additionally, the `for` attribute for that implementation isn't being properly linked to the input.

**How do you reproduce the problem?**
Inspect the HTML of the split toggles in the [split button checkbox with toggle text example](https://www.patternfly.org/components/menus/menu-toggle/html#split-button-checkbox-with-toggle-text) and notice that there is a label inside of a label element. The inner label should be rendered as a span element.

Also try clicking the text in the split button toggle for the second part of this issue.

**Expected behavior**
A label is not rendered inside a label.

Clicking the label text toggles the checkbox.

**Is this issue blocking you?**
List the workaround if there is one.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6923
