### ISSUE TITLE
Table: compound expandable content missing padding

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6782]
Followup for: [10603](https://github.com/patternfly/patternfly-react/pull/10603#issue-2348914372)

![image](https://github.com/patternfly/patternfly/assets/5385435/b79849db-64ad-4a29-9458-5e2fcca37267)

[Lines 950-953)](https://github.com/patternfly/patternfly/blob/v6/src/patternfly/components/Table/table.scss#L950-L953): Should be removed. 

This will result in:

<img width="902" alt="Screenshot 2024-06-12 at 11 17 05 AM" src="https://github.com/patternfly/patternfly/assets/5385435/c3523233-7ff4-4ab3-a579-c9ecd46575e5">

**Before:**

<img width="861" alt="Screenshot 2024-06-12 at 11 16 07 AM" src="https://github.com/patternfly/patternfly/assets/5385435/1d8794bf-1345-4edc-a2a0-1724fe6a3eba">

**After:**

<img width="879" alt="Screenshot 2024-06-12 at 11 16 16 AM" src="https://github.com/patternfly/patternfly/assets/5385435/6a0f945e-e179-4093-8e7f-412a467ab1e7">

@andrew-ronaldson @lboehling Is this an acceptable update?

**Comment by andrew-ronaldson** [comment]
The **After** screenshot has too much margin  above the expandable content block. trying to understand this. if we remove those lines you suggested it fixes one but _breaks_ the other?

**Comment by mcoker** [comment]
@mattnolting can we scope the padding change to just expandable content for compound expansion (where it looks like the bug is)

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6958
