### ISSUE TITLE
Data list: Remove Card styling on Data list demos.

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6795]
All HTML Demos for the data list component are wrapped in a card. Can we please remove that extra wrapper from the demos.

https://staging-v6.patternfly.org/components/data-list/html-demos

<img width="1374" alt="Screenshot 2024-06-13 at 4 21 22 PM" src="https://github.com/patternfly/patternfly/assets/28658548/4f24ff24-0a99-471f-abe3-c7d7a6513826">

**Comment by mcoker** [comment]
You should be able to remove `{{#> card}}` from these demos https://github.com/patternfly/patternfly/blob/b57499ddc4f5315124d7e94c651642d2f46b75b4/src/patternfly/demos/DataList/examples/DataList.md?plain=1#L14

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6811
