### ISSUE TITLE
Bug - Wizard v6 - add styling for wizard main/body

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6809]
**Describe the problem**
This is an issue with 
- [ ] Patternfly 5  
- [x] Patternfly 6  
- [ ] other

Pre-followup to https://github.com/patternfly/patternfly-react/pull/10637. React was previously allowing WizardBody to be omitted by passing `body={null}` to WizardStep. The linked PR removes that option, but we needed additional styling to have the content fill its container.

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6807
