### ISSUE TITLE
Toolbar followup

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6827]
- [ ] Multiple content padding sections have no padding as a result of [#6766](https://github.com/patternfly/patternfly/commit/82ebaf8add2f392873d62c79309a8744c05d2e3c#diff-04ccd6c8202d765341068296fa23550c82f714d91342163ee9329f44f3bee512R40). The solution is straightforward, use `row-gap` on `toolbar` instead of section padding. 

![Screenshot 2024-06-25 at 12 00 47 PM](https://github.com/patternfly/patternfly/assets/5385435/5376d9d7-3a21-42a5-b08d-ea26bee55c22)

- [ ] Expandable content will need padding added back 

![Screenshot 2024-06-25 at 12 21 02 PM](https://github.com/patternfly/patternfly/assets/5385435/a4c6615a-ef4b-4dee-a939-ba5727db13df)

- [ ] Mobile filter presentation needs some attention, possible an alternate style for `label-group`. Following up with @andrew-ronaldson @lboehling @kaylachumley for design direction.

![Screenshot 2024-06-25 at 12 13 20 PM](https://github.com/patternfly/patternfly/assets/5385435/eb98b0cd-ce64-401e-ad23-bfbdf52ee961)

- [ ] update [`align-self` to `align-items`](https://github.com/patternfly/patternfly/blob/v6/src/patternfly/components/Toolbar/toolbar.scss#L291) for `toolbar-group` and `toolbar-item`

- [ ] Update [breakpoint map](https://github.com/patternfly/patternfly/blob/v6/src/patternfly/components/Toolbar/toolbar.scss#L10) to include all spacers

- [ ] Update all tokens to new tokens

React followup:

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6838
