### ISSUE TITLE
Regression tests - Increase mobile width to 480

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6828]
**Describe the enhancement or change**
Our mobile regression tests are narrower than seems necessary. This issue should increase them to 480px.

**Comment by mcoker** [comment]
cc @andrew-ronaldson @lboehling is there a viewport size/width y'all consider the smallest we would support that we should use for the "mobile" version of our screenshot testing?

FYI here are the viewport sizes the visual regression tool is configured to use https://github.com/patternfly/patternfly/blob/4b102468ba0be521304b29d537746dfcf831177a/backstop.config.js#L3-L14

And our smallest viewport breakpoint is 576px https://github.com/patternfly/patternfly/blob/4b102468ba0be521304b29d537746dfcf831177a/src/patternfly/sass-utilities/scss-variables.scss#L32

**Comment by srambach** [comment]
Here's a report showing all the mobile views https://drive.google.com/file/d/1LZFxUWUj797SE_HouR3kjv13wppsnLzb/view?usp=sharing

**Comment by srambach** [comment]
Mobile views at 360px at https://drive.google.com/file/d/1sT5E7W0fbSs5-RRbL_cNmPlC8CAXE1SM/view?usp=sharing

Also, Chrome inspector options have iPhoneSE at 375 and Samsung GalaxyS8+ at 360 as the narrowest (other than the Galaxy fold)

You can see a white edge along the 360px where the kebab button is pushing it out. At 375, it fits.

<img width="2158" alt="image" src="https://github.com/patternfly/patternfly/assets/19825616/01cbc832-4b30-4eee-ad0c-b2892c7d7806">

**Comment by mcoker** [comment]
Just an aside, I don't think the "overview" and "services" toggles should be there at this narrow viewport. I haven't dug in but I suspect they were added to one of the example/demo templates we use and weren't properly hidden or accounted for in the mobile view. So if we prefer `360px` and those toggles are overflowing the page/masthead width, we can fix the toggles.

**Comment by mcoker** [comment]
Updated to 360, closed by https://github.com/patternfly/patternfly/pull/6837
