### ISSUE TITLE
Ensure scrollbars are presenting as expected

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6834]
**Describe the enhancement or change**
Followup to investigation/discussion in https://github.com/patternfly/patternfly/issues/6045#issuecomment-2192500304

We should ensure that scrollbars are being included in any overflow: hidden or clip path on containers to achieve the effect that the scrollbars are being rounded as well. This will include the Page component where we currently visually have the scrollbar offset from the container.

**Is this request originating from a Red Hat product team? If so, which ones and is there any sort of deadline for this enhancement?**

**Any other information?**

**Comment by mcoker** [comment]
@andrew-ronaldson @lboehling I'm good closing this issue since we updated the scrollbar styling. Do y'all want to keep it around? Maybe to maybe do an audit/review at some point?

**Comment by andrew-ronaldson** [comment]
Good to close!
