### ISSUE TITLE
Wizard - nav items need a success status

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#6843]
In order to implement the Quickstart designs in v6, we need a pf-m-success modifier to create a green checkbox icon in lieu of the circled number ::before on the nav item button. 

Much link the pf-m-error modifier applies the styles needed to render an error icon on the wizard step in this demo: https://pf6.patternfly.org/components/wizard/html/error-on-step/

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6844
