### ISSUE TITLE
Replace remaining dropdowns with menu toggles

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6848]
There are a few dropdowns in examples and demos. Replace these with menu toggles.

here's one:
https://staging-v6.patternfly.org/components/input-group/html

**Comment by mcoker** [comment]
@srambach that's staging, which likely just doesn't have the latest core. Here's that link on core - https://pf6.patternfly.org/components/input-group

**Comment by srambach** [comment]
Already done in the latest 🎉
