### ISSUE TITLE
Table - tree table first column heading truncated

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6865]
**Please describe the issue**
On a tree table, the first column's heading is truncated on narrow viewports.
In v5, this heading was omitted completely.

https://pf6.patternfly.org/components/table/#tree-table-basic

<img width="523" alt="image" src="https://github.com/patternfly/patternfly/assets/19825616/96da6655-05b0-4185-bd8d-8c75c8677643">

**Comment by mcoker** [comment]
Follow up from design is to remove this column header in the grid view.

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6868
