### ISSUE TITLE
Form control - update status border color on hover

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6866]
~~@lboehling @andrew-ronaldson currently the border color for status form control elements (text input, select, textarea) does not change on hover/focus - should the border color change on hover/focus to the hover status color?~~ 

(confirmed below) let's update the form control components so their status border color changes on hover/focus, which will mimic the text input group.

**Comment by andrew-ronaldson** [comment]
Feels like it should match the behaviour of the non status form controls (EX: `--pf-t--global--border--color--status--success--hover;` )

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6924
