### ISSUE TITLE
TextInputGroup - alignment for utilities is off

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6867]
**Please describe the issue**
Followup to comment https://github.com/patternfly/patternfly/pull/6802#pullrequestreview-2141654781. The alignment of the "close" button inside a TIG such as with filters is centered, but should probably be aligned at the start. Badges may need to be taken into consideration as well, though.

**Are there visuals for this issue? Please provide screenshots**

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**

**Any other information?**

**Comment by mcoker** [comment]
cc @andrew-ronaldson @srambach is this something we would like to try and get in for the final release?

**Comment by andrew-ronaldson** [comment]
Closed as @andrew-ronaldson silliness
