### ISSUE TITLE
Review banner link color/styles

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6907]
We're overriding styles for regular links and inline-link buttons in the banner component, and I'm wondering if we need to continue to for v6 and if there are any changes we need to make. cc @lboehling @andrew-ronaldson

**Comment by andrew-ronaldson** [comment]
@andrew-ronaldson

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6953
