### ISSUE TITLE
PF6: Performance is horrible with Firefox devtools (this is not a problem in PF5)

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#6913]
**Please describe the issue**

1. Visit the PF6 staging website @ https://staging-v6.patternfly.org/ in Firefox. (Or any component page. Every page seems affected)
2. Open the developer tools (F12 or right-click and select an element)
3. Try to select an element to inspect.
4. Notice several seconds of the browser being frozen.

Resizing the window also takes a very long time. This is also a bit janky in Chrome now too.

Additionally, my CPU fan kicks on and spins up.

**Any other information?**

This wasn't a problem in PF5.

As we ship Firefox as _the browser for our own products at Red Hat_ and it's _what our customers use in RHEL_, we need to develop for and test for Firefox as a tier 1 browser. (It's also the right thing to do overall, to support major browsers.) Having its development tools being this slow makes it unusable in PF6.

There was something (or some things) introduced in PF6 that was not in PF5 that causes massive performance penalties. 

Is there anything listening for browser resizes and/or trying to compute layout in JavaScript instead of using CSS? That would dramatically affect performance like this, and it would affect people with slower computers and those using mobile devices (phones and tablets) as well as us developers.

**Comment by garrett** [comment]
I've asked the team I work with in the Cockpit project (RHEL Web Console) to check and verify that they have these issues as well. They do. This is not isolated to my work laptop.

While I know this is (so far) Firefox on Linux; I am not sure how it is on macOS or Windows. It is probably similar, but haven't been able to check yet.

But even Firefox on Linux is enough to raise huge warning sirens here:

- Firefox is our official browser in RHEL (specifically Firefox Extended Service Release in RHEL)
- Red Hat is full of developers making the software we ship to customers (many using RHEL, many using Fedora, some using other systems)
- we're targeting our web apps to also work on RHEL

...so it's important that this major performance regression is addressed.

**Comment by garrett** [comment]
In Slack, @srambach mentioned that people on the PatternFly team have seen this problem on macOS/Chrome and have been talking about investigating it.

Hopefully running `git bisect` would work to help find the problem! Best of luck! I'm happy to re-test on my end too; just let me know if/when there something to test. Thanks!

**Comment by apollo13** [comment]
I am seeing the same in my project. So it is not just a cockpit specific issue. Chrome/ium performs a bit better but Firefox is basically unbearable.

**Comment by garrett** [comment]
To be clear: We don't see this in Cockpit, as we aren't using PatternFly 6 yet — I asked them to check out the PF6 docs site. It'll take a lot more effort to switch Cockpit to PF6. We'll _eventually_ upgrade at some point in the future.

(I was looking into PF6 for other reasons and noticed this huge performance issue on the staging site, on every page. It _will_ affect _everything_ using PatternFly 6.)

As far as Cockpit is concerned, this will be a nightmare, as many of us use Firefox by default for development (as it is what RHEL customers will see, and many of us prefer using Firefox, as it's the only non-Google browser engine aside from WebKit based ones like GNOME Web and Safari). So hopefully it'll be figured out and fixed soon. I'd suggest marking this as critical and a release blocker. Hopefully there isn't a fundamental problem with PF6, but there might be. But PF6 should not be released in this state regardless.

Thanks for confirming that it happens to you too, @apollo13! The more folks saying that they also see this problem, the more visibility this issue might get.

**Comment by apollo13** [comment]
@srambach I have upgraded my site to [6.0.0-prerelease.13](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-prerelease.13) and while still slow (changing between tags in the inspector still takes 1-3 seconds to update the rules pane) it is usable. Thanks!

**Comment by garrett** [comment]
Thanks for working on this further!

It's still painfully slow on Firefox 130.0.1. It's definitely _better_, but we're talking multiple seconds of waiting when trying to interact with widgets on the site.

And, while it's nice that it's less slow in newer versions of Firefox, those aren't the versions we're shipping to customers. They're stuck on Firefox "ESR" (Extended Support Release) @ https://www.mozilla.org/en-US/firefox/enterprise/ which is 115.14.0esr.

https://whattrainisitnow.com/calendar/

It won't be upgraded to a newer version of Firefox until April 1 2025, and then it'll be bumped up to version 128.9. 

And that version will be replaced by 140.3 in September 16... yes, it'll be a year from now before our customers will see the speed improvements in Firefox that you're talking about... and as pointed out above, PF6 is still slow in current mainline Firefox 130 whereas PF5 is not.

[PF6-Firefox-20240923-1720.webm](https://github.com/user-attachments/assets/b5ff76ad-0fc1-4f18-a013-9de94cc15ffa)

Also, it seems like the site isn't fully loading? So I can't even really test it at the moment, but if it were loading and rendering the components, then it'd be even slower. I didn't get to the part where I would inspect widgets, as those aren't even loading right now, so this is mainly a resize test.

This is on the highest spec laptop available at Red Hat as of a couple months ago, in the latest version of Firefox. I'd late to see this on any laptop that isn't "the latest and greatest".

**Comment by srambach** [comment]
Hi @garrett. Thanks for the info about the ESR release. I think the day you tested on core-staging (which is a surge site) was a day where surge was experiencing an outage. It's actually surprising the page came up at all! We now have the change on https://staging.patternfly.org/, which is not a surge site, so if you have a chance, it's worth another look.
We've set up and tested on Fedora and ubuntu with both FF 130 and 115ESR and are not seeing any significant delay in devtools performance to start up and view elements and styles. I was using rapidly resizing the window/responsive view as a test until I realized that it's just an excellent way to bring devtools to its knees on a great many sites.

**Comment by srambach** [comment]
Closing this, and we will continue to monitor performance moving forward.

**Comment by garrett** [comment]
Hey, thanks. I tried it out and the performance was much better @ https://staging.patternfly.org/. There is still some odd resizing slowness... but not at all to the same degree as what I shared earlier. I think it's probably at least partly due to the flakiness of the server earlier, where things didn't properly load as a result. (Perhaps it was trying to load things in a loop and/or some JS got really upset that other assumed parts did not load.) Part of the odd resizing slowness seems like the breakpoints aren't working properly; they take a second or two to kick in and then the layout is recalculated. You can feel it, even without devtools open (which is expensive in performance too). However, it'll mostly be devs resizing pages, not people using the software we make.

The much more _important_ parts of interacting with the site and inspecting seemed to work at a reasonable speed, at least after the first DOM selection, at least in the most recent version of Firefox.

It'd be worth it to still find and fix performance problems as there are still noticeable issues, but it _feels_ like they're now "minor" UX hitching versus show-stopper, at least on the demos on the site (in-app can always be different, but there's no way to know about that right now).
