### ISSUE TITLE
Nav - drilldown needs to be updated for v6

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6919]
This is what drilldown looks like currently - https://patternfly-react-v6.surge.sh/components/navigation/react-demos/drilldown-nav/

<img width="1269" alt="Screenshot 2024-07-24 at 1 42 29 PM" src="https://github.com/user-attachments/assets/0b587c48-5ff2-460b-92a7-b147311c1800">

cc @lboehling @andrew-ronaldson

**Comment by andrew-ronaldson** [comment]
https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/vzXMoqvEzjcuDRRZT5HQVk/PatternFly-6%3A-Components?m=auto&t=ixL8wLGcUnaZDhCI-1

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6982
