### ISSUE TITLE
Table favorite - favorite icon button missing styles

### ISSUE THREAD

**Issue by adamviktora** [patternfly/patternfly#6925]
Favorite icons (stars) are not yellow even when clicked (when `.pf-m-favorited` is applied)

![Screenshot 2024-07-25 at 16 40 40](https://github.com/user-attachments/assets/98b7cbd0-a8f4-4ce6-a76f-31216172a3e2)

https://staging-v6.patternfly.org/components/table/html/#favorites-examples

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6926
