### ISSUE TITLE
Bug - [MenuToggle] - [dark theme background color is different from normal Button]

### ISSUE THREAD

**Issue by jelly** [patternfly/patternfly#6933]
**Describe the problem**
This is an issue with 
- [x] Patternfly 5  
- [ ] Patternfly 6  
- [ ] other

We use a MenuToggle and a Button next to each other and in a dark theme the background color of the MenuToggle is different from the Button.

![image](https://github.com/user-attachments/assets/b80849cc-d70a-47f7-85f5-ee9f8450247e)

**How do you reproduce the problem?**

I can't get codesandbox to work with a dark theme so the issue basically is:

```
<>
                  <MenuToggle
                    variant="secondary"
                    icon={<StarIcon />}
                    ref={toggleRef}
                  />
                    <Button
                      variant="plain"
                      icon={<CheckIcon  />}
                    />
</>
```

**Expected behavior**

I expect both background colors to be consistent and the same colour.

**Is this issue blocking you?**

No, we will apply a CSS workaround.

**Screenshots**

See above.

**What is your environment?**
 - OS: Linux
 - Browser chrome

**What is your product and what release date are you targeting?**

Cockpit-files

**Any other information?**

**Comment by mcoker** [comment]
Thanks for the bug @jelly. If you have a working override, I think that's the best solution for this. We're code frozen and in the final stage of testing for the v5.4 release, and that will likely be our last v5 release until we release v6.

**Comment by garrett** [comment]
Still a problem
