### ISSUE TITLE
Clean up old transitions

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6936]
**Please describe the issue**
We had a few pre-existing animations (transitions) on a few elements. We need to clean these up so that they use animation tokens and are correctly targeted not to affect things that are not intended.

E.g. An old sidebar transition is causing the sidebar to change between light/dark modes slowly when if really should just be targeted at sliding in/out of view.

Anything using [these variables](https://github.com/patternfly/patternfly/blob/9df42bd68daf4766ec26b32f4054a83f0af45d73/src/patternfly/base/tokens/tokens-local.scss#L118) is a candidate for updating

**Comment by srambach** [comment]
@kaylachumley we have some old transitions used for rotating the toggle icon on expandable things. I'm removing the old in favor of our new tokens for motion - but there are some differences.

old:
  **--pf-t--global--transition: all 250ms cubic-bezier(.42, 0, .58, 1);**

Here are the new timing tokens:
```
  --pf-t--global--timing-function--100: cubic-bezier(.4, 0, .7, .2);
  --pf-t--global--timing-function--200: cubic-bezier(.4, 0, .2, 1);
  --pf-t--global--timing-function--300: cubic-bezier(0, 0, .2, 1);
```

And those are used in these:
```
  --pf-t--global--motion--timing-function--accelerate: var(--pf-t--global--timing-function--100);
  --pf-t--global--motion--timing-function--decelerate: var(--pf-t--global--timing-function--300);
  --pf-t--global--motion--timing-function--default: var(--pf-t--global--timing-function--200);
```

**First question: Is one of these timing functions ok to use, or do we need a new one?**

Next, duration. You can see in the old line above it was 250ms. 

We have these durations:
```
  --pf-t--global--duration--100: 100ms;
  --pf-t--global--duration--200: 200ms;
  --pf-t--global--duration--300: 300ms;
  --pf-t--global--duration--400: 400ms;
  --pf-t--global--duration--50: 50ms;
  --pf-t--global--duration--500: 500ms;
  --pf-t--global--duration--600: 600ms;

  --pf-t--global--motion--duration--2xl: var(--pf-t--global--duration--500);
  --pf-t--global--motion--duration--3xl: var(--pf-t--global--duration--600);
  --pf-t--global--motion--duration--lg: var(--pf-t--global--duration--300);
  --pf-t--global--motion--duration--md: var(--pf-t--global--duration--200);
  --pf-t--global--motion--duration--sm: var(--pf-t--global--duration--100);
  --pf-t--global--motion--duration--xl: var(--pf-t--global--duration--400);
  --pf-t--global--motion--duration--xs: var(--pf-t--global--duration--50);
```

We have specific tokens for icon durations -
```
  --pf-t--global--motion--duration--icon--default: var(--pf-t--global--motion--duration--sm); // This would be 100ms
  --pf-t--global--motion--duration--icon--long: var(--pf-t--global--motion--duration--md); // This would be 200ms
  --pf-t--global--motion--duration--icon--short: var(--pf-t--global--motion--duration--xs); // This would be 50ms
```

**Second question: Does one of these durations work for the toggle icon rotation?**

**Comment by kaylachumley** [comment]
Hi! @srambach I think we are fine to use one of our current timing functions for now until we see need for a new one. As for the duration for icon toggle rotation: I would go with 200ms! Seems like a common duration used.  --pf-t--global--motion--duration--icon--long: var(--pf-t--global--motion--duration--md);

**Comment by srambach** [comment]
Thanks @kaylachumley I'll choose the default timing function for the toggle icon rotation unless you think another would be better.

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6961
