### ISSUE TITLE
Bug - Notification badge needs to be updated to use stateful button

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6965]
Use `.pf-m-stateful` with `.pf-m-read`, `.pf-m-unread`, and `.pf-m-attention`

![image](https://github.com/user-attachments/assets/176d7dd8-abf3-404f-a9f1-c14795cd712e)

**Comment by mcoker** [comment]
Closing in favor of https://github.com/patternfly/patternfly/issues/6238
