### ISSUE TITLE
Verify the label group wrapping here is correct

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6967]
Looks like `<div class="pf-v6-c-toolbar__group pf-m-grow pf-m-label-group">` needs `flex-wrap:wrap`

https://pf6.patternfly.org/components/toolbar/html-demos/toolbar-attribute-value-checkbox-menu-toggle-filter-on-desktop/
<img width="577" alt="image" src="https://github.com/user-attachments/assets/26ffb85a-1c38-49c5-b880-cc5f9a79be5d">

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6987
