### ISSUE TITLE
Slider: Update semantic tokens to support dark theme

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly#6977]
Slider component doesn't have enough contrast between the track and ticks in dark theme. Need to update the following semantic tokens in core: 

track: adjust unfilled bkg color to use color--nonstatus--gray--default token
tick: adjust filled tick color to use icon--color--on-brand
tick: adjust disabled tick color to use icon--color--on-disabled
tick: adjust tick border radius to border--radius--sharp
tick: adjust tick width to .15rem

end result should look like this: 
<img width="820" alt="image" src="https://github.com/user-attachments/assets/3a613230-a7c1-4fe7-aa12-ae6608732ed1">

Design issue for reference -- 
https://github.com/patternfly/patternfly-design/issues/1316

Note -- will need to pull in the latest tokens from figma in order to see the nonstatus gray bkg token color changes

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6981
