### ISSUE TITLE
Bug - [ToggleGroupItems] - [ToggleGroupItems is in foreground when used in Wizard]

### ISSUE THREAD

**Issue by avitova** [patternfly/patternfly#7001]
**Describe the problem**
This is an issue with 
- [ ] Patternfly 5  

When using ToggleGroupItems in a Wizard on a screen with a more narrow size, the Item that is `selected` is kept on the screen over the list of steps in Wizard.

**How do you reproduce the problem?**
I could not get the sandbox working, but this is the code structure that is [problematic](https://codesandbox.io/p/sandbox/demo-bug-jw8zct?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm054xtbh00062v88zsv1z4ae%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm054xtbg00022v880hssxb4c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm054xtbg00032v88nnapzalx%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm054xtbg00052v88dbin1zsf%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm054xtbg00022v880hssxb4c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm054xtbf00012v88lw9d2uq2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cm054xtbg00022v880hssxb4c%2522%252C%2522activeTabId%2522%253A%2522cm054xtbf00012v88lw9d2uq2%2522%257D%252C%2522cm054xtbg00052v88dbin1zsf%2522%253A%257B%2522id%2522%253A%2522cm054xtbg00052v88dbin1zsf%2522%252C%2522activeTabId%2522%253A%2522cm054zf9800102v88l1diuevq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm054xtbg00042v88xgcgiyr7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm054zf9800102v88l1diuevq%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm054xtbg00032v88nnapzalx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm054xtbg00032v88nnapzalx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), reach out for more details.

**Expected behavior**
I expect the selected ToggleItems not to be shown when closing the step in the menu.

**Is this issue blocking you?**
Not really, but is unfortunate in the UI.

**Screenshots**
![bug-patternfly](https://github.com/user-attachments/assets/2e571ec9-b735-4181-881e-25daf06bd770)

**What is your environment?**
 - OS: Fedora 38
 - Browser chrome
 - Version 127.0.6533.119

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/7218

**Comment by avitova** [comment]
Amazing, thank you!
