### ISSUE TITLE
Tokens - create temporary placeholder token for use in codemods

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#7003]
**Describe the enhancement or change**
Create a local token set to the pink highlight color that can be used in code mods to set unknown color tokens to an otherwise unused color so that fixes will stand out.

suggested name: `--pf-t--temp--dev--tbd`
suggested value: #BD11E0 (this does not and should not exist in the color palette) This is the color currently used in design annotations.

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/7005
