### ISSUE TITLE
Titles appear bold

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly#7017]
**Please describe the issue**

Not sure if this is an issue, but titles appear bold?

Perhaps this is expected for the new v6 design, but would like to confirm we've implemented this correctly.

**Are there visuals for this issue? Please provide screenshots**

PF v6
![Screenshot 2024-08-28 at 3 38 15 PM](https://github.com/user-attachments/assets/a1d350bb-25da-427c-a937-e9d57a273b46)

PF v5
![Screenshot 2024-08-28 at 3 43 13 PM](https://github.com/user-attachments/assets/0ebad65c-e8d0-4b85-8d12-cef09b452ec9)

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**

Card title
https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/components/reports/reportSummary/reportSummaryAlt.tsx#L42

Chart title
https://github.com/dlabrecq/koku-ui/blob/pf-v6/src/routes/components/charts/trendChart/trendChart.tsx#L360

**Comment by srambach** [comment]
@lboehling @andrew-ronaldson can one of you verify what we should expect?

**Comment by dlabrecq** [comment]
I met with @mcoker and this appears to be expected

**Comment by mcoker** [comment]
These look good to me - confirmed you're getting the proper font-family and font-weight from v6 for titles and card titles, and you were able to confirm the titles on the page match what is on the v6 staging site.
