### ISSUE TITLE
Demos - Drawer demo(s) w/ jump links are missing the expandable toggle

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#7021]
On https://pf6.patternfly.org/components/drawer/html-demos/collapsed-drawer-with-jump-links/ and maybe others, the drawer demo with jumplinks is missing the expandable toggle.

Per @mcoker this appears to be resulting from a .hbs change

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/7024
