### ISSUE TITLE
Card border is missing

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly#7026]
**Please describe the issue**

Wrapped a table with a `Card` per this [PatternFly example](https://staging-v6.patternfly.org/components/table/react-demos#column-management). In both the PF example and Cost Management, the border is missing for the top-left corner. Also encountered the issue with the scrolling table. However, the entire left-side border is missing for that card.

Note that `CardBody` is omitted from the PF examples -- I've included it in my pages as a workaround.

**Are there visuals for this issue? Please provide screenshots**

Example 1
![Screenshot 2024-08-29 at 5 00 09 PM](https://github.com/user-attachments/assets/86a229fc-54a1-4d20-8ff7-573bdb422224)

Example 2 (scroll table)
![Screenshot 2024-08-29 at 8 35 16 PM](https://github.com/user-attachments/assets/d1238e07-9da6-4fe8-b5d0-672a12b1190e)

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**

https://github.com/project-koku/koku-ui/pull/3984

**Comment by mcoker** [comment]
Hey @dlabrecq for v6, the design recommendation is to remove cards around tables and data-lists in layouts like that. Are you able to just remove the card? If not, can you try putting it in a regular card with padding?

**Comment by mcoker** [comment]
For this, let's try and move the default card border to the outside of the card (border is on `.pf-v6-c-card`, not on a pseudo element) and see if that works easily.
