### ISSUE TITLE
Bug - SelectOption - Screen cuts off when description is too long

### ISSUE THREAD

**Issue by logonoff** [patternfly/patternfly#7037]
**Describe the problem**
This is an issue with 
- [x] Patternfly 5  
- [x] Patternfly 6  
- [ ] other

Please give a clear and concise description of the problem. Which components are affected?

When SelectOption descriptions get really long, they span the whole screen and sometimes get cut off

**How do you reproduce the problem?**
Provide steps to reproduce. A [codepen](http://codepen.io) or [codesandbox](https://codesandbox.io/) demonstrating the problem is appreciated.

PF5: https://codesandbox.io/p/sandbox/wmjfvr?file=%2Findex.tsx%3A4%2C1
PF4 (expected behaviour): https://codesandbox.io/p/sandbox/qzfn2n?file=%2Findex.js%3A7%2C1

**Expected behavior**
A clear and concise description of the expected behavior.

The descriptions of the SelectOptions aren't cut off 

**Is this issue blocking you?**
List the workaround if there is one.

Not blocking, workaround was to just add the `popperProps={{ maxWidth: 'trigger' }}` prop to `Select`

**Screenshots**
If applicable, add screenshots to help explain the issue.

![Screenshot from 2024-09-03 16-28-56](https://github.com/user-attachments/assets/ac586e4d-4fb7-48ca-9b48-be32ef35e2cb)

**What is your environment?**
 - OS: [e.g. iOS] Fedora 40 
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 129.0

**What is your product and what release date are you targeting?**
OpenShift Developer Console, targeting OpenShift 4.18

**Any other information?**

**Comment by nicolethoen** [comment]
Work around discovered: 
turns out I just had to add the following prop to the Select to replicate the PF4 behaviour `popperProps={{ maxWidth: 'trigger' }}`

**Comment by tlabaj** [comment]
Using `popperProps={{ preventOverflow: true }}` is another option that would work here.

**Comment by mcoker** [comment]
@nicolethoen I think this is going to be a react issue. In PF4, the select menu was positioned in CSS, but since there is no common wrapping element for both the select toggle and select menu, we don't have a good way in the PF CSS to limit the menu width to the toggle width.

I think the workaround y'all provided is probably the best. Looks like `SelectPopperProps` also supports a `width` and `minWidth` prop that could be helpful - https://staging-v6.patternfly.org/components/menus/select#selectpopperprops

**Comment by mcoker** [comment]
@logonoff will any of the solutions above address this issue for you?

**Comment by logonoff** [comment]
> @logonoff will any of the solutions above address this issue for you?

Hi, setting the `maxWidth: 'trigger'` popper prop addresses the issue for my use case. Thanks for the help :)

**Comment by mcoker** [comment]
@logonoff great to hear!! 🥳
