### ISSUE TITLE
Control elements - new readonly token 

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly#7056]
> Add a new token for the read-only background color used for control elements. The current styling uses a secondary color that looks more editable in dark theme. 

Will need to collab with design but putting the issue in PF repo. @lboehling was looking into this I believe. design-tokens needs to be merged first with the new token.

**Comment by lboehling** [comment]
Added tokens for read-only border and fills, will need to pull in the latest figma tokens to get them -- opened an issue for that [here](https://github.com/patternfly/design-tokens/issues/87)! 

Once those are pulled in, we should apply the `global--background--color--control--read-only` and `global--border--color--control--read-only` to our read-only inputs

design should look like this: 

<img width="640" alt="image" src="https://github.com/user-attachments/assets/51819e38-1ae9-4072-9647-363ccc5a79ed">
