### ISSUE TITLE
DPO Typography Updates -- Content/Title Component updates? 

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly#7072]
Made a few typography updates per recent DPO decisions. Tokens will be available once the latest figma tokens are pulled in via [#87](https://github.com/patternfly/design-tokens/issues/87). Decided to bump our 22px font size back up to 24px, and reduce the font weight in `global--font--weight--heading--default.` The weights and sizes should be handled by base token updates. 

Want to double check those are pulled in correctly. The DPO group also decided that only the H1 (or largest title if no H1 is present) on the page should be bolded. Our current titles/headings are all set to `global--font--weight--heading--default.`  We have `global--font--weight--heading--bold` that should be used to enable that. I'm not sure if we can just update that token for our H1 headings, or if it should be a modifier on the title component? 

Will create a follow-up design guidelines/typography page content issue. 

FYI @mcoker @andrew-ronaldson

**Comment by mcoker** [comment]
@lboehling @andrew-ronaldson some thoughts:

* The content component styles headings based on heading level, so an `h1` always gets certain styles. You can't have an `h1` that looks like an `h4`, for example.
* The title component styles headings based off of the size modifier/class used. So you can have an `h1` that looks like an `h4`.
* The largest title may not always be an `h1`, depending on the markup on the rest of the page, so we can't just style by the element used.
* The largest title on the page may not always be a specific size (I'm assuming this is the case, please correct me if I'm wrong, or that isn't the design intent). Maybe on one page you have some kind of Super-Cool-Awesome-Hero-Box heading that's ginormous, and on another page, the main title is smaller, but both are the largest/most-prominent on their respective pages.

That says to me that we likely need some sort of modifier class for the content component and the title component that you can apply to whatever heading level and whatever size variation that says "This is my page title" and applies a bold font-weight. We could also use that class to apply any additional styles we decide later we want to add to whatever the "page title" is. wdyt?
