### ISSUE TITLE
Datalist -  There is not spacing above the action buttons when datalist is compact

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly#7105]
**Please describe the issue**

There is no spacing above the action buttons when the Data list has the `pf-m-compact` modifier applied.

**Are there visuals for this issue? Please provide screenshots**

https://core-staging.patternfly.org/components/data-list#compact

![Screenshot 2024-09-24 at 4 14 12 PM](https://github.com/user-attachments/assets/0e99ed64-5320-43af-aa0a-5f0e2b72bdde)

**Comment by mcoker** [comment]
Per @lboehling
* Compact data lists should use small/compact actions, so we should update our examples
* The data list actions element can be updated to use the compact button's vertical spacer

It will probably look like this, but design's feedback is "it still is pretty tight but i'd argue that if you need a whole bunch of buttons in your data list, you probably shouldn't be using a compact variant"

![Screenshot 2024-09-24 at 4 22 33 PM](https://github.com/user-attachments/assets/a77846d8-6021-4af1-8b31-9e57d19ddf55)
