### ISSUE TITLE
Page: Sticky breadcrumb needs a spacer for padding-block-end

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#7145]
Checking the demos as part of our component audit I noticed the [Sticky breadcrumbs](https://staging.patternfly.org/components/page/html-demos/sticky-breadcrumb/) demo could use a small spacer to at the bottom to feel less cramped.

**Before**
![Image](https://github.com/user-attachments/assets/51923d26-5faf-4faf-beca-396bcfc6b22c)

**After** with `--pf-t-global--spacer--sm`
![Image](https://github.com/user-attachments/assets/39aaefcb-19e2-4a03-8db7-93442ac406ad)

**Comment by sg00dwin** [comment]
@andrew-ronaldson I'm going to be opening a fix for this issue and have a couple of questions.  You specified applying the small `--pf-t--global--spacer--sm` spacer on the bottom padding of the `breadcrumb`, which is different from  its top padding of `--pf-t--global--spacer--md`. Just want to confirm that's intended.

With **`--pf-t--global--spacer--sm`**
![Image](https://github.com/user-attachments/assets/ed8a74a1-155c-4710-8ca9-3b29dcb72e78)


With **`--pf-t--global--spacer--md`**
![Image](https://github.com/user-attachments/assets/a4eaa49a-7a9a-4f3c-aed1-0ac3ed83e177)

---

Also, related this issue, the sticky horizontal subnav is missing bottom padding. Do you want me to include it with this issue and put in a fix for both with one PR or should it have it's own issue and PR?
![Image](https://github.com/user-attachments/assets/f082765c-da2c-49f8-b940-326eb122c7e2)

**Comment by andrew-ronaldson** [comment]
Thanks for this @sg00dwin 
Let's go with the md spacer.
