### ISSUE TITLE
[Stack/Split] - Easier interface to use

### ISSUE THREAD

**Issue by andrewballantyne** [patternfly/patternfly#7190]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any? `Stack`, `Split` (maybe this extends to `Flex`) 

**Describe the feature**
A clear and concise description of the new feature. What is the expected behavior?

Can we get a smaller barrier to entry to using Stack and Split where the Item variant is not needed? Officially supporting a more simple interface.

```
<Stack hasGutter>
  <MyItem />
  <MyOtherItem />
</Stack>
```

instead of the more verbose:

```
<Stack hasGutter>
  <StackItem>
    <MyItem />
  </StackItem>
  <StackItem>
    <MyOtherItem />
  </StackItem>
</Stack>
```

The only use-case I see for using a `StackItem` is for `isFilled` -- not sure if there is a better way to get around that. Maybe that's your use-case for `StackItem`? 

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

**Any other information?**

**Comment by mcoker** [comment]
Hey @andrewballantyne, sorry about that, we're starting to work on these types of issues now that v6 is released so I went ahead and put up a PR for the change if you'd like to leave a review - https://github.com/patternfly/patternfly/pull/7201
