### ISSUE TITLE
Bug - Navigation - Long labels don't wrap

### ISSUE THREAD

**Issue by edonehoo** [patternfly/patternfly#7216]
**Describe the problem**
This is an issue with PatternFly 6. The navigation "container" gets wider when you expand nav sections with long nav item labels, because they aren't wrapping.

**How do you reproduce the problem?**
On [PatternFly.org](https://www.patternfly.org/), expand the "Ux writing" section when your browser is fullscreen or almost fullscreen. This can also be seen under "PatternFly AI > Chatbot". Note that this doesn't seem to occur for me in smaller windows (screenshot below).

**Expected behavior**
The navigation container should stay the same size. The longer navigation labels should wrap.

**Is this issue blocking you?**
No. 

**Screenshots**
Default/expected size:
<img src="https://github.com/user-attachments/assets/97fecdd3-49ef-460e-b529-eb62927c8e33" width="500"></img>

Size grows with nav label:
<img src="https://github.com/user-attachments/assets/3d258147-067a-46ff-a6d7-3bfc7d82cd62" width="500"></img>

When I make my browser window small, the label does wrap as expected: 
<img src="https://github.com/user-attachments/assets/3328e670-a89e-4e74-8087-79feb01a572e" width="300"></img>

**What is your environment?**
Mac OS, Chrome

**Comment by mcoker** [comment]
When we fix this, it might also be good to add items to our default page demos that have nav items with a lot of text so we can catch this bug if it pops up again.

**Comment by mcoker** [comment]
Could be addressed as part of https://github.com/patternfly/patternfly/pull/7224
