### ISSUE TITLE
Document modifier variable format

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#741]
When creating a modifier variable the format should be 
`--pf-c-block__element--m-modifierName--PropertyCamelCase`

So for example an success alert with a `pf-m-success` modifier would look like this: 
`--pf-c-alert--m-success__icon--Color`

At the same time we should crawl the code base and ensure that this format is followed.

**Comment by mcoker** [comment]
We did this prior to the last breaking change.
