### ISSUE TITLE
Dropdown/Select move text into example handlebars

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#792]
Currently, the text displayed in the [dropdown variations](https://pf-next.com/components/Dropdown/examples/) is contained in the handlebar files that make the core component. These should be rewritten to move the content into the example handlebar files, and the component handlebar files should pull all the text content from their partials. There will need to be additional handlebars elements and parameters to allow for passing in the subitems, marking disabled items, etc.

**Comment by mcoker** [comment]
We have an issue to update the dropdown HBS, and from there we can apply the same concepts to the other dropdown types of components (select, app launcher, etc)
