### ISSUE TITLE
Align docs in workspace for all components

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#817]
Related to #816 

Go back and investigate components that have already been introduced to make them align/match. This will be a separate issue that we will do later.

**Comment by mcoker** [comment]
@mcarrano @redallen wdyt about this? Is this still something we need to do?

**Comment by mcarrano** [comment]
@mcoker I think this can be closed. Next week during the virtual meetup, @redallen is going to demo the new website structure and there may be some doc updates we'll want to make. But I'd advise we open new issues as those come up.
