### ISSUE TITLE
Allow to put custom elements in BreadcrumbItem

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly#898]
Since the implementation of [react breadcrumb component](https://github.com/patternfly/patternfly-react/pull/872) allows consumers to put there anything (not only strings), it would be nice to support this option in Patternfly-Next.

From a practical point of view, I can imagine that consumers would use Section Home title with HomeIcon, etc.

We discussed it with @mcarrano @christiemolloy

**Comment by mcarrano** [comment]
Thanks for entering this @rvsia .

@LHinson I'm thinking that we can track this as an enhancement request. Not sure that I think we should allow anything inside of a breadcrumb, but I can definitely envision use cases where we will want an icon and text. For example for object details in Storage we had designs that called for reflecting object status within detail views.

**Comment by mcarrano** [comment]
@LHinson @rachael-phillips @mcoker I added this to the prioritized backlog. I don't see any reason we shouldn't support this. For example, a consumer might want to associate a status icon with an object name that is reflected in the breadcrumb control in the same way we do for tabs.

**Comment by mcoker** [comment]
@mcarrano just to verify, it sounds like this issue will add support for an icon in the breadcrumb item that is spaced appropriately from the text?

**Comment by mcarrano** [comment]
Yes
