### ISSUE TITLE
investigate theming further.

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#911]
@srambach brought up recently that when the vertical nav component is toggled to show the dark theme is looks broken. 
<img width="1118" alt="screen shot 2018-11-07 at 6 17 16 pm" src="https://user-images.githubusercontent.com/287880/48164612-610eff00-e2b9-11e8-8982-40fec4377e86.png">

Currently in the workspace you can toggle the theme and depending on the component it can look good or bad. This is determined by where that component is meant to be used so in some cases a component shouldn't exist in a dark area. To an outside/new dev this would be confusing.

After discussing with the CSS team it seems the logical thing to do is assess how many components break in the dark theme. Once determined we can do the following:

1. We can investigate writing more strict css that will lock the theming to just the dashboard. So our theme classes won't work on any other area in the UI.

2. We can ensure that components that shouldn't exist in an area with dark background don't change regardless of the dark/light mode. For example: the vertical nav would have a white background colour applied instead of its transparent one, so regardless of the background of the UI the nav would always remain the same. This is the path of least resistance but could still leave opportunity for developers to make undesired changes to get a true dark theme.

3. We could look at what happens when we create dark and light variables for each theme related global variable so all colours would have both a dark and light variable.

So in the case of `--pf-global--BackgroundColor--100` (which is white) We would ensure there is both a light and dark version. So anytime a component uses that background colour it would have a counterpart for the dark theme by default.

This would require some testing to see how the system would look if it was applied.

4. We can revisit design for key components like Nav to provide an alternative option for the applications that would like a dark UI. This would be a fine tuning of certain components and would allow design to control what the out come would be in each theme.

This all came about after talking with @mcoker about the work he is doing with Insights. 
<img width="843" alt="screen shot 2018-11-07 at 6 25 47 pm" src="https://user-images.githubusercontent.com/287880/48165015-a7b12900-e2ba-11e8-8407-9de997116a55.png">

I think we need to consider these scenarios where a dev could essentially create a dark theme for the entire application with the exception of the vertical nav.

**Comment by mcoker** [comment]
@mceledonia is working on a story this milestone for dark theme.
