### ISSUE TITLE
Identifying components that need to work with dark/light theme 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#932]
Identifying components that need to work with dark/light theme so that we understand which components need to be tested with both themes before merging or which component may need to be revisited.

**Comment by rachael-phillips** [comment]
Are we actively working on this right now? If not, I would like to remove assignees until it is actively being worked on.

**Comment by matthewcarleton** [comment]
@rachael-phillips nope it's not being worked on as far as I know

**Comment by mcarrano** [comment]
Per my conversation with @mceledonia he believes that design work is done for this one. @kybaker @mcoker do we need to do further work before queuing this up for CSS? What specifically was the outcome of this? Is there a list of components somewhere?

**Comment by mcoker** [comment]
@mcarrano I believe the first steps were to identify the components that should work in light/dark theme, and AFAIK we never did that. I think after that we would want to make sure all of our components work in the them they're intended to work in. Currently a lot of our components break if you place them in a dark theme. You can test this by looking at a component in the workspace and toggling the light/dark theme mode button and seeing if the component is still displayed properly.

**Comment by matthewcarleton** [comment]
@mcoker @mcarrano yes I can back that up. It was assigned to me but got punted for other work from what I remember.

**Comment by rachael-phillips** [comment]
It seems like we will need to pick this up whenever it comes back into the roadmap with a conversation with design and Core. I'll remove assignees for now since it is not currently active.

**Comment by mcarrano** [comment]
That makes sense @rachael-phillips . Does that mean that we will also need to revisit #1556 and #1647 or can those move forward separately? Thoughts @mcoker @mceledonia ?

**Comment by mcoker** [comment]
I think #1556 and #1647 are part of this issue, as in we're evaluating the way those components display in dark mode, so we can check them off the list of components we need to look at as part of this issue.

**Comment by mcoker** [comment]
This is being worked on in https://github.com/patternfly/patternfly/issues/1977
