### ISSUE TITLE
Add page header to page layouts

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#939]
Add `pf-l-page__main-header` to page layouts that handles `<h1>`, `<p>`, `<pf-c-breadcrumb>`, `<pf-c-tabs>` automatically.

**Comment by mcoker** [comment]
@mattnolting do you still think we need this?

**Comment by mattnolting** [comment]
I do think we still need this, though low priority

**Comment by rachael-phillips** [comment]
Hi @mattnolting if this is something you are not working on currently do you mind if I un-assign you? I'm cleaning up the repo a bit right now, and moving forward we will only assign out what is currently being worked on :)

**Comment by mattnolting** [comment]
@rachael-phillips Works for me. I think it would be a really good idea to use the enhancements I'm currently making to `pf-l-flex` to build these layouts.

**Comment by rachael-phillips** [comment]
Ok, let's remember that and we can work on this after we wrap up the enhancements that are coming.

**Comment by mcoker** [comment]
@mattnolting do you want to leave this open?
